### ISSUE TITLE
Very Slow and 

### ISSUE THREAD

**Issue by greensquarepanda** [Tunnelblick/Tunnelblick#268]
I am having problems when connected that i only have connection for 5 minutes and the connection is max 30kb/s or so Very slow and annoying please help!
Thanx in advanced

**Comment by jkbullard** [comment]
You need to contact your VPN service provider. That is the organization which gave you your configuration files, and perhaps a username and password, and to which you are probably paying a fee for VPN service. For more information, please see [Getting VPN Service](https://tunnelblick.net/cGettingVPNService.html).

Tunnelblick is just the free software that many VPN service providers recommend or supply to their customers. We do not provide VPN service, just software.

**Comment by greensquarepanda** [comment]
Yes but i have a .ovpn file were should i drop it in my libary i think thats the problem

**Comment by jkbullard** [comment]
Please see my previous answer: contact your VPN service provider. Here's a hint: You don't "drop" your config file anywhere, you double-click it after installing Tunnelblick.

GitHub Issues are not the place to discuss how to use Tunnelblick. Please see the [Support page](https://tunnelblick.net/support.html) on the Tunnelblick website for help. The website also has extensive documentation.

I will not respond to further comments on this Issue #268.
