### ISSUE TITLE
Attempting to install .tblk configuration fails silently

### ISSUE THREAD

**Issue by matfin** [Tunnelblick/Tunnelblick#271]
When I attempt to install an OpenVPN configuration it appears that nothing happens and the attempt has failed silently. 

What I would expect to happen is that the installation succeeds and my configuration appears so I can make a connection.

I am using OS X Yosemite 10.10.5 (14F27) and Tunnelblick 3.6beta08 (build 4371). 

When I open the TunnelBlick dialog from the top right hand of the desktop and select 'Add a VPN' the message appears telling me to double click on a directory renamed with the .tblk extension.

When I click on the configurations tab in the dialog window and click on the plus sign to add a configuration, I see the same alert dialog displayed. 

If there is any reason the installation of the .tblk config files failed, there should be a clear error message displayed detailing the reason why the installation failed.

**Comment by jkbullard** [comment]
This is probably happening because of an OS X problem: OS X is not using /Applications/Tunnelblick to install the configuration.

Try dragging and dropping the configuration onto /Applications/Tunnelblick instead of double-clicking it.

**Comment by matfin** [comment]
Hi,

I tried that and it didn't work. I kept the dialog open and dragged the .tblk package to it with no effect. I also dragged the .tblk package onto TunnelBlick in the /Applications directory and that also had no effect. 

I should also point out than when double clicking on the .tblk package I see the following message: 

“Tunnelblick” is an application downloaded from the Internet. Are you sure you want to open it?

This is the Google Chrome message that pops up.

**Comment by jkbullard** [comment]
1. Eject the Tunnelblick disk image.
2. Quit Tunnelblick.
3. Drag/drop the configuration onto /Applications/Tunnelblick.

The copy of Tunnelblick in /Applications should launch and install the configuration.

(Be sure that your ".tblk" is valid -- it should be created using the procedure at https://tunnelblick.net/cConfigT.html#creating-and-installing-a-tunnelblick-vpn-configuration)

**Comment by matfin** [comment]
Thank you. That seems to have fixed it. I am now connected using the same .tblk directory.

**Comment by jkbullard** [comment]
It appears this problem was caused by OS X using the copy of the Tunnelblick application that is on the disk image (it should be using the copy in /Applications). That's why you got the message

“Tunnelblick” is an application downloaded from the Internet. Are you sure you want to open it?

And you then clicked "cancel", so nothing was done to install the configuration.

A recent commit to the source code ensures that the disk image is ejected when a copy of Tunnelblick in /Applications finishes loading, so this problem won't happen.
