### ISSUE TITLE
“Tunnelblick received Signal 13 and will terminate”

### ISSUE THREAD

**Issue by herzi** [Tunnelblick/Tunnelblick#272]
Sometimes, I see the aforementioned error message (or one that was similar) on the computer we use for continuous integration. The machine automatically suspends at 8PM and will not wake up before 8AM.

As signal 13 is SIGPIPE, I guess, there should be some way to prevent this (maybe check SIGCHLD to close pipes when a child process died).

**Comment by jkbullard** [comment]
It would be helpful to have more information. For example, what version of OS X and Tunnelblick are being used? What entries are in the Console Log?

**Comment by herzi** [comment]
The OS X Version is 10.10.5; Tunnelblick is always the latest non-beta version.

I'll provide the logs the next time I see this. (Happens every couple of weeks.)

**Comment by jkbullard** [comment]
Abandoned.
