### ISSUE TITLE
Upgrade to 3.6beta09 breaking configs

### ISSUE THREAD

**Issue by dpedu** [Tunnelblick/Tunnelblick#273]
I recently updated to Tunnelblick 3.6beta09 (build 4395). Afterwards, I noticed the "Route all IPv4 traffic through the VPN" option has become enabled for all my connections, causing them to break or function not as intended. This option should not be enabled by default, it should only be enabled if the configuration is designed to do so.

Also, why does this option exist? This should be handled in openvpn config (be it on the server or client side), not in the tunnelblick UI. `redirect-gateway` is the openvpn option for this.

**Comment by jkbullard** [comment]
See [this discussion](https://groups.google.com/forum/#!topic/tunnelblick-discuss/RCD_whr9Zt4).

**Comment by jkbullard** [comment]
Tunnelblick 3.6beta10 reverts to the earlier default, to NOT "Route all IPv4 traffic through the VPN".
