### ISSUE TITLE
dns lookup hangs randomly

### ISSUE THREAD

**Issue by benpptung** [Tunnelblick/Tunnelblick#278]
DNS lookup will hangs after connected in a random certain time. Maybe, after 1 minute after connected to the server, or whole day smoothly. While DNS lookup hangs, 

    $ nslookup www.google.com 
will show connection time out; no server could be reached.
And I usually fix it in the following steps to get vpn works again.:

1. disconnect the connection
2. Quit TunnelBlick
3. Start TunnelBlick
4. connect the connection

My environment is in China ( I've been used Tunnelblick for more than 3 years for my company), I have to use Tunnelblick/OpenVPN to bypass the China Firewall, and of course, I set up the DNS server lookup via vpn server to Google public dns. The design is:

Tunnelblick/VPN --> localhost --> stunnel --> remote stunnel --> vpn server

I watch the ping log, the connection speed to my vpn server is quite fast, so I am sure this is not China Firewall problem, and since it happened randomly for a certain time, I think it might be Tunnelblick's bug.

Recently, I upgraded to 3.5.4, it worsen. In a hour, it can happened more than 5 times. Previously, I am not sure which version of Tunnelblick, it happened only 2 -3 times a day. 

Just for your information, and hope it helps. :)

**Comment by jkbullard** [comment]
Thanks. This should not be happening at all. It is probably a configuration problem, probably having to do with the response to network configuration changes.

Please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) to get the info needed to diagnose problems.

This Issue will be closed if a response is not received within 7 days.

**Comment by benpptung** [comment]
Thanks. I've read before you post article. 
Apparently, it is a bug. 
1. DNS lookup hang after a certain time, sometimes, it is only 1 minutes, sometimes, it can last for couple hours.
2. I know China firewall might drop the packets occasionally, however, why Tunnelblick failed to do dns lookup ? Everytime, I have to restart Tunnelblick, I read all of your DNS issue, none of them solve the problem. It is just outdated!!! I am sorry, i've restarted it 10 times this morning. "Read Before you Post "  is useless.

**Comment by jkbullard** [comment]
Please post the info here.
