### ISSUE TITLE
Incorrect localization string

### ISSUE THREAD

**Issue by miksyn** [Tunnelblick/Tunnelblick#280]
HI! When I start Tunnelblick and it not passes self check, it prints Russian words: "Данная копия Tunnelblick была поддерала". But correct words are: "Данная копия Tunnelblick была подделана"

**Comment by jkbullard** [comment]
**Thank you very much.**

We do translation of Tunnelblick on Crowdin.com. I have made the changes there, so the corrected translation will be included in the next release. (Translations are transferred from Crowdin to the Tunnelblick source code immediately before creating a new release, so the change will not appear in the Tunnelblick source code until then.)
