### ISSUE TITLE
Tunnelblick hangs when checking OpenVPN version

### ISSUE THREAD

**Issue by borgand** [Tunnelblick/Tunnelblick#284]
A week or so ago, possibly after I upgraded to `OS X 10.11.1`, Tunnelblick stopped working. Considering the recent upgrace, I tried to install `3.6beta10` with no luck, but reinstalling `3.5.4` fixed it for a while. Yesterday the problem came back and no reinstall fixes it. Using bundled `openvpn` from commandline works and creates working tunnels.

Affected versions: 3.5.4, 3.6beta10, 3.6beta12

**The problem:**

When I start Tunnelblick app, it shows splash screen with text "Starting Tunnelblick..." and stays that way forever. Also the spinning beach ball appears over both the splash screen and Menu Bar icon.

When listing processes in the machine, I found that it waits for this process:

    /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.6/openvpn --version

It just sits there. Running this command from terminal outputs:

```
/Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.6/openvpn --version
OpenVPN 2.3.6 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Sep 19 2015
library versions: OpenSSL 1.0.1p 9 Jul 2015, LZO 2.08
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=no enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_http_proxy=yes enable_iproute2=no enable_libtool_lock=yes enable_lzo=yes enable_lzo_stub=no enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_password_save=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=no enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_socks=yes enable_ssl=yes enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_win32_dll=yes enable_x509_alt_username=no with_crypto_library=openssl with_gnu_ld=no with_mem_check=no with_plugindir='$(libdir)/openvpn/plugins' with_sysroot=no
```

**Exit status: 1**

(I verified that Brew-installed `openvpn --version` gives the same exit status 1)

Normal kill does not end the openvpn process, but `kill -9 <PID>` makes Tunnelblick log this into console and exit:

```
20.11.15 12:59.41,868 Tunnelblick[48635]: openvpnstart returned 9 trying to run '/Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.6/openvpn --version'; stderr was ''; stdout was 'OpenVPN 2.3.8 x86_64-apple-darwin15.0.0 [SSL (OpenSSL)] [LZO] [MH] [IPv6] built on Nov 20 2015
library versions: OpenSSL 1.0.2d 9 Jul 2015, LZO 2.09
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=no enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_http_proxy=yes enable_iproute2=no enable_libtool_lock=yes enable_lzo=yes enable_'


20.11.15 12:59.41,871 Tunnelblick[48635]: Terminating because of error; stack trace:
(
	0   Tunnelblick                         0x000157f9 -[MenuController terminateBecause:] + 129
	1   Tunnelblick                         0x0002abad -[MenuController setUpOpenVPNNamesAndVersionInfo] + 783
	2   Tunnelblick                         0x0001e8eb -[MenuController applicationDidFinishLaunching:] + 230
	3   Foundation                          0x996908a2 __57-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_2 + 50
	4   CoreFoundation                      0x938535a4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
	5   CoreFoundation                      0x9385352b ___CFXRegistrationPost_block_invoke + 75
	6   CoreFoundation                      0x9385349c _CFXRegistrationPost + 460
	7   CoreFoundation                      0x938531d6 ___CFXNotificationPost_block_invoke + 54
	8   CoreFoundation                      0x9380cb53 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1715
	9   CoreFoundation                      0x9380bd72 _CFXNotificationPost + 626
	10  Foundation                          0x99642954 -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
	11  AppKit                              0x9bdca528 -[NSApplication _postDidFinishNotification] + 436
	12  AppKit                              0x9bdca1d6 -[NSApplication _sendFinishLaunchingNotification] + 249
	13  AppKit                              0x9bc74a2a -[NSApplication(NSAppleEventHandling) _handleAEOpenEvent:] + 783
	14  AppKit                              0x9bc74380 -[NSApplication(NSAppleEventHandling) _handleCoreEvent:withReplyEvent:] + 291
	15  libobjc.A.dylib                     0x949cc5ac -[NSObject performSelector:withObject:withObject:] + 84
	16  Foundation                          0x99694180 __76-[NSAppleEventManager setEventHandler:andSelector:forEventClass:andEventID:]_block_invoke + 118
	17  Foundation                          0x99693cd7 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 451
	18  Foundation                          0x99693ad2 _NSAppleEventManagerGenericHandler + 211
	19  AE                                  0x92b54e54 _Z20aeDispatchAppleEventPK6AEDescPS_mPh + 595
	20  AE                                  0x92b51b75 _ZL25dispatchEventAndSendReplyPK6AEDescPS_ + 44
	21  AE                                  0x92b51a88 aeProcessAppleEvent + 299
	22  HIToolbox                           0x9643dc5a AEProcessAppleEvent + 55
	23  AppKit                              0x9bc6fca8 _DPSNextEvent + 2415
	24  AppKit                              0x9bc6ecd0 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1057
	25  AppKit                              0x9bc6e8a7 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 121
	26  AppKit                              0x9bc6201b -[NSApplication run] + 1063
	27  AppKit                              0x9bc286a4 NSApplicationMain + 1630
	28  Tunnelblick                         0x00002079 _start + 208
	29  Tunnelblick                         0x00001fa8 start + 40
)

20.11.15 12:59.41,871 Tunnelblick[48635]: applicationShouldTerminate: termination because of an error; delayed until 'shutdownTunnelblick' finishes

20.11.15 12:59.45,599 Tunnelblick[48635]: Finished shutting down Tunnelblick; allowing termination


```

Replaced the `openvpn` binary with a shell script that just echoes the above version info and exits allows Tunnelblick to start up normally (with alert on checksum mismatch of course). If I replace the original `openvpn` binary after that, Connecting to a VPN logs this into Console:

 ```
20.11.15 13:11.08,909 Tunnelblick[49295]: runTunnelblickd: no data available from tunnelblickd socket; sleeping 0.100000 seconds...

```

And the connection times out while Tunnelblick log window stays rather blank.

It seems as if Tunnelblick is uncapable of communicating with `openvpn` binary.

**Comment by borgand** [comment]
OK, after some more debugging, I finally rebooted my Mac and now Tunnelblick works again (probably last time I also rebooted during reinstalling Tunnelblick).

This means that **reboot fixes the issue**, but somehow it creeps up after some use. I use extensive VirtualBox and Vagrant VM-s, but starting them up now, did not cause problems (at least right away).

I'll try to keep my eyes open and notice what might cause the problem.

**Comment by jkbullard** [comment]
/Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.6/openvpn.orig

is not included in Tunnelblick. Did you add it?

/Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.6/openvpn

is the standard version that is included.

I will be releasing a new beta later today (I hope) that will fix a problem (only in 3.6beta12) when using languages other than English. It messes things up in some very weird ways when you open the "VPN Details" window, so you should avoid beta12 if you aren't using English.

**Comment by borgand** [comment]
Ah, sorry, copied wrong line from terminal history. Actual problem is still related to the bundled openvpn binary.

Yes, I added it when I played with the wrapper script. I'll fix the original description.

**Comment by jkbullard** [comment]
If I understand what's happening, the "openvpn --version" process is hanging.

That looks like a problem with the pipe that Tunnelblick uses to communicate with the OpenVPN process that is running "--version". Somehow Tunnelblick isn't emptying the pipe, so it fills up, and OpenVPN stalls when it can't output any more data.

I had a problem something like that when I was debugging this (the code that runs OpenVPN to get the version info). But otherwise this is the first time I remember seeing the problem.

**Comment by borgand** [comment]
Yes, this seems probable cause. I'll see if I can shed any more light onto what causes it to reappear after a while.

**Comment by jkbullard** [comment]
I have created a pre-release version of Tunnelblick that fixes a bug that could cause this problem and does some extra checking and logging in this area of the program.

I sent "borgand" a link to download a copy; anyone else who wants to try it can send an email to my Gmail address, jkbullard.

**Comment by nw-wind** [comment]
I have the same problem with 3.6.5, 3.6.6 and the 3.6beta16

The output of openvpn --version is:

bash-3.2# /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.7/openvpn --version
OpenVPN 2.3.7 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Dec  4 2015
library versions: OpenSSL 1.0.2e 3 Dec 2015, LZO 2.09
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=no enable_def_auth=yes enable_dependency_tracking=no enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=needless enable_fragment=yes enable_http_proxy=yes enable_iproute2=no enable_libtool_lock=yes enable_lzo=yes enable_lzo_stub=no enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_password_save=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=no enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=no enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_socks=yes enable_ssl=yes enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_win32_dll=yes enable_x509_alt_username=no with_crypto_library=openssl with_gnu_ld=no with_mem_check=no with_plugindir='$(libdir)/openvpn/plugins' with_sysroot=no

Manual start in the Terminal shows:

bash-3.2# /Applications/Tunnelblick.app/Contents/MacOS/Tunnelblick --version
2015-12-09 23:07:19.482 Tunnelblick[5350:2554235] Tunnelblick: OS X 10.11.1; Tunnelblick 3.6beta16 (build 4461)
2015-12-09 23:07:20.205 Tunnelblick[5350:2554235] Error returned from attributesOfItemAtPath: /var/root/Library/openvpn;
Error was Error Domain=NSCocoaErrorDomain Code=260 "Не удалось открыть файл «openvpn», так как такого файла не существует." UserInfo={NSFilePath=/var/root/Library/openvpn, 

no such file, why Tunnelblibk search it here???
WTF?
bash-3.2# ls -l /var/root/Library/openvpn
lrwxr-xr-x  1 root  wheel  64  9 дек 23:07 /var/root/Library/openvpn -> /var/root/Library/Application Support/Tunnelblick/Configurations

NSUnderlyingError=0x25c550 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}; stack trace: (
	0   Tunnelblick                         0x0003d06c fmCallStack + 66
	1   Tunnelblick                         0x0003d426 -[NSFileManager(TB) tbFileAttributesAtPath:traverseLink:] + 103
	2   Tunnelblick                         0x00018848 -[MenuController makeSymbolicLink] + 76
	3   Tunnelblick                         0x0002924e -[MenuController init] + 7302
	4   AppKit                              0x98a8ce54 -[NSCustomObject nibInstantiate] + 380
	5   AppKit                              0x98a8cc66 -[NSIBObjectData instantiateObject:] + 317
	6   AppKit                              0x98a8c1e7 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 450
	7   AppKit                              0x98a8c01f -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 56
	8   AppKit                              0x98a828bb loadNib + 462
	9   AppKit                              0x98a81ca5 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 328
	10  AppKit                              0x98d10bbc +[NSBundle(NSNibLoadingInternal) _loadNibFile:externalNameTable:options:withZone:] + 161
	11  AppKit                              0x98dd4a72 +[NSBundle(NSNibLoading) loadNibFile:externalNameTable:withZone:] + 67
	12  AppKit                              0x98a81916 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 743
	13  AppKit                              0x98a7c2c5 NSApplicationMain + 639
	14  Tunnelblick                         0x000021d9 _start + 208
	15  Tunnelblick                         0x00002108 start + 40
)
2015-12-09 23:07:20.207 Tunnelblick[5350:2554235] Created a symbolic link to /var/root/Library/Application Support/Tunnelblick/Configurations at /var/root/Library/openvpn
2015-12-09 23:07:23.836 Tunnelblick[5350:2554235] Set program update feedURL to https://www.tunnelblick.net/appcast-b.rss
2015-12-09 23:07:24.034 Tunnelblick[5350:2554235] Launching a thread to remove the old login item (if any) so we can use the new mechanism that controls Tunnelblick's launch on login
2015-12-09 23:07:24.164 Tunnelblick[5350:2554235] Copied our 'net.tunnelblick.tunnelblick.LaunchAtLogin.plist' into ~/Library/LaunchAgents
2015-12-09 23:07:24.354 Tunnelblick[5350:2554469] No old login item to remove

**Comment by jkbullard** [comment]
I'm not surprised that

<code>
bash-3.2# /Applications/Tunnelblick.app/Contents/MacOS/Tunnelblick --version
</code>

doesn't work; you can't launch an application such as Tunnelblick that way because it is not a Unix executable. (You can use the "open" command to launch an application, but why not just double-click it?)

**Comment by nw-wind** [comment]
It doesnot matter the methos of invocation. 
The ugly solution was to uninstall using the Uninstaller, then install again and reboot. This works :(

**Comment by intel352** [comment]
I have this issue as well, same experience. I'll try uninstalling + reboot.

Regarding the private beta, has anyone been able to verify it fixes the issue?

**Comment by nw-wind** [comment]
The beta has the same problem.
Yes, i got uninstall & reboot but it is windows way. :(

Ср, 16 дек. 2015 г. в 2:32, Jonathan Langevin <notifications@github.com>:

**Comment by picsar** [comment]
Beta 17 (build 4476) fixes the problem for me.

**Comment by jkbullard** [comment]
A pre-release version of Tunnelblick, 3.6beta17 (build 4476) is available which fixes this problem. Email me privately at my Gmail address, jkbullard, for a link to download it. The fix will be a available in the next beta release.

(It is **not** the same version as "the beta" referred to by nw-wind in an earlier comment).

**Comment by jkbullard** [comment]
Tunnelblick 3.6beta18 contains the fix for this problem. It is available on the [Tunnelblick Downloads page](https://tunnelblick.net/downloads.html).
