### ISSUE TITLE
Block all IPv4 traffic when VPN is disconnected

### ISSUE THREAD

**Issue by kaminix** [Tunnelblick/Tunnelblick#285]
Hi
There's an option in Tunnelblick already that says "Route all IPv4 traffic through the VPN". Would it be possible to route all traffic through tunnelblick when it's not connected as well, and block it? So that if the VPN isn't connected, all Internet traffic is blocked. A frequent issue I have is that if my connection goes down, the programs that use the Internet will access the network unprotected until my VPN reconnects.

**Comment by jkbullard** [comment]
This is a great idea; it's been on my TODO list for a long time. I just haven't had the time or knowledge to get it done.

A possible user interface would be a new TB menu command, either just above or just below "VPN Details", that would toggle between "Block all Internet Access" and "Allow Internet access". There would also have to be some kind if visual indicator in the Tunneblick icon indicating that access was blocked, perhaps a big red X over the entire icon.

Implementing the block would be tricky - we  can't block the VPN server that you want to connect to, for example. And if the block is actually done by Tunnelblick itself, it couldn't take effect until after the user has logged in. So it probably should be done by Tunnelblick setting something up that survives reboots. I don't know what that is. Or if that can't be done, perhaps it is something that tunnelblickd can do (it is "active" even before anyone logs in).

**Comment by Erulezz** [comment]
Hi,

Is there any progress on this? :)

**Comment by jkbullard** [comment]
No.

**Comment by ajvpot** [comment]
:thumbsup: I would love to see this.

**Comment by coagmano** [comment]
Until this gets implemented (if it does), you can use a firewall like Little Snitch to block traffic on unsecured networks:
http://asciithoughts.com/posts/2014/02/15/using-little-snitch-to-prevent-internet-access-without-vpn/

**Comment by kaminix** [comment]
That looks like a great suggestion coagmano, gonna try it out soon.

**Comment by shtirlic** [comment]
It's nice feature for me too, can we just create some kind of fake interface(loopback?) and route all traffic to it while not connected and after tunnelblick made connection switch to vpn interface.

**Comment by s4y** [comment]
One approach might be to investigate how macOS handles WiFi portals. When the system believes that you're behind a portal, Captive  can acces

**Comment by s4y** [comment]
One approach might be to investigate how macOS handles WiFi portals: when the system believes that you're behind a portal, Captive Network Assistant can access the network but other apps can't. Seems like we'd want the same thing here.

**Comment by Fmstrat** [comment]
This is a must have. Once TunnelBlick is started all traffic should be run through the interface, connected or not. Without that, if the VPN goes down identity is leaked, which is sort of the opposite of what's needed for a VPN. I'm actually amazingly surprised at the lack of thumbs up for such a core feature. Please add this, dev.

**Comment by mikeappell** [comment]
For reference, Eddie (AirVPN's open-source client) does this, and it works great. It has a 'Network Lock' feature which blocks all traffic which doesn't go through their interface, though I'm not knowledgeable about VPNs to really understand it.

https://github.com/AirVPN/airvpn-client/

**Comment by ichernev** [comment]
I also think this is a must have feature of a VPN. Everytime you wake your computer the open tabs in a browser will make a connection outside of the VPN which defeats the whole purpose.

**Comment by jkbullard** [comment]
@ichernev - Try setting the configuration to NOT disconnect when the computer goes to sleep.

You can do that on the "Connecting & Disconnecting" tab of Tunnelblick's "Advanced" settings window. Changes you make there will affect all configurations that are selected in the "Configurations" panel of Tunnelblick's "VPN Details" window.

**Comment by yassinei** [comment]
One may implement a solution using info [here](http://www.sparklabs.com/support/kb/article/preventing-network-and-dns-traffic-leaks/#preventing-network-leaks-when-a-drop-out-disconnect-occurs) and [here](https://www.tunnelblick.net/cUsingScripts.html).

**Comment by jkbullard** [comment]
A "kill switch" is available in Tunnelblick 3.7.5beta04 which you can update to (on the "Preferences" panel: put a check in "Check for updates to beta versions", then click the "Check Now" button) or download from the [Tunnelblick Downloads page](https://tunnelblick.net/downloads.html).

**Comment by kamelkev** [comment]
@jkbullard Might be good to give a little more detail about how to use this feature. A lot of people have waited for this since 2015, but as far as I can tell there is no documentation discussing it's use. The only mention of the change is in the release notes.

**Comment by jkbullard** [comment]
I agree.

**Comment by jomo** [comment]
As noted in #428, Tunnelblick's kill-switch feature isn't fully protecting you.

I've come up with something very reliable. It's done by the kernel and doesn't rely on Tunnelblick (or anything else) to be running. I don't know if Tunnelblick developers are interested in implementing it like this, but it may be useful for some of you: https://jomo.tv/security/pf-prevent-traffic-bypassing-vpn

**Comment by 2600box** [comment]
Thanks to @jomo for sharing his write-up. I too have been using a similar `pf` setup for some years.

I do however believe that this is not user-friendly and beyond the scope of most users. This functionality should be a core feature of Tunnelblick.
