### ISSUE TITLE
Tunnelblick is freezing immediately

### ISSUE THREAD

**Issue by aringa** [Tunnelblick/Tunnelblick#287]
Immediately after starting tunnelblick.app, the application is freezing. no UI is displayed. process needs to be killed. same on both 3.5.4 and 3.6beta14.
Please help.TY

**Comment by jkbullard** [comment]
Please read https://tunnelblick.net/support.html
and https://tunnelblick.net/cBeforeYouPost.html

For information about what I assume is the problem you are having, please see https://groups.google.com/forum/#!topic/tunnelblick-discuss/2mqTc1Ti0Nc
