### ISSUE TITLE
consider using travis-ci for building/testing/deploying

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#290]
I've managed to build Tunnelblick on travis-ci

https://github.com/chipitsine/Tunnelblick/blob/master/.travis.yml

it might be usefull for continuos development and deploying

**Comment by jkbullard** [comment]
Thanks for your suggestion.

None of the commits to https://github.com/chipitsine/Tunnelblick have comments, which isn't helpful.

**Comment by chipitsine** [comment]
there's clean build: https://travis-ci.org/chipitsine/Tunnelblick/builds/98819888
you are right about comments (


the only magic I did was changing check against xcode 6.30 --> 6.00 (currently travis supports xcode 6.1 only)

usefull about travis is that is builds every pull request, so you have some knowledge about pull requst quality

also, I'm going to make travis sign builds for me.
also we can make it build general tunnelblick releases and publish them

**Comment by jkbullard** [comment]
Please let me know where the 6.30 --> 6.00 change is, or make a pull request for it and I will look into changing it in the Tunnelblick source. (It probably shouldn't even require 6.00; I think Xcode 4.0 would do.)

I don't think I will be using Travis Cl:
  * Official Tunnelblick builds are created and signed on machines under my control. I don't want to delegate that to a third-party such as Travis Cl.

  * Official Tunnelblick builds support OS X 10.4 and PowerPC processors, and must be built on Xcode 3.2.2, which is not supported on Travis Cl.

  * It would be nice to have a quick "pre-filter" for pull requests, but (A) I always look them over before even bothering to build them, and (B) pull requests are so rare that building them by hand isn't a burden.

**Comment by chipitsine** [comment]
https://github.com/Tunnelblick/Tunnelblick/pull/292

**Comment by chipitsine** [comment]
travis-ci is good from any point of view, it will at least build pull requests.
