### ISSUE TITLE
correct url at 'Building Tunnelblick from Source Code.rtf'

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#291]
rtf document says 'svn checkout https://tunnelblick.googlecode.com/svn/trunk/   TunnelblickSource'
can you please replace it with github ?

also, I would suggest converting RTF to README.md, it is better from any point of view

**Comment by jkbullard** [comment]
Thanks for the correction. I have committed that and fixed a small typo in the same document.

RTF is more readable for users using OS X, and most people interested in the document are using OS X, so I don't think I will change it to be a .md file any time soon.
