### ISSUE TITLE
app and openvpn crashes

### ISSUE THREAD

**Issue by tiiiecherle** [Tunnelblick/Tunnelblick#296]
Hey, 

first of all thanks for all the hard work that is put into this project which I really like to use. I have a problem that is present (let`s say for at least months, sorry, I can`t specify more concrete).

I use tunnelblick v. 3.6beta18 (but all the last versions including stable have this problem) to connect to our openvpn server from a late 2013 macbook pro.

When I copy over big files (only tried over 10 GB) from the server to the macbook, everything seems to work fine until (after around 3-5 GB) the connection breaks to upload 0 and download 0 and openvpn hangs completely. The problem is that I couldn`t get a log cus only a complete reboot makes it possible to use openvpn and tunnelblick again. The error is reproducable for me everytime I try it. The internet connection is good and stable on both sides.

I first thought it is a configuration problem and tried several things. Then I tried with viscosity and with a brew openvpn installation and command line connection (both with the same settings) and both manage to copy the big files completely. 

Please let me know if you need any config or log (and how to get it) to investigate the problem.

Looking forward to a fix. Thanks in advance. 

Tom

**Comment by jkbullard** [comment]
Please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html). If Tunnelblick itself hangs when the problem occurs (not just OpenVPN), please connect, disconnect, and then get the diagnostic info as directed but without trying to download the large file.

**Comment by tiiiecherle** [comment]
Thanks for the fast answer. I can not disconnect when the error occurs cus the complete application hangs and only shows the beachball. And I cannot get to the preferences window. It only opens again after rebooting. Is the log from the last session saved somewhere, even if the app is force killed?

**Comment by jkbullard** [comment]
The OpenVPN log is saved somewhere in /Library/Application Support/Tunnelblick/Logs. The Console log, of course, is kept over reboots. But the "diagnostic info" would help even if it is taken before the problem occurs.

**Comment by tiiiecherle** [comment]
ok, I see what I´ll find. I´ll try in the next days.

**Comment by tiiiecherle** [comment]
ok, I tried and could reproduce the error. Unfortunately when I try to get the diagnostic info, tunnelblick crashes with the following error:

Tunnelblick encountered a fatal error.
Please contact the developers at developers@tunnelblick.net for help.

The problem was:
Schwerwiegendes Fehler Signal 5 empfangen.

I could copy the log. I don`t want to attach it here cus it contains our certificate data and email address. Can I send you an email with it?

And there is no folder  /Library/Application Support/Tunnelblick/Logs for me.

**Comment by jkbullard** [comment]
You can email me at my Gmail address, jkbullard. The Console Log should have the info (including a stack trace) that I need to see what is going on. And/or you can edit it (in any text editor, for example, TextEdit) to remove your certificate data and email address.

**Comment by tiiiecherle** [comment]
ok, thanks, just edited it and sent it to you. did you get it and does it help in any way?

**Comment by tiiiecherle** [comment]
ok, just had to get back in the log timeline to find the date I tested it. I copied everything out and sent it to you. Hope that is what you were looking for and hope it helps.

**Comment by jkbullard** [comment]
Closed. Assuming it was the crash when sleep/wake problem fixed in 3.7.5.
