### ISSUE TITLE
Two menubar icons when using two displays

### ISSUE THREAD

**Issue by alex-tan** [Tunnelblick/Tunnelblick#299]
Whenever I plug my external monitor into my Macbook pro, the Tunnelblick icon will show up twice on my  Macbook Pro menubar, one looking like it's connected, and one looking like it's not connected, whether I'm actually connected or not.

it does not appear on my external monitor, however.

![voila_capture 2016-02-25_04-03-23_pm](https://cloud.githubusercontent.com/assets/1841328/13336034/8d774fbe-dbd9-11e5-94e7-bb78737429db.png)

**Comment by jkbullard** [comment]
What version of Tunnelblick are you using?

Try the latest beta.

**Comment by alex-tan** [comment]
I was on 3.5.7 but the beta appears to have fixed the issue. Thanks!
