### ISSUE TITLE
system process 'symptomsd' crash after disconnecting VPN in OSX 11.4

### ISSUE THREAD

**Issue by EldhoseIssac** [Tunnelblick/Tunnelblick#301]
[Systemlog.txt](https://github.com/Tunnelblick/Tunnelblick/files/209716/Systemlog.txt)
[TunnelBlickLog.txt.zip](https://github.com/Tunnelblick/Tunnelblick/files/209728/TunnelBlickLog.txt.zip)

Hi,
I saw a system process  'symptomsd' crashing every time on disconnecting VPN connection . I used a free vpn profile from [OpenVpn](http://www.vpnbook.com/#openvpn)

**Comment by mohammad-rahchamani** [comment]
@EldhoseIssac any updates?
I'm having the same issue in my project and I would be happy if someone could help me with that.

**Comment by jkbullard** [comment]
Tunnelblick is not responsible for crashes in other programs.
