### ISSUE TITLE
Disable warnings

### ISSUE THREAD

**Issue by mdanetzky** [Tunnelblick/Tunnelblick#302]
It would be great to have a way to disable the warning saying:
> After 30.0 seconds, gave up trying to fetch IP address information.

I tried  **VPN status windows: -> Never show** to no avail.

**Comment by jkbullard** [comment]
If you don't want that warning, un-check "Check if the apparent public IP address changed after connecting" on the "Configurations" panel of Tunnelblick's "VPN Details" window.
