### ISSUE TITLE
restart dns responder on mac

### ISSUE THREAD

**Issue by thestick613** [Tunnelblick/Tunnelblick#306]
if i open www.youtube.com before i start connecting, then refresh the page after the vpn connected, i get a blank page, which easily gets repaired by running:
`sudo killall -HUP mDNSResponder`
can this be run exactly after the vpn connection is established?

**Comment by jkbullard** [comment]
Make sure that "Flush DNS cache after connecting or disconnecting" is checked (on the "Connecting & Disconnecting" tab of the "Advanced" settings window). It is checked by default, so perhaps you changed it.

If the problem still occurs, please post the diagnostic info obtained by following the instructions in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html)
