### ISSUE TITLE
Expired certificates cause DoS against server

### ISSUE THREAD

**Issue by CapitalF** [Tunnelblick/Tunnelblick#309]
Tunnelblick v 3.6.3 (build 4560) on OSX 10.11.4.
Server info:>openvpn --version
OpenVPN 2.3.11 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6]
library versions: OpenSSL 1.0.2h, LZO 2.08

I have a tunnelblick client for an OpenVPN server which recently caused some problems.

This is UDP protocol only.

In this case, both the server and the client TLS certificates had expired. The result was that the tunnelblick client opened the maximum number of clients (max-clients) and DoSed the server.

It may be that I need to declare explicit-exit-notify somewhere, like my client config file, but it seems wrong that tunnelblick did not issue any sort of error when both the client and server certificates were expired.

You might want to test this and make sure tunnelblick is behaving the way it should.

**Comment by jkbullard** [comment]
Tunnelblick itself doesn't know anything about certificate expiration; that's handled by OpenVPN. You could report this to them.
