### ISSUE TITLE
Support auto-connect to specific VPN when on (or NOT on) a certain network

### ISSUE THREAD

**Issue by pengux** [Tunnelblick/Tunnelblick#310]
Ability to select a VPN for Tunnelblick to automatically connect to when the computer is on or NOT on a specific network. Would be useful for example when you are not on a trusted network.

**Comment by jkbullard** [comment]
Thanks for the suggestion, but Tunnelblick can't do everything, so I am going to say no.

You can use AppleScript to control Tunnelblick to connect and disconnect configurations, so I suggest you write a shell script to detect the network (I have no idea how) and connect/disconnect configurations as needed.

If you create a script to do that, please share it with the [Tunnelblick Discussion Group](https://groups.google.com/forum/#!forum/tunnelblick-discuss) or email it to developers@tunnelblick.net so it can be added to Tunnelblick's [User Contributed Downloads](https://tunnelblick.net/downloads.html#user-contributions).

**Comment by timfeirg** [comment]
this is a simple hammerspoon script that does exactly this (and some other necessary bits):

```lua
wifiwatcher = hs.wifi.watcher.new(function ()
  net = hs.wifi.currentNetwork()
  vpn_app = hs.application.find('tunnelblick')
  if net == "ShouldntUseVPN" then
    if vpn_app ~= nil then
      vpn_app:kill()
    end
    pac_url = '"http://gfw.guazi-corp.com"'
    hs.execute('sudo networksetup -setautoproxyurl "Wi-Fi" '..pac_url)
    hs.notify.show("Tunnelblick terminated", "Using Auto Proxy", pac_url)
  else
    if vpn_app == nil then
      hs.application.launchOrFocus('tunnelblick')
    end
    pac_url = '"http://mirrors.ricebook.net/gfw/auto-switch.pac"'
    hs.execute('sudo networksetup -setautoproxyurl "Wi-Fi" '..pac_url)
    hs.notify.show("Tunnelblick started", "Using Auto Proxy", pac_url)
  end
end)
wifiwatcher:start()
```

hammerspoon is a lot simpler than apple script, you can just install it and grab this script and it'll work. hope this helps.

@pengux @jkbullard
