### ISSUE TITLE
Disable time machine per connection

### ISSUE THREAD

**Issue by beren12** [Tunnelblick/Tunnelblick#316]
I backup to a network time machine and need to tun tmutil disable/enable myself otherwise it tries to backup over a slow vpn link. It would be great if I could have a setting per VPN to toggle this. Thanks!

**Comment by jkbullard** [comment]
You could create a "pre-connect.sh" script that looks like this

    #!/bin/bash
    sudo tmutil disable

and a "post-disconnect.sh" script that looks like this:

    #!/bin/bash
    sudo tmutil enable

and add them to your Tunnelblick VPN Configuration. See [Using Scripts](https://tunnelblick.net/cUsingScripts.html).
