### ISSUE TITLE
FEATURE REQUEST [in-progress]: OpenVPN binary with LibreSSL

### ISSUE THREAD

**Issue by iamGavinJ** [Tunnelblick/Tunnelblick#317]
x-linking to Google Groups:
https://groups.google.com/d/msg/tunnelblick-discuss/ijYitWvgG0Y/P7VviHHaCwAJ

Thanks.

**Comment by jkbullard** [comment]
Tunnelblick 3.6.9beta01 includes versions of OpenVPN that are static-linked with LibreSSL. The user can select OpenSSL or LibreSSL versions on the "Settings" tab.

Many thanks to @iamGavinJ for his encouragement and PRs.
