### ISSUE TITLE
Application caches configuration file in .tblk bundle

### ISSUE THREAD

**Issue by lazzarello** [Tunnelblick/Tunnelblick#332]
I was debugging a custom server installation and using Tunnelblick as the client. The client configuration had some variability during the debugging session, including a change of the server endpoint IP address. I had imported the client configuration into Tunnelblick, then within the finder, opened and edited the openvpn.conf file to reflect the IP address change. 

My expectation was that after saving the change to this file, the next time I clicked the Connect button in Tunnelblick the change would be reflected in the application. In reality, the application cached the previous version of the config and continued to use the obsolete IP address, resulting in some frustration debugging network timeout issues.

It could be useful for the application to read the config file from disk each time the Connect button is pressed.

**Comment by jkbullard** [comment]
Yes, the config file is cached; we invalidate the cache when you edit the config file through the user interface (accessed via the "gear" menu below the list of configurations in the "VPN Details" window.

But I agree that it makes sense to invalidate the cache when a Connect button or menu item is clicked.

**Comment by lazzarello** [comment]
I can give a quick pass at a PR, though this would be the first time I looked at the source code and I'm not an experienced Cocoa developer. I could probably open it in XCode and find the config handling function  :)

**Comment by jkbullard** [comment]
Feel free, but I'll probably get to it today or tomorrow if you don't. (There is a "valid cached config" flag of some sort, and the connect:something-something should just need to set it false.)

**Comment by jkbullard** [comment]
I have committed a fix for this (3c4299f6e26f04487e8d292d010bc94a675e952c) to the source code; it will be included in the next beta release.

Thanks to @lazzarello for reporting this problem.
