### ISSUE TITLE
[encoding] macOs sierra 10.12 rus

### ISSUE THREAD

**Issue by zhuykovkb** [Tunnelblick/Tunnelblick#335]
i have a problem with encoding with the Russian language as default system (see an attachment)
<img width="720" alt="2016-10-01 10 26 54" src="https://cloud.githubusercontent.com/assets/8007038/19012543/cced722e-87c1-11e6-952b-18651cffd8d7.png">

**Comment by jkbullard** [comment]
@zhuykovkb - Thank you for reporting this. Is this with Tunnelblick 3.6.8beta10?

**Comment by zhuykovkb** [comment]
It was with Tunnelblick 3.6.7c (build 4606).
Now i install Tunnelblick 3.6.8beta10 (build 4622) and get it again :(

**Comment by jkbullard** [comment]
OK, thanks. I will look into this and report back.

**Comment by jkbullard** [comment]
Fixed in the source; the fix will be included in the next beta release.

Thanks again for reporting this, @zhuykovkb.
