### ISSUE TITLE
TB freezes in seconds/minutes + reboot mac os x is needed

### ISSUE THREAD

**Issue by Trepliev** [Tunnelblick/Tunnelblick#343]
Hello. I have macbook pro with Sierra + all updates. I used TB stable and now I use beta 3.6.10b1. I have 4 vpn configs imported.

1. I connect to the vpn
2. connection is ok, I have vpn IP address, I can connect inside the vpn
3. in a few seconds (but it can be after 10 minutes or more) the connection freezes
3. I click on the TB icon and select disconnect
4. TB never disconnects (tested for 12 hours)
5. TB cannot be killed with sudo kill -9 PID
6. I have to reboot the machine because inet connection is broken
7. In mac os x El Capitan it works ok
8. I use "default" openvpn in TB settings and I tried the newest too (2.4b1), the same problem
9. tried in multiple networks with different IP ranges (my work, my home, iphone hotspot)
10. all connections are made by wifi, I do not use wired connection

I have no idea how debug this but I will try your suggestions of course.
Thank you very much for your help

**Comment by jkbullard** [comment]
@Trepliev - When you write "freeze", do you mean that when you hover over Tunnelblick's icon in the status/menu bar you see a spinning wheel, and a click on the icon doesn't cause the menu to drop down?

If so, then please use Activity Manager and get a "Spindump" of the Tunnelblick process and post that.

It would also help if you posted the info described in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html). For that, please connect and then disconnect quickly (so the "freeze" doesn't happen).

**Comment by Trepliev** [comment]
Hello. When the problem starts, the old connections sometimes work ok but not new connections. When I click on disconnect, it never disconnects but the icon is still animated. When I click to close the app, the icon stops animating and the whole Mac top panel freeze - no icon works, panel is "dead". In netstat -nr I can see in Internet6 _two_ "default" routes (but I have no ipv6 connection/addresses)
[Spindump.txt](https://github.com/Tunnelblick/Tunnelblick/files/608321/Spindump.txt)
:

`Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.1.1        UGSc          231        0     en0
127                127.0.0.1          UCS             1        0     lo0
127.0.0.1          127.0.0.1          UH             11   218181     lo0
169.254            link#11            UCS             1        0    tap0
169.254.245.34/32  link#11            UCS             1        0    tap0
192.168.1          link#4             UCS             8        0     en0
192.168.1.1/32     link#4             UCS             3        0     en0
192.168.1.1        52:54:0:4:9c:ba    UHLWIir       177      486     en0    772
192.168.1.5/32     192.168.234.1      UGSc            1        0    tap0
192.168.1.9        link#4             UHLWIi          1        0     en0
192.168.1.10/32    192.168.234.1      UGSc            2        0    tap0
192.168.1.77/32    link#4             UCS             1        0     en0
192.168.1.179      8:11:96:50:f:c0    UHLWIi          1        0     en0   1105
192.168.1.186      34:e6:ad:3a:ba:b0  UHLWIi          3      155     en0      5
192.168.1.220/32   192.168.234.1      UGSc            1        0    tap0
192.168.1.224      link#4             UHLWIi          2        0     en0
192.168.1.250      14:99:e2:77:d2:d8  UHLWIi          1        0     en0    190
192.168.1.251      80:71:7a:8a:cb:3b  UHLWIi          1        0     en0   1172
192.168.1.255      link#4             UHLWbI          1       60     en0
192.168.234        link#11            UC              4        0    tap0
192.168.234.1      6a:56:5c:e8:3f:22  UHLWIi          3        0    tap0
224.0.0/4          link#4             UmCS            2        0     en0
224.0.0/4          link#11            UmCSI           1        0    tap0
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          3        0     en0
255.255.255.255/32 link#4             UCS             1        0     en0
255.255.255.255/32 link#11            UCSI            1        0    tap0

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
default                                 fe80::%utun1                    UGcI          utun1
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#4                          UCI             en0
fe80::1069:19d3:553e:68fd%en0           80:e6:50:9:5b:dc                UHLI            lo0
fe80::%awdl0/64                         link#8                          UCI           awdl0
fe80::1072:3aff:fe46:faae%awdl0         12:72:3a:46:fa:ae               UHLI            lo0
fe80::%utun0/64                         fe80::cdf7:57bb:730d:172f%utun0 UcI           utun0
fe80::cdf7:57bb:730d:172f%utun0         link#10                         UHLI            lo0
fe80::%utun1/64                         fe80::ad43:9edd:877:6ace%utun1  UcI           utun1
fe80::ad43:9edd:877:6ace%utun1          link#12                         UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#4                          UmCI            en0
ff01::%awdl0/32                         link#8                          UmCI          awdl0
ff01::%utun0/32                         fe80::cdf7:57bb:730d:172f%utun0 UmCI          utun0
ff01::%utun1/32                         fe80::ad43:9edd:877:6ace%utun1  UmCI          utun1
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#4                          UmCI            en0
ff02::%awdl0/32                         link#8                          UmCI          awdl0
ff02::%utun0/32                         fe80::cdf7:57bb:730d:172f%utun0 UmCI          utun0
ff02::%utun1/32                         fe80::ad43:9edd:877:6ace%utun1  UmCI          utun1`

**Comment by Trepliev** [comment]
Is there any progress please? In a few minutes a had to reset my mac again :-(. For now I am not able to use TB because I really do not want to hardreset my mac.

**Comment by jkbullard** [comment]
I'm waiting for the info described in [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html). As I wrote before, when getting that info, please connect and then disconnect quickly (so the "freeze" doesn't happen).

**Comment by Trepliev** [comment]
*Tunnelblick: OS X 10.12.1; Tunnelblick 3.6.10beta04 (build 4730); prior version 3.6.10beta03 (build 4720); Admin user
git commit 17796ee905b231e31a6e6da41401001c698ffb45


Configuration ovpn-router

"Sanitized" condensed configuration file for /Users/trepliev/Library/Application Support/Tunnelblick/Configurations/ovpn-router.tblk:

remote x.x.x.x
proto udp
port 1194
dev tap
client
mute-replay-warnings
verb 5
persist-tun
persist-key
tls-auth ta.key 1
tls-client
ca ca.crt
cert crt.crt
key key.key
comp-lzo
keepalive 10 30
route-method adaptive
route-delay 2


================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  145    3 0xffffff7f83221000 0x63000    0x63000    org.virtualbox.kext.VBoxDrv (5.0.30) D7C3AFE8-4CFF-3962-86C1-270ED56E249F <7 5 4 3 1>
  152    0 0xffffff7f83284000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.0.30) A4785347-3EE0-3451-878B-624AB0BF17AC <151 145 40 7 5 4 3 1>
  153    0 0xffffff7f8328c000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.0.30) 85DF3486-4C01-35E9-8161-2C8B42419918 <145 7 5 4 3 1>
  154    0 0xffffff7f83291000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.0.30) B3867056-18BE-3BD4-81D2-602F1894479B <145 5 4 1>
  155    0 0xffffff7f83297000 0xd000     0xd000     com.eset.kext.esets-pfw (630.07.01f01) CC5FEC8D-5A61-3175-A73E-4C83AF283572 <5 4 1>
  156    0 0xffffff7f832a4000 0x13000    0x13000    com.eset.kext.esets-kac (630.07.01f01) B502AB9A-953D-3B14-BA3E-77BA0DA3A0B6 <5 4 3 1>

================================================================================

There are no unusual files in ovpn-router.tblk

================================================================================

Configuration preferences:

-notMonitoringConnection = 0
-resetPrimaryInterfaceAfterDisconnect = 0
-openvpnVersion = -
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
-lastConnectionSucceeded = 1

================================================================================

Wildcard preferences:

-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 1

================================================================================

Program preferences:

skipWarningThatIPAddressDidNotChangeAfterConnection = 1
placeIconInStandardPositionInStatusBar = 1
launchAtNextLogin = 1
notOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
askedUserIfOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
tunnelblickVersionHistory = (
    "3.6.10beta04 (build 4730)",
    "3.6.10beta03 (build 4720)",
    "3.6.10beta01 (build 4700)",
    "3.6.9beta02 (build 4675)",
    "3.6.8 (build 4625)",
    "3.6.7c (build 4606)",
    "3.6.7a (build 4603)",
    "3.6.7 (build 4602)",
    "3.6.6 (build 4582)",
    "3.6.5 (build 4566)"
)
lastLaunchTime = 503307049.423458
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = ovpn-router
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
updateSendProfileInfo = 1
NSWindow Frame SettingsSheetWindow = 898 537 829 524 0 0 2560 1418 
NSWindow Frame ConnectingWindow = 1085 934 389 187 0 0 2560 1418 
detailsWindowFrameVersion = 4730
detailsWindowFrame = {{820, 723}, {920, 468}}
detailsWindowLeftFrame = {{0, 0}, {165, 350}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = log
leftNavSelectedDisplayName = ovpn-router
AdvancedWindowTabIdentifier = connectingAndDisconnecting
haveDealtWithSparkle1dot5b6 = 1
haveDealtWithOldTunTapPreferences = 1
haveDealtWithOldLoginItem = 1
SUEnableAutomaticChecks = 1
SUFeedURL = https://www.tunnelblick.net/appcast-b.rss
SUScheduledCheckInterval = 86400
SUSendProfileInfo = 1
SULastCheckTime = 2016-12-13 07:31:06 +0000
SULastProfileSubmissionDate = 2016-12-09 14:08:37 +0000
SUHasLaunchedBefore = 1
WebKitDefaultFontSize = 11
WebKitStandardFont = .AppleSystemUIFont
tunnelblickdHash = 004cdba8e08abd144bc48409040bc80e29c12ee9741ed7d73754f51d2547f7ea
tunnelblickdPlistHash = ce400d395d1801b003398461b5420021f4d591822783a04b79b2f43956d28620

================================================================================

Tunnelblick Log:


================================================================================

"Sanitized" full configuration file

remote x.x.x.x
proto udp
port 1194
dev tap
client
mute-replay-warnings
verb 5
persist-tun
persist-key
tls-auth ta.key 1
tls-client
ca ca.crt
cert crt.crt
key key.key
comp-lzo
#status openvpn.log
keepalive 10 30
route-method adaptive
route-delay 2



================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 80:e6:50:09:5b:dc 
	inet6 fe80::9c:eaee:df10:c39%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.1.77 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:05:00:52:c0 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:05:00:52:c1 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 02:e6:50:09:5b:dc 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 92:2b:93:b8:c4:6b 
	inet6 fe80::902b:93ff:feb8:c46b%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 72:00:05:00:52:c0 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::4edf:d55b:7fc6:e9ba%utun0 prefixlen 64 scopeid 0xa 
	nd6 options=201<PERFORMNUD,DAD>

================================================================================

Console Log:

2016-12-13 08:30:46 Tunnelblick[5813] Tunnelblick: OS X 10.12.1; Tunnelblick 3.6.10beta04 (build 4730)
2016-12-13 08:30:46 Tunnelblick[5813] Warning: preferences contain unknown preference 'NSWindow Frame SUUpdateAlert'
2016-12-13 08:30:48 Tunnelblick[5813] Set program update feedURL to https://www.tunnelblick.net/appcast-b.rss
2016-12-13 08:30:50 Tunnelblick[5813] Sparkle: ===== Tunnelblick.app =====
2016-12-13 08:30:50 Tunnelblick[5813] Sparkle: Verified appcast signature
2016-12-13 08:31:02 Tunnelblick[5813] Sparkle: Verified appcast signature
2016-12-13 08:37:59 esets[762] summ[02fa0700]: ESET démon: vdb=31716, agent=fac, name="/Users/trepliev/Library/Preferences/net.tunnelblick.tunnelblick.plist.Pi7xTzv", virus="", action="", info="Tato událost nastala na nově vytvořeném souboru.", avstatus="not scanned"

**Comment by jkbullard** [comment]
It's difficult to tell what's going on because the Tunnelblick Log is not shown.

However, since the problem probably has to do with OpenVPN trying to reconnect, I suggest you remove or comment out (by prefixing with a "#" or ";" character) the "persist-tun" option in your configuration file. It can often cause problems when reconnecting.

It might also be helpful to enable "Reset the primary interface after disconnecting" for this configuration.

An entry in the Console Log is also interesting:
<blockquote>2016-12-13 08:37:59 esets[762] summ[02fa0700]: ESET démon: vdb=31716, agent=fac, name="/Users/trepliev/Library/Preferences/net.tunnelblick.tunnelblick.plist.Pi7xTzv", virus="", action="", info="Tato událost nastala na nově vytvořeném souboru.", avstatus="not scanned"</blockquote>

This seems to indicate that Esets antivirus software is active on this computer. That could also be contributing the the problem; antivirus software often interferes with the operation of Tunnelblick.

The fact that "sudo kill -9 _pid_" doesn't terminate the Tunnelblick process is interesting because it seems to point to a problem with macOS itself. (Tunnelblick has nothing to do with a SIGKILL that is "sent" to it's process; SIGKILL is something that is done by OS X to terminate the process.)

**Comment by timemaster5** [comment]
Same problem here but only on one mac with configuration that works great on the others.. Hard reset is needed after a few minutes of connected state..

**Comment by Trepliev** [comment]
The problem disappeared after I removed the ESET antivirus.

**Comment by timemaster5** [comment]
confirmed

**Comment by brugnara** [comment]
This error still happens (Tunnelblick 3.7.2 (build 4850))

I'll try removing the `persist-tun` option. It's very awful.

**Comment by sepisoad** [comment]
The best and quickest solution is to find "ovpnagent" process and kill it, also kill tunnelbluck and its daemon

**Comment by jkbullard** [comment]
@sepisoad - What is the "ovpnagent" process and who creates it? It isn't a Tunnelblick or OpenVPN process.
