### ISSUE TITLE
Tunnelblick for Linux-based operating systems?

### ISSUE THREAD

**Issue by baimafeima** [Tunnelblick/Tunnelblick#348]
Are there any plans to make Tunnelblick available for Linux-based operating systems such as Debian, Fedora or Solus?

**Comment by jkbullard** [comment]
No, Tunnelblick is an OS X (now macOS) program and there are no plans that I'm aware of to make it available on any other OS. It is free software, so anybody could try, but it is written in Objective C and makes heavy use of OS-specific system calls, so I think that would be difficult.

**Comment by baimafeima** [comment]
Thank you for your reply. This currently makes Fruho the only universal VPN client for Linux-based operating systems that I am aware of.
