### ISSUE TITLE
beta/stable version no longer works in Mac OS 10.12.2

### ISSUE THREAD

**Issue by CaledoniaProject** [Tunnelblick/Tunnelblick#350]
Looks like the kext could not be loaded, any ideas?

```
tap: could not register character device switch.
Kext net.tunnelblick.tap start failed (result 0x5).
Kext net.tunnelblick.tap failed to load (0xdc008017).
Failed to load kext net.tunnelblick.tap (error 0xdc008017).
```

**Comment by jkbullard** [comment]
See [An OpenVPN log entry says "Tunnelblick: openvpnstart status #247: Error: Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 71"](https://tunnelblick.net/cCommonProblems.html#an-openvpn-log-entry-says-tunnelblick-openvpnstart-status-247-error-unable-to-load-net.tunnelblick.tun-andor-net.tunnelblick.tap-kexts-in-5-tries.-status-71).

**Comment by CaledoniaProject** [comment]
I do not have any of these kexts listed above ...

**Comment by jkbullard** [comment]
Please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) to get the info needed to diagnose problems and then post that info.

**Comment by jkbullard** [comment]
Closing this for lack of requested information.
