### ISSUE TITLE
Weird problems running on Sierra if build with Xcode 8

### ISSUE THREAD

**Issue by jkbullard** [Tunnelblick/Tunnelblick#353]
If Tunnelblick is built with Xcode 8 on Sierra (including at least up through 8.2.1), it has weird problems when running on Sierra. For example:
 1. After connecting, the icon shows the connected status correctly, but if you click on the icon the status is described as "No Active Connections".

 2. Tunnelblick neither logs that the IP address changed (when it should), nor complains that the IP address didn't change. This may be related to 1. 

The problems happen consistently when running on Sierra but don't happen when running on El Capitan.

**Comment by Bo98** [comment]
From my tests on Xcode 8.3.3 on macOS 10.12.6:

1. I do not experience this issue.
2. I experience the opposite - it complains that the IP didn't change **except** when "route all IPv4 traffic through the VPN" is enabled where it detects the IP change correctly.

**Comment by jkbullard** [comment]
@Bo98 - Thanks for your report, which seems to indicate that it works properly for you.

I will continue build the official Tunnelblick releases using Xcode 7 on El Capitan until I get reliable results (and at this point I will probably skip to Xcode 9).

**Comment by Bo98** [comment]
Considering Xcode 9 will be releasing next month, that seems fair.

**Comment by jkbullard** [comment]
Closing this -- Xcode 9 seems to fix this problem.
