### ISSUE TITLE
Crash on windows line ending in ca.crt file.

### ISSUE THREAD

**Issue by mikkeljohnsen** [Tunnelblick/Tunnelblick#356]
When dobbelt clicking a .tblk file Tunnelblick crashes. If not open it starts up and the closes again.

The problem is when a "ca.crt" is formatted in "/r/n" line ending.

**Comment by jkbullard** [comment]
@mikkeljohnsen - Thanks for your report, but I cannot reproduce this problem by changing a ca.crt file to have Windows line endings, so there must be something else going on, too.
 * What version of Tunnelblick are you using?
 * What version of OS X or macOS are you using?
 * Does OS X or macOS produce a "crash report"? If so, please post it or send it to developers@tunnelblick.net.
 * Does the same thing happen when you launch Tunnelblick and then drag the .tblk onto the Tunnelblick icon in the menu bar? (That is the recommended method to install a .tblk.)
 * Are you willing to help debug this? (That would involve sending a copy of your .tblk -- with private information obscured --  to developers@tunnelblick.net.)

**Comment by mikkeljohnsen** [comment]
* Newest version 3.7.0
* macOS Sierra
* See end
* Yes no matter what I do.
* Yes, can send you the ca.crt with the error.

It is a problem when detecting a "/r".

When I remove the "/r" from the ca.crt file, it works.

--
Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff95075e7b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffa9c5fcad objc_exception_throw + 48
2   CoreFoundation                      0x00007fff950f499d +[NSException raise:format:] + 205
3   CoreFoundation                      0x00007fff94fed876 -[__NSCFString characterAtIndex:] + 102
4   Tunnelblick                         0x00000001052f26a8 -[ConfigurationConverter removeOrReplaceCRs:] + 115
5   Tunnelblick                         0x00000001052f2839 -[ConfigurationConverter duplicateFileFrom:toPath:] + 282
6   Tunnelblick                         0x00000001052f3a2f -[ConfigurationConverter processPathRange:removeBackslashes:needsShExtension:okIfNoFile:ignorePathInfo:] + 3188
7   Tunnelblick                         0x00000001052f5d43 -[ConfigurationConverter convertConfigPath:outputPath:replacingTblkPath:displayName:nameForErrorMessages:useExistingFiles:logFile:fromTblk:] + 3646
8   Tunnelblick                         0x00000001052c45b9 -[ConfigurationManager convertOvpnOrConfAtPath:toTblkAtPath:replacingTblkPath:displayName:nameForErrorMessages:useExistingFiles:fromTblk:] + 244
9   Tunnelblick                         0x00000001052c4a20 -[ConfigurationManager convertInnerTblkAtPath:outerTblkPath:outerTblkInfoPlist:displayName:isInAnUpdatableTblk:] + 1006
10  Tunnelblick                         0x00000001052c5830 -[ConfigurationManager convertOuterTblk:haveOvpnOrConfs:] + 1210
11  Tunnelblick                         0x00000001052c5f54 -[ConfigurationManager setupToInstallTblks:haveOvpnOrConfs:] + 143
12  Tunnelblick                         0x00000001052c8bd4 -[ConfigurationManager installConfigurations:skipConfirmationMessage:skipResultMessage:notifyDelegate:disallowCommands:] + 1987
13  Tunnelblick                         0x00000001052c8f5a -[ConfigurationManager installConfigurations:skipMessages:notifyDelegate:disallowCommands:] + 77
14  Tunnelblick                         0x00000001052cd8d0 +[ConfigurationManager installConfigurationsShowMessagesNotifyDelegateOperation:] + 93
15  Foundation                          0x00007fff96a10c6d __NSThread__start__ + 1243
16  libsystem_pthread.dylib             0x00007fffaa75aaab _pthread_body + 180
17  libsystem_pthread.dylib             0x00007fffaa75a9f7 _pthread_body + 0
18  libsystem_pthread.dylib             0x00007fffaa75a1fd thread_start + 13

**Comment by jkbullard** [comment]
I have found a problem that could cause this, fixed it, and committed the fix (205f9b26). It will be included in the next Tunnelblick releases.

The crash that I found and fixed only happened when the last character of the file was a "\r". That would not be a normal Windows line ending, which would be "\r\n", with "\n" being the last character.

@mikkeljohnsen - Thanks again for your report. If this is not the problem you are having (that is, if the last character of your file is not a \r but Tunnelblick still crashes), please send the ca.crt file to developers@tunnelblick.net. 

I am closing this Issue but will reopen it if other problems still exist.
