### ISSUE TITLE
Tunnelblick should not warn about lack of public IP address when "route all traffic" is not selected

### ISSUE THREAD

**Issue by explody** [Tunnelblick/Tunnelblick#361]
Some time ago, Tunnelblick's behavior changed to now alert users that:

```
This computer's apparent public IP address was not different after connecting to XXX. It is still xx.xx.xx.xx.

This may mean that your VPN is not configured correctly.
```

But, unless "Route all IPv4 traffic through the VPN" is selected, a public IP address change should *not* be expected, which renders this warning as erroneous unless that option is indeed checked.

**Comment by jkbullard** [comment]
No.

If "Route all IPv4 traffic through the VPN" is not selected might not mean that the apparent public IP address should not change. It depends on what is in the OpenVPN configuration file, what the server "pushes" to the client, and what other routing is done.

If you don't want the warning:
 * Uncheck the setting to check for it; or
 * Select "Do not warn me about this again" when the warning appears.

**Comment by greggles** [comment]
I ran into this today as well.

* Can you clarify what the setting is that controls this?
* There is no option for "Do not warn me about this again".

**Comment by jkbullard** [comment]
Checking for IP address changes is a per-configuration setting.

On the "Settings" tab of the "Configurations" panel of the "VPN Details" window, there is a checkbox labelled "Check if the apparent public IP address changed after connecting".

If that checkbox _has_ a check, Tunnelblick will check and, if the warning has not been turned off (see below), will warn that the address didn't change.

If that checkbox _does not_ have a check, Tunnelblick will not check (and will not warn).

Note: checking for IP address changes also does not take place if there is a check in the "Inhibit automatic update checking and IP Address checking" checkbox on the "Preferences" panel of the "VPN Details" window.

============

There is a "Do not check for IP address changes" checkbox in the window that warns that the address didn't change. That label is misleading and will be changed in the next Tunnelblick beta release to read "Do not warn about this again for any configuration". It does not prevent checking for changes, it only stops the warning from appearing again (for any configuration). A warning will continue to be put into the Tunnelblick log when the address doesn't change, even if the warning is not being shown to the user.

**Comment by greggles** [comment]
Thanks so much for the thorough response!
