### ISSUE TITLE
Any way to make separate VPN connections use separate gateways?

### ISSUE THREAD

**Issue by bgdavidx** [Tunnelblick/Tunnelblick#362]
I have a bunch of private networks, all on the 172.XXX.XXX.XXX IP space. When I connect via Tunnelblick sometimes the VPNs end up connecting through the same gateway which only allows traffic from the first VPN to work.

Example:
```
$ netstat -nr
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
............
172.31             10.8.0.5           UGSc            1        0   utun3
172.32             10.8.0.5           UGSc            1        0   utun3
```

here 172.31.XXX.XXX and 172.32.XXX.XXX are using the same gateway, which only allows traffic from the first connected VPN to transfer.

OpenVPN config for server #1:
push "route 172.32.0.0 255.255.0.0"

OpenVPN config for server #2:
push "route 172.31.0.0 255.255.0.0"

Is there any way to make the two use different tunnels/gateways? Sometimes when I disconnect and connect a bunch of times they will eventually use different tunnels, but it doesn't happen every time and it's also a pain to have to connect and disconnect until things work.

**Comment by jkbullard** [comment]
This is really an OpenVPN configuration question -- OpenVPN does this; Tunnelblick itself doesn't have anything to do with it.
