### ISSUE TITLE
openvpn 2.4.1  - 05-tunnelblick-openvpn_xorpatch-d.diff patch fails

### ISSUE THREAD

**Issue by kapitainsky** [Tunnelblick/Tunnelblick#363]
when trying to apply xorpatch 05-tunnelblick-openvpn_xorpatch-d.diff for openvpn 2.4.1 it fails with the following output:

git apply 05-tunnelblick-openvpn_xorpatch-d.diff

error: patch failed: src/openvpn/socket.c:55
error: src/openvpn/socket.c: patch does not apply

All other patches work (02,  03,  04 and 06)

**Comment by jkbullard** [comment]
It works for me.

Did you download the Tunnelblick source code from GitHub and build it using the instructions in "Building Tunnelblick from Source Code.markdown"?

**Comment by kapitainsky** [comment]
well. I am not trying to build Tunnelblick but openvpn server (it runs on linux) and apply Tunnelblick openvpn_xorpatch. I was doing it for all previous openvpn versions without any issue. But now with openvpn 2.4.1 something is broken with one of the patch files.

**Comment by jkbullard** [comment]
As I said, it works when you're building Tunnelblick. Perhaps you have a bad download or mistyped something.

I suggest you look at the patch file itself (it is a single insertion into socket.c) and try to figure out what is going on.

**Comment by kapitainsky** [comment]
I pull openvpn source from https://swupdate.openvpn.org/community/releases/openvpn-2.4.1.tar.gz

then download all 2.4.1 openvpn_xorpatch from https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.1/patches

and apply them to openvpn source. It work for all but 05-tunnelblick-openvpn_xorpatch-d.diff

**Comment by jkbullard** [comment]
Try comparing your copy of OpenVPN with the one included in the Tunnelblick source code.

**Comment by kapitainsky** [comment]
the problem is in the line 5 of the 05-tunnelblick-openvpn_xorpatch-d.diff file.

It has only 3 instead of 5 leading spaces.

**Comment by jkbullard** [comment]
Ah. Interesting. That patch was the only one that didn't change (because it applied cleanly for me) in OpenVPN 2.4.1. Apparently the "patch" command on OS X is not as strict as the one you are using (on Linux?).

2.4.1 included reformatting changes to all of the files, and that included changing the indenting from two spaces per indent to four spaces per indent.

Commit  a9870926 adds two leading spaces to line 5 of the file and should resolve this problem.

Thanks for helping track this down.

**Comment by kapitainsky** [comment]
it works now. have not noticed that you updated 05-tunnelblick-openvpn_xorpatch-d.diff so got very confused that line 5 was not what I saw before:)

Anyway - thank you for being so prompt
