### ISSUE TITLE
route -n flush required to route some traffic through vpn

### ISSUE THREAD

**Issue by 2600box** [Tunnelblick/Tunnelblick#364]
I have an openvpn server on Debian 8 jessie. 

I connect, and whatsmyip services respond with the correct ip. when I try to ping a server that is blocked by isp, it fails with 'Can't assign requested address'

by running `route -n flush` a few times and then adding the local gateway and the vpn gateway with `route add default` I can ping to the server. this seems to be a common problem described by people that they fix by running a script. 

this should be handled by Tunnelblick without a script, right?

**Comment by jkbullard** [comment]
This is the first I've heard of this problem and solution. Can you provide references to it being "a common problem"?

Are you pinging by name or IP address? The "ping" command on macOS does not use the system's standard domain name resolution (and neither do several other commands).

Why would you have to run `route -n flush` several times for it to take effect?

**Comment by dafresh90** [comment]
Same for me here: tunnel seems to be established, but no data through vpn. All routes are correctly set, but no ping and not data through tunnel. 
_MACOS: 10.12.4 Tunnelblick: 3.7.1beta2_

`/sbin/ifconfig utun2 delete
 ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure`

**Comment by jkbullard** [comment]
@dafresh90 - And is that fixed by "repeated" `route -n flush` followed by `route add default`?

**Comment by dafresh90** [comment]
@jkbullard: can not confirm that workaround

**Comment by dafresh90** [comment]
Seems like the problem has finish of by restarting and updating openvpn service on server...

**Comment by jkbullard** [comment]
"ping" and several other commands do not use the standard macOS DNS resolution, so that may have something to do with this problem.
