### ISSUE TITLE
crush after using for a while & can't kill

### ISSUE THREAD

**Issue by looqy** [Tunnelblick/Tunnelblick#366]
Hi~    
Tunnelblick crushed and not work anymore after using for a while, I can not click the icon at the notice board nor restart it from Library which will prompt--"you can not open Tunnelblick, because it can't respond".    

I have tried to kill all processes  about tunnelblick, but it's not working, things still like above .   
My tunnelblick version is 3.7.0, and my system is MacOS sierra 10.12.3.    

I have meeted this situation a few times, at last I have to reboot my system to end it 😅    

my English level is so sad, sorry and thx!

**Comment by jkbullard** [comment]
I am sorry that Tunnelblick is not working correctly.

If your computer "sleeps", this may be the same problem as #355 ("Tunnelblick freezes after sleep"). Please look at that.

**Comment by dragz202** [comment]
Unsubscribe please. 

Thx

**Comment by jkbullard** [comment]
Closed. Assuming it was the sleep problem which was fixed in 3.7.5
