### ISSUE TITLE
Tunnelblick icon not clickable and notifications do not appear

### ISSUE THREAD

**Issue by inputvalidation** [Tunnelblick/Tunnelblick#368]
I'm on OS X 10.11.6 and Tunnelblick 3.7.0 (build 4790). Not sure exactly when it happens but at some point I can no longer click the Tunnelblick item in the top bar and notifications (connecting... etc) do not appear in the top right corner.

Strange thing is that Tunnelblick *is* still working, if I use CMD+space and type 'tunnelblick' I can still access it and my VPN connection is also up when I return my laptop from sleep. Only way to resolve it is to kill all processes or reboot my laptop.

Saw #355 but there it seems to freeze which is not what's happening in my case (only partially).

**Comment by rosatrancoso** [comment]
Happened to me too for the first time after 1 year using it.  Same OSX 10.11.6, Tunnelblick 3.6.4a (build 4561)

**Comment by jkbullard** [comment]
@rosatrancoso - Could it have been associated with waking up the computer after it was sleeping?

**Comment by rosatrancoso** [comment]
@jkbullard I think it was, but I couldn't replicate the issue so far.

**Comment by jkbullard** [comment]
@rosatrancoso - OK, thanks. That helps narrow it down.

**Comment by gsvitak** [comment]
Hello. 

I have been able to replicate. If you lock your screen while connected to a VPN connection, you will loose the ability to click on the icon and notifications do not appears. I am using latest version of High Sierra. 

As a work around, you can use System Monitoring and kill the Tunnelblick process. Alternatively, you can launch the application via application launcher. Your can then connect or disconnect any connection.

**Comment by jkbullard** [comment]
@gsvitak - I can't replicate it by locking the screen on latest High Sierra. Perhaps it has something to do with your configuration. Please get a "Spin Dump" in Activity Monitor for the Tunnelblick process when the problem occurs and either post it her or send it to my Gmail address, jkbullard. Thanks.

**Comment by gsvitak** [comment]
Thanks!! Just sent the spin dump.

**Comment by jkbullard** [comment]
Closed -- this was fixed in Tunnelblick 3.7.5.
