### ISSUE TITLE
IV_GUI_VER is missing

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#373]
for tunnelblick I see the following

```
Wed May 10 22:08:48 2017 x.x.x.x peer info: IV_VER=2.3.14
Wed May 10 22:08:48 2017 x.x.x.x peer info: IV_PLAT=mac
Wed May 10 22:08:48 2017 x.x.x.x peer info: IV_PROTO=2
```

it would be very nice to see  IV_GUI_VER as well, for example, as for windows:
```
peer info: IV_GUI_VER=OpenVPN_GUI_11
```

it would help to identify tunnelblick users in server logs

**Comment by jkbullard** [comment]
Commit 6243a286da7b7e131f66f546cf81e26a0fa442fa fixes this.

IV_GUI_VER is set to
 * The CFBundleIdentifier
 * A space
 * The CFBundleVersion
 * A space
 * The CFBundleShortVersionString

(The CFBundleIdentifier and CFBundleVersion do not contain any spaces, but the CFBundleShortVersionString may contain spaces.)

Example "net.tunnelblick.tunnelblick 4840 3.7.2beta03 (build 4840)"
