### ISSUE TITLE
Menu bar icon not aligned

### ISSUE THREAD

**Issue by jbernardo95** [Tunnelblick/Tunnelblick#375]
Hi !

Every time I looked at the Tunnelblick icon it seemed odd to me. Today I decided to check it.

<img width="729" alt="screen shot 2017-05-20 at 17 58 56" src="https://cloud.githubusercontent.com/assets/6342528/26277766/74cbbff8-3d86-11e7-9872-fbfca11de743.png">

As you can see from the image above, the icon fells out of the normal menu bar icon guard zone. Is this on purpose ? Or is this something that should be fixed ?

I personally think it should be fixed, and as I was getting around your repo I could not find an editable version of the icon so that I could resize it and see how it would look. Do you have an editable version of the icon ? I am open to help and fix this.

**Comment by jkbullard** [comment]
I don't know what you mean by "normal menu bar icon guard zone" -- what's that?

Assuming that's something that Apple says shouldn't be used, I am open to a PR that would fix the problem. But it's complicated; there are a lot of images!

The "icon" in the menu/status bar isn't a .icon file. It is a set of .png files:
 * open.png
 * closed.png
 * 0.png
 * 1.png
 * 2.png
 * 3.png

The images are sequenced to animate the image when connecting or disconnecting.

The tunnelblick/IconSets folder contains subfolders for several different icons: "standard", "monochrome", and "3.3" (see the "Appearances" panel of the "VPN Details" window). Both .png and .psd files are usually included in the subfolder.

There are usually two different versions of each icon, a normal version and a version for when the icon is highlighted. You can ignore the "large-..." version; that isn't displayed in the menu/status bar.

**Comment by jbernardo95** [comment]
"normal menu bar icon guard zone" is something I came up with. What I meant is that the Tunnelblick icon is the only one that fells out of the red line.

As it is the only one the overall bar becomes visually unbalanced. As far as I can tell Apple does not have guidelines for menu bar icons.

I checked the IconSets folder, but the only `.psd` files that exist are for the "3.3", the other ones only includes `.tiff` files...

**Comment by jkbullard** [comment]
The icon to the left of the Tunnelblick icon goes lower than your guard bar, too. And many other third-party icons that I have do (all of the iStatMenu icons, for example). Try adding all the other Apple icons, -- I think the Bluetooth icon, the volume icon and the "person" icon (for Fast User Switching or whatever it's called) are the height of the current Tunnelblick icon.

In any case, you can fool around with custom icons easily; see [Icon Animation](https://tunnelblick.net/cIconAnimation.html).

And if you want to make a PR for a new set, or a replacement set, I'll be happy to look at it.

**Comment by jbernardo95** [comment]
@jkbullard Fair enough.

Can close the issue.
