### ISSUE TITLE
Add option to keep the VPN status window visible while connected

### ISSUE THREAD

**Issue by goulvench** [Tunnelblick/Tunnelblick#377]
I connect to a VPN only to run long-running commands on a server. I often forget to check back and disconnect, therefore remaining connected for no reason. Showing the VPN connection window as long as I am connected would make it much harder to forget disconnecting when I am done. This would save traffic, and force me to retype my password before running potentially harmful commands, in case I run them in the wrong environment.
I don't know if this requires many changes, but it would be very appreciated. Thanks!

**Comment by brightcode** [comment]
I have the same problem, forgetting that you are connected with VPN. It shouldn't be too hard to keep the status window floating on top. This would help me a lot.

**Comment by Olivermz** [comment]
That would be a great enhancement
I also tend to forget when I am connected through a VPN

**Comment by jkbullard** [comment]
@goulvench, @brightcode, @Olivermz - Have you tried using a colored icon (in the "Appearance" panel)?

**Comment by brightcode** [comment]
I use Tunnelblick 3.7.3 on MacOS. I see 3 Icon options: Standard icon, Monochrome icon, Tunnelblick 3.3 icon. But they are all grey/black and don't stand out of the menu when connected.

**Comment by jkbullard** [comment]
@brightcode -- Sorry, you're absolutely correct, my mistake. Color icons have not been accepted into the master branch from which Tunnelblick releases are built.

Please try out colored icons. I have attached is a .zip of a folder named "IconSets". Copy the folder to your /Library/Application Support/Tunnelblick/Shared folder and two slightly different colored icons will be available the next time you launch Tunnelblick.

(To get to /Library/Application Support/Tunnelblick, open a Finder window and click the "Go" menu, then "Go to folder…" copy/paste **/Library/Application Support/Tunnelblick** into the dialog box, and click "Go".)

I am wondering if different colors would be better: the usual grey icon when disconnected, but a brighter green icon when connected, and bright yellow when connecting/disconnecting. The dull green in these icon sets are too dull for me, though -- I would prefer them brighter.

[IconSets.zip](https://github.com/Tunnelblick/Tunnelblick/files/1441340/IconSets.zip)

**Comment by brightcode** [comment]
@jkbullard Thank you for that. I have installed the icons. This will improve visibility and awareness of VPN status. I hope I don't forget I'm on VPN again...

For me a grey icon when disconnected would be better. But I can imagine that others want to be alerted when they are not using VPN. And yes, the green does not stand out as much as the red.

Perhaps the MacOS window controls would be a good color. The red is #FF5F58, the yellow is #FFBD2E, the green is #28C941.

**Comment by goulvench** [comment]
@jkbullard Unfortunately, the icons are hidden when working full-screen, as I tend to do. I would really appreciate if the status window stayed visible on top.
I usually connect to VPN to perform actions on a server, and when I start focusing on the action itself I tend to forget entirely about the connection. When I get interrupted or if I leave a tab tracking a logfile open, it often happens that I completely forget about VPN status.
Our brains are just not wired for remembering states :-)

**Comment by jkbullard** [comment]
Ah, fullscreen, I understand. I never use it myself.

I will put this on my list. (But it's a long list…)

**Comment by jkbullard** [comment]
@goulvench, @brightcode, @Olivermz - I took a quick look at this and realized it was very easy to add a "Show when connecting and connected" option for the status window.

If anyone would like to try out a version of Tunnelblick which includes this, they should email developers at tunnelblick dot net and I will send it to them in return for feedback about any problems with it.

**Comment by jkbullard** [comment]
@goulvench, @brightcode, @Olivermz - This feature is now included in Tunnelblick 3.7.4a and 3.7.5beta02.
