### ISSUE TITLE
Automatically choose OpenVPN ≥2.4 if GCM cipher mode is used

### ISSUE THREAD

**Issue by Nirusu** [Tunnelblick/Tunnelblick#378]
Hi,

Given the following scenario:
My university provides .ovpn and .tblk config files to allow students to connect to the university's VPN network. Recently, they switched the cipher algorithm to "aes-128-gcm", which is only supported from OpenVPN 2.4 on. Now, Tunnelblick still seems to use OpenVPN 2.3 as standard, and if you import the .tblk file and forget to set the version to OpenVPN 2.4 afterwards, you get the following error while connecting:

> Tue May 30 16:01:39 2017 us=105730 Cipher algorithm 'AES-128-GCM' not found
Tue May 30 16:01:39 2017 us=105825 Exiting due to fatal error

That doesn't seem intuitive and can be confusing, so I think it would be a good idea if Tunnelblick would notify the user that OpenVPN 2.4 is required and automatically switch (or prompt the user) to the recommended version ≥2.4. Or maybe it would be possible to add a field with the minimum required OpenVPN version in the .tblk file, although I guess the automatic detection would be better.

**Comment by jkbullard** [comment]
Thanks for the suggestion, but it seems like this is a fairly temporary problem.

2.3 will be removed soon, probably from the next beta (2.4 and a git-master version of OpenVPN will be included).

In the meantime, you could include an Info.plist file in the .tblk for each configuration that includes an entry that sets "-openvpnVersion" to "-". The "-" is the same as "the most recent version of OpenVPN, with the LibreSSL library". See [Tunnelblick VPN Configurations Details](https://tunnelblick.net/cPkgs.html) and [Preferences](https://tunnelblick.net/cPreferences.html) -- although that specific preference ("-openvpnVersion") is not documented, by default the earliest version of OpenVPN with OpenSSL is used, a value of "-" uses (as written above) the latest version of OpenVPN with LibreSSL, and other values are interpreted as specific OpenVPN versions.
