### ISSUE TITLE
IPv6 DNS Servers not supported 

### ISSUE THREAD

**Issue by zhovner** [Tunnelblick/Tunnelblick#379]
In OpenVPN 2.4 new option `dhcp-option DNS6` was added: https://community.openvpn.net/openvpn/ticket/243  
This option allows to assign ipv6 dns resolvers to the client. 
It's required for correct ipv6 support in applications like web browsers.

OpenVPN server config:
```
.....
# Google Public DNS
push "dhcp-option DNS6 2001:4860:4860::8888" 
push "route-ipv6 2001:4860:4860::8888"

push "dhcp-option DNS6 2001:4860:4860::8844" 
push "route-ipv6 2001:4860:4860::8844"
.....
```

Tunnelblick with OpenVPN 2.4.2 can't recognise this option: 
```
 **********************************************
 Start of output from client.up.tunnelblick.sh
 WARNING: 'foreign_option_3' = 'dhcp-option DNS6 2001:4860:4860::8888' ignored
 WARNING: 'foreign_option_4' = 'dhcp-option DNS6 2001:4860:4860::8844' ignored
```

You can use my public vpn profile for testing this issue: https://zaborona.help/zaborona-help.ovpn

Tunnelblick version: **3.7.2beta02_build_4830**
macOS: **10.12.5 Sierra**

**Comment by JohnsonGoey** [comment]
Yes, i am getting this problem too, if i am using pure ipv6 connection to connect openvpn server ,it will get the ipv6 changes to mine openvpn server address, which is correct, but the ipv6 dns still remain what my router give me.

**Comment by adudek16** [comment]
+1

**Comment by petraks** [comment]
Same problem

**Comment by jkbullard** [comment]
Support for OpenVPN's`dhcp-option DNS6` was added in Tunnelblick 3.7.7beta03.
