### ISSUE TITLE
Bug with configuration names containing a trailing dot

### ISSUE THREAD

**Issue by yurisend** [Tunnelblick/Tunnelblick#381]
Not really a crippling issue, but it threw me off for a second

The configuration file won't be located when you try to connect

In the GUI, all you can do is remove the configuration whose name contains the trailing dot char; you cannot rename. 

Based on the log, it seems like the illegal character is recognized, but the rename is still allowed

Excerpt from log contents: 

```
2017-06-07 15:43:42 Tunnelblick[3167] Error status 237 returned from 'openvpnstart printSanitizedConfigurationFile myconfig. 0'
2017-06-07 15:43:42 Tunnelblick[3167] Error returned from 'openvpnstart printSanitizedConfigurationFile myconfig. 0':
                                       Configuration name has one or more prohibited characters or character sequences
```

**macOS 10.12.5**

**Comment by jkbullard** [comment]
Thanks for your report.

I have fixed the GUI to not allow you to rename a configuration to have a trailing period (commit c1e82644e3b97c274e703fcc17f39c36dfd336e2).
