### ISSUE TITLE
Add "ignore home network" on auto-connect option

### ISSUE THREAD

**Issue by afonseca08** [Tunnelblick/Tunnelblick#384]
It'd be great to have the ability to specify the SSID of your home network and then be able to specify that auto-connect not take place when on the home network. 

I'm running a VPN server at home on my wireless router and use Tunnelblick to connect to it when I'm away from home on unsecured networks. When I get home I'd like to still leave Tunnelblick running but not have it try to connect to the home VPN server.

There are scripting ways to accomplish this I'm sure but it'd be a nice feature to have built in as VPN servers built into wireless routers become more mainstream.

**Comment by wingsuitist** [comment]
That would be an amazing option => maybe not based on the SSID, as it's not always a Wifi but maybe based on an IP-Range or Gateway address or Gateway Mac-Address. 

A button like "this is my internal network" which then captures the gateway mac address would  be amazing.

I could write it as a shellscript, but it makes much more sense to integrate it into the app and config.

**Comment by jkbullard** [comment]
@wingsuitist - This isn't going to be in Tunnelblick any time soon unless someone else does it. If you write a script to do it, please send it to me at developers@tunnelblick.net so it can be added to Tunnelblick's [User-Contributed Downloads](https://tunnelblick.net/downloads.html#user-contributions).
