### ISSUE TITLE
Tunnelblick 3.7.2beta03 - Lack of new "compress lz4" feature

### ISSUE THREAD

**Issue by WillyTP** [Tunnelblick/Tunnelblick#390]
Hello everybody,
I'm using a particular setup, using the new feature of OpenVPN 2.4+ "compress lz4".

For details:
https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage

In a few words, the --compress parameter will replace the --comp-lzo.

As it seems, Tunnelblick doesn't recognize this parameter.
I get the following error:

Options error: Unrecognized option or missing parameter(s) in /Library/Application Support/Tunnelblick/Users/William/MacBookPro-TCP.tblk/Contents/Resources/config.ovpn:122: compress (2.3.17)

**Comment by jkbullard** [comment]
To use a feature that is in OpenVPN 2.4, you need to use OpenVPN 2.4. You are using 2.3.17.

Select the version of OpenVPN to use in the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" menu.

If you change a setting such as this one, it will be changed for all configurations that are selected in the list on the left side of the "Configurations" panel.
