### ISSUE TITLE
Menubar icon doesn't shade with multiple spaces on multiple monitors

### ISSUE THREAD

**Issue by mdbraber** [Tunnelblick/Tunnelblick#398]
Hi,

I have a setup with two monitors and different spaces on each monitor. This means that each monitor gets its own menubar. The inactive monitor's menubar becomes shaded (I'm running OS X dark) which "grays out" all the white in menubar icons. Except for Tunnelblick it seems. See the included  screenshots for an idea (btw - the green hue is due to the transparency / my background image). 

![shaded](https://user-images.githubusercontent.com/1781890/29262751-3597b326-80d6-11e7-9da4-12e72bb47931.png)
![non-shaded](https://user-images.githubusercontent.com/1781890/29262752-35ae52ac-80d6-11e7-8bfd-ae0db2fb405b.png)

Assuming this is not intentional (I can see Tunnelblick on both screens clear whether it's connected or not) - can this be fixed?

**Comment by Bo98** [comment]
Does this happen with the standard icon? They are treated quite differently in code now.

**Comment by mdbraber** [comment]
Hi Bo,

This only goes wrong with the Tunnelbick 3.3 icon.

Thanks for looking into this!

Maarten

On Wed, Aug 16, 2017, at 15:10, Bo Anderson wrote:
> Does this happen with the standard icon? They are treated quite
> differently in code now.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
Maarten den Braber
+31613897073
mdbraber.com


Links:

  1. https://github.com/Tunnelblick/Tunnelblick/issues/398#issuecomment-322765821

**Comment by jkbullard** [comment]
Not going to fix this for the (very) old Tunnelblick 3.3 icon.
