### ISSUE TITLE
DNS problem on Sierra

### ISSUE THREAD

**Issue by adrianmihalko** [Tunnelblick/Tunnelblick#401]
I successfully installed OpenVpn via pivpn on my rPi Zero and I can connect from my iPhone without any problem (OpenVPN client). I can browse internet, I can access my LAN devices.

The problem is with Mac OS X client, the nameservers are not be set (pinging ip's are working like ping 8.8.8.8, or my internal LAN).
After connecting to xy, DNS does not appear to be working.
This may mean that your VPN is not configured correctly.

Output:

https://pastebin.ca/3857090

**Comment by jkbullard** [comment]
This:
> WARNING: Ignoring ServerAddresses '8.8.8.8 8.8.4.4' because ServerAddresses was set manually and '-allowChangesToManuallySetNetworkSettings' was not specified

is the problem.

Select the configuration on the left side of the Configurations panel of Tunnelblick's "VPN Details" window, then click the "Advanced" button on that panel's "Settings" tab, and put a check in "Allow changes to manually-set network settings" on the Advanced window's "Connecting & Disconnecting" tab.

**Comment by adrianmihalko** [comment]
Thanks! It's working! :)

**Comment by FredClement91** [comment]
Confirmed, it's working.
