### ISSUE TITLE
Add support for OpenVPN-AS / standard https configuration retrieval

### ISSUE THREAD

**Issue by SerialVelocity** [Tunnelblick/Tunnelblick#403]
Hey @jkbullard,

Love Tunnelblick so far! It would be great if you could add support for configuration retrieval from https endpoints.

It would be great if there was support for not only getting the configuration once (what Viscosity does) but also getting it every time I try and connect to the VPN (like Cisco AnyConnect does).

For OpenVPN-AS support, you need to take in a URL and append `/rest/GetUserLogin` and an OpenVPN client configuration is returned (preferably don't just take in a host as it is nice to have `vpn.domain.com/full-vpn` and `vpn.domain.com/split-vpn`) (spec is [here](https://openvpn.net/images/pdf/REST_API.pdf))

For standard https support (up to you if you think this is useful), you just hit a user-defined URL and an OpenVPN client configuration is returned.

The OpenVPN-AS URL is usually (if not always) secured using basic authentication.

If on-connect configuration retrieval is added, it would be great if it would be possible to re-use the credentials used to retrieve the configuration as login credentials to connect to the VPN.

Thanks for reading,
Ben

**Comment by jkbullard** [comment]
Tunnelblick's [Updatable Configurations](https://tunnelblick.net/cNewUpdatableConfigurations.html) do this.
