### ISSUE TITLE
Add support for TUN ipv6 and routing all ipv6 traffic over VPN

### ISSUE THREAD

**Issue by SerialVelocity** [Tunnelblick/Tunnelblick#404]
Hey @jkbullard,

Love Tunnelblick so far! It would be great if you could add support for TUN ipv6 and tunneling all ipv6 traffic over the VPN. OpenVPN 2.3.0+ [supports this](https://community.openvpn.net/openvpn/wiki/IPv6).

Thanks,
Ben

**Comment by kpfleming** [comment]
I'm already doing this with Tunneblick, using a hand-written configuration file. I wasn't aware that it was unsupported or didn't work!

**Comment by SerialVelocity** [comment]
This may already be done. I may have just got confused because in the advanced settings it has "Enable IPv6 (tap only)" that is greyed out so I probably thought it wasn't going to work. (Just now I saw the "Disable IPv6 (tun only)" option outside of the advanced settings. Maybe they should be combined into one option?

It also didn't work when using OpenVPN 2.3.x but did when I used OpenVPN 2.4.x but it looks like that is because I was using `redirect-gateway ipv6` which is only supported in OpenVPN 2.4.x and above.

**Comment by jkbullard** [comment]
Tunnelblick should work OK except in an IPv6-only setup. I expect that to be fixed in the next beta and will keep this issue open until then.

Regarding combining "DIsable IPv6 (tun only)" and "Enable IPv6 (tap only)", they can't be combined. They do two different things.

**Comment by jkbullard** [comment]
As far as I know, Tunnelblick works with IPv6, depending on which version of OpenVPN is being used and what options the OpenVPN configuration includes and are pushed from the OpenVPN server.
