### ISSUE TITLE
dns issue when connecting to 2 openvpn servers at the same time

### ISSUE THREAD

**Issue by hsvlz** [Tunnelblick/Tunnelblick#405]
Hi,

I have setup 2 identical openvpn servers - both servers resolve internal DNS.
```
push "dhcp-option DOMAIN server1"
push "dhcp-option DNS 10.30.0.2"
```
and
```
push "dhcp-option DOMAIN server2"
push "dhcp-option DNS 10.31.0.2"
```

When I connect to one von at the time, I can resolve the internal DNS on such location.

However, if I connect to both vpns at the same time, I can only resolve DNS of the server that was connected first. (This is confirmed by looking at scutil --dns)
When checking the logs of the second vpn connection, I can see:
```
WARNING: Ignoring DomainName 'server2' because DomainName was set manually
WARNING: Ignoring ServerAddresses '10.31.0.2' because ServerAddresses was set manually
WARNING: Not prepending domain 'server2' to search domains 'server2' because the search domains were set manually
```

and I guess that the 'manually set DomainName' refers to the one set by server1.

What would be the solution?
Thank you for your help!

**Comment by jkbullard** [comment]
What exactly do you want? On macOS, you only have one DNS server active at any one time (unlike Windows, which sends DNS queries to all nameservers).

Tunnelblick's include up/down scripts do not handle "split DNS" or "split tunneling", which may be what you want. You would have to do that yourself, or use a different VPN client that supports split DNS.

**Comment by jkbullard** [comment]
Perhaps Viscosity; I don't know.
