### ISSUE TITLE
3.7.4beta01 build 4890 (2017-10-19) - recording IP address on installing or upgrading

### ISSUE THREAD

**Issue by dnivi3** [Tunnelblick/Tunnelblick#406]
I noticed that in the [release notes for 3.7.4beta01 build 4890 (2017-10-19)](https://tunnelblick.net/cRlsNotes.html#version-3.7) it states that:

>- Requires the user's consent to terms of use before installing or updating and logs the install or update to the Tunnelblick website. (Other than the IP address, no personally identifiable information is sent.)

I can see that the relevant commit is 7a37c51e9d4d7de7e9d9f9a55323d6f9f3d7e6cc.

This has privacy implications for users as IP addresses are sensitive information and brings up several questions: 

- What is the IP address retention policy?
- What are the IP addresses collected upon installing or updating Tunnelblick used for?
- Why do the IP addresses have to be collected?

**Comment by jkbullard** [comment]
Please see [Privacy and Security](https://tunnelblick.net/cPrivacy.html).

(Of course, you'll have to visit the website to do that, but what is logged for that is pretty much the minimum of what any website logs.)

**Comment by dnivi3** [comment]
@jkbullard: I already checked out that page. The question remains: why are you only now recording the IP address of every install or upgrade? Why did this recently change?

**Comment by jkbullard** [comment]
@dnivi3 - As it says on the page I linked to (in at least four places), it changed so an estimate of the number of installations and upgrades of Tunnelblick could be kept. It changed _recently_ because I had not had time to do it until recently.

**Comment by srcshelton** [comment]
@jkbullard This is, you realise, a *terrible* way of gathering usage metrics: you've provided no opt-out, no justification in the product itself - and the end result will be people forking your codebase and removing the links back to your site, fragmenting the product and overall making your life more difficult.

Providing no opt-out and aborting if the user does not agree is aggressive and belittling of your user-base.  Also note that the GPL explicitly states "You are not required to agree to anything to merely use software which is licensed under the GPL", so you could be seen to be applying an additional restriction beyond what the GPL allows.  In any case, by collecting this data and not providing an opt-out, you may be opening yourself to significant liabilities under the EU GDPR (https://ico.org.uk/for-organisations/data-protection-reform/overview-of-the-gdpr/) - bear in mind that IP addresses are specifically classified as personally-identifiable information (https://www.enterprisetimes.co.uk/2016/10/20/ecj-rules-ip-address-is-pii/) and as such an opt-out from data collection is required (https://iapp.org/news/a/top-10-operational-impacts-of-the-gdpr-part-3-consent/) as is a clearly documented method to withdraw consent and have all collected data destroyed. 

Please reconsider this change, given the friction that it has and will inevitably continue to cause.

**Comment by jkbullard** [comment]
I have removed the problematic dialog and attempted access to tunnelblick.net. The changes are included in Tunnelblick 3.7.4a and 3.7.5beta02.
