### ISSUE TITLE
Updater does not respect Do Not Disturb

### ISSUE THREAD

**Issue by lwahonen** [Tunnelblick/Tunnelblick#409]
Having my computer in Do Not Disturb for a slideshow, I still get these notifications on top of whatever I'm presenting currently.

<img width="732" alt="screenshot 2017-11-12 22 54 41" src="https://user-images.githubusercontent.com/3996667/32713168-d8712dee-c7fc-11e7-94ce-f254c0617bd5.png">

**Comment by jkbullard** [comment]
Thanks for your report. I'm sorry this happened during your presentation.

The Sparkle Updater software that Tunnelblick uses to process updates doesn't use the Notification Center, so it isn't affected by Do Not Disturb.

There has been discussion by the Sparkle developers about using the Notification Center but as I recall they decided it couldn't display enough information and so they aren't going to use it.

I will look into having Tunnelblick itself disable Sparkle's update checks while Do Not Disturb mode is active. (And having Sparkle honor Do Not Disturb, but that's less likely).

For now, all I can suggest is that you quit Tunnelblick, or inhibit update checks in Tunnelblick's "Preferences" panel. But remembering to turn them back on could be problematic.

**Comment by martinosorb** [comment]
An additional problem is that, during updates, the window with the download status bar will not go to the background. This is slightly annoying. More annoying is that I have to click on "install and relaunch", otherwise the popup won't go away, and sometimes I may need to wait before relaunching, as I may have a connection that shouldn't be interrupted.

**Comment by kwin** [comment]
AFAIK this has been fixed in Sparkle in https://github.com/sparkle-project/Sparkle/commit/7a30cca92cb222d7079126387530fc972c712de0 (compare with https://github.com/sparkle-project/Sparkle/issues/1064).

**Comment by jkbullard** [comment]
Thanks, @kwin.

This is fixed in Tunnelblick 3.7.8beta01 via 4961191.
