### ISSUE TITLE
documentation bug

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#411]
link to pkcs11-helper here https://github.com/Tunnelblick/Tunnelblick/blob/master/third_party/README.txt#L160 is wrong

1.22 is available on github: https://github.com/OpenSC/pkcs11-helper

**Comment by jkbullard** [comment]
@chipitsine - Thanks. The link didn't get updated the last time pccs11-helper was updated, in PR #393.

A PR would be appreciated!

I can't verify that GitHub was the origin of the source code in PR #393, it matches the source code from GitHub. That was verified when the PR was accepted, so it is indeed only the link in the documentation, not the source code, that is the problem.

**Comment by chipitsine** [comment]
sure,  https://github.com/Tunnelblick/Tunnelblick/pull/412

**Comment by jkbullard** [comment]
Thanks!
