### ISSUE TITLE
Add Quad9 to the list of free and public DNS services

### ISSUE THREAD

**Issue by FlorianLoch** [Tunnelblick/Tunnelblick#414]
![image](https://user-images.githubusercontent.com/5587805/33028597-a4011824-ce16-11e7-8198-ba30b3c4e8d3.png)

Just read that warning and thought Quad9 DNS should be added as it seems to be a major upcoming player in its domain.

Quad9: [https://www.globalcyberalliance.org/initiatives/quad9.html](https://www.globalcyberalliance.org/initiatives/quad9.html)

**Comment by jkbullard** [comment]
@FlorianLoch  - Thanks.

I agree. Actually, I not only agree -- I committed a change for that to my local repo several hours ago! It will appear in the GitHub repo the next time I sync, and it will be in the next beta release -- both probably later this week.

Let's leave this Issue open until then.

**Comment by jkbullard** [comment]
Fixed in  commit 3d57a0ddfcbaeba95c1d6affd48852a0f7b799c6.
