### ISSUE TITLE
status window does not automatically close when after disconnecting

### ISSUE THREAD

**Issue by agalathynius** [Tunnelblick/Tunnelblick#416]
after manually disconnecting, the status windos remains on screen and does not fadeout like the connected status screen. In settings I have vpn status window: show when connection status changes. This seems to be a bug introduced recently since I have not observed this before and my settings for tunnelblick has not been changed. anyone confirms? thanks!

**Comment by jkbullard** [comment]
Thanks for reporting this. I can replicate it and will look into fixing it. It probably has something to do with adding "Show while connecting and connected", which was done recently

For now, you can close the window manually by clicking the "X" in the upper left corner, or move the pointer over the window and then outside of the window.

**Comment by jkbullard** [comment]
This is fixed in Tunnelblick 3.7.5beta04.
