### ISSUE TITLE
Update to 3.7.5beta03 breaks all connectivity

### ISSUE THREAD

**Issue by bradmurray** [Tunnelblick/Tunnelblick#418]
I just updated this morning and I can't get anything to connect even after a reboot. The log window simply says "Disconnecting; VPN Details... window connect button pressed" when I hit connect. It's supposed to be auto-connecting to my default config on launch so I think it thinks it's doing that, but nothing happens.

Also, the splash dialog seems to come up on launch and never go away. I'm going to try going back to the previous version.

Reverting to beta02 solved the problem. OSX 10.13.1

**Comment by iMiMx** [comment]
Same, 3 users seeing the same.  Using 10.12 and 10.13.1

**Comment by winsmith1984** [comment]
Same here, using 10.13.1

**Comment by jkbullard** [comment]
Tunnelblick 3.7.5beta03 has been withdrawn from distribution and earlier versions will not update to it.

It has a bug which can cause unpredictable behavior. Tunnelblick 3.7.5beta04 will correct the bug and be available soon, possibly as early as Thursday December 7, but more likely on Friday, December 8. It will also include OpenSSL version 1.0.2n.

A fix for this bug has been committed to Tunnelblick's GitHub source code repository.

**Comment by bradmurray** [comment]
Just installed beta04 and while it doesn't have the same problem I still can't connect to anything. It just keeps saying host is down in the log. Reverting to beta02 solved the problem again.

**Comment by jkbullard** [comment]
@bradmurray - Please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) to get the info needed to diagnose problems and then post that info.
