### ISSUE TITLE
Can't connect after having updated to OSX 10.13.2 (Tunnelblick 3.7.5 beta04)

### ISSUE THREAD

**Issue by rr-appadaptive** [Tunnelblick/Tunnelblick#419]
After having updated my iMac (Late 2012) to OSX 10.13.2 the VPN-connection is refused (cannot start...).  I had to downgrade to build 4920 (3.7.4a) to get Tunnelblick working again.

**Comment by Spooky1977** [comment]
after updating to 3.7.4b (build 4921) VPN Connection doesnt work on macOS 10.13.2 (temporarily workaround remove the line with `remote-tls`. that will work (or comment it)

**Comment by jkbullard** [comment]
See [this discussion](https://groups.google.com/forum/#!topic/tunnelblick-discuss/BDtZF17zEEQ).
