### ISSUE TITLE
route-up script not executed - 3.7.4b (build 4921)

### ISSUE THREAD

**Issue by antigraviton** [Tunnelblick/Tunnelblick#420]
Since the last update, the route-up script is no longer executed, where the route-pre-down script is.

**Comment by jkbullard** [comment]
Thanks for your report.

Please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) to get the info needed to diagnose problems and then post that info.

**Comment by jkbullard** [comment]
Closed for lack of response.
