### ISSUE TITLE
Tunnelblick website down: Response data was too long

### ISSUE THREAD

**Issue by Michael-LLD** [Tunnelblick/Tunnelblick#424]
2018-01-11 10:22:50 Tunnelblick[752] currentIPInfo(Name):  Response data was too long (5776 bytes)
2018-01-11 10:22:50 Tunnelblick[752] An error occured fetching IP address information before connecting

**Comment by jkbullard** [comment]
This was fixed by  commit 6de3233ada on 2017-11-28. It is included in beta versions since 3.7.5beta03.

**Comment by jkbullard** [comment]
Sorry, that was much too hasty of me.

5776 bytes is way too long. Is it consistent? If so, in a browser go to `https://tunnelblick.net/ipinfo` and post the result.

**Comment by Michael-LLD** [comment]
My Tunnelblick is lastet version. I can connect vpn, but that confused me reminds “An error occured fetching IP address information before connecting” every time  when i ready to connect vpn.

**Comment by jkbullard** [comment]
@Michael-LLD - Please use a browser to go to `https://tunnelblick.net/ipinfo` and post what you see. If possible, post the result of a "Show Page Source", "View Source", or equivalent (the exact command depends on your browser).

**Comment by Michael-LLD** [comment]
<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>


<title>tunnelblick.net | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css <https://tunnelblick.net/cdn-cgi/styles/cf.errors.css>" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>

<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js <https://tunnelblick.net/cdn-cgi/scripts/zepto.min.js>"></script>
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js <https://tunnelblick.net/cdn-cgi/scripts/cf.common.js>"></script>

</head>
<body>
<div id="cf-wrapper">


<div id="cf-error-details" class="cf-error-details-wrapper">
<div class="cf-wrapper cf-error-overview">
<h1>
<span class="cf-error-type" data-translate="error">Error</span>
<span class="cf-error-code">520</span>
<small class="heading-ray-id">Ray ID: 3db4b34bdc8aa2fc &bull; 2018-01-11 03:13:29 UTC</small>
</h1>
<h2 class="cf-subheadline" data-translate="error_desc">Web server is returning an unknown error</h2>
</div>

<div class="cf-section cf-highlight cf-status-display">
<div class="cf-wrapper">
<div class="cf-columns cols-3">
<div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-browser"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="browser_desc">You</span>
<h3 class="cf-status-name" data-translate="browser_label">Browser</h3>
<span class="cf-status-label" data-translate="browser_status_label">Working</span>
</div>

<div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status ">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-cloud"></i>
<i class="cf-icon-status cf-icon-ok"></i>
</div>
<span class="cf-status-desc" data-translate="cloud_desc">Hong Kong</span>
<h3 class="cf-status-name" data-translate="cloud_label">Cloudflare</h3>
<span class="cf-status-label" data-translate="cloud_status_label">Working</span>
</div>

<div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source">
<div class="cf-icon-error-container">
<i class="cf-icon cf-icon-server"></i>
<i class="cf-icon-status cf-icon-error"></i>
</div>
<span class="cf-status-desc" data-translate="server_desc">tunnelblick.net</span>
<h3 class="cf-status-name" data-translate="server_label">Host</h3>
<span class="cf-status-label" data-translate="server_status_label">Error</span>
</div>

</div>
</div>
</div>

<div class="cf-section cf-wrapper">
<div class="cf-columns two">
<div class="cf-column">
<h2 data-translate="what_happened">What happened?</h2>
<p data-translate="unknown_error_desc">There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
</div>

<div class="cf-column">
<h2 data-translate="what_can_i_do">What can I do?</h2>
<h5 data-translate="if_website_visitor">If you are a visitor of this website:</h5>
<p data-translate="try_again_in_a_few">Please try again in a few minutes.</p>

<h5 data-translate="if_website_owner">If you are the owner of this website:</h5>
<p><span data-translate="520_owner_desc">There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page).</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520 <https://support.cloudflare.com/hc/en-us/articles/200171936-Error-520>" data-translate="addtl_troubleshooting">Additional troubleshooting resources</a>.</p>
</div>
</div>
</div>

<div class="cf-error-footer cf-wrapper">
<p>
<span class="cf-footer-item">Cloudflare Ray ID: <strong>3db4b34bdc8aa2fc</strong></span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 43.230.90.181</span>
<span class="cf-footer-separator">&bull;</span>
<span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
</p>
</div>


</div>
</div>

**Comment by leighghunt** [comment]
Hi there - this could be a complete red herring (apologies for hijacking this ticket if it is), but I just started getting errors myself connecting (first time attempting in a month or more), and found this ticket, and also spotted that you're getting Cloudflare errors on your site.

Is something down centrally that could be affecting connections?

VPN connection error:
![screen shot 2018-01-11 at 4 09 34 pm](https://user-images.githubusercontent.com/349153/34807026-385dc6aa-f6eb-11e7-89a3-bea383494593.png)

![screen shot 2018-01-11 at 4 09 27 pm](https://user-images.githubusercontent.com/349153/34806847-407cc6b6-f6ea-11e7-998c-9d4e4786533e.png)

Log: (username replaced)

```
*Tunnelblick: OS X 10.13.2; Tunnelblick 3.7.4b (build 4921); prior version 3.7.4a (build 4920)
2018-01-11 16:09:20 *Tunnelblick: Attempting connection with [username] using shadow copy; Set nameserver = 769; monitoring connection
2018-01-11 16:09:20 *Tunnelblick: openvpnstart start [username] 1337 769 0 1 0 1065264 -ptADGNWradsgnw 2.4.4-openssl-1.0.2n
2018-01-11 16:09:21 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #251)

Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     OpenVPN returned with status 1, errno = 0:
          Undefined error: 0
     
     Command used to start OpenVPN (one argument per displayed line):
     
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.4-openssl-1.0.2n/openvpn
          --daemon
          --log
          /Library/Application Support/Tunnelblick/Logs/-SUsers-Slhunt-SLibrary-SApplication Support-STunnelblick-SConfigurations-S[username]-SContents-SResources-Sconfig.ovpn.769_0_1_0_1065264.1337.openvpn.log
          --cd
          /Library/Application Support/Tunnelblick/Users/lhunt/[username]/Contents/Resources
          --setenv
          IV_GUI_VER
          "net.tunnelblick.tunnelblick 4921 3.7.4b (build 4921)"
          --verb
          3
          --config
          /Library/Application Support/Tunnelblick/Users/lhunt/[username]/Contents/Resources/config.ovpn
          --verb
          3
          --cd
          /Library/Application Support/Tunnelblick/Users/lhunt/[username]/Contents/Resources
          --management
          127.0.0.1
          1337
          --management-query-passwords
          --management-hold
          --script-security
          2
          --up
          /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down
          /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
     
     Contents of the OpenVPN log:
     
          Options error: Unrecognized option or missing or extra parameter(s) in /Library/Application Support/Tunnelblick/Users/lhunt/[username]/Contents/Resources/config.ovpn:6: tls-remote (2.4.4)
          Use --help for more information.
          
     More details may be in the Console Log's "All Messages"


```

ipinfo page on your site:
![screen shot 2018-01-11 at 4 11 41 pm](https://user-images.githubusercontent.com/349153/34806898-90358c1a-f6ea-11e7-9510-9be4441ca045.png)

**Comment by jkbullard** [comment]
Yes, this looks like a problem with the site or a problem with Cloudflare.

It's very odd, because I am **not** seeing a problem from my location on the east coast of USA, but see the problem from more-or-less everywhere else in the world.

I'll look into this.

**Comment by Michael-LLD** [comment]
OK. Thank you so much.

**Comment by jkbullard** [comment]
Anyone who needs to access the website for documentation, downloads, etc., can use the GitHub-hosted mirror of the site, at `https://tunnelblick.github.io`

**Comment by Michael-LLD** [comment]
I got it. Thank you.

**Comment by dannytip** [comment]
I'm also suffering from this in the UK.  Same cloudfront error.  Means i can't connect to my VPN at all.

**Comment by jkbullard** [comment]
You should be able to connect to your VPN.

See https://groups.google.com/forum/#!topic/tunnelblick-discuss/_zHto0jGFe0

Note: It isn't a Cloudflare problem; they are simply reporting a problem that originates on the tunnelblick.net website itself.

**Comment by leighghunt** [comment]
Thanks for your efforts @jkbullard.

Turns out my issue was a red herring, and probably just a coincidence.

If anyone else gets the issue I received and finds this page via google, I'll record my workaround:

```
          Options error: Unrecognized option or missing or extra parameter(s) in /Library/Application Support/Tunnelblick/Users/lhunt/[connection.tblk]/Contents/Resources/config.ovpn:6: tls-remote (2.4.4)
```

I suspect this was possibly related to an update to Tunnelblick since I had last used it, causing the ```tls-remote``` option to start causing issues with v2.4.4 of OpenVPN.

![screen shot 2018-01-12 at 9 54 25 am](https://user-images.githubusercontent.com/349153/34846934-a42cdf18-f77e-11e7-86f8-4887d79b3916.png)

May not be the correct resolution, but switching **OpenVPN version** back to **v2.3.18 OpenSSL v1.0.2n** allowed me to connect again.

**Comment by jkbullard** [comment]
@leighghunt - "cannot start OpenVPN" is a separate issue and you the solution you used (change version of OpenVPN), is OK for now. But it means that your configuration, which includes "remote-tls", is out-of-date and does not work with the current stable version of OpenVPN, 2.4, which has been out for nearly a year. At some point Tunnelblick will stop including old OpenVPN 2.3 versions and your configuration will stop working. You need to get your OpenVPN configuration updated (which means you may need to update the OpenVPN server, or have it updated.

**Comment by jkbullard** [comment]
The problems with the website seem to have been corrected by "pausing" Cloudflare, so it is not acting as a middleman.

So I'm closing this issue.
