### ISSUE TITLE
Tunnelblick causes kernel panics on OSX 10.13 

### ISSUE THREAD

**Issue by mateusz-lacki** [Tunnelblick/Tunnelblick#431]
Several times openvpn process caused my new macbook pro to kernel panic. Here is one exemplary crash log:

Sat Jan 27 16:02:50 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff8005f6f2e9): Kernel trap at 0xffffff8006185c14, type 13=general protection, registers:
CR0: 0x000000008001003b, CR2: 0x0000000101f10f28, CR3: 0x0000000439f231e6, CR4: 0x00000000001627e0
RAX: 0x000000000000015b, RBX: 0xc085fffffd9ee8e6, RCX: 0x0000000003000000, RDX: 0xffffff8006804360
RSP: 0xffffff91f95fb890, RBP: 0xffffff91f95fb8e0, RSI: 0x0000000000000002, RDI: 0xffffff7f87546a7c
R8:  0x0000000000000000, R9:  0xffffff80066988b0, R10: 0x0000000000000005, R11: 0xffffff81e64dd000
R12: 0x0000000000000000, R13: 0xffffff8028971060, R14: 0xffffff7f87546a7c, R15: 0xffffff800659fb84
RFL: 0x0000000000010282, RIP: 0xffffff8006185c14, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000101f10f28, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xfffffd000004d270 : 0xffffff8005e505f6 
0xfffffd000004d2c0 : 0xffffff8005f7d604 
0xfffffd000004d300 : 0xffffff8005f6f0f9 
0xfffffd000004d380 : 0xffffff8005e02120 
0xfffffd000004d3a0 : 0xffffff8005e5002c 
0xfffffd000004d4d0 : 0xffffff8005e4fdac 
0xfffffd000004d530 : 0xffffff8005f6f2e9 
0xfffffd000004d6b0 : 0xffffff8005e02120 
0xfffffd000004d6d0 : 0xffffff8006185c14 
0xffffff91f95fb8e0 : 0xffffff800619105c 
0xffffff91f95fb900 : 0xffffff80061d32fa 
0xffffff91f95fba20 : 0xffffff80061d1274 
0xffffff91f95fbaa0 : 0xffffff80060e7558 
0xffffff91f95fbb30 : 0xffffff80060ecb4f 
0xffffff91f95fbb60 : 0xffffff800634a3db 
0xffffff91f95fbbb0 : 0xffffff80061343e9 
0xffffff91f95fbd30 : 0xffffff80061316c2 
0xffffff91f95fbd80 : 0xffffff8006304d71 
0xffffff91f95fbdc0 : 0xffffff8006370879 
0xffffff91f95fbe10 : 0xffffff8006370e13 
0xffffff91f95fbe30 : 0xffffff80062ee5b3 
0xffffff91f95fbea0 : 0xffffff80062ee244 
0xffffff91f95fbf00 : 0xffffff80062f2b44 
0xffffff91f95fbf40 : 0xffffff80063fb3e8 
0xffffff91f95fbfa0 : 0xffffff8005e02906 

BSD process name corresponding to current thread: openvpn

Mac OS version:
17C205

Kernel version:
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Kernel UUID: 87641697-A3DD-30C4-B010-E65ECE57550B
Kernel slide:     0x0000000005a00000
Kernel text base: 0xffffff8005c00000
__HIB  text base: 0xffffff8005b00000
System model name: MacBookPro11,4 (Mac-06F11FD93F0323C5)

System uptime in nanoseconds: 288817739724959
last loaded kext at 108158015825688: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8b757000, size 69632)
last unloaded kext at 341114682765: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8b66d000, size 61440)
loaded kexts:
com.apple.filesystems.msdosfs	1.10
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.iokit.IOBluetoothUSBDFU	6.0.2f2
com.apple.filesystems.smbfs	3.2
com.apple.filesystems.afpfs	11.1
com.apple.nke.asp-tcp	8.0.2
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleHDA	280.12
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleGraphicsDevicePolicy	3.16.21
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.driver.AppleIntelHD5000Graphics	10.3.0
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.eficheck	1
com.apple.driver.AppleBacklight	170.10.2
com.apple.driver.AppleThunderboltIP	3.1.1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleIntelFramebufferAzul	10.3.0
com.apple.iokit.BroadcomBluetooth20703USBTransport	6.0.2f2
com.apple.driver.AppleCameraInterface	6.01.2
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleUSBCardReader	439.30.4
com.apple.driver.AppleTopCaseHIDEventDriver	127
com.apple.driver.AppleUSBTopCaseDriver	127
com.apple.filesystems.apfs	748.31.8
com.apple.driver.AirPort.BrcmNIC	1220.28.1a3
com.apple.driver.AppleAHCIPort	329
com.apple.filesystems.hfs.kext	407.30.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.driver.AppleXsanScheme	3
com.apple.security.SecureRemotePassword	1.0
com.apple.driver.usb.cdc	5.0.0
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	517.22
com.apple.iokit.IOAcceleratorFamily2	376.6
com.apple.iokit.IOSurface	209.2.2
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.AppleGPUWrangler	3.16.2
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHSBluetoothDriver	127
com.apple.driver.IOBluetoothHIDDriver	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleActuatorDriver	1204.13
com.apple.driver.AppleHIDKeyboard	203
com.apple.driver.AppleMultitouchDriver	1204.13
com.apple.driver.AppleInputDeviceSupport	1201.8
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.6.3
com.apple.iokit.IOAHCIBlockStorage	301.20.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.iokit.IOAHCIFamily	288
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF

**Comment by jkbullard** [comment]
@mateusz-lacki - Thanks for your report. I'm sorry this is happening.

Can you describe more about the circumstances in which this happens? (Computer, network, what activity is taking place, etc.)

Does the computer show any other signs of instability?

**Comment by jkbullard** [comment]
@mateusz-lacki  - What version of Tunnelblick are you using? What version of OpenVPN is Tunnelblick using when the problem happens?

Does it help to use a different version of OpenVPN? (See the "Settings" tab on the "Configurations" panel of Tunnelblick's "VPN Details" window.)

**Comment by mateusz-lacki** [comment]
Hi,
The computer was playing you-tube video which has ended, but it does not play over the VPN. I was having a few SSH sessions open, but I was not actively working on them for at least 15 minutes (they might have actually disconnected due to inactivity).
This crash occured third time since I have bought the machine one month ago. The computer is new and It works stable.

I am using Tunnelblick 3.7.4b (build 4921). A few more details from the TB log:

2018-01-27 16:16:50 WARNING: Ignoring option 'dh' in tls-client mode, please only include this in your server configuration
2018-01-27 16:16:50 OpenVPN 2.4.4 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [MH/RECVDA] [AEAD] built on Dec  7 2017
2018-01-27 16:16:50 library versions: OpenSSL 1.0.2n  7 Dec 2017, LZO 2.10

**Comment by jkbullard** [comment]
@mateusz-lacki - are you using a "tap" connection? If not, is it using "tun" or "utun"?

**Comment by mateusz-lacki** [comment]
I am using both "tap" and "tun" but at the time of the crash only "tun" was connected.

**Comment by jkbullard** [comment]
@mateusz-lacki  - Was it "tun" or "utun"? (You can find that in Tunnelblick's log.)

"Tun" connections use the "TunTapOsX" kext, but "utun" connections uses macOS's built-in utun driver. 

If you're using "tun", you should try changing your setup to use "utun". To do that, usually all you need to do is remove or comment out any "dev-type tun" lines in the OpenVPN configuration file. (Don't change "dev tun" lines, though.)

From [Tunnelblick and macOS High Sierra (10.13)](https://tunnelblick.net/cHighSierra.html):
> If you are using a "tun" VPN, you can avoid needing to load a system extension by making sure your configuration file does not include a "dev-type tun" option (it should include a "dev tun" option). The "dev-type tun" option causes OpenVPN to use a "tun" device, which requires a kext to be loaded. If a "dev-type tun" option is not present, OpenVPN will use a "utun" device which is built into macOS 10.6.8 and higher and does not require a kext to be loaded.

**Comment by jkbullard** [comment]
Ok, thanks.

I will look into getting you a "debug" version that includes symbols so we could figure out exactly what in OpenVPN is crashing.

In the meantime, two things:

 1. Could this have to do with sleeping or waking up the computer? If so, try setting all your VPNs to not "Disconnect when computer goes to sleep" (on the "Advanced" settings window). (When you change settings, the changes apply to all configurations that are selected on the left side of the "Configurations" panel of Tunnelblick's "VPN Details" window.)

 2. Set up OpenVPN to stop running as root as soon as it can by adding lines "user nobody" and "group nogroup" to your OpenVPN configuration file. This would (I hope) mean that the OpenVPN process would crash but the kernel panic would be avoided. Note that this could have consequences such as not being able to restore routing when disconnecting. That can usually be "fixed" by having Tunnelblick "Reset the primary interface after disconnecting", but if you have more than one VPN connected simultaneously that can cause problems.

**Comment by mateusz-lacki** [comment]
Thanks for reply.
I think that waking or sleeping is a likely suspect in this crash, but also in previous crashes. I was away from the computer now, but it sleeps after 5 minutes of inactivity (sounds about right), and at least one prior crash definitely happened during waking up. 

If debug version will be available I can install it and get back with a report with symbols. Until it is available I will add "user/group nobody".

**Comment by kklliu** [comment]
For your information, I've met kernel panic with using tunnelblick these days. 
When I failed to use macOS's feature, Continuity, to make a phone call by my Mac, 
or could not connect back to my NAS by connecting via OpenVPN,
my Mac would get panic in short time.
After reboot, everything gets fine, and waits until next panic.
I did not realize Tunnelblick is the reason why my Mac gets panic until I check panic log today.
Really looking forward to you finding out the root cause of that.
Thank you very much.

**Comment by jkbullard** [comment]
@kklliu - Thanks for your report. Please send the panic report to developers@tunnelblick.net.

**Comment by mateusz-lacki** [comment]
I also have problem with Continuity on my mac (same phone, different mac works fine).

**Comment by kklliu** [comment]
@jkbullard I will keep my latest panic report and send it to developers' mail.
Thanks again!

**Comment by kklliu** [comment]
@jkbullard Hello, luckily(?) my Mac got panic today, and I saved the crash report and sent it to your developer team. Hope you could find something in that report. Thank you so much.

**Comment by jkbullard** [comment]
@kklliu - Thanks. I received your panic report. It shows a crash in the kernel, not in OpenVPN (which is where the crash which was originally reported occurred). It also shows that no Tunnelblick kexts were loaded. That means is that it is unlikely that Tunnelblick itself is the cause of the panics, but it is still possible that OpenVPN is causing corruption which later manifests itself as a panic, or some other program or a big in macOS is involved.

It would help if anyone getting panics could:
 1. Report here what version(s) of OpenVPN they were using at the time the panic occurred. (Tunnelblick lets you select what version of OpenVPN to use, separately for each configuration.)

 2. Try to use a different version of OpenVPN. That may not be possible because some configurations work only with older versions of OpenVPN, or only with newer versions, but it might help narrow down the problem.

 3. Try to use "user nobody" and "group nobody" options in your OpenVPN configuration file. As noted earlier, that may cause problems on disconnection which may be worked around with "Reset primary interface after disconnecting" (it's a checkbox in stable versions of Tunnelblick and a menu item under "On expected disconnect" and "On unexpected disconnect" in beta versions).

Several years ago Tunnelblick included a third-party kext which sometimes caused kernel panics. Because Apple receives reports of panics, they noticed the problem and contacted the Tunnelblick developers and we all worked together to isolate and fix the problem. If these new panics are widespread, I think Apple might do the same today and they haven't yet done that, so perhaps the problem is not widespread. But of course it is devastating for those who get a panic.

**Comment by jkbullard** [comment]
@kklliu Thanks for submitting the panic report from the original crash, which happened while executing OpenVPN.

However, just because OpenVPN was executing at the time of the panic does not mean that OpenVPN *caused* the panic. One problem with panics is that the panic itself often doesn't happen until after the damage has been done. That is, there are two steps to a panic:
 1. A program damages something in the kernel, either data or itself or another program. The program doing the damage could be part of the kernel, or a kext, or a program such as OpenVPN running as root.

 1. A program attempts to execute, but either it has been damaged in 1, or kernel data that it needs to use has been damaged in 1. The program could be the same program as in 1, but could also be a different program.

When OpenVPN is active, it is typically executed many thousands of times per second because it handles each packet of data going through the VPN separately. Because it is so active, it is more likely to be the program that is running when the damage is "discovered".

Please try the third suggestion in my earlier comment. If OpenVPN isn't running as root then it would not be able to be program that "causes" the panic.

**Comment by kklliu** [comment]
@jkbullard  Hi, Thanks for your explanation and suggestion. I will try it then.

**Comment by cluck** [comment]
I started to see a fair number (1/month) of kernel crashes which I believe are related to VirtualBox VMs generating lots of network traffic. When I started to use Tunnelblick, these(?) crashes are now triggered almost immediately after starting a VPN. Without starting a VPN, I don't see kernel crashes for many days/weeks. Not sure what role VirtualBox really plays in it, but it might be a pointer to the problem.

Using:
Tunnelblick 3.7.4b (build 4921)
VirtualBox Version 5.2.6 r120293 (Qt5.6.3)

*** Panic Report ***
panic(cpu 1 caller 0xffffff8018d6e339): Kernel trap at 0xffffff8018c8b907, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000000048, CR3: 0x00000003feb75040, CR4: 0x00000000003627e0
RAX: 0xffffff80435e4030, RBX: 0x0000000000000000, RCX: 0x0000000009000000, RDX: 0xffffff801949a468
RSP: 0xffffff920acdb4a0, RBP: 0xffffff920acdb4c0, RSI: 0xffffff8019647460, RDI: 0xffffff801949a468
R8:  0x0000000000000000, R9:  0xffffff80435e4030, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0xffffff81fc6eb200, R13: 0xffffff804104e008, R14: 0xffffff801949a468, R15: 0x0000000000040246
RFL: 0x0000000000050046, RIP: 0xffffff8018c8b907, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000048, Error code: 0x0000000000000000, Fault CPU: 0x1, PL: 2, VF: 0

Backtrace (CPU 1), Frame : Return Address
0xffffff920acdaf50 : 0xffffff8018c4f606 
0xffffff920acdafa0 : 0xffffff8018d7c654 
0xffffff920acdafe0 : 0xffffff8018d6e149 
0xffffff920acdb060 : 0xffffff8018c01120 
0xffffff920acdb080 : 0xffffff8018c4f03c 
0xffffff920acdb1b0 : 0xffffff8018c4edbc 
0xffffff920acdb210 : 0xffffff8018d6e339 
0xffffff920acdb390 : 0xffffff8018c01120 
0xffffff920acdb3b0 : 0xffffff8018c8b907 
0xffffff920acdb4c0 : 0xffffff8018ef55c0 
0xffffff920acdb530 : 0xffffff8018ef512c 
0xffffff920acdb5b0 : 0xffffff7f9e5d8f56 
0xffffff920acdb620 : 0xffffff7f9e5d85ef 
0xffffff920acdb670 : 0xffffff921ed11444 
0xffffff920acdb770 : 0xffffff921ed0bc33 
0xffffff920acdb810 : 0xffffff921ed0a2a6 
0xffffff920acdb8b0 : 0xffffff921ec5c982 
0xffffff920acdb920 : 0xffffff921ec5a92f 
0xffffff920acdb9a0 : 0xffffff7f9e56de46 
0xffffff920acdba30 : 0xffffff7f9e56d890 
0xffffff920acdba70 : 0xffffff7f9e57facf 
0xffffff920acdbb30 : 0xffffff7f9e57f259 
0xffffff920acdbb50 : 0xffffff8018ec75fa 
0xffffff920acdbb80 : 0xffffff8018ebc47f 
0xffffff920acdbc00 : 0xffffff8018eae2eb 
0xffffff920acdbe00 : 0xffffff80190f1bbb 
0xffffff920acdbe30 : 0xffffff80191439ac 
0xffffff920acdbf40 : 0xffffff80191fa978 
0xffffff920acdbfa0 : 0xffffff8018c01906 
      Kernel Extensions in backtrace:
         org.virtualbox.kext.VBoxDrv(5.2.6)[C32CCC8B-7E44-3974-BEC0-9C1FA570690D]@0xffffff7f9e56c000->0xffffff7f9e5cefff
         org.virtualbox.kext.VBoxNetFlt(5.2.6)[552BD757-0D66-3F90-9A20-C6C7881F4A2F]@0xffffff7f9e5d7000->0xffffff7f9e5dbfff
            dependency: org.virtualbox.kext.VBoxDrv(5.2.6)[C32CCC8B-7E44-3974-BEC0-9C1FA570690D]@0xffffff7f9e56c000

BSD process name corresponding to current thread: VirtualBoxVM

Mac OS version:
17D47

Kernel version:
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
Kernel UUID: 18D901F1-4A03-3FF1-AE34-C26B2732F13C
Kernel slide:     0x0000000018800000
Kernel text base: 0xffffff8018a00000
__HIB  text base: 0xffffff8018900000
System model name: MacBookPro13,2 (Mac-66E35819EE2D0D05)

System uptime in nanoseconds: 930336741283
last loaded kext at 246616262295: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f99c8e000, size 69632)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.2.6
org.virtualbox.kext.VBoxNetFlt	5.2.6
org.virtualbox.kext.VBoxUSB	5.2.6
org.virtualbox.kext.VBoxDrv	5.2.6
com.apple.filesystems.msdosfs	1.10
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.30
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDAHardwareConfigDriver	280.12
com.apple.driver.AppleHDA	280.12
com.apple.driver.AppleGraphicsDevicePolicy	3.16.21
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.AppleHIDALSService	1
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AGDCBacklightControl	3.16.2
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleBacklight	170.10.2
com.apple.driver.eficheck	1
com.apple.driver.AppleThunderboltIP	3.1.1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.AppleIntelSKLGraphics	10.3.0
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleEmbeddedOSSupportHost	1
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	10.3.0
com.apple.filesystems.apfs	748.41.3
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.hfs.kext	407.30.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.driver.AppleTopCaseHIDEventDriver	127
com.apple.driver.AirPort.BrcmNIC	1220.28.1a3
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	183
com.apple.security.TMSafetyNet	8
com.apple.security.quarantine	3
com.apple.IOBufferCopyEngineTest	1
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.AppleGPUWrangler	3.16.2
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleThunderboltEDMSink	4.1.2
com.apple.driver.AppleThunderboltDPOutAdapter	5.0.2
com.apple.iokit.IONDRVSupport	517.22
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.iokit.IOAcceleratorFamily2	376.6
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.IOSurface	209.2.2
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.usb.AppleUSBiBridge	1.0
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleXsanScheme	3
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleActuatorDriver	1204.13
com.apple.driver.AppleHIDKeyboard	203
com.apple.driver.AppleHSBluetoothDriver	127
com.apple.driver.IOBluetoothHIDDriver	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleMultitouchDriver	1204.13
com.apple.driver.AppleInputDeviceSupport	1201.8
com.apple.driver.AppleHSSPIHIDDriver	52
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleHPM	3.1.3
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleHSSPISupport	52
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.6.3
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0
```

**Comment by jkbullard** [comment]
It might be worth trying to narrow the problem down:

 1. Try the current beta version of Tunnelblick.

 2. Try different versions of OpenVPN. Tunnelblick betas usually include an additional version of OpenVPN based on the git master branch.

 3. Have OpenVPN drop privileges by adding "user nobody" and "group nogroup" lines in the OpenVPN configuration file. That will cause OpenVPN to drop its root/wheel access as soon as it can. If OpenVPN is messing up the kernel when there is a high traffic (or CPU?) load, it will be unable to do so, but it might crash itself, which would be interesting. Dropping privileges can cause problems because OpenVPN will be unable to restore routes. That may or may not matter, depending on your setup, but a workaround is to have Tunnelblick reset the primary interface (in the Advanced settings window) after expected and unexpected disconnections.

**Comment by dscreve** [comment]
Same issue here since around 1 month ago...crash usually occurs when shutting down...today I got à crash while disconnecting

**Comment by mateusz-lacki** [comment]
I just also got it while disconnecting - 20 seconds ago.

**Comment by jkbullard** [comment]
@mateusz-lacki - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html)

**Comment by jnfeinstein** [comment]
Any updates on this?  My system routinely crashes whenever Tunnelblick is open, even when disconnected.  Running 3.7.6beta04.

Are there log files that might be helpful?  This is 100% reproducible so let me know what I can do to help.

**Comment by jkbullard** [comment]
@jnfeinstein -

Please post crash reports from when it panics. I think you can find them in "System Reports" in /Applications/Utilities/Console.app.

Posting the the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) would also be helpful.

Also, does it ever crash when Tunnelblick is not running? How often do you work with Tunnelblick not running? Does it ever crash before you've connected to a VPN (after restarting)?

**Comment by jnfeinstein** [comment]
@jkbullard thanks, can't find any logs unfortunately.  I'm starting to think it might be an issue with the power that Tunnelblick might somehow be triggering.
