### ISSUE TITLE
Dvorak keyboard support

### ISSUE THREAD

**Issue by Smike16** [Tunnelblick/Tunnelblick#434]
Hello. First of all, thank you guys for an amazing tool. It is really useful for me.

Here is my problem:
I'm using dvorak keyboard layout. And when I enter password from my yubikey, password is denied, because of dvorak. When I change layout for qwerty it works pretty well.

Please, add dvorak support for Tunnelblick. =)

**Comment by jkbullard** [comment]
No. This is something that should be handled by macOS and/or Yubikey.

**Comment by Smike16** [comment]
Thank you for fast reply! I'll try to figure out what to do =)
