### ISSUE TITLE
tap-signed.kext always fails to load

### ISSUE THREAD

**Issue by alexchandel** [Tunnelblick/Tunnelblick#435]
Tunnelblick's `tap-signed.kext` fails to load for any `tap` connection. From the Tunnelblick log:
```
*Tunnelblick: OS X 10.13.1; Tunnelblick 3.7.5beta05 (build 4980); prior version 3.7.4b (build 4921)
2018-02-14 13:05:45 *Tunnelblick: Attempting connection with Test using shadow copy; Set nameserver = 768; not monitoring connection
2018-02-14 13:05:45 *Tunnelblick: openvpnstart start Test.tblk 1337 768 0 1 1 1065330 -ptADGNWradsgnw 2.5_git_5a0e82c-libressl-2.6.3
2018-02-14 13:05:55 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     Loading tap-signed.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 71
2018-02-14 13:05:45 *Tunnelblick: openvpnstart starting OpenVPN
```

Attempting to load it with `kextutil` ~results in a few strange, unrelated errors, but~ fails to load nonetheless:

```
sudo kextutil /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext
(kernel) Kext net.tunnelblick.tap start failed (result 0x5).
(kernel) Kext net.tunnelblick.tap failed to load (0xdc008017).
(kernel) Failed to load kext net.tunnelblick.tap (error 0xdc008017).
Failed to load /Library/StagedExtensions/Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext - (libkern/kext) kext (kmod) start/stop routine failed.
```

Attempting with `kextload` has similar results:

```
sudo kextload /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext 
Password:
/Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
```

What does a result of 0x5 mean in `Kext net.tunnelblick.tap start failed`? (No system popup appears when Tunnelblick attempts to load the kext, and nothing in System Preferences/Security/General ask for reauthorization.)

System is High Sierra, Tunnelblick 3.7.5beta05 build 4980 (and the last stable).

**Edit:** fixed unrelated `kextutil` errors, issue still persists.

**Comment by jkbullard** [comment]
Please see item `#`1 in [Tunnelblick and macOS High Sierra (10.13)](https://tunnelblick.net/cHighSierra.html).

**Comment by alexchandel** [comment]
@jkbullard It's not that. It's explicitly approved. And the errors generated by unapproved kexts are different from what `kextload` & `kextutil` return.

**Comment by jkbullard** [comment]
You'll have to ask Apple what the "0x5" error means -- it comes from their program, not Tunnelblick. Are there any conflicting kexts loaded?

**Comment by alexchandel** [comment]
It's possible. Let me unload everything & bisect…

**Comment by alexchandel** [comment]
Aha. Apparently `net.sf.tuntaposx.tap` (the common, non-Tunnelblick TAP kext) conflicts with Tunnelblick's TAP kext, resulting in silent failure when it's loaded.

* What are the differences between Tunnelblick's `tap-signed.kext` (whose plist claims version `20141104 (Tunnelblick build 4980)`) and the common `tap.kext` (whose plist claims version `20150118`)?
* Is Tunnelblick using an outdated kext?
* Could Tunnelblick use the `tap.kext` that's already loaded?

**Comment by alexchandel** [comment]
In any case, add `net.sf.tuntaposx.tap` and `net.sf.tuntaposx.tap` to the [list of conflicting kexts](https://tunnelblick.net/cKextLoadError.html). For future users, it would be nice if Tunnelblick checked for the presence of these & offered to unload them as it does with `foo.tap` & `foo.tun`.

**Comment by jkbullard** [comment]
Tunnelblick's version is based on the 20141104 version of net.sf.tuntaposx.tap. It patches the bundle ID and version (see the source code at third_party/source/tuntap/tuntap-20141104/patches). As I recall (I can't check now because the tuntaposx site is down for maintenance), the changes after 20141104 were not relevant to Tunnelblick (maybe they only changed the bundle ID?).

You can use an already-loaded kext, just tell Tunnelblick to not load its own kext (on Tunnelblick's "Advanced" settings page).

I've added net.sf.tuntaposx.tap to the documentation; thanks for the suggestion.

If you want, you can submit a separate Issue about checking for kexts beyond foo.tun & foo.tap, but it would have a very low priority on my to-do list.
