### ISSUE TITLE
Search bar in dropdown menu

### ISSUE THREAD

**Issue by dszakallas** [Tunnelblick/Tunnelblick#438]
I have a more than 500 configurations installed. At this size, I find it rather cumbersome to select the one I need by scrolling the dropdown. I think a better option would be to include a search bar when the amount of installed configurations is too large to fit on the screen. Then we could filter the available configurations by the string typed in the search bar.

**Comment by jkbullard** [comment]
Thanks for the suggestion. I'll consider it.

Tunnelblick's current solution for the "lots of configurations" problem is to arrange your configurations in a hierarchy using folders, the same way you might for a large number of documents.

I've just added a new page that describes that &mdash; [Managing a Large Number of Configurations](https://tunnelblick.net/cManyConfigurations.html).

**Comment by szdavid92** [comment]
Sounds great! I didn't know of this, I will try it out and see how it work out, thanks!
