### ISSUE TITLE
AAAA records not queried by Mac OS X after successful connection to dual stack tun tunnel

### ISSUE THREAD

**Issue by Strangelovian** [Tunnelblick/Tunnelblick#440]
Scenario:
- fully functional "dual stack" tunnel (confirmed with android openvpn app )
- with tunnelblick, ipv6 only sites fail: DNS AAAA record are ignored / not queried
- only a few terminal commands dig, ping6, traceroute6 fetch the AAAA records correctly
- all other Mac OS X apps, nc, curl, safari, firefox, ignore the AAAA records

scutil --dns ouput with tunnel enabled (AAAA records not included in flags):
```
DNS configuration (for scoped queries)

resolver #1
  search domain[0] : openvpn
  nameserver[0] : 192.168.2.254
  if_index : 8 (en0)
  **flags    : Scoped, Request A records**
  reach    : 0x00000002 (Reachable)
```

scutil --dns output without the tunnel (with IP dual stack):
```
DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 2a01:xxxx:yyyy:zzzz::1
  nameserver[1] : 192.168.2.254
  if_index : 8 (en0)
  **flags    : Scoped, Request A records, Request AAAA records**
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
```

version used : Tunnelblick 3.7.5beta08 (build 5003)

**Comment by jkbullard** [comment]
Tunnelblick does not support IPv6-only situations such as you describe. See #379, for example.
