### ISSUE TITLE
Downloading updates fails on older versions of Mac OS X

### ISSUE THREAD

**Issue by sideeffect42** [Tunnelblick/Tunnelblick#442]
When I try to download the Tunnelblick 3.5.23 update through the built-in Sparkle updater I get this error:
![Screenshot Update Error](https://user-images.githubusercontent.com/940027/37240684-b8944ef6-2446-11e8-9792-4f9d10427ddf.png)

Checking for updates works.
I assume that the download is from GitHub which does not support TLS 1.0 anymore.

**Comment by jkbullard** [comment]
@sideeffect42  - Yes, that's correct.

This is not something that we are going to fix.
