### ISSUE TITLE
Tunnelblick fails to convert config if inline certificate contains apostrophes

### ISSUE THREAD

**Issue by Epi-JJones** [Tunnelblick/Tunnelblick#443]
I have a config that contains inline certificates; most of the time this works as expected. I have one user though (last name O'Brien) whose inline cert causes Tunnelblick to fail importing the config. The problem is that the plaintext portion of the certificate headers (Subject line and X509v3 SAN line) contained within the certificate file have that apostrophe in them.

Despite these apostrophes being between the \<cert> and \</cert> tags, Tunnelblick still complains:
```
Tunnelblick[1951] Converting/Installing /Users/*****/AWS-VPN.ovpn: Single-quote missing in line 69
```
The line number pointing at the line within the certificate containing the apostrophe from the user's name.

As a workaround, I've set up my scripts to strip the plaintext portion so only the bit between "BEGIN CERTIFICATE" and "END CERTIFICATE" lines gets put in, and that behaves fine, but I think Tunnelblick should not be attempting to parse anything between \<cert> and \</cert> anyways.

**Comment by jkbullard** [comment]
@Epi-JJones - Thanks for your report.

Fixed in the source code by e7c956f7061f4c5aa0727ded3bc7bf7a8c0079ed; the fix will be included in the next beta release.
