### ISSUE TITLE
Ability to choose specific server in configs with multiple servers

### ISSUE THREAD

**Issue by frankhommers** [Tunnelblick/Tunnelblick#444]
I would love to create one config for my VPN provider:

Example .opvn file snippet:
```
# Amsterdam, NL 1
remote ams-a01.wlvpn.com

# Amsterdam, NL 2
remote ams-a02.wlvpn.com

# Ashburn, US 1
remote iad-a01.wlvpn.com

# Ashburn, US 2
remote iad-a02.wlvpn.com
```
I would love that when I connect, a pop-up shows with a message "Choose server", and a dropdown containing "Amsterdam, NL 1", "Amsterdam, NL 2", "Ashburn, US 1", "Ashburn, US 2".

**Comment by jkbullard** [comment]
Thunnelblick is not going to do this for you, but you could easily make an AppleScript program to do that. See [AppleScript Support](https://tunnelblick.net/cAppleScriptSupport.html).

**Comment by frankhommers** [comment]
The documentation doesn't show any option to select a specific remote inside a config. Just a config as a whole. So the current AppleScript support can't do this either.

Can we change this issue so that at least AppleScript will allow this?

**Comment by jkbullard** [comment]
Sorry, you're correct -- I was focusing on the idea of picking a configuration to connect.

Why does it need to be "in one config"? Why not have a bunch of configs and choose between them? If you have a lot of configs, see [Managing a Large Number of Configurations](https://tunnelblick.net/cManyConfigurations.html).

**Comment by jkbullard** [comment]
@frankhommers -

Also, if you have just three configs (for example), put them into a .tblk like this:
```
     outer.tblk/
          config1
          config2
          config3
``` 
Then you can install one .tblk and it will install the three configs. (It doesn't matter if the configs themselves are .ovpn/.conf or .tblk.)
