### ISSUE TITLE
minimal required version in Info.plist

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#445]
we distribute config via tblk.zip (it is very comfortable)
however, we cannot be sure that customer is using recent tunnelblick (we use options for recent tunnelblicks)

is there a way to specify minimal required version of tunnelblick ?

**Comment by jkbullard** [comment]
Not currently, but such a feature sounds reasonable.

If it was added to Tunnelblick, it wouldn't work for old versions. So it wouldn't really work the way you want until all of your users had a new version of Tunnelblick that included it.

It isn't obvious to me what should be done if the version of Tunnelblick does not satisfy the requirement:
 * Should the installation of the configuration be stopped with a message about the problem?
 * Should the configuration be installed, but a popup window warn the user that the configuration requires a later (or earlier, if a maximum Tunnelblick version is also implemented)?

**Comment by chipitsine** [comment]
I vote for simplicity, i.e. if tunnelblick does not satisfy the requirement, so stop installation.

**Comment by jkbullard** [comment]
It's not any simpler to stop the installation, but I agree that's best.

Installing the .tblk and warning usually would give a better user experience: it lets the user fix the problem by updating Tunnelblick. If the installation is stopped, the user would have to first update Tunnelblick **and then reinstall the configuration**.

However, if the .tblk replaces an existing configuration, the new configuration may not be usable. And if you want users to update over that VPN, it might not work!

So stopping the installation is probably better (although worse for some users).

**Comment by jkbullard** [comment]
This was implemented in cea8e0d5d935e517c185af654cfa6b69ae7ff83e.
