### ISSUE TITLE
Tunnelblick can't connect OpenVPN after I installed Shimo 4

### ISSUE THREAD

**Issue by menduo** [Tunnelblick/Tunnelblick#446]
Hi:

I can't connect to my OpenVPN after I installed Shimo 4. Shimo asked for load a system extension and tell me to do allow in System Settings, I did. Then I can't connect via Tunnelblik, but I can Connect via Shimo 4.

Can anyone help me?

Thanks.

The log is here:

```
*Tunnelblick: OS X 10.13.3; Tunnelblick 3.7.5 (build 5010)
2018-03-21 23:03:24 *Tunnelblick: Attempting connection with jlb-vpn-idc using shadow copy; Set nameserver = 769; monitoring connection
2018-03-21 23:03:24 *Tunnelblick: openvpnstart start jlb-vpn-idc.tblk 1337 769 0 1 0 1065330 -ptADGNWradsgnw 2.4.4-openssl-1.0.2n
2018-03-21 23:03:24 *Tunnelblick: openvpnstart starting OpenVPN
2018-03-21 23:03:34 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     Loading tap-signed.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 71


```

**Comment by menduo** [comment]
I found an article about restore this, https://discussions.apple.com/thread/8172194 

Can I follow these steps?

**Comment by jkbullard** [comment]
I suspect that Shimo loaded a tap kext that conflicts with the tap kext that Tunnelblick wants to load.

Take a look at [Errors Loading Kexts (Device Drivers)](https://tunnelblick.net/cKextLoadError.html). You can ignore the first part about High Sierra if you were able to connect to your VPN using Tunnelblick before you installed Shimo.

@menduo  - If you do see that Shimo has loaded a kext, please post the kext's name so I can add it to the list on that page.

**Comment by menduo** [comment]
@jkbullard 

I think Shimo's kext's name is `net.sf.tuntaposx.tap`(from `sqlite3 /private/var/db/SystemPolicyConfiguration/KextPolicy '.dump kext_policy'`)

It works now, after I checked `Never load Tap driver ` and  `Never load Tun driver `.
Thank you.

**Comment by vinnytroia** [comment]
Where did you check Never Load tap driver and never load tun driver. In Shimo or Tunnelblick?
