### ISSUE TITLE
fatal error 13 after update 

### ISSUE THREAD

**Issue by AddaxSoft** [Tunnelblick/Tunnelblick#448]
I'm having issue connecting to the VPN server after the latest update.

> 2018-04-03 11:10:30 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
> 2018-04-03 11:10:30 TCP/UDP: Preserving recently used remote address: [AF_INET]x.x.x.x:443
> 2018-04-03 11:10:30 Socket Buffers: R=[131072->131072] S=[131072->131072]
> 2018-04-03 11:10:30 Attempting to establish TCP connection with [AF_INET]x.x.x.x:443 [nonblock]
> 2018-04-03 11:10:30 MANAGEMENT: >STATE:1522743030,TCP_CONNECT,,,,,,
> 2018-04-03 11:10:30 TCP: connect to [AF_INET]x.x.x.x:443 failed: Can't assign requested address
> 2018-04-03 11:10:30 SIGUSR1[connection failed(soft),init_instance] received, process restarting
> 2018-04-03 11:10:30 MANAGEMENT: >STATE:1522743030,RECONNECTING,init_instance,,,,,
> 2018-04-03 11:10:30 MANAGEMENT: CMD 'hold release'
> 2018-04-03 11:10:30 MANAGEMENT: CMD 'hold release'
> 2018-04-03 11:10:30 PLUGIN_CLOSE: /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.4-openssl-1.0.2o/openvpn-down-root.so
> 2018-04-03 11:10:30 SIGTERM[hard,init_instance] received, process exiting
> 2018-04-03 11:10:30 MANAGEMENT: >STATE:1522743030,EXITING,init_instance,,,,,

- I'm on a mac OS 10.13.1 (17B1003)
- Tunnelblick 3.7.5a (build 5011)

the app goes crazy in loop of connecting / disconnecting then gets a fatal error 13

**Comment by AddaxSoft** [comment]
update: I installed openvpn, and I get this too:

> openvpn /path/to/file.ovpn
> 
> Tue Apr  3 12:27:38 2018 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> Tue Apr  3 12:27:38 2018 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
> Tue Apr  3 12:27:38 2018 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
> Tue Apr  3 12:27:38 2018 TCP/UDP: Preserving recently used remote address: [AF_INET]x.x.x.x:443
> Tue Apr  3 12:27:38 2018 Socket Buffers: R=[131072->131072] S=[131072->131072]
> Tue Apr  3 12:27:38 2018 Attempting to establish TCP connection with [AF_INET]x.x.x.x:443 [nonblock]
> Tue Apr  3 12:27:38 2018 TCP: connect to [AF_INET]x.x.x.x:443 failed: Can't assign requested address
> Tue Apr  3 12:27:38 2018 NOTE: UID/GID downgrade will be delayed because of --client, --pull, or --up-delay
> Tue Apr  3 12:27:38 2018 SIGUSR1[connection failed(soft),init_instance] received, process restarting
> Tue Apr  3 12:27:38 2018 Restart pause, 5 second(s)
> Tue Apr  3 12:27:41 2018 SIGINT[hard,init_instance] received, process exiting


Is this a bug in Mac ?
It was working before

**Comment by jkbullard** [comment]
@AddaxSoft - For the "Signal 13" error, the latest Tunnelblick beta fixes that. It also includes several other enhancements and fixes several other problems. See the [Release Notes](https://tunnelblick.net/cRlsNotes.html#version-3.7) for details.

You can download it from the [Tunnelblick Downloads page](https://tunnelblick.net/downloads.html), or you can update to it using Tunnelblick's built-in updater if you check "Check for updates to beta versions" on the "Preferences" panel of Tunnelblick's "VPN Details" window and then click "Check Now".

However, the "looping and relooping" problem is different. It's usually a configuration problem or you've selected the wrong version of OpenVPN/SSL within Tunnelblick. Please ask your question on the [Tunnelblick Discussion Group](https://groups.google.com/forum/#!forum/tunnelblick-discuss). **Before you do so**, please follow the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) and include the "Diagnostic Info" inline in your post.

For the other problem you mentioned, you'll have to talk to the OpenVPN folks.
