### ISSUE TITLE
NOT working in UAE over4G Internet

### ISSUE THREAD

**Issue by addijan** [Tunnelblick/Tunnelblick#453]
it's not working on4G Internet in UAE, on wifi its working well
if we use the same config.ovpn file with Openvpn connect app Over4G thats working fine, but issue is only with blinkt code, 
all over The world its working fine on4G but not in UAE,

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by jkbullard** [comment]
@addijan - Perhaps this has something to do with IPv6. Try disabling it in the Settings tab of the Configurations panel of Tunnelblick's "VPN Details" window.

**Comment by jkbullard** [comment]
Closing do to lack of response.
