### ISSUE TITLE
Building never stops on Mac OS High Sierra

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#454]
Hi guys,

Anyway thank you for your great application. I want to make a own build. 
I have done steps on this direction: https://github.com/Tunnelblick/Tunnelblick/blob/master/Building%20Tunnelblick%20from%20Source%20Code.markdown

But no luck. Final step is to build Xcode project. This never ends. 

Here are my steps:

1. Installed VirtualBox on my MAC computer. (1 CPU, 4GB RAM, 80GB hard)
2. Installed MAC OSX High Sierra 10.13.4 (17E199)
3. Installed Xcode 9.3.
4. Installed Xcode tools, home-brew, autotools...etc.
5. Downloaded source code from GitHub server.
6. Configured project settings as on instruction.
7. Cleaned project.
8. Build project. 

Building process never ends.

What do I messed ? Could you please suggest for my case ?

Thank you.

**Comment by jkbullard** [comment]
From the instructions:
> As of 2016-09-30, Tunnelblick is built using Xcode 7.3.1 on OS X 10.11.6. (Xcode 8.0 creates binaries without complaint but they cause peculiar, unreproducible crashes.)

That's still true. And with Xcode 9, who knows -- maybe it makes Xcode's analyzer loop or something. Does Xcode 9 show what it is doing when it stops making progress? (e.g., "Analyzing 9 of 68 source files")

**Comment by tugsjargal1** [comment]
Hi, @jkbullard ,

When I compile source code first time, building process never ends. 
But second try is "Build success" with compile errors. I can using .dmg files. 

Thank you.
