### ISSUE TITLE
Compiler Error:tests/unit_tests/plugins/auth-pam/Makefile.am:10: but option 'subdir-objects' is disabled

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#455]
Hi guys,

Finally I got compiler error: 
`tests/unit_tests/plugins/auth-pam/Makefile.am:10: but option 'subdir-objects' is disabled`

How can I fix this error ?

Thanks.

**Comment by jkbullard** [comment]
I don't recommend using build tools – such as Xcode 9 and build environments such as macOS 10.13 – that are not supported and have not been thoroughly tested.

**Comment by tugsjargal1** [comment]
Hi @jkbullard ,

So, Do I need to downgrade Xcode ? Or build tools are not comfortable to build ?
On the instruction, 

```
To build Tunnelblick using Xcode 7.0+, it needs to be set up to use "legacy" locations for build products:

Launch Xcode
Click "File" > "Project Settings..."
Click the "Advanced" button
Click on the "Legacy" radio button
Click the "Done" button
```

My XCode is v9.3. 

How can I compile In this case ?

Thank you.

**Comment by jkbullard** [comment]
@tugsjargal1 - As I wrote to you in #454, you should use macOS 10.11.6 and Xcode 7.3.1 to build Tunnelblick.

**Comment by tugsjargal1** [comment]
Hi @jkbullard ,

Thank you for your suggestion. 

Do you have any link to download macOS 10.11.6 and Xcode 7.3.1 ?
Only latest versions are available on AppStore.

**Comment by jkbullard** [comment]
@tugsjargal1 - No, sorry, I don't. If you're an Apple developer you can download [Xcode 7.3.1](https://download.developer.apple.com/Developer_Tools/Xcode_7.3.1/Xcode_7.3.1.dmg) but I don't know about macOS 10.11.6.

**Comment by tugsjargal1** [comment]
@jkbullard Thank you! 

This is great!
