### ISSUE TITLE
Unable to check for update (Invalid appcast signature)

### ISSUE THREAD

**Issue by rhazegh** [Tunnelblick/Tunnelblick#457]
`Tunnelblick 3.7.5a (build 5011)`

When I try to check for update:
<img width="910" alt="screenshot 2018-06-03 17 03 55" src="https://user-images.githubusercontent.com/2200559/40891260-590e9b1a-6750-11e8-923f-694a3f387720.png">

I get this error dialogue box:

<img width="600" alt="screenshot 2018-06-03 17 04 24" src="https://user-images.githubusercontent.com/2200559/40891267-72c4a02c-6750-11e8-9308-15d63e2092c8.png">

Relevant entries from `/var/log/system.log`
```
Jun  3 17:01:00 MB-Pro Tunnelblick[1551]: Sparkle: Failed to verify appcast signature; signature no longer valid; it was valid until 2018-05-27T15:54:52 (now = 2018-06-03T21:01:00)
Jun  3 17:01:03 MB-Pro Tunnelblick[1551]: Sparkle: Error: An error occurred in retrieving update information. Please try again later. The update feed was not properly signed. (URL (null))
Jun  3 17:01:03 MB-Pro Tunnelblick[1551]: Sparkle: Error: The update feed was not properly signed. (null) (URL (null))
```

**Comment by jkbullard** [comment]
@rhazegh - Thanks for reporting this. The problem has been fixed.

**Comment by chrisdel101** [comment]
I get this too. How did U solve it?

**Comment by rhazegh** [comment]
@chrisdel101 download the application separately and install over the previous version.

**Comment by chrisdel101** [comment]
I tried it again and it worked. No idea why. Thanks for response anyway.
