### ISSUE TITLE
Implementation for AFNetworking library 

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#458]
Hi Guys,

I am trying to customize the tunnelblick application with own design. Also I implemented AFNetworking 3.2 (https://github.com/AFNetworking/AFNetworking) to connect our Service API. 

There is no error when we compile whole project with AFNetworking library. 

But when we create HTTP connection via AFNetworking the app crashes. I have no idea about this issue. Actually AFNetworking library works perfectly on other projects(other MAC OS app).

Do you have any experience on my case ? Please help.

Thanks in advance.

**Comment by jkbullard** [comment]
I don't have any experience with AFNetworking and I doubt any of the other Tunnelblick developers do. I'll leave this open for a week for them to contribute.

**Comment by jkbullard** [comment]
Closed because of lack of responses.
