### ISSUE TITLE
How to fix "error: Invalid action. Must be empty or 'clean'" when we archive the build ? 

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#459]
Hi guys,

I compiled the source code on MAC OS High Sierra 10.13.4 successfully. Debug build works perfect.
And now I want to make a build for "Archive" and sign it with our Apple Developer's certificate.

When I run "Archive" from "Product" menu -> "Archive", I am getting error message in the console: 
`error: Invalid action. Must be empty or 'clean'`

How can I make an "Archive" build ?

Thank in advance.

**Comment by jkbullard** [comment]
I don't know. Perhaps you need to 'clean' first. If that doesn't help, you should ask for help with Xcode somewhere.

Building with anything other than Xcode 7.3.1 on OS X 10.11.6 is not recommended.

**Comment by tugsjargal1** [comment]
Hi @jkbullard 

Do we need to compile on 1 CPU virtual machine(VirtualBox ..etc) ?

Thanks.

**Comment by jkbullard** [comment]
As it says in Building Tunnelblick from Source Code.markdown:

> Using a virtual machine to build Tunnelblick is fine – Tunnelblick releases are built using Parallels and VirtualBox. However, there have been unreproducible errors when the Tunnelblick source code is located on a network device or the host computer, so copying the source to the virtual machine's hard drive and building there is recommended. Using Parallels with more than one virtual CPU also can also cause unreproducible errors, so a virtual machine setting of one CPU is recommended for Parallels.

**Comment by tugsjargal1** [comment]
Thank you :)

**Comment by jkbullard** [comment]
Commit 1b648574ff1c1b6b1d89ecce723c5b3d7c3fc2e3 fixes the problem doing an "Archive".

You must still 'Clean', then 'Build', then 'Archive'. (That is, 'Archive' must be preceded by 'Build'.)
