### ISSUE TITLE
Username and Password not loaded from Keychain

### ISSUE THREAD

**Issue by letronje** [Tunnelblick/Tunnelblick#460]
I am on Tunnelblick 3.7.6 (build 5060)
MacBook Pro (15-inch, 2017) on macOS High Sierra Version 10.13.5 ( 17F77 )

I am asked to enter username and password everytime i try to connect, even after selecting "Save in Keychain" for both username and password.

What do I do ?

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by jkbullard** [comment]
Closed because of lack of a response.
