### ISSUE TITLE
Endless attempts to establish a connection

### ISSUE THREAD

**Issue by puhoshville** [Tunnelblick/Tunnelblick#462]
The problem occurs, for example, if you are connected to a public wifi network but have not yet logged in. In this case, tunnelblick sees that wifi connection is established, but attempts to establish a connection with the VPN server do not bring results => endless attempts to establish a connection. I think it will be the good thing to add **wait(5sec)** as a hotfix.

macOS High Sierra 10.13.4
Tunnelblick 3.7.5 (build 5010)

**Comment by jkbullard** [comment]
Tunnelblick probably isn't doing this – it's probably OpenVPN.

To make sure it isn't Tunnelblick, un-check "Keep connected" on the "Connecting & Disconnecting" tab of Tunnelblick's "Advanced" settings window. (Be sure to have the configuration(s) you want the change to apply to selected in Tunnelblick's "VPN Details" window when you make the change.)

**Comment by jkbullard** [comment]
Closed because of lack of a response.
