### ISSUE TITLE
How to change link in "Online Document.webloc" ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#468]
Hi Guys,

I am trying to make a customized version. I would like to change a link in "Online Document.webloc" that I get when we run the .dmg installation file.

This link calls "https://www.tunnelblick.net/documents.html". 

Thanks in advance.

**Comment by jkbullard** [comment]
Just replace the existing one in the source code

**Comment by tugsjargal1** [comment]
@jkbullard 
I found the source at:
tunnelblick/Online Documentation.webloc 

Thank you :)
