### ISSUE TITLE
How can I make a .dmg file signed app ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#469]
Hi guys,

I got an archive when we sign the application. But this archive includes only Tunnelblick.app file.
How can I make a .dmg with signed Tunnelblick.app ?

Thanks.

**Comment by jkbullard** [comment]
I don't know. The app store doesn't distribute .dmgs (as far as I know), only applications.

**Comment by tugsjargal1** [comment]
Hi @jkbullard 
I having a problem when I install the app from .dmg. In your document, this issue is presented:
https://tunnelblick.net/cInstall.html
**"Tunnelblick.app" can't be opened because it was not downloaded from Mac App store.**

On MacOS High Sierra, users can open only from Settings -> Security & Privacy -> Here allows to open.

How can I make it open from .dmg file ?

Thanks.

**Comment by tugsjargal1** [comment]
My expectation was it is possible if we replace signed .app in .dmg file. 
How about this issue ?

Thanks.

**Comment by jkbullard** [comment]
The .dmg itself must be signed, too. That's what was downloaded, not the .app.

You can do that with   &nbsp;&nbsp;&nbsp;&nbsp;  `codesign   -s`  &nbsp;&nbsp;&nbsp;&nbsp; _signing-identity_  &nbsp;&nbsp;&nbsp;&nbsp; _path_to_dmg_.

**Comment by tugsjargal1** [comment]
@jkbullard 
You are awesome! Thank you.
