### ISSUE TITLE
OpenVPN version warning

### ISSUE THREAD

**Issue by diachedelic** [Tunnelblick/Tunnelblick#470]
I'm getting a warning every time I connect/disconnect to a VPN profile.  I just updated to Tunnelblick beta but the warning persists.  It sometimes pops up several times in the same place and I have to close them all, quite annoying!

![image](https://user-images.githubusercontent.com/310464/43523595-3a7d8800-95e0-11e8-913f-ceddfe3bd7d7.png)

# Warning Text:

'Switzerland' will connect using OpenVPN 2.4.6 - OpenSSL v1.1.0h instead of the requested version (OpenVPN 2.5 git 57d6f10 - OpenSSL v1.1.0h).

# Logs:

```
*Tunnelblick: OS X 10.12.6; Tunnelblick 3.7.7beta04 (build 5120); prior version 3.7.6a (build 5080); Admin user

Console Log:
...
2018-08-01 23:08:11 Tunnelblick[75069] Configuration Switzerland will use OpenVPN 2.4.6 - OpenSSL v1.1.0h instead of 2.5 git 57d6f10 - OpenSSL v1.1.0h
...
```

# Profile settings

![image](https://user-images.githubusercontent.com/310464/43523627-5b6c1a04-95e0-11e8-9c8f-38fea3683cee.png)

# OpenVPN status

```
$ ps -ef | grep openvpn
    0 75370     1   0 11:11pm ??         0:03.35 /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.6-openssl-1.1.0h/openvpn --daemon ...etc

$ ls -la /Applications/Tunnelblick.app/Contents/Resources/openvpn/
total 8
drwxr-xr-x    9 root  wheel   306  1 Aug 08:37 .
drwxr-xr-x  125 root  wheel  4250  1 Aug 08:37 ..
lrwxr-xr-x    1 root  wheel    36  1 Aug 08:38 default -> openvpn-2.4.6-openssl-1.0.2o/openvpn
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.3.18-libressl-2.7.1
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.3.18-openssl-1.0.2o
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.4.6-openssl-1.0.2o
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.4.6-openssl-1.1.0h
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.5_git_57d6f10-openssl-1.0.2o
drwxr-xr-x    4 root  wheel   136  1 Aug 08:37 openvpn-2.5_git_57d6f10-openssl-1.1.0h
```

**Comment by jkbullard** [comment]
@diachedelic - I'm sorry this is happening. Please post the output from:

     defaults read net.tunnelblick.tunnelblick | grep version

**Comment by diachedelic** [comment]
```
$ defaults read net.tunnelblick.tunnelblick | grep -i version
    "*-openvpnVersion" = "-";
    "Singapore-openvpnVersion" = "2.4.6-openssl-1.1.0h";
    detailsWindowFrameVersion = 5120;
    openvpnVersion = "-";    tunnelblickVersionHistory =     (
        "3.7.7beta04 (build 5120)",
        "3.7.6a (build 5080)",
        "3.7.6 (build 5060)",
        "3.7.5a (build 5011)",
        "3.7.5 (build 5010)",
        "3.7.4b (build 4921)",
        "3.7.4a (build 4920)",
        "3.7.4 (build 4900)",
        "3.7.3 (build 4880)",
        "3.7.2a (build 4851)"
    );
    userAgreementVersionAgreedTo = 1;
```

**Comment by jkbullard** [comment]
@diachedelic - Thanks.

To fix this, delete the "*-openvpnVersion" preference with

     defaults delete net.tunnelblick.tunnelblick "*-openvpnVersion"

That will let Tunnelblick use the default OpenVPN which is included in each version of Tunnelblick.(The default version of OpenVPN used by each version of Tunnelblick can be different because different versions of Tunnelblick include different versions of OpenVPN.)

Tunnelblick probably created this preference itself as a result of a conversion from an older version of Tunnelblick.

To find out _why_ Tunnelblick is refusing to use the latest version of OpenVPN:
 1. Click on the "Reset Disabled Warnings" button in the "Preferences" panel of Tunnelblick's "VPN Details" window; then
 1. Try to select the latest version of OpenVPN in the "Settings" tab.

**Comment by diachedelic** [comment]
Thanks, that fixed it!  Although the wildcard in `"*-openvpnVersion"` didn't match anything so I had to remove the matching entry manually.  I'm on macOS 10.12.6.

And I found the underlying warning by following your instructions, I will fix my configurations.

```
'Switzerland' will connect using OpenVPN 2.4.6 - OpenSSL v1.1.0h instead of the requested version (OpenVPN 2.5 git 57d6f10 - OpenSSL v1.1.0h).

Warning: This VPN may not connect in the future.

The OpenVPN configuration file for 'Switzerland' contains these OpenVPN options:

'comp-lzo' was deprecated in OpenVPN 2.4 and removed in OpenVPN 2.5

You should update the configuration so it can be used with modern versions of OpenVPN.

Tunnelblick will use OpenVPN 2.4.6 - OpenSSL v1.1.0h to connect this configuration.

However, you will not be able to connect to this VPN with future versions of Tunnelblick that do not include a version of OpenVPN that accepts the options.
```
