### ISSUE TITLE
Reconnecting never ends after switches WiFi network

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#471]
Hi guys,

I have an issue that reconnecting never ends after switched WiFi network. 
Do you have any experience about this issue ?

Thanks,

**Comment by jkbullard** [comment]
Yes.

Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by tugsjargal1** [comment]
Thank you @jkbullard

**Comment by vtushevskiy** [comment]
I have same problem on Mac OS: when I switch wifi network, Tunnelblick is frozen

**Comment by jkbullard** [comment]
@vtushevskiy - See my previous post on this issue.
