### ISSUE TITLE
Username and Passwords are not getting saved and stored in Keychain Access password application on macOS Sierra 10.12.6.

### ISSUE THREAD

**Issue by kaushalshriyan** [Tunnelblick/Tunnelblick#472]
Hi,

I have installed Tunnelblick 3.7.6a (build 5080) on macOS Sierra 10.12.6.  While clicking on "Connect officevpn" it keeps asking username and password inspite of enabling checkbox "Save in Keychain" whenever i connect it again. Ideally the username and password should have been saved and stored in Keychain Access password. Any clue?

Any help will be highly appreciable.

Best Regards,

Kaushal

**Comment by jkbullard** [comment]
Please don't [cross post](https://en.wikipedia.org/wiki/Crossposting).
