### ISSUE TITLE
Uninstaller won't be opened

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#474]
Hi guys,

I have re-branded the tunnelblick. Xcode builds Uninstaller.dmg file.
When we run the uninstaller, I got this message: 
You can’t open the application “Myapp Uninstaller.app” because it may be damaged or incomplete.

How to fix this issue ?

Thank you.

**Comment by jkbullard** [comment]
You need to sign the rebranded Uninstaller, just like you sign the rebranded application.

If you have one, you also need to sign the .dmg that contains the uninstaller.

**Comment by tugsjargal1** [comment]
Dear @jkbullard 

How did you sign Uninstaller application ?
I did try to sign in command link as below:
`codesign -s XXXXXXXXXXXXXXXXXXXXXXXXXX --keychain /Users/user/Library/Keychains/login.keychain ./MyApp\ Uninstaller.dmg`
 
But no luck. Same message throwing:

`You can’t open the application “Myapp Uninstaller.app” because it may be damaged or incomplete.`

Thanks.

**Comment by jkbullard** [comment]
We sign the uninstaller app with:
```
# Sign the uninstaller. It is already signed (apparently as part of the AppleScript
# "droplet" creation process), but this replaces that signature with our own
# Remove write permissions for the .scpt first (or codesign will fail)
chmod a-w "${new_signed_uninstaller_scpt_path}"
codesign --force -s "${signing_identity}" -r "${requirements_uninstaller}" "${new_signed_uninstaller_path}"

# Check that the signing was done properly
codesign -v -v --deep "${new_signed_uninstaller_path}"
spctl -a -v --no-cache "${new_signed_uninstaller_path}"
```
I can't give you our definition of "$requirements_uninstaller" because it includes security-related information. Try leaving off ` -r "${requirements_uninstaller}"`. If that doesn't work, the Internet is full of information, try searching it!  : )

We sign the uninstaller .dmg with:
```
# Sign the uninstaller disk image
codesign -s "${signing_identity}" "${new_signed_uninstaller_dmg_path}"

# Check that the signing was done properly
codesign -v -v --deep "${new_signed_uninstaller_dmg_path}"
```

**Comment by tugsjargal1** [comment]
Dear @jkbullard 

You are always awesome :)
