### ISSUE TITLE
How to set initial value of "Keep Connected" configuration  as "Checked" ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#476]
Hi guys,

I have re-branded tunnelblick. In my case, VPN should always be connected. Once user installed configuration (.opvn file), when user goes to "VPN Details" -> Settings tab -> "Advanced..." -> "Connecting & Disconnecting" -> "Keep Connected" should be checked.

How to set initial value as "Checked" for above configuration programmatically ?

Thank you.

**Comment by jkbullard** [comment]
Almost everything that is a "setting" is stored as a preference. See [Preferences](https://tunnelblick.net/cPreferences.html) for details.

"Keep Connected" is controlled by a preference called "-keepConnected".

BUT be sure you understand what it does: it keeps trying to connect even if OpenVPN crashes or fails with an error and does not pop up a warning to the user. It will use 100% of CPU time if  a problem in the configuration file or other errors cause OpenVPN to fail. Almost nobody using Tunnelblick as an OpenVPN client needs to have it set and probably should not have it set. It's mostly useful for unattended OpenVPN servers.

**Comment by tugsjargal1** [comment]
Thank you @jkbullard
