### ISSUE TITLE
How to turn off "Check if the apparent public IP address changed after connecting" configuration as default ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#485]
Hi guys,

I have rebranded Tunnelblick application. This works great. Our server side does not have "ipinfo" service and we do not have check public IP change actually. 

My question is how to set off "Check if the apparent public IP address changed after connecting" configuration as default.

I wrote below code in after installing a profile. But it did not work:

```
MenuController *menuController = (MenuController*)[NSApp delegate];
[menuController setBooleanPreferenceForSelectedConnectionsWithKey: @"-notOKToCheckThatIPAddressDidNotChangeAfterConnection"
                                                                                                    to: NO
                                                                                              inverted: NO];
```

Thank you.

**Comment by jkbullard** [comment]
As the name indicates, that method sets the preference for the selected connection(s). If there aren't any connections selected (by the user in the "VPN Details" window), it won't do anything.

Try including a `Deploy/forced-preferences.plist` file in Resources that includes a "*-notOKToCheckThatIPAddressDidNotChangeAfterConnection" entry set to "true". (See [Forced Preferences](https://tunnelblick.net/cCusDeployed.html#forced-preferences) for details.)
