### ISSUE TITLE
Status window flickers distractingly when network is unavailable

### ISSUE THREAD

**Issue by jessereynolds** [Tunnelblick/Tunnelblick#487]
When Tunnelblick is attempting to reconnect while the network unavailable, the status window flickers very fast between "Reconnecting MM:SS" and "Waiting for server response MM:SS". It's visually very distracting. I suspect this occurs when the network is blocking the connection attempts eg because a wifi hotspot / captive portal has not been authenticated with yet. 

Can Tunnelblick be told to wait for some period (eg 1 second) Between retry attempts so it's not so frenetic? 

![tunnelblick-blinkenlights-status-window mov](https://user-images.githubusercontent.com/391439/46132814-6886c580-c282-11e8-9779-f334d5e8619b.gif)

**Comment by jkbullard** [comment]
This is done by OpenVPN and can only be controlled by OpenVPN's options in your configuration file. See the Tunnelblick [Support](https://tunnelblick.net/support.html) page for links to OpenVPN resources.
