### ISSUE TITLE
Disable IPv6 (tun only) switch not working in Tunnelblick 3.7.7 (build 5150)

### ISSUE THREAD

**Issue by tonyquan68** [Tunnelblick/Tunnelblick#489]
Description of the issue:
The "Disable IPv6 (tun only)" switch allows IPv6 traffic even when it's selected.

To reproduce:
1. Ensure that your network interface on the Mac is set to "Automatic" for IPv6
2. Connect to an IPv6 enabled internet connection (test at http://test-ipv6.com)
3. Ensure "Disable IPv6 (tun only)" is selected in Tunnelblick
4. Connect to the OpenVPN server
5.  Hit http://test-ipv6.com again, observe that IPv6 traffic is not disabled.

Expected behavior
No IPv6 traffic should be passed

There are two issues in the Tunnelblick up and down scripts causing this problem.  First in `client.up.tunnelblick.sh` in function `disable_ipv6()`, at line 76 of the file the wrong variable is used. This keeps the code from ever disabling the IPv6 interfaces.  It reads

`if [ -n "$ripv6_service" ] ; then`

when it should read

`if [ -n "$dipv6_service" ] ; then`

Secondly, in `client.down.tunnelblick.sh`, if you have more than one interface set to IPv6 automatic, the last interface in the list doesn't have its IPv6 turned back on at disconnection.  This seems to be because the main loop of the `restore_ipv6` function doesn't properly handle this case.  The name of the last interface passed is not followed by a carriage return so the code doesn't process it.  The current main loop looks like this

>     printf %s "$1$LF"  |   while IFS= read -r ripv6_service ; do
>                if [ -n "$ripv6_service" ] ; then
>                        /usr/sbin/networksetup -setv6automatic "$ripv6_service"
>                        logMessage "Re-enabled IPv6 (automatic) for '$ripv6_service'"
>                fi
>     done

I have changed it like so and now it works

>     while IFS= read -r ripv6_service ; do
>                if [ -n "$ripv6_service" ] ; then
>                        /usr/sbin/networksetup -setv6automatic "$ripv6_service"
>                        logMessage "Re-enabled IPv6 (automatic) for '$ripv6_service'"
>                fi
>     done < <(printf '%s\n' "$1")

I've attached my versions of these scripts for your review.
[client.up.tunnelblick.sh.txt](https://github.com/Tunnelblick/Tunnelblick/files/2431917/client.up.tunnelblick.sh.txt)
[client.down.tunnelblick.sh.txt](https://github.com/Tunnelblick/Tunnelblick/files/2431919/client.down.tunnelblick.sh.txt)

**Comment by jkbullard** [comment]
@tonyquan68 - Thank you very much, both for reporting these problems and for your analysis and proposed fixes.

The variable was, as you note, mistyped in the up script: `$ripv6_service` should have been `$dipv6_service`.

But there was another problem in the up script, too: a missing variable definition. `LF` is a variable that should contain a LF character, but its definition was missing.

Not restoring IPv6 was caused by the same missing definition of `LF`.

NOTE: client.4.up had the same mistyped variable, but has the definition of `LF` (as does client.4.down). (client.4 scripts are based on the client. scripts.)

**Comment by tonyquan68** [comment]
No problem @jkbullard I just tested your revised scripts and they work great.  Thanks for your very quick response.   I totally missed the bug caused by the missing `LF` in the up script, obviously that also caused a problem there (the last interface wouldn't get IPv6 disabled on connection).  Now that is fixed as well.

**Comment by kabouzeid** [comment]
Thanks for the quick fix. I had the same problem. When will you release the update?
