### ISSUE TITLE
Unreadable info popup text on Mojave Dark Mode

### ISSUE THREAD

**Issue by ngyikp** [Tunnelblick/Tunnelblick#491]
**Describe the bug**

**To Reproduce**
1. Enable Dark Mode on macOS Mojave
2. Open the main Tunnelblick window
3. Select any configuration
4. Click Advanced
5. On the "Connecting & Disconnecting" tab, mouse over the blue info icon next to "Load Tun driver automatically"

**Expected behavior**
The text should be readable

**Screenshots**
![dark](https://user-images.githubusercontent.com/6135313/46328313-26220780-c639-11e8-82d2-fbfb6c2c7de9.png)

**Additional context**
The info popups on checkboxes are ok, just not on the blue info icons

**Diagnostic information**
Tunnelblick: OS X 10.14.0; Tunnelblick 3.7.7 (build 5150); prior version 3.7.6a (build 5080); Admin user
git commit b95dc49e170d50d401e0304919b3d143d0bba8db

**Comment by jkbullard** [comment]
Thank you very much for this report.

a5e358e fixes this issue and will be included in the next beta release. It removes the separate info buttons and displays the popup help window when the 'Load Tun Driver' or 'Load Tap Driver' buttons are mouseovered.
