### ISSUE TITLE
Remove warning about comp-lzo

### ISSUE THREAD

**Issue by d12fk** [Tunnelblick/Tunnelblick#496]
Discussed an issue with the migration from openvpn's --comp-lzo option to --compress with the devs today. Turns out that both are not compatible. So, until further notice comp-lzo is still deprecated, but will no longer be removed in 2.5. Please adjust the Tunnelblick warning about the comp-lzo option accordingly.

These changes are reflected here:
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--comp-lzo

**Comment by jkbullard** [comment]
@d12fk - This was fixed on 2018-09-06 in commit 4d818ec4ee17dcdf9efb750442b95a6ab793dbdf, and is included in Tunnelblick stable version 3.7.7 and Tunnelblick 3.7.8beta01, both released on 2018-09-29.

The warning now reads:

> Warning: This VPN may not connect in the future.
> 
> The OpenVPN configuration file for '*****' contains these OpenVPN options:
> 
>  • 'comp-lzo' was deprecated in OpenVPN 2.4 and has been or will be removed in a later version
> 
> You should update the configuration so it can be used with modern versions of OpenVPN.
> 
> Tunnelblick will use OpenVPN 2.5 ********* to connect this configuration.
> 
> However, you will not be able to connect to this VPN with future versions of Tunnelblick that do not include a version of OpenVPN that accepts the options.
