### ISSUE TITLE
Does have iOS version On Ipad Pro?

### ISSUE THREAD

**Issue by longxianlin** [Tunnelblick/Tunnelblick#499]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
There is not an iOS version of Tunnelblick. Use the "OpenVPN Connect" app, which is from on of the OpenVPN developers.
