### ISSUE TITLE
Cannot add configuration to Tunnelblick in Mac

### ISSUE THREAD

**Issue by vishnusajev** [Tunnelblick/Tunnelblick#500]
I have installed Tunnelblick latest and my mac os version is 10.12.6. I cannot added .ovpn config file to tunnelblick.

I tried
1. Drag and drop,
2. Double click,
3. Open with (In open with option, am not able to select Tunnelblick application)

I tried 2 latest versions of tunnelblick Tunnelblick 3.7.8beta01 and Tunnelblick 3.7.7.

**Comment by jkbullard** [comment]
@vishnusajev

First, make sure the filename of your file ends in ".ovpn" and that it does not have a hidden ".txt" or other extension after the ".ovpn". See [Q: How do I show or hide file extensions on a Mac?](https://fileinfo.com/help/mac_show_extensions) to see how to find out.

Assuming it is a ".ovpn" file, if "Open with" does not show Tunnelblick as an option for opening ".ovpn" files, your "Launch Services" database is corrupted. That's the database that macOS uses to decide what application(s) can be used to open a particular type of file.

Tunnelblick should be installed by double-clicking the Tunnelblick icon in the disk images you downloaded. If not, try that first and see if it helps.

A big problem with rebuilding the database is that each version of macOS seems to require a different method. The best articles about how to do it seem to be:
 * [Rebuild LaunchServices to Fix Duplicate Entries in OS X’s ‘Open With’ Menu](https://www.tekrevue.com/tip/rebuild-launchservices-fix-duplicate-entries-os-xs-open-menu); and
 * [Launch Services database problems: correcting and rebuilding](https://eclecticlight.co/2017/08/11/launch-services-database-problems-correcting-and-rebuilding/)

Or do your own search for **rebuild launch services database**.
