### ISSUE TITLE
Stops Openvpn to Override DNS

### ISSUE THREAD

**Issue by Tsiddiqui123** [Tunnelblick/Tunnelblick#501]
**Describe the bug**
When i establish the connection with openvpn using up/down scripts on my mac, the Network interface DNS overrides the previous DNS with the new one from the openvpn

**To Reproduce**
1. Connect with openvpn on mac
2. Go to network Preference settings and then in advance tab check DNS .

**Expected behavior**
The DNS Should be the old one not override it as it is set by the company. 

**Additional context**
What is the suggestion for that , it is caused by the up/down scripts or by the configuration I used for openvpn connection ?

Please Help 
Thanks in advance

**Comment by jkbullard** [comment]
@Tsiddiqui123 - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by ChasingRainbows** [comment]
+1

**Comment by jkbullard** [comment]
@ChasingRainbows - Same answer as to @Tsiddiqui123 : Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by ChasingRainbows** [comment]
mac os 10.14.2, my default dns is 1.1.1.1:
`cat /etc/resolv.conf` shows my dns, but after connection it sets another dns (that dns doesnt works). `sudo networksetup -setdnsservers Wi-Fi 1.1.1.1` helps to set my dns, and use vpn together, but after tunnelblick reconnects, `cat /etc/resolv.conf` shows another dns.

**Comment by jkbullard** [comment]
(Third time:) Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html). /etc/resolv.conf on macOS is irrelevant.

**Comment by ChasingRainbows** [comment]
It can be little bit sensetive. Can u give me email?

**Comment by jkbullard** [comment]
@ChasingRainbows: developers@tunnelblick.net

**Comment by ChasingRainbows** [comment]
Thx!

**Comment by ChasingRainbows** [comment]
Yep. I excepting tunnelblick would not change my dns. But it change it.

**Comment by jkbullard** [comment]
@ChasingRainbows - Tunnelblick didn't change the DNS in the log you sent.
 * How was it set originally (manually, DHCP,...)?
 * Why do you think the DNS is being changed?
 * What was the original DNS setting, and what was it changed to?

**Comment by ChasingRainbows** [comment]
- manually (By mac settings gui/networksetup)
 - because it sets dns that didnt works, sites open only by ip after connections, and /etc/resolv.conf not my dns from settings. But, networksetup to my dns fix it.
 - original dns was 1.1.1.1, after tunnelblick on - 10.121.224.1 (idk where it get this dns, maybe from vpn server)

**Comment by jkbullard** [comment]
@Tsiddiqui123:

> because it sets dns that didnt works, sites open only by ip after connection

So
 1. You set DNS manually to 1.1.1.1
 2. You connect the VPN using Tunnelblick
 3. The DNS has been changed to 10.121.224.1

That is not what is shown in the diagnostic info you sent. That shows nothing about DNS.

It is difficult to diagnose problems with DNS because you didn't follow the instructions I linked to, which include using "set nameserver" so that extra logging of DNS activity is done.

**Comment by ChasingRainbows** [comment]
My fault, i would send new log.

**Comment by ChasingRainbows** [comment]
Done

**Comment by jkbullard** [comment]
On macOS, **OpenVPN itself never changes DNS**. (It may change DNS on other platforms.)

When the VPN configuration or server requires a change to DNS, OpenVPN sends instructions to scripts to make the change. Tunnelblick's built-in "up" scripts then makes the changes. Which Tunnelblick "up" script is used depends on the Tunnelblick "Set DNS" setting. If "Set DNS" is set to "Do not set nameserver", no Tunnelblick scripts are run, and no DNS changes are made unless an "up" script provided by the VPN setup does so.

@ChasingRainbows's new log shows that Tunnelblick's "up" script says:
> DNS servers '10.121.224.1' were set manually

which means that by the time the "up" script was run, DNS was set to 10.121.224.1.

It appears that networking on your computer is messed up. Aside from the DNS problem, the following in the log:
> 2018-12-08 00:09:31 Opening utun (connect(AF_SYS_CONTROL)): Resource busy (errno=16)

means that there may be some other VPN software or other intermediary network software being used. Perhaps that software is fiddling with DNS, too.

**Comment by ChasingRainbows** [comment]
Magic. Have no idea how to fix it. Will try to reset network settings, or system... 
Thx, anyway.
