### ISSUE TITLE
Tunnelblick tries reconnecting through utun interface

### ISSUE THREAD

**Issue by jomo** [Tunnelblick/Tunnelblick#506]
**Describe the bug**

Tunnelblick 3.7.8beta01 (build 5160)

I have this in my `/etc/hosts`, which is equal to the actual DNS records:
```hosts
123.123.123.1 vpn.example.com
123.123.123.2 vpn.example.com
123.123.123.3 vpn.example.com
```

The OpenVPN config uses that hostname:
```ovpn
remote vpn.example.com 443
```

When Tunnelblick makes the initial connection, the hostname might resolve to `123.123.123.1` and a route is added for that address via the internet interface before changing the default route to the utun interface.
When Tunnelblick then loses the connection, and tries to reconnect, the hostname might now resolve to `123.123.123.2`, which is routed through the (still existing) utun interface, which obviously doesn't work.

**Possible solutions**

1. Remove utun interface and default route when connection is lost
1. Remember the IP address when connecting and reuse it when reconnecting

**Workarounds**

1. Use IP-Adress `remote`
1. Put single IP in `/etc/hosts`

**Comment by jkbullard** [comment]
OpenVPN does this, not Tunnelblick.

You should consult sources of information about OpenVPN (see the [Tunnelblick Support page](https://tunnelblick.net/support.html)).

The following might work for you, though:

> 1. Remove utun interface and default route when connection is lost

Do not use "persist-tun".

> 2.Remember the IP address when connecting and reuse it when reconnecting

Use "persist-remote-ip".

I you don't use "persist-tun" then you won't need to use "persist-remote-ip".
