### ISSUE TITLE
How to set initial value of "On expected disconnect" configuration? 

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#507]
Hi Guys,

I want to set configuration of "On expected disconnect" -> "Reset primary interface" as default. 
On my code, "Do nothing" is default value.

I found "-resetPrimaryInterfaceAfterDisconnect" preference. But I not sure how to set it as initial value.

How to set it as default ?

Thank you.

**Comment by jkbullard** [comment]
It is a per-configuration preference, so you need to prefix the name of the preference with the configuration name. For example, if the configuration is named "Test VPN", you would set the "Test VPN-resetPrimaryInterfaceAfterDisconnect" preference to true.

See [Preferences](https://tunnelblick.net/cPreferences.html) for more details.

(See your own Issue #476, too.)

**Comment by tugsjargal1** [comment]
@jkbullard 

Thank you :)
