### ISSUE TITLE
Tunnelblick 无法加载该系统扩展

### ISSUE THREAD

**Issue by Yatoo2018** [Tunnelblick/Tunnelblick#508]
version info: 
Tunnelblick: macOS 10.14.1; Tunnelblick 3.7.9beta01 (build 5190); prior version 3.7.8beta02 (build 5170)

error tip:
连接到 我的vpn 需要加载一个系统扩展，但当前 Tunnelblick 无法加载该系统扩展
更多信息[tunnelblick.net]

error popup window：
![image](https://user-images.githubusercontent.com/40135699/49350176-f2bb3200-f6e8-11e8-8534-6c6748e1270e.png)

my vpn config:

client
dev        tap
proto    tcp
remote  here is my-compony-vpn-domain  port
resolv-retry  infinite
nobind
persist-key
persist-tun
mute-replay-warnings
comp-lzo
verb    3
mute    20
reneg-sec  0
auth-user-pass
<ca>
[Security-related  line(s)  omitted]
</ca>

the vpn connect faild.
How can I do?

**Comment by jkbullard** [comment]
Please see [Errors Loading Kexts (Device Drivers) on macOS High Sierra (10.13)](https://tunnelblick.net/cKextLoadErrorHighSierra.html).

If that does not help, please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by Yatoo2018** [comment]
thanks.
Tunnelblick worked.
[Errors Loading Kexts (Device Drivers)](https://tunnelblick.net/cKextLoadError.html)

**Comment by MukjepScarlet** [comment]
Doc removed
