### ISSUE TITLE
Please do not claim ownership of .conf extension on macOS

### ISSUE THREAD

**Issue by rgov** [Tunnelblick/Tunnelblick#510]
Tunnelblick claims ownership of .conf files, but this is a very common extension so it shouldn't do this. For instance, Apache has used .conf as its extension since long before Tunnelblick. And Tunnelblick already has more descriptive extensions like .ovpn, and .tblk.

So I would argue to remove .conf altogether. But at the least, Tunnelblick should use `LSHandlerRank` to declare itself as an alternate.

I'm not sure any of the document types should declare themselves to be bundles with `LSTypeIsPackage` since I think they're flat files aren't they?

https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/Info.plist#L32

**Comment by jkbullard** [comment]
@rgov - Thanks for pointing this out.

**Comment by chucker** [comment]
This makes sense for `.conf`, which is simply too generic, but it's not clear to me why `.ovpn` was removed as well. `.ovpn` doesn't strike me as particularly generic, and opening an OpenVPN config in order to import it into Tunnelblick sounds like a reasonable default workflow.

**Comment by jkbullard** [comment]
> This makes sense for .conf, which is simply too generic, but it's not clear to me why .ovpn was removed as well. .ovpn doesn't strike me as particularly generic, and opening an OpenVPN config in order to import it into Tunnelblick sounds like a reasonable default workflow.

.ovpn was changed along with .conf to avoid problems that macOS Finder has had with finding the correct program to use when they are opened via double-click. (For examples, see some of the posts in [this thread](https://groups.google.com/forum/#!msg/tunnelblick-discuss/vhO9bxXdV4I/WhoqaEWKBAAJ).)

For a long time the approved method of installing configurations has been to drag/drop them onto the Tunnelblick icon in the menu bar. That continues work for .conf, .ovpn, and .tblk files and is much more reliable.
