### ISSUE TITLE
Received control message (PUSH REPLY) from server too large, with result --> Option error.

### ISSUE THREAD

**Issue by LodBrok3** [Tunnelblick/Tunnelblick#511]
**Describe the bug**
Server replies with a PUSH Reply too big, with too many options, the client is unable to read the options and get an error, so the tunnel does not work.

**To Reproduce**
when I try to connect with a server, the server sends a PUSH Reply too big, and the following message appears in the log:

2018-12-27 00:37:22 WARNING: Received unknown control message: <and the bad read options>

**Expected behavior**
In openvpn, there is a file called common.h, if a couple of values in that file are modified to these following values the tunnel will work:

#define TLS_CHANNEL_BUF_SIZE 8192
#define PUSH_BUNDLE_SIZE 4096

these are the original values:

#define TLS_CHANNEL_BUF_SIZE 2048
#define PUSH_BUNDLE_SIZE 1024

 I have tried with these modified values In UNIX and it works, but I am unable to compile the tunnelblick with this values in openvpn in order to use it with macos.

I you could compile one version of tunnelbclick with that openvpn modified values, that would be really useful for me.

I will really appreciate if you can do that for me.

**Screenshots**

**Additional context**
Thanks a lot in advance!!!

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
Have you tried having your server to send multiple push-reply messages in stead of one huge push-reply?

If you want to build Tunnelblick with your own build options for OpenVPN, follow the instructions in _Building Tunnelblick from Source Code.markdown_, which is included in the source code.

**Comment by LodBrok3** [comment]
Hi, thanks for answer, that would be a solution, but I cannot modify the server config.

I tried to build Tunnelblick but I got errors, I guess I have to try again.

thanks.

**Comment by jkbullard** [comment]
Not going to do this.
