### ISSUE TITLE
DNS Issues OSX

### ISSUE THREAD

**Issue by joshbranham** [Tunnelblick/Tunnelblick#512]
**Describe the bug**
When using any version of Tunnelblick (even latest betas) there seems to be an issue where sometimes the DNS will stop functioning for connections to OpenVPN Access Server on Mac OSX (Mojave)

**To Reproduce**
1. Connect to VPN with split tunnel and DNS being set by client
2. Browse sites and services using FQDN from private network
3. Eventually some things will stop resolving: Chrome, iTerm, etc.
4. IP will still work

**Expected behavior**
DNS should function especially when the DNS server is specified via the OpenVPN config

**Screenshots**

**Additional context**

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

(I will get this next time it fails)

We have this issue with every developer trying to use this over the OpenVPN client.

**Comment by acaporrini** [comment]
I'm also experiencing the exact same issue after upgrading to Mojave, would be great to have a feedback on this. 

Thank you!

**Comment by jkbullard** [comment]
@joshphp: This hasn't repeated? Perhaps a problem with the DNS server itself. Also, be aware that Chrome may do its own DNS resolution (without using macOS). I'm not sure about that, though.

@acaporrini: 
 1. "Exact same issue"? You also have a split tunnel? This happens "after a while"?
 1. I agree, it would be nice to have feedback: please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
 3. This could have something to do with DHCP being renewed (which would reset DNS to the pre-VPN server). Do you have "Monitor network settings" checked? Are you using Tunnelblick's "Set nameserver" setting?

**Comment by alexchandel** [comment]
FYI issue #305 is open for supporting multiple VPN-connection-specific DNS servers in addition to your non-VPN DNS server, and the workaround at the bottom may also help your issue.

**Comment by mattkanwisher** [comment]
Ok what solved it for me, Two things

1) Enable "Set default name server"
2) Goto advanced tab
Set "Allow changes to manually set networking"
https://github.com/Tunnelblick/Tunnelblick/issues/401

Not sure why this config would work ;/ seems opposite of what I wanted

**Comment by jkbullard** [comment]
@mattkanwisher - I apologize for forgetting to thank you for posting the solution to the problem you were experiencing. THANKS for that!

I'm closing this because
 1. Neither @joshbranham nor @acaporrini have responded; and

 1. I don't want people to post to this Issue with a "me, too" even when their problem is completely different from the problem described in the original post simply because the Issue includes "DNS" in its title.

**Comment by joshbranham** [comment]
For those still following, I believe the issue was related to the settings for DNS on the server side. When using OpenVPN Access Server, I set the following keys in the DB using `sacli` and that forced the proper DNS settings down to the client:
```
vpn.client.routing.reroute_dns = custom
dhcp_option.dns.0 = <internal-DNS>
dhcp_option.dns.1 = 8.8.8.8
vpn.server.dhcp_option.domain = "internal-zone1.domain.com,internal-zone2.domain.com,etc"
