### ISSUE TITLE
Add wireguard support 

### ISSUE THREAD

**Issue by haad** [Tunnelblick/Tunnelblick#513]
I understand that it might not be easy but tunnelblick already has ui. Only thing required is to switch vpn provider from openvpn to wireguard-tools.

**Comment by jkbullard** [comment]
Sorry, but we're not going to do this.

**Comment by wyager** [comment]
Out of curiosity, have you expounded on the reasons for this anywhere? I can imagine a few reasons why you might decide not to, but it would certainly  be convenient.

**Comment by jkbullard** [comment]
@wyager:

 1. It would be a lot of work.
 2. There already is [an open source GUI](https://git.zx2c4.com/wireguard-ios/about/).
 3. WireGuard only works on the most recent version of macOS, five-month-old 10.14. That goes against Tunnelblick's practice of supporting older versions of macOS (our current version works on all versions of the OS from eight-year-old OS X 10.7.5 to macOS 10.4). 
 4. I could be wrong about this, but WireGuard seems to have several dependencies and includes them "automatically". That goes against Tunnelblick's practice of having a small number of stable dependencies and testing them independently. We include the source code of dependencies within the Tunnelblick source code in a way that is easily verified.

**All that said, a PR or set of PRs that adds support for WireGuard** would be welcomed, as long as the PRs had short, well documented commits that were easily understood. Anyone interested in creating such a PR or PRs is encouraged to contact developers@tunnelblick.net.

**Comment by abumalick** [comment]
The command line utility works on 10.13. I don't know for other mac versions through.

Can be installed from macOS Homebrew and MacPorts (info in https://www.wireguard.com/install/)
