### ISSUE TITLE
Tunnelblick does not ask to set the new passphrase after a renewal

### ISSUE THREAD

**Issue by polak785** [Tunnelblick/Tunnelblick#514]
**Describe the bug**

Our certificates are protected by a passphrase.

After renewal a certificate by opening a `.opvn` file, Tunnelblick keeps using the old passphrase and does not asks to set a new one. I had to remove the certificate from Tunnelblick and re-add the new one, then Tunnelblick asks for the passphrase.

It happened almost all the time since we use the latest version. Before, a workaround was to disconnect the VPN before replacing the certificate but now it has not effect.

**Expected behavior**
After replacing a certificate, Tunnelblick should ask to set a new passphrase.

**Additional context**
We use `OpenVPN/easy-rsa` to handle our certificates
We use the latest stable Tunnelblick version `3.7.8`
We use the latest MacOS X version `10.14`

**Comment by polak785** [comment]
Hello @jkbullard 

1. That's the certificate key which is protected by a passphrase. Here is the content of the `.ovpn` file:
```
client
dev tun
proto tcp
remote server1.example.com 443
remote server2.example.com 443
remote-random
resolv-retry infinite
persist-key
persist-tun
ca ./ca.crt
cert ./cert.crt
key ./cert.key
remote-cert-tls server
comp-lzo
verb 3
nobind
route-metric 50
```

2. Yes, by ticking the related option when we set the passphrase

3. I never install or replace a configuration by dragging/dropping. I always double-click on the `.ovpn` file and then Tunnelblick install or replace the configuration.

4. No I'm not asked to enter a new passphrase (when replacement)
When I click on "connect", Tunnelblick try to connect with the same passphrase as before and the connection attempt loops. Is there a timeout when happened for this and then a new passphrase is asked? We have security checks and a blockage is triggered if they are too many attempts failing. Thus, when this behavior happened, I stop the connection attempts after around 3 seconds.


> I had to remove the certificate from Tunnelblick and re-add the new one, then Tunnelblick asks for the passphrase.

I meant, I remove the configuration from Tunnelblick. On "Configurations" tab, I select the configuration and then I click on the button `-`.
Then, to re-add the new configuration, I double-click on the `.ovnp` file

**Comment by polak785** [comment]
I just found the option "Delete Configuration's Credentials in Keychain..." and now I do this instead of removing then re-adding the configuration. But Tunnelblick should ask to enter a new passphrase by itself.

**Comment by jkbullard** [comment]
The problem was that Tunnelblick was not detecting that the passphrase verification had failed in some situations (perhaps different versions of OpenVPN, or if there were certain OpenVPN options specified).

This is fixed in the source code and will be included in the next beta release.
