### ISSUE TITLE
Suddenly not connecting on macOS Mojave version 10.14.2 (18C54)

### ISSUE THREAD

**Issue by ShahadIshraq** [Tunnelblick/Tunnelblick#518]
**Description of the bug**
When I try to connect, the following error occurs.
```
Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
*Tunnelblick: openvpnstart log:
     Loading tun-signed.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext failed to load - (libkern/kext) kext (kmod) start/stop routine failed; check the system/kernel logs for errors or try kextutil(8).
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. Status = 71
2019-02-11 18:42:29 *Tunnelblick: openvpnstart starting OpenVPN
```
Have searched this on forums and Tunnelblick website. None of the solutions worked. In fact, found no tun or tap kext by running kextstat.

**To Reproduce**
This started absolutely out of nowhere.

**Diagnostic information**
Got [these logs](https://pastebin.com/XdniqpWW) following [these instructions](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by jkbullard** [comment]
@ShahadIshraq - Thanks for providing the diagnostic info.

In modern versions of macOS, there is almost never a good reason to use Tunnelblick's tun kexts. Allow Tunnelblick/OpenVPN to use the built-into-macOS "utun" driver instead, by removing or commenting out the following line in your OpenVPN configuration file:

     dev-type tun

(You must also **not** have "Always load Tun driver" set in the "Connecting & Disconnecting" tab of the "Advanced" settings window. The default, "Load Tun driver automatically" is usually the best setting.)

**To answer your implied question**: This is probably caused by one of the Sophos kexts. Perhaps an update to Sophos causes it to now load kexts that conflict with Tunnelblick's tun kext.
 
You can get more info about why loading the Tunnelblick kext fails by copy/pasting the following in Terminal:

     sudo kextutil  -no-load -print-diagnostics /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext

I'm not sure why running kextstat didn't show you any kexts (note that they don't have to have "kext" in their name). They appear in the diagnostic info you provided (which is generated by `kextstat`):

     Non-Apple kexts that are loaded:
 
     Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
       108    0 0xffffff7f83f90000 0x28000    0x28000    com.intel.kext.intelhaxm (7.3.2) 58DFBE80-E54A-3EFE-B38A-215C5ED8E828 <8 6 5 3 1>
       109    3 0xffffff7f83fb8000 0xef000    0xef000    org.virtualbox.kext.VBoxDrv (6.0.4) B3C930F3-E26A-3EAF-A252-107E7A11FBD2 <8 6 5 3 1>
       139    0 0xffffff7f8452a000 0x8000     0x8000     com.sophos.driver.devctrl (9.8.0) 7CB58D78-DA57-3E8C-B2EC-EFA16E1AF05B <21 6 5 3 1>
       155    0 0xffffff7f847d2000 0x4000     0x4000     com.intel.driver.EnergyDriver (3.5.5) 60449181-1B5B-374C-84C4-F81DDE69DAF8 <8 6 5 3>
       168    0 0xffffff7f849b1000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (6.0.4) 90FE754B-B46F-32F8-8D2C-02EB31FB78BE <167 109 54 8 6 5 3 1>
       181    0 0xffffff7f84ac5000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (6.0.4) 81B0D8D5-7054-3283-9E2A-9F7C6CC34D4C <109 8 6 5 3 1>
       185    0 0xffffff7f860de000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (6.0.4) 7565C853-F81D-3BF1-885E-6F5D18282AF5 <109 6 5 1>
       186    0 0xffffff7f860e4000 0x7000     0x7000     com.sophos.nke.swi (9.8.0) 5620238F-3F6B-3E00-862F-AC57B405C10D <5 1>
       187    0 0xffffff7f860eb000 0x8000     0x8000     com.sophos.kext.sfm (9.8.0) 2D899F9F-93DD-3AE6-A78E-EA36EBB381D1 <6 5 2 1>
       188    0 0xffffff7f860f3000 0x8000     0x8000     com.sophos.kext.oas (9.8.2) C88D55AB-C351-3BD9-9B0B-87105FAB3D35 <6 5 2 1>

**Comment by ShahadIshraq** [comment]
Thank you for the quick reply
```
sudo kextutil  -no-load -print-diagnostics /Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext
/Applications/Tunnelblick.app/Contents/Resources/tun-signed.kext appears to be loadable (including linkage for on-disk libraries).
```

**Comment by ShahadIshraq** [comment]
Btw, worked after commenting out dev-type tun. Sincere gratitude for your assistance.
