### ISSUE TITLE
OpenVPN crashes when try to connect

### ISSUE THREAD

**Issue by dandaka** [Tunnelblick/Tunnelblick#521]
**Describe the bug**
Tunnelblick can't connect to VPN due errors with OpenVPN

**To Reproduce**
1. Click on Connect
2. Message "Waiting for Deamon"
3. Disconnected

**Expected behavior**
When I click on Connect, it connects without errors.

**Additional context**
This error started to appear, when I have tried to implement "constant VPN connection". I have set up configuration to be shared. And enabled setting to connect to VPN on system launch and wake up from hibernation.

**Diagnostic information**

*Tunnelblick: macOS 10.14.3; Tunnelblick 3.7.9beta03 (build 5210); prior version 3.7.9beta02 (build 5200); Admin user
git commit 3bc5f074cf33b72021afb017dfeba375cb8dcd18

Configuration 46.101.94.17-direct

"Sanitized" condensed configuration file for /Library/Application Support/Tunnelblick/Shared/46.101.94.17-direct.tblk:

client
remote 46.101.94.17 636
proto tcp
dev tun
cipher AES-256-CBC
auth SHA256
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name uniform-example-clock name
tls-version-min 1.2
comp-lzo
verb 3
route 46.101.94.17 255.255.255.255 net_gateway
<ca>
[Security-related line(s) omitted]
</ca>
<cert>
[Security-related line(s) omitted]
</cert>
<key>
[Security-related line(s) omitted]
</key>
<tls-crypt>
[Security-related line(s) omitted]
</tls-crypt>

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  155    0 0xffffff7f83916000 0x29000    0x29000    org.pqrs.driver.Karabiner (10.22.0) 75A195F3-FC81-39D0-9040-64D3880249EE <43 6 5 3 1>
  159    3 0xffffff7f8393f000 0xef000    0xef000    org.virtualbox.kext.VBoxDrv (6.0.0) 90C5538D-EAA4-3EE0-AFF7-C60B469DCC90 <8 6 5 3 1>
  164    0 0xffffff7f83a2e000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (6.0.0) 05696B73-790D-3AEA-A761-D596A8594380 <163 159 56 8 6 5 3 1>
  165    0 0xffffff7f83a36000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (6.0.0) B6345263-C6EB-3365-BC16-7594E4B9870A <159 8 6 5 3 1>
  167    0 0xffffff7f83a3b000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (6.0.0) C12A4634-55F8-39C2-848D-7E358A29E174 <159 6 5 1>

================================================================================

Files in 46.101.94.17-direct.tblk:
      Contents/Resources/config.ovpn

================================================================================

Configuration preferences:

-skipWarningThatNotUsingSpecifiedOpenVPN = 1
autoConnect = 1
-onSystemStart = 1
-doNotDisconnectOnFastUserSwitch = 0
-resetPrimaryInterfaceAfterDisconnect = 0
-resetPrimaryInterfaceAfterUnexpectedDisconnect = 0
-loadTap = 
-loadTun = 
-openvpnVersion = 2.4.7-openssl-1.1.1b
-keepConnected = 0
-doNotDisconnectOnSleep = 0
-loggingLevel = 3
-disableNetworkAccessAfterDisconnect = 0
-disableNetworkAccessAfterUnexpectedDisconnect = 0
-lastConnectionSucceeded = 0
-tunnelUpSoundName = None

================================================================================

Wildcard preferences:

================================================================================

Program preferences:

launchAtNextLogin = 1
notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0
tunnelblickVersionHistory = (
    "3.7.9beta03 (build 5210)",
    "3.7.9beta02 (build 5200)",
    "3.7.8 (build 5180)",
    "3.7.7 (build 5150)",
    "3.7.6 (build 5060)",
    "3.7.5a (build 5011)",
    "3.6.9 (build 4685)"
)
statusDisplayNumber = 0
lastLaunchTime = 575372086.075377
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = 46.101.94.17-direct
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
updateCheckBetas = 1
NSWindow Frame ConnectingWindow = 645 630 389 187 0 0 1680 1027 
NSWindow Frame SUStatusFrame = 654 755 400 129 0 0 1680 1027 
NSWindow Frame SUUpdateAlert = 530 476 620 392 0 0 1680 1027 
detailsWindowFrameVersion = 5210
detailsWindowFrame = {{380, 419}, {920, 468}}
detailsWindowLeftFrame = {{0, 0}, {165, 350}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = settings
leftNavSelectedDisplayName = 46.101.94.17-direct
AdvancedWindowTabIdentifier = connectingAndDisconnecting
haveDealtWithOldTunTapPreferences = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUFeedURL = https://www.tunnelblick.net/appcast-s.rss
SUScheduledCheckInterval = 86400
SUSendProfileInfo = 1
SULastCheckTime = 2019-03-27 09:34:46 +0000
SULastProfileSubmissionDate = 2019-03-21 10:28:04 +0000
SUHasLaunchedBefore = 1
WebKitDefaultFontSize = 16
WebKitStandardFont = Times
askedUserIfOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
haveDealtWithSparkle1dot5b6 = 1
updateSendProfileInfo = 1

================================================================================

Tunnelblick Log:

*Tunnelblick: macOS 10.14.3; Tunnelblick 3.7.9beta03 (build 5210); prior version 3.7.9beta02 (build 5200)
2019-03-27 11:44:49 *Tunnelblick: Attempting connection with 46.101.94.17-direct; Set nameserver = 769; monitoring connection
2019-03-27 11:44:49 *Tunnelblick: openvpnstart start 46.101.94.17-direct.tblk 49725 769 0 3 0 1048880 -ptADGNWradsgnw 2.4.7-openssl-1.1.1b
2019-03-27 11:44:49 *Tunnelblick: openvpnstart log:
     Warning: The bitMask setting to disable OpenVPN logging is being ignored because the configuration is starting when the computer startsThe Internet (host 'tunnelblick.net') is reachable; flags = 0x2
     OpenVPN started successfully. Command used to start OpenVPN (one argument per displayed line):
     
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.7-openssl-1.1.1b/openvpn
          --daemon
          --log /Library/Application Support/Tunnelblick/Logs/-SLibrary-SApplication Support-STunnelblick-SShared-S46.101.94.17--direct.tblk-SContents-SResources-Sconfig.ovpn.769_0_3_0_1048880.54017.openvpn.log
          --cd /Library/Application Support/Tunnelblick/Shared/46.101.94.17-direct.tblk/Contents/Resources
          --setenv IV_GUI_VER "net.tunnelblick.tunnelblick 5210 3.7.9beta03 (build 5210)"
          --verb 3
          --config /Library/Application Support/Tunnelblick/Shared/46.101.94.17-direct.tblk/Contents/Resources/config.ovpn
          --setenv TUNNELBLICK_CONFIG_FOLDER /Library/Application Support/Tunnelblick/Shared/46.101.94.17-direct.tblk/Contents/Resources
          --verb 3
          --cd /Library/Application Support/Tunnelblick/Shared/46.101.94.17-direct.tblk/Contents/Resources
          --management 127.0.0.1 54017 /Library/Application Support/Tunnelblick/piehhggkjhjgeaidjcmbhjledaadebfkhonbocpg.mip
          --script-security 2
          --up /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw

2019-03-27 11:44:49 *Tunnelblick: openvpnstart starting OpenVPN
2019-03-27 11:44:50 *Tunnelblick: OpenVPN appears to have crashed -- the OpenVPN process has terminated without running a 'down' script, even though it ran an 'up' script. Tunnelblick will run the 'down' script #0 to attempt to clean up network settings.
2019-03-27 11:44:50 *Tunnelblick: Running 'route-pre-down 0' script first.
2019-03-27 11:44:52 *Tunnelblick: No 'post-disconnect.sh' script to execute
2019-03-27 11:44:52 *Tunnelblick: Expected disconnection occurred.

================================================================================

"Sanitized" full configuration file

client
remote 46.101.94.17 636
proto tcp
dev tun
cipher AES-256-CBC
auth SHA256
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name uniform-example-clock name
tls-version-min 1.2
comp-lzo
verb 3
route 46.101.94.17 255.255.255.255 net_gateway

<ca>
 [Security-related line(s) omitted]
</ca>

<cert>
 [Security-related line(s) omitted]
</cert>

<key>
 [Security-related line(s) omitted]
</key>

<tls-crypt>
 [Security-related line(s) omitted]
</tls-crypt>

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
HUAWEIMobile-
HUAWEIMobile- 2
USB Ethernet
Wi-Fi
iPhone USB
Bluetooth PAN
Thunderbolt Bridge
Ethernet Adaptor (en1)
Ethernet Adaptor (en2)
Ethernet Adaptor (en8)

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether b8:e8:56:3c:3f:88 
	inet 192.168.88.134 netmask 0xffffff00 broadcast 192.168.88.255
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 0a:e8:56:3c:3f:88 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 9a:c8:4c:59:43:72 
	inet6 fe80::98c8:4cff:fe59:4372%awdl0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:00:92:92:20 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:00:92:92:21 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 72:00:00:92:92:20 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::10b2:eb36:28ee:7f15%utun0 prefixlen 64 scopeid 0xb 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.6 --> 10.8.0.5 netmask 0xffffffff 
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.10 --> 10.8.0.9 netmask 0xffffffff 
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.14 --> 10.8.0.13 netmask 0xffffffff 
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.18 --> 10.8.0.17 netmask 0xffffffff 
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.22 --> 10.8.0.21 netmask 0xffffffff 
utun6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.26 --> 10.8.0.25 netmask 0xffffffff 
utun7: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.30 --> 10.8.0.29 netmask 0xffffffff 
utun8: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.34 --> 10.8.0.33 netmask 0xffffffff 
utun9: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.38 --> 10.8.0.37 netmask 0xffffffff 
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.42 --> 10.8.0.41 netmask 0xffffffff 
utun11: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.46 --> 10.8.0.45 netmask 0xffffffff 
utun12: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.50 --> 10.8.0.49 netmask 0xffffffff 

================================================================================

Console Log:

2019-03-27 11:34:12 Tunnelblick[541] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2019-03-27 11:34:12 Tunnelblick[541] Set 'expect disconnect 0 ALL'
2019-03-27 11:34:13 Tunnelblick[541] Finished shutting down Tunnelblick; allowing termination
2019-03-27 11:34:15 Tunnelblick[8802] Tunnelblick: macOS 10.14.3; Tunnelblick 3.7.9beta03 (build 5210)
2019-03-27 11:34:16 Tunnelblick[8802] DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
2019-03-27 11:34:17 Tunnelblick[8802] Sparkle: ===== Tunnelblick.app =====
2019-03-27 11:34:17 Tunnelblick[8802] Sparkle: Verified appcast signature
2019-03-27 11:34:41 Tunnelblick[8802] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2019-03-27 11:34:41 Tunnelblick[8802] Finished shutting down Tunnelblick; allowing termination
2019-03-27 11:34:45 Tunnelblick[9120] Tunnelblick: macOS 10.14.3; Tunnelblick 3.7.9beta03 (build 5210)
2019-03-27 11:34:45 Tunnelblick[9120] DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
2019-03-27 11:34:46 Tunnelblick[9120] Sparkle: ===== Tunnelblick.app =====
2019-03-27 11:34:46 Tunnelblick[9120] Sparkle: Verified appcast signature
2019-03-27 11:34:54 Tunnelblick[9120] The OpenVPN log contains the following message: 
                                       
                                       "Unrecognized option or missing or extra parameter(s)".
                                       
                                       This error means that an option that is contained in the OpenVPN configuration file or was "pushed" by the OpenVPN server:
                                       
                                            • has been misspelled,
                                       
                                            • has missing or extra arguments, or
                                       
                                            • is not implemented by the version of OpenVPN which is being used for this configuration. It may be a new option that is not implemented in an old version of OpenVPN, or an old option that has been removed in a new version of OpenVPN. You can choose what version of OpenVPN to use with this configuration in the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window.
                                       
                                       See the VPN log in the "Log" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window for details.
2019-03-27 11:35:45 Tunnelblick[9120] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SShared-S46-D101-D94-D17--direct-Dtblk-SContents-SResources'
2019-03-27 11:35:59 Tunnelblick[9120] No way to disconnect '46.101.94.17-direct': pid = 0; connectedList = (
                                           "VPN Connection 46.101.94.17-direct"
                                       ); notConnectWhenComputerStarts = NO; [managementSocket isConnected] = NO
2019-03-27 11:39:30 Tunnelblick[9120] The OpenVPN log contains the following message: 
                                       
                                       "Unrecognized option or missing or extra parameter(s)".
                                       
                                       This error means that an option that is contained in the OpenVPN configuration file or was "pushed" by the OpenVPN server:
                                       
                                            • has been misspelled,
                                       
                                            • has missing or extra arguments, or
                                       
                                            • is not implemented by the version of OpenVPN which is being used for this configuration. It may be a new option that is not implemented in an old version of OpenVPN, or an old option that has been removed in a new version of OpenVPN. You can choose what version of OpenVPN to use with this configuration in the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window.
                                       
                                       See the VPN log in the "Log" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window for details.
2019-03-27 11:40:09 Tunnelblick[9120] No way to disconnect '46.101.94.17-direct': pid = 0; connectedList = (
                                           "VPN Connection 46.101.94.17-direct"
                                       ); notConnectWhenComputerStarts = NO; [managementSocket isConnected] = NO
2019-03-27 11:44:08 Tunnelblick[9120] No way to disconnect '46.101.94.17-direct': pid = 0; connectedList = (
                                           "VPN Connection 46.101.94.17-direct"
                                       ); notConnectWhenComputerStarts = NO; [managementSocket isConnected] = NO
2019-03-27 11:44:09 Tunnelblick[9120] startDisconnectingUserKnows: while already disconnecting '46.101.94.17-direct'; OpenVPN state = 'DISCONNECTING'
2019-03-27 11:44:09 Tunnelblick[9120] No way to disconnect '46.101.94.17-direct': pid = 0; connectedList = (
                                           "VPN Connection 46.101.94.17-direct"
                                       ); notConnectWhenComputerStarts = NO; [managementSocket isConnected] = NO
2019-03-27 11:44:42 Tunnelblick[9120] The OpenVPN log contains the following message: 
                                       
                                       "Unrecognized option or missing or extra parameter(s)".
                                       
                                       This error means that an option that is contained in the OpenVPN configuration file or was "pushed" by the OpenVPN server:
                                       
                                            • has been misspelled,
                                       
                                            • has missing or extra arguments, or
                                       
                                            • is not implemented by the version of OpenVPN which is being used for this configuration. It may be a new option that is not implemented in an old version of OpenVPN, or an old option that has been removed in a new version of OpenVPN. You can choose what version of OpenVPN to use with this configuration in the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window.
                                       
                                       See the VPN log in the "Log" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window for details.

**Comment by dandaka** [comment]
I have restarted a computer and it doesn't solve the problem. Updated the description.

**Comment by dandaka** [comment]
After computer restart I see:

1. Tunnelblick shows "disconnected" state (according to menubar icon)
2. Actually computer is connected to VPN
3. I restart Tunnelblick
4. This message appears

![image](https://user-images.githubusercontent.com/2384694/55138560-71c2f300-513c-11e9-9818-aa04419c56f6.png)

**Comment by jkbullard** [comment]
Using "connect when computer starts" is problematic. It is always a good idea to try to connect manually, to make sure the configuration works properly both during connection and during disconnection. Doing that should show the problem in the OpenVPN log.

But if it doesn't, the raw OpenVPN log file is located at 
/Library/Application Support/Tunnelblick/Logs/-SLibrary-SApplication Support-STunnelblick-SShared-S46.101.94.17--direct.tblk-SContents-SResources-Sconfig.ovpn.769_0_3_0_1048880.54017.openvpn.log.

My advice is to quit all OpenVPN processes using the button on Tunnelblick's Utilities panel, quit Tunnelblick itself, remove all files from /Library/Application Support/Tunnelblick/Logs/, and then launch Tunnelblick, open Tunnelblick's "VPN Details" window to the "Log" tab on the "Configurations" panel, and try to connect manually. If it crashes, look at the file in that folder that has a name ending in ".openvpn.log. If it doesn't crash, disconnect it and then examine the regular Tunnelblick log for any errors in the connecting or disconnecting process.

**Comment by dandaka** [comment]
> My advice is to quit all OpenVPN processes

Which setting should I use? "Connect when computer starts" or "When Tunnelblick launches"?

**Comment by pierredGitHub** [comment]
Thank you to jkbullard for his remark 
     Using "connect when computer starts" is problematic.
I switched to "connect when Tunnelblick launches" and that solved those pesky OpenVPN processes that seemed to accumulate every time I was trying to connect (and failing to).

For now I have put Tunnelblick in the Login item of the user, but a restart of the computer will not start Tunnelblick until the user logs in. For remote management of the machine, it's a problem. I have a temp workaround with TeamViewer but it's inconvenient. I'd rather connect through the VPN.

Is it possible to get Tunnelblick to launch at boot time? Or does it need a GUI present to get going?

But that begs the question as to why the option "when the computer starts" cannot work correctly, or reliably. Any idea?

Thanks.

**Comment by jkbullard** [comment]
@ pierredGitHub wrote:
> Is it possible to get Tunnelblick to launch at boot time? Or does it need a GUI present to get going?

Sorry, but no. You need to be logged into run Tunnelblick. It needs a GUI – it accesses the logged-in-user's preferences, displays to the logged-in user's screens, accepts input from the logged-in-user's keyboard and mouse, etc.

> But that begs the question as to why the option "when the computer starts" cannot work correctly, or reliably. Any idea? Is it the underlying OpenVPN, or is it Tunnelblick itself?

I haven't been able to reproduce this problem (in part because it isn't a high priority for me), but it may be a combination of problems with both OpenVPN and Tunnelblick. Or it might be caused by more than one bug in Tunnelblick:
 * It may be due to a problem with Tunnelblick's down script (which runs independently of Tunnelblick). Because of what I consider a bug in OpenVPN, a failure of the down script will cause OpenVPN to not release the utun device, and perhaps not restore the routing info.

 * I recently fixed (via de83234f) a bug in Tunnelblick's script which handles network setup changes. That bug would crash Tunnelblick itself, and although I don't think it's causing the "when computer starts" problems, but it won't hurt to have fixed that bug.

If someone who is having problems with "when computer starts" wants to work with me to reproduce this bug and/or get logs and info about it, I am willing to do that. But it will be a lot of back-and-forth via email (which is the way I would want to do it). Email me at developers@tunnelblick.net if you're interested.

**Comment by jkbullard** [comment]
@ pierredGitHub wrote:

> For now I have put Tunnelblick in the Login item of the user, but a restart of the computer will not start Tunnelblick until the user logs in. For remote management of the machine, it's a problem. I have a temp workaround with TeamViewer but it's inconvenient. I'd rather connect through the VPN.

 1. You may not want to do this, but you could have macOS log in the user automatically on boot. Then you wouldn't need to do it with TeamViewer.

 2. You needn't have a Login item of Tunnelblick, and in fact you probably don't want to or need to. Tunnelblick will launch at a user's login if it was running the last time that user logged out (or the computer shut down or restarted with that user logged in (and in a couple of other situations; see [Tunnelblick Launching at Login](https://tunnelblick.net/tunnelblickLaunchAtLogin.html) for details).

**Comment by pierredGitHub** [comment]
Having macOS log the user in automatically is a bit of a security exposure, until the automatic lock kicks in. But I have been considering that option. It all depends where the machine is located of course.

I still prefer having it in the Login Items in case the user (not me) unchecks the box to reopen the apps, which can happen, and also in case Tunnelblick got closed for whatever reason by the user.

Appreciate the support nonetheless.

**Comment by jkbullard** [comment]
@pierredGitHub wrote:
>Having macOS log the user in automatically is a bit of a security exposure, until the automatic lock kicks in. But I have been considering that option. It all depends where the machine is located of course.

Maybe you could lock the Desktop via a script invoked as a Login Item. That would reduce the exposure time to nearly nothing. See [Lock the Mac Desktop from the Command Line](http://osxdaily.com/2012/03/30/lock-mac-desktop-command-line/) I don't think locking the Desktop would stop Tunnelblick from running and connecting the VPN, although you should of course test that.

**Comment by prathameshd9** [comment]
How to add these preferences "-resetPrimaryInterfaceAfterDisconnect = 0
-resetPrimaryInterfaceAfterUnexpectedDisconnect = 0" to our final ovpn file ?? How does this work exactly ?

**Comment by jkbullard** [comment]
@prathameshd9 - **Your inquiry is completely unrelated to this Issue.**

Please use the [Tunnelblick Discussion Group](https://groups.google.com/forum/#!forum/tunnelblick-discuss) for questions such as this.
