### ISSUE TITLE
Proposal: display VPN name in the menu bar

### ISSUE THREAD

**Issue by Leksat** [Tunnelblick/Tunnelblick#523]
OS X menu bar allows to display some text to the right of the menu icon. This can be used to display the current connection name. So one can realize which configuration is currently used with a quick glance at the menu bar.

However, I'm not sure how this should work with multiple active connections. I never used this feature.

**Comment by jkbullard** [comment]
You can find out what configurations are connected by mousing over the Tunnelblick icon, which will (by default) pop up a status window for each active configuration.

I admit that's not as easy as glancing at the menu bar, but I'm not inclined to work on this myself. Anyone else can, though, and make a PR.

Here are some comments:
 * It will take more space on the menu bar, so it must be enabled/disabled with a per-configuration preference (disabled by default). Name the preference "-showConfigurationNameWithIcon" (see [Preferences](https://tunnelblick.net/cPreferences.html)).
 * Figure out how to handle this with RTL languages such as Arabic and Hebrew. (Does the name go to the right of the icon normally, and to the left if a RTL language is being used?)
 * This isn't workable with multiple connections, so automatically disable it when a second connection becomes active and reenable it when there is only one remaining connection. Or perhaps just change the name to (localized) "Multiple VPNs".
 * Add a checkbox on the appearance panel to enable/disable it. This touches several places in the code, so if someone makes a PR with all the other stuff, I can/will do this..
