### ISSUE TITLE
Can no longer initiate connection with OpenVPN 2.3

### ISSUE THREAD

**Issue by chucker** [Tunnelblick/Tunnelblick#525]
**Describe the bug**
VPN configurations targeting OpenVPN 2.3 will no longer start. In the log, we see:

```
Contents of the openvpnstart log:
openvpnstart log:
     OpenVPN returned with status 1, errno = 0:
          Undefined error: 0

     Contents of the OpenVPN log:
     
          Options error: Unrecognized option or missing parameter(s) in [CMD-LINE]:1: machine-readable-output (2.3.18)
          Use --help for more information.
```

Setting the same connection to OpenVPN 2.4 (assuming it is compatible) resolves the issue.

**To Reproduce**
1. Go to **VPN Details…**, **Configurations**
2. Select a VPN configuration
3. Go to **Settings**
4. Set *2.3.18 - LibreSSL v2.7.1* or similar as the **OpenVPN version**
5. Connect

**Expected behavior**
It should connect fine, assuming it is otherwise compatible with 2.3.

**Additional context**
This is likely a side effect of https://github.com/Tunnelblick/Tunnelblick/commit/b3dd37043641411933078653c88e0510bf8fd826.

**Comment by jkbullard** [comment]
@chucker - The machine-readable-output command is not available in OpenVPN 2.3, it is only available in OpenVPN 2.4.

See the man pages for [OpenVPN 2.3](https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage) and [OpenVPN 2.4](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage).

**Comment by mfpp** [comment]
The machine-readable-output option is automatically set by tunnelblick when starting OpenVPN... how can I remove it?

**Comment by jkbullard** [comment]
@mfpp - Ouch. That was a total mis-thinking on my part –I made that change. You'll have to revert to Tunnelblick 3.7.9beta03 until this is fixed.

Thanks for reporting this!

**Comment by jkbullard** [comment]
The fix will be included in the next beta release of Tunnelblick. Thanks again for reporting this, @mfpp.

**Comment by chucker** [comment]
Yeah, just to be clear — I didn’t set or intend to set that option. :-)

**Comment by jkbullard** [comment]
Yeah, sorry, @chucker, I didn't realize that from reading your post. My apologies.

**Comment by mfpp** [comment]
No problem @jkbullard. I'll switch back to the stable version meanwhile.

**Comment by jkbullard** [comment]
@mfpp - 3.7.9beta03 should work and not have this problem. It's on the [Deprecated Downloads page](https://tunnelblick.net/downloadsDeprecated.html).

**Comment by jkbullard** [comment]
@mfpp, @chucker - Tunnelblick 3.7.9beta05 has been released and should work.

**Comment by mfpp** [comment]
Great, it's working again. Thanks
