### ISSUE TITLE
[feature request] set rules for vpn connection, some ip/hostname use vpn while others not

### ISSUE THREAD

**Issue by huahuayu** [Tunnelblick/Tunnelblick#526]
## Feature summary
I want to set rules for vpn connection, some ip/hostname use vpn while others not  

## Scenario
Our company have a policy for network connection, internal service must use vpn to visit, but if I connected to the vpn, other internet services will use that vpn connection too and it's slow. I want to set a list for specific ip,  but I don't find the function in settings & manual.  

## Question
Do you have it or not? If not will you add it?  I also use ShadowsocksX-NG they do it well, they have a PAC list

**Comment by jkbullard** [comment]
@huahuayu - There are no plans to add such support to Tunnelblick.

OpenVPN already has a way to use the VPN for some IP addresses but not others using routing. However, that cannot be used to use the VPN for some domains or hostnames and not others. See the [OpenVPN 2.4 man page](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage).

To use that feature of OpenVPN, you need to make sure that you do not check "Route all IPv4 traffic through the VPN" on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window and do not use OpenVPN's "redirect-gateway" option.
