### ISSUE TITLE
VoiceOver menu navigation support

### ISSUE THREAD

**Issue by Phisto** [Tunnelblick/Tunnelblick#531]
**Describe the bug**
When using VoiceOver(VO) one can not open the menu item with VO-controls.

**To Reproduce**
1. Activate VoiceOver (CMD+F5).
2. Navigate the VO-cursor to the Tunnelblick menu (CTRL+OPTION+M+M).
3. Open the menu (CTRL+OPTION+SPACE).
4. The menu does not open.

**Expected behavior**
The menu should expand so that the user can navigate the menu and (in my case) select ""vpnname" verbinden".

**Screenshots**

**Additional context**
- Tunnelblick 3.7.8 (build 5180)
- macOS Mojave 10.14.3
- The solution(s) in issue [156](https://github.com/Tunnelblick/Tunnelblick/issues/156) do not help with that.

I do not have a visual impairment and dont use VO on a daily basis so i'm not really an expert with VO usage but if needed i can make contact with the student who came to me with this issue.

**Diagnostic information**

**Comment by jkbullard** [comment]
We don't have a way to get VO to open the Tunnelblick menu, but we do have a way to open the Tunnelblick menu from the keyboard: Command+Option+F1 (on most laptops, you need to use the Fn key to access the function keys, so it would be Command+Option+Fn+F1).

You can choose a different function key in the "Preferences" panel of "Tunnelblick's "VPN Details" window. You can choose any of F1 through F12, but it must always be used with Command and Option.

As developers, we have almost no contact from those using VO or other assistive support (we haven't for several years, anyway), so please encourage your student to contact us directly at developers@tunnelblick.net for more support -- perhaps they can help us make Tunnelblick better for them and for others using assistive technologies.

**Comment by Phisto** [comment]
Thank you, this works great! Sorry for opening a github issue, i just did not look carefully.
I will ask him.
