### ISSUE TITLE
macos built-in vpn does not work when tunnelblick is running

### ISSUE THREAD

**Issue by lydasia** [Tunnelblick/Tunnelblick#533]
macos built-in vpn does not work when tunnelblick is running(no active openvpn connection)

macos 10.14.4
tunnelblick 3.7.8

**Comment by jkbullard** [comment]
I'm sorry, that should not be happening. When no OpenVPN VPN is active, Tunnelblick does not do anything with networking that could interfere with other VPNs. (It even goes out of its way, which some other VPN software doesn't, to load and unload kexts only when necessary, and if necessary, only when a connection is active.)

Please try the following:
1. Make sure no Tunnelblick VPN configuration is set to connect "when Tunnelblick launches" or "when computer starts".
2. Leave Tunnelblick running.
3. Restart your computer (it doesn't matter whether or not you tell macOS to keep windows open).
4. Verify that Tunnelblick is running when you've logged in.
5. Try macOS's built-in VPN.

**(A) If the built-in VPN fails**, post any messages from the log in the Console application about why the built-in VPN failed. (Console application is located in /Applications/Utilities.)

**(B) If the built-in VPN works**, then do the following
6. Disconnect macOS's built-in VPN.
7. Reconnect macOS's built-in VPN. (To make sure it can connect a second time.)
8. Disconnect macOS's built-in VPN.
9. Open Tunnelblick's VPN Details window.
10. Click on the large "Configurations" button at the top right of the window, then click on the "Log" tab on the right. (This makes sure Tunnelblick is recording the log.)
11. Select a configuration in the list on the left and click the "Connect" button.
12. Make sure the OpenVPN VPN is behaving as you expect.
12. Disconnect the VPN but leave Tunnelblick's "VPN Details" window open..
13. Try macOS's built-in VPN.

If it fails, click Tunnelblick's "Copy Diagnostic Info to Clipboard" button, and paste into a reply.

**Comment by jkbullard** [comment]
Closed due to lack of response from original poster.
