### ISSUE TITLE
Can't connect  using my .ovpn file

### ISSUE THREAD

**Issue by destah21** [Tunnelblick/Tunnelblick#534]
**Describe the bug**
Can't connect. Error says 
Tunnelblick was not able to load a system extension that is needed to connect to destahowens.
More information [tunnelblick.net]

**To Reproduce**
1. Drag and drop my .ovpn file to tunnelblick
2. Click on 'connect'
3. fail to connect, get above error message.

**Expected behavior**
I would expect this .ovpn file to work since it works on other machines. 

**Screenshots**

**Additional context**
There is another vpn installed on this machine to log into corporate network as needed. I have this vpn closed when I am trying to use tunnelblick

**Diagnostic information**

*Tunnelblick: macOS 10.13.6; Tunnelblick 3.7.8 (build 5180); Admin user
git commit 75a15f3fcb6de5a66bb6b7175b720645332ee778

Configuration destahowens

"Sanitized" condensed configuration file for /Library/Application Support/Tunnelblick/Shared/destahowens.tblk:

[Lines that appear to be security-related have been omitted]
setenv FORWARD_COMPATIBLE 1
client
server-poll-timeout 4
nobind
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 443 tcp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
dev tun
dev-type tun
ns-cert-type server
reneg-sec 604800
sndbuf 100000
rcvbuf 100000
comp-lzo no
verb 3
setenv PUSH_PEER_INFO
<ca>
[Security-related line(s) omitted]
</ca>
<cert>
[Security-related line(s) omitted]
</cert>
<key>
[Security-related line(s) omitted]
</key>
key-direction 1
<tls-auth>
[Security-related line(s) omitted]
</tls-auth>
no-replay
[Lines that appear to be security-related have been omitted]
[Lines that appear to be security-related have been omitted]
[Lines that appear to be security-related have been omitted]

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   16    0 0xffffff7f80d69000 0x10000    0x10000    com.displaylink.driver.DisplayLinkDriver (4.3 (206)) 21BA08D2-055E-380E-B526-1798079CF68D <15 12 5 4 3>
  153    0 0xffffff7f80cea000 0x12000    0x12000    net.pulsesecure.PulseSecureFirewall (9.0.3f4) 3CA418D7-FC1A-35D3-A46B-5033C74B9C44 <5 4 3 2 1>
  170    0 0xffffff7f80ea1000 0x18000    0x18000    com.GSI.kext.gsidrv (1) EDEC770A-780E-3EB7-AB25-46DE13DCD904 <7 5 4 1>
  172    0 0xffffff7f8490b000 0x21000    0x21000    com.symantec.dlp.fsd (15.1.01) 514055E8-6EED-3490-8F97-0307BD321996 <5 4 3 1>
  173    0 0xffffff7f8492c000 0xd0000    0xd0000    com.crowdstrike.sensor (86.02) 165D5A32-A252-395A-8753-3CEF20B307DE <17 7 5 4 3 2 1>
  174    0 0xffffff7f849fc000 0x3000     0x3000     com.symantec.dlp.macpd (15.1.01) 8D487A87-FFA3-3381-9D3D-F4354EC48F95 <7 5 4 3 2 1>
  176    0 0xffffff7f849ff000 0x30000    0x30000    net.elastica.reachagent.macosx.kext (2.15.2b1) 29C5FAF9-7219-30EA-B395-EB58CC4490F8 <5 4 2 1>

================================================================================

Files in destahowens.tblk:
      Contents/Resources/config.ovpn

================================================================================

Configuration preferences:

-skipWarningThatMayNotConnectInFutureBecauseOfOpenVPNOptions = 1
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0
-lastConnectionSucceeded = 0

================================================================================

Wildcard preferences:

-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0

================================================================================

Program preferences:

launchAtNextLogin = 1
tunnelblickVersionHistory = (
    "3.7.8 (build 5180)"
)
lastLaunchTime = 577913057.495098
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
NSWindow Frame ConnectingWindow = 645 646 389 187 0 0 1680 1027 
detailsWindowFrameVersion = 5180
detailsWindowFrame = {{194, 477}, {920, 468}}
detailsWindowLeftFrame = {{0, 0}, {165, 350}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = log
leftNavSelectedDisplayName = destahowens
AdvancedWindowTabIdentifier = vpnCredentials
haveDealtWithOldTunTapPreferences = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUScheduledCheckInterval = 86400
SULastCheckTime = 2019-04-25 22:28:35 +0000
SUHasLaunchedBefore = 1
WebKitDefaultFontSize = 16
WebKitStandardFont = Times

================================================================================

Tunnelblick Log:

================================================================================

"Sanitized" full configuration file

# Automatically generated OpenVPN client config file
# Generated on Thu Jan 28 10:02:59 2016 by OVPNAS20
# Note: this config file contains inline private keys
#       and therefore should be kept confidential!
# Note: this configuration is user-locked to the username below
# OVPN_ACCESS_SERVER_USERNAME=destahowens
# Define the profile name of this particular configuration file
# OVPN_ACCESS_SERVER_PROFILE=destahowens@medianodevpn.sensity.com/AUTOLOGIN
# OVPN_ACCESS_SERVER_AUTOLOGIN=1
# OVPN_ACCESS_SERVER_CLI_PREF_ALLOW_WEB_IMPORT=True
# OVPN_ACCESS_SERVER_CLI_PREF_BASIC_CLIENT=False
# OVPN_ACCESS_SERVER_CLI_PREF_ENABLE_CONNECT=True
# OVPN_ACCESS_SERVER_CLI_PREF_ENABLE_XD_PROXY=True
# OVPN_ACCESS_SERVER_WSHOST=medianodevpn.sensity.com:443
# OVPN_ACCESS_SERVER_WEB_CA_BUNDLE_START
# -----BEGIN CERTIFICATE-----
 [Lines that appear to be security-related have been omitted]
# -----END CERTIFICATE-----
# OVPN_ACCESS_SERVER_WEB_CA_BUNDLE_STOP
# OVPN_ACCESS_SERVER_IS_OPENVPN_WEB_CA=1
# OVPN_ACCESS_SERVER_ORGANIZATION=OpenVPN Technologies, Inc.
setenv FORWARD_COMPATIBLE 1
client
server-poll-timeout 4
nobind
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 443 tcp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
remote medianodevpn.sensity.com 1194 udp
dev tun
dev-type tun
ns-cert-type server
reneg-sec 604800
sndbuf 100000
rcvbuf 100000
# NOTE: LZO commands are pushed by the Access Server at connect time.
# NOTE: The below line doesn't disable LZO.
comp-lzo no
verb 3
setenv PUSH_PEER_INFO

<ca>
 [Security-related line(s) omitted]
</ca>

<cert>
 [Security-related line(s) omitted]
</cert>

<key>
 [Security-related line(s) omitted]
</key>

key-direction 1
<tls-auth>
 [Security-related line(s) omitted]
</tls-auth>

# Extra user-defined configuration
no-replay
## -----BEGIN RSA SIGNATURE-----
 [Lines that appear to be security-related have been omitted]
## -----BEGIN CERTIFICATE-----
 [Lines that appear to be security-related have been omitted]
## -----BEGIN CERTIFICATE-----
 [Lines that appear to be security-related have been omitted]
## -----END CERTIFICATE-----

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
TTL232R-3V3
USB 10/100/1000 LAN
Wi-Fi
Bluetooth PAN
Thunderbolt Bridge

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
XHC1: flags=0<> mtu 0
XHC0: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether f4:0f:24:30:50:f1 
	inet6 fe80::c4:96fc:a629:b5ff%en0 prefixlen 64 secured scopeid 0x8 
	inet 68.140.241.67 netmask 0xfffffc00 broadcast 68.140.243.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 06:0f:24:30:50:f1 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether b2:a1:51:eb:3f:0b 
	inet6 fe80::b0a1:51ff:feeb:3f0b%awdl0 prefixlen 64 scopeid 0xa 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 26:00:44:11:86:05 
	media: autoselect <full-duplex>
	status: inactive
en4: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 26:00:44:11:86:04 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 26:00:44:11:86:00 
	media: autoselect <full-duplex>
	status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 26:00:44:11:86:01 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 26:00:44:11:86:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 14 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 13 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 11 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 12 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::98b6:58bf:cc46:f00%utun0 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22 
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active

================================================================================

Console Log:

2019-04-25 12:23:37 Tunnelblick[1160] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2019-04-25 12:23:37 Tunnelblick[1160] Set 'expect disconnect 0 ALL'
2019-04-25 12:23:38 Tunnelblick[1160] Finished shutting down Tunnelblick; allowing termination
2019-04-25 12:24:16 Tunnelblick[5546] Tunnelblick: macOS 10.13.6; Tunnelblick 3.7.8 (build 5180)
2019-04-25 12:24:17 Tunnelblick[5546] Sparkle: ===== Tunnelblick =====
2019-04-25 12:24:17 Tunnelblick[5546] Sparkle: Verified appcast signature
2019-04-25 12:25:02 Tunnelblick[5546] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2019-04-25 12:25:04 tunnelblickd[5562] Status = 247 from tunnelblick-helper command 'start destahowens.tblk 63550 769 0 1 0 1065265 -ptADGNWradsgnw 2.4.6-openssl-1.0.2q'
2019-04-25 12:25:07 Tunnelblick[5546] tunnelblickd status from start: 247
2019-04-25 15:24:16 Tunnelblick[5546] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2019-04-25 15:24:19 tunnelblickd[9223] Status = 247 from tunnelblick-helper command 'start destahowens.tblk 56399 769 0 1 0 1065265 -ptADGNWradsgnw 2.4.6-openssl-1.0.2q'
2019-04-25 15:24:21 Tunnelblick[5546] tunnelblickd status from start: 247
2019-04-25 15:24:34 Tunnelblick[5546] Tunnelblick needs to perform an action that requires a computer administrator's authorization.
2019-04-25 15:24:34 Tunnelblick[5546] Beginning installation or repair
2019-04-25 15:24:34 Tunnelblick[5546] Installation or repair succeeded; Log:
                                       Tunnelblick installer started 2019-04-25 15:24:34. 2 arguments: 0x2001
                                            /Users/destah/Library/Application Support/Tunnelblick/Configurations/destahowens.tblk
                                       removed /Users/destah/Library/Application Support/Tunnelblick/Configurations/destahowens.tblk
                                       removed /Library/Application Support/Tunnelblick/Users/destah/destahowens.tblk
                                       Tunnelblick installer finished without error
2019-04-25 15:24:34 Tunnelblick[5546] Uninstalled configuration file /Users/destah/Library/Application Support/Tunnelblick/Configurations/destahowens.tblk
2019-04-25 15:25:14 Tunnelblick[5546] Error returned from setAttributes: {
                                           NSFilePosixPermissions = 488;
                                       } ofItemAtPath: /private/var/folders/h0/08s90bfd15sbldyn47nj0_n00000gn/T; Error was Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “T” in the folder “08s90bfd15sbldyn47nj0_n00000gn”." UserInfo={NSFilePath=/private/var/folders/h0/08s90bfd15sbldyn47nj0_n00000gn/T, NSUnderlyingError=0x604000241770 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}; stack trace: (
                                       	0   Tunnelblick                         0x0000000100c21376 -[NSFileManager(TB) tbChangeFileAttributes:atPath:] + 161
                                       	1   Tunnelblick                         0x0000000100c61a8c createDir + 303
                                       	2   Tunnelblick                         0x0000000100c61ae8 createDir + 395
                                       	3   Tunnelblick                         0x0000000100c2cb35 -[ConfigurationManager installConfigurations:skipConfirmationMessage:skipResultMessage:notifyDelegate:disallowCommands:] + 1578
                                       	4   Tunnelblick                         0x0000000100c2d177 -[ConfigurationManager installConfigurations:skipMessages:notifyDelegate:disallowCommands:] + 77
                                       	5   Tunnelblick                         0x0000000100c3266d +[ConfigurationManager installConfigurationsShowMessagesNotifyDelegateOperation:] + 93
                                       	6   Foundation                          0x00007fff4e3b01f8 __NSThread__start__ + 1197
                                       	7   libsystem_pthread.dylib             0x00007fff74410661 _pthread_body + 340
                                       	8   libsystem_pthread.dylib             0x00007fff7441050d _pthread_body + 0
                                       	9   libsystem_pthread.dylib             0x00007fff7440fbf9 thread_start + 13
                                       )
2019-04-25 15:25:14 Tunnelblick[5546] Warning: Unable to change permissions from 700 to 750 on /private/var/folders/h0/08s90bfd15sbldyn47nj0_n00000gn/T
2019-04-25 15:25:14 Tunnelblick[5546] Converting/Installing /Users/destah/Downloads/destahowens.ovpn: Converted OpenVPN configuration
2019-04-25 15:25:32 Tunnelblick[5546] Tunnelblick needs to perform an action that requires a computer administrator's authorization.
2019-04-25 15:25:32 Tunnelblick[5546] Beginning installation or repair
2019-04-25 15:25:32 Tunnelblick[5546] Installation or repair succeeded; Log:
                                       Tunnelblick installer started 2019-04-25 15:25:32. 3 arguments: 0x0001
                                            /Library/Application Support/Tunnelblick/Shared/destahowens.tblk
                                            /private/var/folders/h0/08s90bfd15sbldyn47nj0_n00000gn/T/Tunnelblick-dT7Wf9/destahowens.tblk
                                       Copied /private/var/folders/h0/08s90bfd15sbldyn47nj0_n00000gn/T/Tunnelblick-dT7Wf9/destahowens.tblk
                                           to /Library/Application Support/Tunnelblick/Shared/destahowens.tblk.temp
                                       Renamed /Library/Application Support/Tunnelblick/Shared/destahowens.tblk.temp
                                            to /Library/Application Support/Tunnelblick/Shared/destahowens.tblk
                                       Changed ownership of /Library/Application 
Support/Tunnelblick/Shared/destahowens.tblk and its contents from 501:20 to 0:0
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/destahowens.tblk
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/destahowens.tblk/Contents
                                       Changed permissions from 750 to 755 on /Library/Application Support/Tunnelblick/Shared/destahowens.tblk/Contents/Resources
                                       Changed permissions from 740 to 700 on /Library/Application Support/Tunnelblick/Shared/destahowens.tblk/Contents/Resources/config.ovpn
                                       Tunnelblick installer finished without error
2019-04-25 15:25:46 Tunnelblick[5546] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2019-04-25 15:25:48 tunnelblickd[9260] Status = 247 from tunnelblick-helper command 'start destahowens.tblk 55189 769 0 3 0 1065265 -ptADGNWradsgnw 2.4.6-openssl-1.0.2q'
2019-04-25 15:25:51 Tunnelblick[5546] tunnelblickd status from start: 247
2019-04-25 15:28:32 Tunnelblick[5546] Sparkle: Verified appcast signature
2019-04-25 15:31:17 Tunnelblick[5546] runTunnelblickd: no data available from tunnelblickd socket; sleeping 5.000000 seconds...
2019-04-25 15:31:19 tunnelblickd[9305] Status = 247 from tunnelblick-helper command 'start destahowens.tblk 63416 769 0 3 0 1065265 -ptADGNWradsgnw 2.4.6-openssl-1.0.2q'
2019-04-25 15:31:22 Tunnelblick[5546] tunnelblickd status from start: 247

**Comment by jkbullard** [comment]
The problem is probably the "net.pulsesecure.PulseSecureFirewall" kext.

As can be seen in [Errors Loading Kexts](https://tunnelblick.net/cKextLoadError.html), if you remove the "dev-type tun" line in your OpenVPN configuration file Tunnelblick/OpenVPN will use the macOS "utun" device and not need to load its kext.

However, be aware that firewalls often interfere with VPNs.

**Comment by jkbullard** [comment]
Closing this issue because of a lack of response.
