### ISSUE TITLE
Tunnelblick always pops up "no network connection available" on startup with no network

### ISSUE THREAD

**Issue by tidalscale-keithr** [Tunnelblick/Tunnelblick#536]
Whenever I start my computer with no network connection, I get a popup from Tunnelblick with the message:

"No network connection is available.

Please turn on Wi-Fi and connect to a wireless network, plug in an Ethernet cable, or connect to a network in some other way.

See the Network panel in macOS System Preferences for more information."

Usually I *know* I don't have a network connection; I don't need Tunnelblick telling me that. I don't have any VPNs configured to connect at startup, and I tried turning off automatic updates. There should be no reason for Tunnelblick to even notice that there's no network.

**To Reproduce**
1. Quit Tunnelblick
2. Disconnect your network (e.g. turn off WiFi)
3. Start Tunnelblick
4. See the popup that tells you what you already know, and makes you waste your time clicking "OK"

**Expected behavior**
Tunnelblick shouldn't even try to access the network until I select "connect <vpn_name>". If it does try to access the network in the background (e.g. to check for an update), it should fail silently and try again when the network is connected.

**Screenshots**
<img width="617" alt="Screen Shot 2019-05-18 at 16 36 46" src="https://user-images.githubusercontent.com/3484080/57976020-58476600-798b-11e9-940c-e9625d04ad23.png">

**Diagnostic information**
*Tunnelblick: macOS 10.14.4; Tunnelblick 3.7.8 (build 5180); prior version 3.7.7 (build 5150); Admin user
git commit 75a15f3fcb6de5a66bb6b7175b720645332ee778

Configuration TidalScale

"Sanitized" condensed configuration file for /Users/keithr/Library/Application Support/Tunnelblick/Configurations/TidalScale.tblk:

client
dev tun
proto udp
remote vpn.tidalscale.com 1194
nobind
persist-key
persist-tun
ca ca.crt
cert client.crt
key client.key
tls-auth ta.key 1
cipher AES-256-CBC
remote-cert-tls server
verb 3
route-up /usr/local/libexec/ts-vpn-up
route-pre-down /usr/local/libexec/ts-vpn-down

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  156    0 0xffffff7f80eca000 0xf000     0xf000     com.displaylink.driver.DisplayLinkDriver (3.1.0 (82262)) 8834A2E2-3D40-310C-8196-1B1D9D0A8BF5 <107 6 5 3>
  169    0 0xffffff7f84037000 0x14000    0x14000    com.intel.kext.intelhaxm (1.1.5) F9B0BE86-B3BA-3DE8-A974-060C7D21EA30 <8 6 5 3 1>

================================================================================

Files in TidalScale.tblk:
      Contents/Resources/ta.key
      Contents/Resources/cli….crt
      Contents/Resources/ca.crt
      Contents/Resources/config.ovpn
      Contents/Resources/cli….key

================================================================================

Configuration preferences:

useDNS = 0
-doNotReconnectOnFastUserSwitch = 1
-doNotReconnectOnWakeFromSleep = 0
-runMtuTest = 1
-useRouteUpInsteadOfUp = 1
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 1
-keepConnected = 1
-lastConnectionSucceeded = 1
-prependDomainNameToSearchDomains = 1

================================================================================

Wildcard preferences:

-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0

================================================================================

Program preferences:

launchAtNextLogin = 1
tunnelblickVersionHistory = (
    "3.7.8 (build 5180)",
    "3.7.7 (build 5150)",
    "3.7.6a (build 5080)",
    "3.7.6 (build 5060)",
    "3.7.5a (build 5011)",
    "3.7.5 (build 5010)",
    "3.7.4b (build 4921)"
)
statusDisplayNumber = 0
lastLaunchTime = 579915325.029899
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
lastConnectedDisplayName = TidalScale
keyboardShortcutIndex = 1
updateCheckAutomatically = 0
NSWindow Frame SettingsSheetWindow = 175 219 829 524 0 0 1440 900 
NSWindow Frame ConnectingWindow = 525 534 389 187 0 0 1440 900 
NSWindow Frame SUStatusFrame = -1160 713 400 129 -1920 0 1920 1080 
NSWindow Frame SUUpdateAlert = 650 498 620 392 0 0 1920 1057 
detailsWindowFrameVersion = 5180
detailsWindowFrame = {{260, 324}, {920, 468}}
detailsWindowLeftFrame = {{0, 0}, {165, 350}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = settings
leftNavSelectedDisplayName = TidalScale
AdvancedWindowTabIdentifier = connectingAndDisconnecting
haveDealtWithOldTunTapPreferences = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 0
SUScheduledCheckInterval = 86400
SULastCheckTime = 2019-04-18 18:15:36 +0000
SUHasLaunchedBefore = 1
WebKitDefaultFontSize = 16
WebKitStandardFont = Times

================================================================================

Tunnelblick Log:

================================================================================

"Sanitized" full configuration file

client
dev tun
proto udp
remote vpn.tidalscale.com 1194
nobind
# Try to preserve some state across restarts.
persist-key
persist-tun

ca ca.crt
cert client.crt
key client.key

tls-auth ta.key 1
cipher AES-256-CBC

remote-cert-tls server

# Set log file verbosity.
verb 3

route-up /usr/local/libexec/ts-vpn-up
route-pre-down /usr/local/libexec/ts-vpn-down

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
USB-Serial Controller
USB 10/100/1000 LAN
AX88179 USB 3.0 to Gigabit Ethernet
Wi-Fi
Bluetooth PAN

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 60:f8:1d:c5:ad:b4 
	inet6 fe80::b9:3a34:f614:3110%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.100.122 netmask 0xfffffc00 broadcast 192.168.103.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 02:f8:1d:c5:ad:b4 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 36:76:f3:49:58:4b 
	inet6 fe80::3476:f3ff:fe49:584b%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:07:a4:68:b0 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:07:a4:68:b1 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 72:00:07:a4:68:b0 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::b995:dfe:fab7:3a9b%utun0 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>

================================================================================

Console Log:

2019-05-18 13:25:34 ksinstall[83241] 2019-05-18 13:25:34.710 ksinstall[83241/0x1076775c0] [lvl=2] -[KeystoneInstallTool main] Google Software Update installer started.
2019-05-18 13:25:34 ksinstall[83241] 2019-05-18 13:25:34.715 ksinstall[83241/0x1076775c0] [lvl=2] -[KeystoneInstallTool main] Google Software Update installer starting Installation.
2019-05-18 13:25:34 ksinstall[83241] 2019-05-18 13:25:34.881 ksinstall[83241/0x1076775c0] [lvl=2] -[KeystoneInstallTool main] Google Software Update installer ran successfully.
2019-05-18 15:54:32 Tunnelblick[436] connect: cancelled when asked to re-enabling network access
2019-05-18 16:30:06 Tunnelblick[436] Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SUsers-Skeithr-STidalScale-Dtblk-SContents-SResources'
2019-05-18 16:30:09 Tunnelblick[436] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2019-05-18 16:30:10 Tunnelblick[436] Set 'expect disconnect 0 ALL'
2019-05-18 16:30:10 Tunnelblick[436] Finished shutting down Tunnelblick; allowing termination
2019-05-18 16:30:17 Tunnelblick[85564] Tunnelblick: macOS 10.14.4; Tunnelblick 3.7.8 (build 5180)
2019-05-18 16:30:17 Tunnelblick[85564] DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
2019-05-18 16:35:09 Tunnelblick[85564] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2019-05-18 16:35:09 Tunnelblick[85564] Set 'expect disconnect 0 ALL'
2019-05-18 16:35:09 Tunnelblick[85564] Finished shutting down Tunnelblick; allowing termination
2019-05-18 16:35:24 Tunnelblick[85693] Tunnelblick: macOS 10.14.4; Tunnelblick 3.7.8 (build 5180)
2019-05-18 16:35:24 Tunnelblick[85693] DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug

**Comment by jkbullard** [comment]
Thanks for your report, and for providing all the info.

This was fixed in Tunnelblick 3.7.9beta02 build 5200 (2019-01-10).

The fix will be in Tunnelblick 3.7.9 which is scheduled for release next week.
