### ISSUE TITLE
i need a whitelist...

### ISSUE THREAD

**Issue by qzd1989** [Tunnelblick/Tunnelblick#541]
I need to visit or connect chinese website/ip without vpn, and visit youtube/google with vpn, how can i do?

thank you~

Tunnelblick 3.7.8 (build 5180)  on macos mojave 10.14.4

**Comment by qzd1989** [comment]
better has an easy way to solve my problem           -_-

**Comment by jkbullard** [comment]
Tunnelblick does not do that easily.

The VPN works using IP addresses (not domain names like "youtube.com"), so it may be very hard to set up for the websites you want. If you know the IP addresses of the sites you need to visit with the VPN, you could probably set up the VPN to be used only for those IP addresses. But it is difficult to do and may be impossible if your VPN service provider (the organization that you get your VPN from) does not support that setup. Briefly, you would set up the VPN to:
 1. Not send all IPv4 traffic through the VPN; and
 1. Send IPv4 traffic through the VPN for each IP address or range of IP addresses that you want, using "route" commands in your OpenVPN configuration file.

Your VPN service provider may not support 1., so I suggest you contact their tech support.

Good luck and please report back here what you find out.
