### ISSUE TITLE
Unreadable alert text on Dark Mode

### ISSUE THREAD

**Issue by DominikPalo** [Tunnelblick/Tunnelblick#543]
**Describe the bug**
Different alert windows have an unreadable text (black-colored text) when using Dark Mode in macOS.

Tunnelblick version: 3.7.9 (build 5320)
OS version: macOS Mojave 10.14.4

**Expected behavior**
Text is white-colored and readable.

**Screenshots**
<img width="507" alt="tunnelblick" src="https://user-images.githubusercontent.com/1623257/58759499-4a691780-852b-11e9-92b3-2484524ab9e7.png">

**Comment by jkbullard** [comment]
@DominikPalo - Thanks for reporting this. It affects many other alert windows, too.

If you're running 10.14.5 or later, this will be fixed for all alert windows in the next Tunnelblick beta, which will be released soon.

The fix has been waiting for Apple to fix a bug in Mojave, which they have done in 10.14.5. The fix makes links in some alert windows unusable on earlier versions of Mojave, so the fix only applies to 10.14.5 and higher.
