### ISSUE TITLE
Tunnelblick website down: Connection timed out

### ISSUE THREAD

**Issue by chrissinclairedited** [Tunnelblick/Tunnelblick#556]
**Describe the bug**
Accessing https://tunnelblick.net/ shows a Cloudflare HTTP 522 (Connection Timed Out) error. 

**To Reproduce**
1. Go to 'https://tunnelblick.net/'
2. See error

**Expected behavior**
The website should be live.

**Screenshots**
<img width="1107" alt="Screenshot 2019-06-26 at 10 18 47" src="https://user-images.githubusercontent.com/39764468/60167875-e0772180-97fb-11e9-97f7-467a7b448343.png">

<img width="944" alt="Screenshot 2019-06-26 at 10 22 18" src="https://user-images.githubusercontent.com/39764468/60168224-59767900-97fc-11e9-8e20-03784cc840d0.png">

**Additional context**
Accessing from London, UK.

**Diagnostic information**
N/A

**Comment by jkbullard** [comment]
Thanks for your report.

I'm working to get this fixed. Apparently some ISPs are blocking traffic to/from the Tunnelblick server that processes "ipinfo" requests.

**Comment by chrissinclairedited** [comment]
No worries - let me know if you need any more info / retesting. Thanks for looking at it so quickly.

On the off chance that anyone lands here wondering, looks like the backup site tunnelblick.github.io is still working properly.

**Comment by jkbullard** [comment]
> looks like the backup site tunnelblick.github.io is still working properly.

Yes, thanks for mentioning that.

Accessing the backup website for information and downloads should work, and little has changed since the backup was last updated. (It's updated each time there's a release). And access for checking for updates to Tunnelblick should also continue to work (for a while), since it is being cached by Cloudflare.

However, access to the primary server is necessary for Tunnelblick to do IP address checks. The backup server can't do that.

**Comment by mmahut** [comment]
And given tunnelblick is using tunnelblick.net it fails to connect.

```
2019-06-27 09:58:13.801616 Tunnelblick[1798] currentIPInfo(Name): IP address info could not be fetched within 35.6 seconds; the error was 'Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x600002eb9a70 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=https://tunnelblick.net/ipinfo, NSErrorFailingURLKey=https://tunnelblick.net/ipinfo, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}'; the response was '(null)'
```

**Comment by jkbullard** [comment]
@mmahut wrote:
> And given tunnelblick is using tunnelblick.net it fails to connect.

No, it connects VPNs and they work properly. It just can't verify that the IP address changed. (And it can't check for updates.)

This is a website (or Cloudflare) problem that only affects users in some areas (Toronto, Mexico, and Paris, for example, but not New York, Frankfurt, or Sydney.) It is being worked on.

**Comment by jkbullard** [comment]
This problem seems to have been resolved (a few days ago) so I'm closing this Issue.
