### ISSUE TITLE
Wish: one-time entering of VPN user and code

### ISSUE THREAD

**Issue by krabaten** [Tunnelblick/Tunnelblick#557]
My VPN-provider updates the logon files as needed. Maybe twice a year, maybe 4. 

I then have to enter user and code for every one of them.

Is there a con to making that possible? 

![VPN-servers](https://user-images.githubusercontent.com/45611170/60190009-38307f80-9832-11e9-957a-92c2b7819ae9.png)

**Comment by jkbullard** [comment]
You can have all configurations "share" a username and password:

 1. Select all of the configurations in the Configurations panel of Tunnelblick's "VPN Details" window.
 2. Click the "Advanced" button on the "Settings" tab.
 3. Click the "VPN Credentials" tab on the new "Advanced Settings" window that appeared.
 4. Put a check in the "All configurations use Common credentials" checkbox.

If I recall correctly, Tunnelblick will ask for the username/password the first time you try to connect to any configuration. If you save them in the Keychain, subsequent attempts to connect any configuration will get them from the Keychain.

(You can have named "sets" of credentials, for example, if you have two different VPN providers. To do that, you'd use the other buttons on that page, creating a name for the credentials, then specifying what named set of credentials the configurations that are currently selected in the "VPN Details" window should use.)
