### ISSUE TITLE
IPv6 DNS servers are not recognised as being routed through VPN

### ISSUE THREAD

**Issue by bert128** [Tunnelblick/Tunnelblick#558]
**Describe the bug**
When an OpenVPN server pushes a list of IPv6 DNS servers and a route which covers traffic to these servers via the VPN, Tunnelblick does not recognise the servers as being routed via VPN.

**To Reproduce**
1, create an openvpn server which pushes one or more ipv6 dns servers, and a route to the network prefix containing these servers.
2, connect

**Expected behavior**
In the example below, tunnelblick should recognise the route to 2001:470:ed03::/48 which covers the DNS servers 2001:470:ed03:9::43 and 2001:470:ed03:9::44

**Logs**

2019-07-02 08:13:52.361551 add_route_ipv6(2001:470:ed03::/48 -> 2402:6540:ed03:70::1 metric -1) dev utun3
2019-07-02 08:13:52.361641 /sbin/route add -inet6 2001:470:ed03:: -prefixlen 48 -iface utun3 add net 2001:470:ed03::: gateway utun3
(...)
2019-07-02 08:13:57.560761 *Tunnelblick: Warning: DNS server address 2001:470:ed03:9::43 is not a public DNS server known to Tunnelblick and is not being routed through the VPN
2019-07-02 08:13:57.874063 *Tunnelblick: Warning: DNS server address 2001:470:ed03:9::44 is not a public DNS server known to Tunnelblick and is not being routed through the VPN

**Comment by jkbullard** [comment]
@bert128 - Thanks for your report.

 1. Please connect your VPN and post the output of the following Terminal commands:

    route -n get -inet6 2001:4860:4860::8888
    route -n get -inet6 2001:470:ed03:9::43

(The first is an IPv6 server address for Google Public DNS, the second is an IPv6 server address you posted.)

 2. Then please post the output of repeating the commands after disconnecting the VPN.

**Comment by bert128** [comment]
**VPN Connected:**
$ route -n get -inet6 2001:4860:4860::8888
   route to: 2001:4860:4860::8888
destination: ::
       mask: default
    gateway: fe80::ec4:7aff:fe19:898c%en0
  interface: en0
      flags: <UP,GATEWAY,DONE,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0

$ route -n get -inet6 2001:470:ed03:9::43
   route to: 2001:470:ed03:9::43
destination: 2001:470:ed03:9::43
  interface: utun3
      flags: <UP,HOST,DONE,WASCLONED,IFSCOPE,IFREF>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0


**VPN disconnected:**
vulcan:run bert$ route -n get -inet6 2001:4860:4860::8888
   route to: 2001:4860:4860::8888
destination: ::
       mask: default
    gateway: fe80::ec4:7aff:fe19:898c%en0
  interface: en0
      flags: <UP,GATEWAY,DONE,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0
$ route -n get -inet6 2001:470:ed03:9::43
   route to: 2001:470:ed03:9::43
destination: ::
       mask: default
    gateway: fe80::ec4:7aff:fe19:898c%en0
  interface: en0
      flags: <UP,GATEWAY,DONE,PRCLONING>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500         0

**Comment by jkbullard** [comment]
Thanks, @bert128. The fix will be included in the next beta release of Tunnelblick.
