### ISSUE TITLE
Tunnelblick 3.8.1beta01 (build 5380) marked as LATEST RELEASE instead of PRERELEASE

### ISSUE THREAD

**Issue by core-code** [Tunnelblick/Tunnelblick#562]
the github release markings don't seem to be correctly set - each new release is always marked as 'latest release', even if it is not a stable official release

e.g. the newest release 
Tunnelblick 3.8.1beta01 (build 5380) 
should be correctly marked as 'prerelease' in github instead of as 'latest release'

**Comment by jkbullard** [comment]
Beta versions of Tunnelblick are full releases (and fall under that category on GitHub); they are not "prereleases".

**Comment by core-code** [comment]
well, this is not what common sense dictates and means i won't be able to provide proper support for 'tunnelblick' over at Homebrew Cask.

i suggest you take over the task of making sure tunneblick is kept up-to-date at Homebrew Cask yourself if you make sure that any automated approach to doing so is impossible.

**Comment by jkbullard** [comment]
> i suggest you take over the task of making sure tunneblick is kept up-to-date at Homebrew Cask yourself if you make sure that any automated approach to doing so is impossible.

No thanks.
