### ISSUE TITLE
Sparkle Codesign Fail and Project Using Outdated, Security Risk Version for Builds

### ISSUE THREAD

**Issue by robertleeblairjr** [Tunnelblick/Tunnelblick#563]
**Describe the bug**
Xcode fails to codesign Sparkle framework during builds in default configuration which are in the build instructions.

**To Reproduce**
1. Download a .zip package or clone the repo for master/develop branch
2. Load the project and configure according to build instructions
3. Initiate analysis/build and it fails
4. The error is the build failed because of the codesign for Sparkle framework

**Expected behavior**
Sparkle should build properly with codesign, as long as, the same signing certificate is used for the target build

**Screenshots**

**Additional context**
The Sparkle framework that this project has been using is very outdated. It poses a security risk because of patches that have been applied to the Sparkle framework over the past 2-3 years. I don't know exactly how this project has incorporated the Sparkle framework but in a couple of other projects I've built which use it, there was no problem with upgrading it to the next stable release. Perhaps, some time can be taken to investigate why Tunnelblick needs so many patches for using Sparkle. In fact, there are other VPN clients which use Sparkle, as well, so there shouldn't be the excuse of OpenVPN, OpenSSL, etc. inconsistencies. I've attempted to import a local build of the latest stable Sparkle and have made some progress but because of some codesign patching with OpenVPN, then it fails to build, unless I use the Sparkle package included with source. I really enjoy the app and will attempt to contribute but this project needs to some cleaning up with the hacks and unorthodox patching it has been using. Even the Localized.strings are deprecated and will not import/export to being compatible with newer Xcode versions without failing. It's like an app that's only intent was to be used on macOS but without the conformity and compatibility of developing an app for the platform. This is the only app that I've come across which is developed only for macOS but has the most failures with building on the target platform.

Additional: I've been attempting to migrate a newer Sparkle.framework using suggestions from the project page documentation.
[https://sparkle-project.org/documentation/](url)

The build utilizes the imported framework but fails with OpenVPN. I can only think that perhaps, there's a patch which is attempting to use the Sparkle update framework to pass checks/requests through the tunnel and because of this hack/patch, then OpenVPN fails to build from the inconsistencies. However, this is just a guess since I've only been trying to troubleshoot the short period of time I've devoted to it.

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
Thanks for your report and comments.

@robertleeblairjr wrote:
 > Xcode fails to codesign Sparkle framework during builds in default configuration which are in the build instructions.

That's correct. The instructions for building Tunnelblick do not result in a signed build. Xcode is unable to correctly sign Tunnelblick's complex mix of components.

> 1. Download a .zip package or clone the repo for master/develop branch
> 2. Load the project and configure according to build instructions
> 3. Initiate analysis/build and it fails
> 4. The error is the build failed because of the codesign for Sparkle framework

This doesn't happen to me. (I downloaded a .zip of the master branch, expanded it, opened it in Xcode, cleaned, analyzed, then built it. There were 19 warnings, mostly in the oldest version of OpenVPN, but no errors.)

Are you doing this on macOS 10.11.6 with Xcode 7.3.1? That's the only build configuration we support, as documented in the build instructions you reference.

> The Sparkle framework that this project has been using is very outdated. It poses a security risk because of patches that have been applied to the Sparkle framework over the past 2-3 years.

Could you give some examples of patches to Sparkle that fix security risks that have not also been incorporated into Tunnelblick's copy of Sparkle?

> Perhaps, some time can be taken to investigate why Tunnelblick needs so many patches for using Sparkle.

We make patches to Sparkle because our threat model is different from Sparkle's.

For example, Sparkle accepts – at least the last time I looked – unsigned appcasts and release notes. That's not acceptable to us and the Sparkle developers do not want to add signed appcasts to Sparkle, so we patch Sparkle to require that appcasts be signed and imbed the release notes within the appcasts so the release notes are protected by the appcasts' signatures.

**Comment by robertleeblairjr** [comment]
> Thanks for your report and comments.
> 
> @robertleeblairjr wrote:
> 
> > Xcode fails to codesign Sparkle framework during builds in default configuration which are in the build instructions.
> 
> That's correct. The instructions for building Tunnelblick do not result in a signed build. Xcode is unable to correctly sign Tunnelblick's complex mix of components.
> 
> > 1. Download a .zip package or clone the repo for master/develop branch
> > 2. Load the project and configure according to build instructions
> > 3. Initiate analysis/build and it fails
> > 4. The error is the build failed because of the codesign for Sparkle framework
> 
> This doesn't happen to me. (I downloaded a .zip of the master branch, expanded it, opened it in Xcode, cleaned, analyzed, then built it. There were 19 warnings, mostly in the oldest version of OpenVPN, but no errors.)
> 
> Are you doing this on macOS 10.11.6 with Xcode 7.3.1? That's the only build configuration we support, as documented in the build instructions you reference.

I'm using 10.14.6 with Xcode 8.0 compatibility. It will build unsigned in Xcode 10.3 from the download Source.zip but not with enabling signing credentials. I would believe that it should allow at least Ad hoc or another valid developer certificate for signing. However, if there are conflicts when signing/building Sparkle.framework that you guys have a workaround, then this makes sense as to why it was failing. I didn't have time to fully understand, other than, knowing Sparkle.framework should build with the same used for codesign target.
> 
> > The Sparkle framework that this project has been using is very outdated. It poses a security risk because of patches that have been applied to the Sparkle framework over the past 2-3 years.
> 
> Could you give some examples of patches to Sparkle that fix security risks that have not also been incorporated into Tunnelblick's copy of Sparkle?

EdDSA and Apple Code Signing support, to include, the hardened runtime which will be required for notarized apps in 10.15. Generate appcast can sign bundles and authenticate, mem leaks, etc. I'm sure there are others since it's going on 3 years of patches, changes, and other revisions made. Simply reading over the past couple of years releases page for a basic rundown of commits would find applicable changes and recommendations to using a more up-to-date framework.
[https://github.com/sparkle-project/Sparkle/releases](url)
I'm sure the app is built upon and uses a function from the framework which has had a fix since 1.15 in 2016.
> 
> > Perhaps, some time can be taken to investigate why Tunnelblick needs so many patches for using Sparkle.
> 
> We make patches to Sparkle because our threat model is different from Sparkle's.
> 
> For example, Sparkle accepts – at least the last time I looked – unsigned appcasts and release notes. That's not acceptable to us and the Sparkle developers do not want to add signed appcasts to Sparkle, so we patch Sparkle to require that appcasts be signed and imbed the release notes within the appcasts so the release notes are protected by the appcasts' signatures.

I thought the framework was used per needed extensibility of the functions. Those that are used are enabled, not used disabled, and it allows the framework to be extended for user-specific functions but not modified. As far as I know, modifying/patching software frameworks can cause different problems which would never occur or even introduce an additional security issue. Is the Sparkle.framework only used for checking/verifying/downloading updates for only the app?

What's the point of this if update archives are signed via EdDSA in Sparkle and must adhere to Apple's App Transport Security requirements?

[https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33](url)

However, I do understand if the reason for the lag in being able to update the project for compatibility of newer Xcode versions and third-party software is because of the hacking/patching which has been done and causes builds to break. This would make sense in why it is more difficult to make revisions to the project when the subcomponents don't build without patching them again. Sorry, if I missed something in the reply, it was getting lengthy.

**Comment by jkbullard** [comment]
@robertleeblairjr wrote:

> I'm using 10.14.6 with Xcode 8.0 compatibility.

You're not using a supported build environment; I'm not surprised it doesn't build.

>> Could you give some examples of patches to Sparkle that fix security risks that have not also been incorporated into Tunnelblick's copy of Sparkle?

> EdDSA and Apple Code Signing support, to include, the hardened runtime which will be required for notarized apps in 10.15. Generate appcast can sign bundles and authenticate, mem leaks, etc.

Hardened runtime is part of Apple's code signing process, not part of the build process. Tunnelblick binaries are notarized for macOS 10.15, including hardened runtime signing for Sparkle's fileop binary, updater app, and framework. (Tunnelblick and its other components are also signed with the hardened runtime option.)

Tunnelblick's version of Sparkle includes Apple code signing support. It does not include EdDSA, but it requires both the DSA signature and the Apple code signatures to be valid; Sparkle accepts an update if either one is valid.

So Tunnelblick's Sparkle is insecure if **both**:
 * A developer's DSA key is stolen **or** our DSA implementation is insecure; **and**
 * A developer's Apple Signing Identity key is stolen **or** Apple Signing is insecure.

Standard Sparkle is insecure if:
 * A developer's EdDSA key is stolen; **or**
 * A developer's Apple Signing Identity key is stolen; **or**
 * EdDSA is insecure; **or**
 * Apple signing is insecure.

> Generate appcast can sign bundles and authenticate, mem leaks, etc. I'm sure there are others since it's going on 3 years of patches, changes, and other revisions made.

We don't use Generate appcast and there are no known memory leaks in Tunnelblick's version of Sparkle.

There's no way I can respond to "it's old, so it must be insecure". Generally speaking, "patches, changes, and other revisions" can introduce their own security vulnerabilities, too.

> I thought the framework was used per needed extensibility of the functions. Those that are used are enabled, not used disabled, and it allows the framework to be extended for user-specific functions but not modified. As far as I know, modifying/patching software frameworks can cause different problems which would never occur or even introduce an additional security issue.

Sparkle doesn't have the flexibility you seem to think it has. There aren't delegates to or options to require both DSA and Apple signatures, or that appcasts and release notes be signed.

> Is the Sparkle.framework only used for checking/verifying/downloading updates for only the app?

Sorry, but I don't think I understand. Tunnelblick uses Sparkle to check/verify/download/install updates for the app, yes. (Tunnelblick also does its own integrity checks, including signature verifications, each time it is launched.)

> What's the point of this if update archives are signed via EdDSA in Sparkle and must adhere to Apple's App Transport Security requirements?

The point is it's another layer of security. More layers of security are better, in general. https: doesn't help if the site hosting appcasts is compromised, for example.

> However, I do understand if the reason for the lag in being able to update the project for compatibility of newer Xcode versions and third-party software is because of the hacking/patching which has been done and causes builds to break.

Tunnelblick patches:
 * tuntap to use it's own BundleIdentifier, per a specific request by Apple engineers;
 * easy-rsa so it works with paths that include spaces (and other things, I think);
 * OpenVPN to include the openvpn-xor-patch, which Tunnelblick developers have audited (and fixed many security problems with), and which the OpenVPN developers have decided not to include in OpenVPN, but which is used in many VPNS. Details are at [Tunnelblick and openvpn_xorpatch](https://tunnelblick.net/cOpenvpn_xorpatch.html).
 * Sparkle to fix a bug which was used to DOS appcast servers (and which a Tunnelblick developer found, developed a patch for, which was sent to Sparkle's developers who then accepted it), require signed appcasts, include less information in the system profile that it sends when asking for an appcast, change the name of the updater application, not interrupt if "do not disturb" is on, and correct some Turkish translations. (Some of these are included in newer versions of Sparkle, too, of course.)

Sparkle is the only code that is patched very much.

Patching has nothing to do with why we use an old version of Xcode. Newer versions of Xcode don't create stable builds, which has nothing to do with Sparkle. I'm not saying it's a problem with Xcode; I assume it's a problem with Tunnelblick, but, again, nothing to do with Sparkle.

**Comment by robertleeblairjr** [comment]
Again, it builds with code signing disabled on 10.14.6, Xcode 10.3 with 8.0 compatibility for target 10.10. Sparkle build fails in the TB building process with a valid developer certificate. Building without a certificate doesn't fail. Of course, it's unsigned, which sounds as though was the intent since I'm not a known developer. There are other different nuances which can cause a failure, as well, but this is the primary one whenever using default build configuration, regardless of the Xcode and macOS versions. Should I be able to sign this app with my certificate or use Ad hoc or is the build, to include third party software, intended to fail for anyone other than specific developers?

I've attempted to just use an updated package for any of the third party software and each of them fail to build. However, I can't say for certain that this wasn't muddled together with failures of Sparkle builds whenever I was trying to determine why the code signing didn't work. Along with, trying to import another Sparkle.framework which was built with code signing. So, I'll try to just test and see if making changes to the third party software one-by-one will be successful.

I'll have to research further about your proposal of supposed security risk but it doesn't seem any more likely than TB's own repos, dev certs, builds, etc. being compromised. Or, the OpenVPN, cryplibs, etc. that it relies upon. I can't really reply effectively but I even if an appcast server were compromised then the keys used to validate, along with checking signatures of the builds would be more than efficient at detecting a compromised package being transported to the client. Even TB has had security vulnerabilities, along with the third party software it relies upon. 
[https://www.cvedetails.com/vulnerability-list/vendor_id-1224/product_id-22982/Google-Tunnelblick.html](url)

The patching seems to not really add that much value in security over the difficulty of contributing and incompatibility of building the app. But, I'll digress since I only have a shallow knowledge of the topic. I would like to know if I can build with signing though or it's not allowed in the patching. It would seem odd that it succeeds without signing and fails with signing.

**Comment by jkbullard** [comment]
> Should I be able to sign this app with my certificate or use Ad hoc or is the build, to include third party software, intended to fail for anyone other than specific developers?

To repeat, Xcode is unable to correctly sign Tunnelblick's complex mix of components.

> I would like to know if I can build with signing though or it's not allowed in the patching. It would seem odd that it succeeds without signing and fails with signing.

See above. Signing has nothing to do with patching, it has to do with the complex layout of Tunnelblick's components.

To repeat, the use of build environments other than those tested by the developers has, in our experience, resulted in builds that do not work properly and is not recommended.

**Comment by robertleeblairjr** [comment]
I suppose I overlooked if you inferred that any signing during the build process wasn't supported. I was wanting to build for trying code found in similar apps preferences menus for correcting fading effects. That, or a proper way to add in enable/disable fade to the menu. Of course, this spiraled into numerous other issues whenever I first began trying to build what/with the inability to sign which I thought should be doable. Plus, I thought I'll try to import the framework to see if that may have an issue but then OpenVPN wouldn't build. At that point, I had built OpenVPN and wouldn't accept. Tried linking to Homebrew built; no go. And so on...which is what led me to this issue I submitted. Of course, there were quite a few others but I just focused on this one. Either way, I suppose this is something that won't be updated until it's causing a problem with the app not building at all or issues with operation. Thanks for the replies.

**Comment by robertleeblairjr** [comment]
I had slight progress with modifying the Preferences controller, 'DBPrefsWindowController', but grew tired of the difficulty in building because of unnecessary restrictions and lack of updates to the source for compatibility with Xcode 8+. In my opinion, placing overly restrictive measures on a client program is rather mundane but alienates individuals who could likely contribute to a project. If the hassle in it exceeds the free time they are willing to devote to it, then it would seem appropriate to direct a project with that intent. Although, I may have mistook this the wrong way, but there's no reason this project needed to have difficulties with signing and required patches for third party software which is used and trusted by other entities with much greater resources and needs for more secure software than this one. Either way, my opinion, but the evidence is in commits and work to solve long standing issues with something like an appearance rendering discrepancy. Perhaps, moving from this older window controller to something newer would be better but I didn't make any progress in trying to import with changing over to another project, RHPreferences. Maybe, the developers who have a tighter restraint on the builds for TB can take a look at moving to another preferences window controller.

[https://github.com/heardrwt/RHPreferences](url)

**Comment by tmthecoder** [comment]
@jkbullard I was able to successfully build Tunnelblick on Xcode 10 on macOS 10.14.6, and Sign it successfully by checking. the Sign on Copy option for sparkle. It still shows a "This copy has been tampered with", but runs normally with my VPN profiles. I'm wondering why don't you build with Xcode 10?

**Comment by jkbullard** [comment]
@tmthecoder - As I wrote earlier:
> Patching has nothing to do with why we use an old version of Xcode. Newer versions of Xcode don't create stable builds, which has nothing to do with Sparkle. I'm not saying it's a problem with Xcode; I assume it's a problem with Tunnelblick, but, again, nothing to do with Sparkle.

"This copy has been tampered with" means that checking the codesigning fails, so you didn't get Xcode to "sign it successfully" -- Xcode may have reported success but the signature is invalid.

Xcode apparently isn't able to codesign the complex structure of a Tunnelblick binary. Tunnelblick developers use a separate, non-public script to codesign and notarize Tunnelblick binaries for distribution.

I'm glad building with Xcode 10 results in working binaries for you. It doesn't for me. (And apparently it doesn't codesign properly for you.)

**Comment by tmthecoder** [comment]
@jkbullard XCode 10 didn't work for me initially, but once I changed the compatibility layer to XCode 8(Right sidebar) it worked like a charm. I have to clean every now and then just due to signing problems, but with signing disabled I haven't had any problems. Have you tried with the compatibility layer on? And If signing, in build settings check code sign on copy for sparkle

**Comment by tmthecoder** [comment]
@jkbullard on another note, will the signing script ever be released as I am looking to making a signed build, but I can't get hardened runtime enabled on every binary when sending the .app to notarize

**Comment by jkbullard** [comment]
1. Tunnelblick builds with Xcode 13.4.1 on macOS 12.6.6 ("Monterey").
 2. Since 2021-01-14, Tunnelblick has included tunnelblick/SignTunnelblickAppOrDmg.sh which can sign Tunnelblick.app and/or a disk image containing Tunnelblick with an ad-hoc or Developer ID signature.
