### ISSUE TITLE
Error during connection

### ISSUE THREAD

**Issue by zakabluk** [Tunnelblick/Tunnelblick#565]
I have tried to launch vpn and got error:
```
2019-07-29 14:39:06.088052 *Tunnelblick: macOS 10.14.6 (18G84); Tunnelblick 3.8.1beta01 (build 5380)
2019-07-29 14:39:06.544279 *Tunnelblick: Attempting connection with client.a.zakabluk.mgmt.linux using shadow copy; Set nameserver = 769; monitoring connection
2019-07-29 14:39:06.544519 *Tunnelblick: openvpnstart start client.a.zakabluk.mgmt.linux.tblk 63695 769 0 1 0 1098098 -ptADGNWradsgnw 2.4.7-openssl-1.0.2r
2019-07-29 14:39:06.569864 *Tunnelblick: openvpnstart starting OpenVPN
2019-07-29 14:39:21.653755 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
openvpnstart log:
     Loading tap-notarized.kext
     stderr from kextload: /Applications/Tunnelblick.app/Contents/Resources/tap-notarized.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
```

Config file
```
dev tap
proto tcp-client
remote remote.host
port 443
client
tls-client
resolv-retry infinite
nobind
remote-cert-tls server
```

**Comment by jkbullard** [comment]
@zakabluk - Please see [Errors Loading Kexts (Device Drivers) on macOS High Sierra (10.13) and higher
](https://tunnelblick.net/cKextLoadErrorHighSierra.html).

**Comment by zakabluk** [comment]
Thnx for your response. 
1. My firewall is disable.
2. not selected "Always load Tun driver.
3. Always load tap driver selected .
But I got same error.

**Comment by jkbullard** [comment]
@zakabluk - 

Because your configuration includes `dev tap`, you have a "Tap" VPN, not a "Tun" VPN.

 1. This problem has nothing to do with firewalls.
 2. This problem has nothing to do with your "load… driver" settings. Your tun and tap driver load settings will work, but so would the default settings (load automatically).

Did you read the document at the link I posted? Your response does not have anything to do with what is discussed on that page.

**Comment by zakabluk** [comment]
@jkbullard 
I realy don't understand what you want said me. First of all, i know what I'm using tap. On page which you sent me firs parte finished whith words:
...If you are using a "tap" VPN, Tunnelblick must load a kext for your VPN to operate.
and what? How I have to load and which modules?
third  part about System Blocked Extention - it's not my situation. I allowed that was need.
Remains  only secondary part with link to Errors Loading Kexts (Device Drivers). 
Whith example: 
kextstat | grep -v com.apple
Andreis-MacBook-Pro:ansible-playbook-proxmox zakabluk$ kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  109    0 0xffffff7f83eb2000 0x7000     0x7000     net.sf.tuntaposx.tun (1.0) 95DD963D-E23D-3B0F-8DE8-A4D2F6BFA5CC <8 6 5 1>
  110    0 0xffffff7f83eb9000 0x7000     0x7000     net.sf.tuntaposx.tap (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <8 6 5 1>
and example for load kext.
sudo kextunload -b tun-notarized.kext
Password:
(kernel) Kext tun-notarized.kext not found for unload request.
Failed to unload tun-notarized.kext - (libkern/kext) not found.

Maybe you have more clear manual for create connection?

**Comment by jkbullard** [comment]
@zakabluk - I'm sorry I was not clear.

> firs parte finished whith words:
> ...If you are using a "tap" VPN, Tunnelblick must load a kext for your VPN to operate.
> and what? How I have to load and which modules?

No, **you** do not have to load anything, **Tunneblick** needs to load something: a tap kext.

That is the problem: macOS is not letting Tunnelblick load the tap kext.

Your list of the kexts that are loaded shows:

    109    0 0xffffff7f83eb2000 0x7000     0x7000     **net.sf.tuntaposx.tun** (1.0) 95DD963D-E23D-3B0F-8DE8-A4D2F6BFA5CC <8 6 5 1>
    110    0 0xffffff7f83eb9000 0x7000     0x7000     **net.sf.tuntaposx.tap** (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <8 6 5 1>

That means that **those** kexts are loaded. If **they** are loaded, Tunnelblick cannot load its own kexts.

To unload the tap kext that is causing the problem, you need to use:

    sudo kextunload -b **net.sf.tuntaposx.tap**

If you also want to unload the other kext (which is not causing problems but probably does not need to be loaded), use

    sudo kextunload -b **net.sf.tuntaposx.tun**

If the net.sf.tuntaposx.tun and net.sf.tuntaposx.tap kexts reload when you restart your computer, you need to do the "sudo" commands each time you restart your computer. Better would be fore you to find out what is loading them and remove it. See the last part of [Errors Loading Kexts (Device Drivers) on macOS High Sierra (10.13) and higher](https://tunnelblick.net/cKextLoadErrorHighSierra.html).

**Comment by zakabluk** [comment]
It's reale help me. Thenx a lof! I Stoped kexts and have launched  vpn. 
p.s. Nessesary it's installed - tuntaposx.
