### ISSUE TITLE
"route-up" script not executed after upgrading from 3.7.9 to 3.8.0

### ISSUE THREAD

**Issue by mikedvsn** [Tunnelblick/Tunnelblick#567]
**Describe the bug**

After upgrading Tunnelblick from 3.7.9 to 3.8.0, my route-up script is not executed upon connection to my VPN server. Downgrading from 3.8.0 to 3.7.9 resolves the issue. I also tried upgrading to 3.8.1beta01 but not executing on that version either.

**To Reproduce**
1. On 3.8.0 add a route-up script as part of your OpenVPN configuration.
2. Connect to your VPN using this configuration.
3. Verify that the route-up script was not executed.
4. Downgrade Tunnelblick to 3.7.9.
5. Retry the VPN connection using the same configuration.
6. Witness that the route-up script was executed as desired.

**Expected behavior**
Upon connection the route-up script is always executed.

**Diagnostic information**

[3.7.9.txt](https://github.com/Tunnelblick/Tunnelblick/files/3476047/3.7.9.txt)
[3.8.0.txt](https://github.com/Tunnelblick/Tunnelblick/files/3476049/3.8.0.txt)

**Comment by jkbullard** [comment]
@mikedvsn, thanks for your report.

In Tunnelblick 3.8.0, Un-check "Set DNS after routes are set" on the "Connecting & Disconnecting" tab of the "Advanced" settings window after selecting the configuration(s) the change is to be applied to in the list on the left side of the Configurations panel of Tunnelblick's "VPN Details" window.

**Comment by mikedvsn** [comment]
Nice! That worked. The option was unchecked in 3.7.9 but checked after upgrading to 3.8.0. Thanks for the help @jkbullard !
