### ISSUE TITLE
Regarding warning message "this config can take control of your ENTIRE MACHINE"

### ISSUE THREAD

**Issue by shamilovtim** [Tunnelblick/Tunnelblick#568]
Let's say I get a .ovpn config file from my VPN provider. I load it into Tunnelblick and receive a warning: "this config can take control of your ENTIRE MACHINE." Presumably, I can take that same config file and load it into Viscosity or OpenVPN Client and do not receive this warning. 

1) Is this config permissions flaw unique to Tunnelblick or do all Open VPN clients suffer from this same lack of security? Does Tunnelblick have a vulnerability that these two clients don't have, or are they choosing not to give me this warning despite the existence of this flaw?
2) What can be done about these types of configs that cause this warning? Does Tunnelblick need to change its code or do the VPN providers need to stop writing open VPN files that lack security best practices?

**Comment by jkbullard** [comment]
What Tunnelblick is warning about is that the configuration includes scripts (programs) that will be run as root (the most powerful user on a computer, who can do almost anything with any other user's data). Most configurations do not contain such scripts. Recent version of macOS have begun to limit what even the "root" user can do -- for example, critical parts of macOS itself cannot be modified by root, and access to some sensitive user data is protected from root. So the risk is not quite as high as it was a few years ago in older versions of macOS.

To answer your specific questions:
 1. All OpenVPN clients that I know of that use the configuration would expose their users to the same situation. Tunnelblick warns users about it.
 2. A couple of things can be done: (A) examine the scripts to make sure they don't do anything you don't want done, or (B) if possible, have the VPN service provider rewrite their configuration to not require the scripts. Without the specific scripts, I can't say more.
