### ISSUE TITLE
Building from Source: This copy of Tunnelblick has been tampered with

### ISSUE THREAD

**Issue by tmthecoder** [Tunnelblick/Tunnelblick#569]
When I start the application upon a successful build, with Xcode auto signing, the app starts and gives me an alert dialog with: 
`This copy of Tunnelblick has been tampered with (the digital signature is invalid).
Please check with the provider of this copy of Tunnelblick before using it.`

OR

When I click on the .app file in the DMG, I am given the dialog with this message:
`This copy of Tunnelblick is not digitally signed.
There is no way to verify that this copy has not been tampered with.
 Check with the provider of this copy of Tunnelblick before using it.` 

1. Build from source
2. Launch the .app file OR Install via .dmg for the second outcome
It is supposed to just launch and ask to install to /Applications, as per my belief

I also tried signing with the script on the webpage to sign the .app file and set my build type to Unsigned, but the same issue persisted. 

How can I sign the, if I am not signing it properly?

**Comment by jkbullard** [comment]
See #563 for a discussion of codesigning Tunnelblick. The short answer is that Tunnelblick's binary structure cannot be signed automatically by Xcode.

The [script for signing Tunnelblick](https://tunnelblick.net/cSigningTunnelblick.html) is out-of-date by a few years and doesn't include notarization. Apple changed requirements for signatures several times with new releases of OS X and macOS, making it more and more complex, and the requirement for notarization introduced further complexities.

**Comment by jkbullard** [comment]
Other than updating the outdated script or developing your own, I don't know of any. The developers haven't released the script they use to sign and notarize releases.

**Comment by tmthecoder** [comment]
@jkbullard What exactly do I need to sign as I do not know what Tunnelblick needs to sign and how notarization works

**Comment by jkbullard** [comment]
You could start with Apple's [Code Signing Guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html) and [Notarizing Your App Before Distribution](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc).
