### ISSUE TITLE
OpenConnect as backend

### ISSUE THREAD

**Issue by TheKnarf** [Tunnelblick/Tunnelblick#570]
It would be nice if Tunnelblick included [OpenConnect](https://www.infradead.org/openconnect/index.html) as a backend so that we could use Tunnelblick to connect to Cisco AnyConnect servers.

OpenConnect [even mentions it](https://www.infradead.org/openconnect/contribute.html) their-self that it's something they hope for.

**Comment by segabor** [comment]
That would be awesome. AnyConnect tends to kill the whole networking so I'd love to switch to Tunnelblick.

**Comment by v1k7g85** [comment]
Three years have passed, no response. Very strange!

**Comment by jkbullard** [comment]
What kind of response are you looking for, @v1k7g85?

Tunnelblick and OpenConnect are both free software: if nobody is willing to _**_writing the code_**_ for an enhancement it won't get done, no matter how many people vote for it.
