### ISSUE TITLE
TunnelBlick can't load kext 

### ISSUE THREAD

**Issue by coogle** [Tunnelblick/Tunnelblick#575]
**Describe the bug**

TunnelBlick when attempting to make a VPN connection fails because it can't install the kernel extension on High Sierra OS X. There are no other `tel` or `tun` extensions loaded, but there are other extensions for virtual machines that might be the cause.

**To Reproduce**

Start a VPN connection and it errors out.

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

I followed the instructions regarding this issue and can confirm:

- The permissions have been given to run the software in the Settings of OS/X
- The problem goes away after a full reboot

Here are the kextensions I have loaded:

```
mbp:~ john$ kextstat | grep -v com.apple
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  110    0 0xffffff7f83d7a000 0x28000    0x28000    com.intel.kext.intelhaxm (7.3.2) 58DFBE80-E54A-3EFE-B38A-215C5ED8E828 <7 5 4 3 1>
  111    3 0xffffff7f83da2000 0x64000    0x64000    org.virtualbox.kext.VBoxDrv (5.2.22) D2696352-336F-361B-8717-797487B076F5 <7 5 4 3 1>
  147    0 0xffffff7f84488000 0x1d000    0x1d000    com.razer.common.razerhid (21.80) 05CC9886-AECE-392B-8DCD-3439C4DB224B <146 106 51 42 5 4 3>
  180    0 0xffffff7f85af0000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.2.22) B3032E66-0313-3B15-AE85-38D3773435BB <179 111 51 7 5 4 3 1>
  181    0 0xffffff7f85af8000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.2.22) 139430EF-8433-390B-A389-C7DC9B3B50C4 <111 7 5 4 3 1>
  182    0 0xffffff7f85afd000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.2.22) F11F6B94-BF8D-3841-85BB-EFFBBF27CE29 <111 5 4 1>
  226    1 0xffffff7f844cf000 0x11000    0x11000    com.vmware.kext.vmci (90.8.2) 9E116534-F8D9-3F50-9542-55BF67EDCB2E <12 5 4 3 1>
  227    0 0xffffff7f844e0000 0x16000    0x16000    com.vmware.kext.vmnet (1432.85.61) C1766CFF-CD78-37F3-B540-9D4F000BB2D0 <226 5 4 3 1>
  228    0 0xffffff7f844f6000 0x13000    0x13000    com.vmware.kext.vmx86 (1432.85.61) B4801DEA-2CB7-3377-86E2-4CFC7F2552B1 <7 5 4 3 1>
  229    0 0xffffff7f83e16000 0x7000     0x7000     com.vmware.kext.vmioplug.18.1.2 (18.1.2) A3019F09-7FF5-36C5-A9F5-7EAC1DF20C2A <51 5 4 3 1>
```

**Comment by jkbullard** [comment]
If by "The problem goes away after a full reboot" you mean that you can then load the Tunnelblick kexts after rebooting, but you can't at some later time, then some other software is interfering, probably VirtualBox or VMWare.

Tunnelblick can't fix this; your only recourse is to unload the offending kext(s). From the names, those that look the most likely to be problematic are VBoxNetFlt, VBoxNetAdp, and vmnet. If you figure out which one(s) are causing the conflict, please post back here so others can benefit.

**Comment by coogle** [comment]
I have tried unloading pretty much everything I can, and it still won't work

```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  111    0 0xffffff7f83da2000 0x64000    0x64000    org.virtualbox.kext.VBoxDrv (5.2.22) D2696352-336F-361B-8717-797487B076F5 <7 5 4 3 1>
  147    0 0xffffff7f84488000 0x1d000    0x1d000    com.razer.common.razerhid (21.80) 05CC9886-AECE-392B-8DCD-3439C4DB224B <146 106 51 42 5 4 3>
```

**Comment by jkbullard** [comment]
Try unloading both of them and see what happens.

**Comment by coogle** [comment]
It won't let me unload either as they are both being used. But I'll try restarting and before I open a VPN check my kexts to see what's there when it succeeds.

**Comment by coogle** [comment]
This is def. something strange.

So after I reboot, I ran this command, it produces the original list of kexts that I posted first:

```
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
  111    0 0xffffff7f83d7a000 0x28000    0x28000    com.intel.kext.intelhaxm (7.3.2) 58DFBE80-E54A-3EFE-B38A-215C5ED8E828 <7 5 4 3 1>
  112    3 0xffffff7f83da2000 0x64000    0x64000    org.virtualbox.kext.VBoxDrv (5.2.22) D2696352-336F-361B-8717-797487B076F5 <7 5 4 3 1>
  148    0 0xffffff7f84488000 0x1d000    0x1d000    com.razer.common.razerhid (21.80) 05CC9886-AECE-392B-8DCD-3439C4DB224B <147 106 51 42 5 4 3>
  181    0 0xffffff7f85af0000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.2.22) B3032E66-0313-3B15-AE85-38D3773435BB <180 112 51 7 5 4 3 1>
  182    0 0xffffff7f85af8000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.2.22) 139430EF-8433-390B-A389-C7DC9B3B50C4 <112 7 5 4 3 1>
  183    0 0xffffff7f85afd000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.2.22) F11F6B94-BF8D-3841-85BB-EFFBBF27CE29 <112 5 4 1>
```

Except TunnelBlick works perfectly and connected/loaded the exts without an issue. There is something wrong here.

**Comment by coogle** [comment]
It looks like VMWare breaks TunnelBlick. That's super unfortunate.

**Comment by jkbullard** [comment]
If you can get the VMWare kexts unloaded and are then able to load the Tunnelblick kext, you could write scripts for Tunnelblick to run before connecting and after disconnecting to unload and then reload those kexts. See https://tunnelblick.net/cUsingScripts.html. You'd use pre-connect.sh and post-disconnect.sh. You might want to take a look at the "Scripts to Unload Cisco Tun Kext" on Tunnelblick's Downloads page at https://tunnelblick.net/downloads.html#user-contributions.

**Comment by coogle** [comment]
Unfortunately it looks like for some reason once that kext loads from VMware, the Tunnelblick kexts will no longer load even after the VMWare ones have been unloaded w/o doing a reboot. Any thoughts on why that might be??

**Comment by jkbullard** [comment]
@coogle - Sorry, I don't have any ideas about how to fix this. I assume the VMWare kext does something to macOS that prevents it from loading the Tunnelblick kext even after the VMWare kext itself is unloaded. Ask VMWare why unloading its kext doesn't restore the system so that the Tunnelblick kext will load

**Comment by jkbullard** [comment]
There doesn't seem to be anything that Tunnelblick can do to fix this, so I'm closing this Issue.
