### ISSUE TITLE
load window server / menu bar item / connection info popup

### ISSUE THREAD

**Issue by mo8Zomo0** [Tunnelblick/Tunnelblick#577]
Hi!

MacOS 10.13.6, Tunnelblick 3.8.1 (build 5400)

I noticed one thing, sometimes the CPU usage of the MacOS WindowServer is higher.
By chance I noticed that if I hover over the TunnelBlick icon the bigger grey popup
style connection info window is shown (which was hidden before).
If I then close this window the WindowServer load seems to go down.
It can just be a coincidence but I wanted to share it with you, maybe one 
can reproduce or comment on it.

Btw, after closing it I did not find on how to get this popup window for the existing
connection again besides closing it. That said, I am more happy with a lower cpu
usage than it being there and hiding again.

**Comment by jkbullard** [comment]
> I noticed one thing, sometimes the CPU usage of the MacOS WindowServer is higher.

Yes, it goes up and down when any program does something with a window.

> By chance I noticed that if I hover over the TunnelBlick icon the bigger grey popup
style connection info window is shown (which was hidden before).

It does that by default, but you can change that. (See below.)

> If I then close this window the WindowServer load seems to go down.
> It can just be a coincidence but I wanted to share it with you, maybe one can reproduce or comment on it.

I think it is a coincidence. On my 2012 MacBook Pro, WindowServer's CPU use is so variable that I can't see any difference when the grey window is shown or not, even when the VPN is connected and the window is updating the connection time and VPN in/out byte counts. (It is necessary to wait several seconds for WindowServer CPU use to settle.)

> Btw, after closing it I did not find on how to get this popup window for the existing connection again besides closing it.

Yes, that's how it works: if you close it with the close box (the "X" in the corner), it's closed until you relaunch TunnelblickBy default, if you move the mouse off of the Tunnelblick icon (or the window itself), the window will disappear and will reappear when you mouseover the Tunnelblick icon again.

**Changing if/when the status window appears**

If/when the grey window (which we call the "status" window) is shown can be specified on the "Appearances" tab of Tunnelblick's "VPN Details" window. Hover over a control to get a popup elaboration of what the control does.
