### ISSUE TITLE
Incompatibility with macOS 10.15 Catalina

### ISSUE THREAD

**Issue by straurob** [Tunnelblick/Tunnelblick#579]
I  just installed the update to macOS 10.15 (Catalina). Upon starting Tunnelblick the following error message is shown:

<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/18437455/66634916-633ab580-ec0e-11e9-8b55-ef6a80c6f66b.png">

It basically means that the system requirements are not fulfilled due to an insecure `/tmp` folder.

**Comment by jkbullard** [comment]
@straurob - This appears to be a duplicate of #554.

If updating to the latest stable or beta version of Tunnelblick does not fix the problem, please provide the output from the following command in Terminal:

    ls -l@ed /tmp ; ls -l@ed /private/tmp

See [System Folder Security](https://tunnelblick.net/cSystemFolderNotSecure.html) for more information about this type of problem.

**Comment by t1maccapp** [comment]
Same problem:
`lrwxr-xr-x@ 1 root  admin  11 Oct 11 13:45 /tmp -> private/tmp
	com.apple.rootless	 0 
drwxrwxrwt  7 root  wheel  224 Oct 11 16:36 /private/tmp`

**Comment by jkbullard** [comment]
@t1maccapp - What version of Tunnelblick are you using?

**Comment by t1maccapp** [comment]
> @t1maccapp - What version of Tunnelblick are you using?

I updated my answer. I've used brew cask to upgrade to the latest Tunnelblick version. Now I get it that I have to wait until 3.8.0.

**Comment by t1maccapp** [comment]
OK, Sorry. I had some trouble with brew cask. I reinstalled tunnelblick and the latest version is 3.8.1 (build 5400) now. Issue is solved for me.

**Comment by jkbullard** [comment]
@straurob - Did updating to the latest version of Tunnelblick fix this problem for you?

**Comment by straurob** [comment]
> @straurob - Did updating to the latest version of Tunnelblick fix this problem for you?

Yes, I updated Tunnelblick to version 3.8.1 and this runs smoothly. Thanks :-)
