### ISSUE TITLE
This site can’t be reachedgithub-production-release-asset-2e65be.s3.amazonaws.com’s server IP address could not be found 

### ISSUE THREAD

**Issue by MichealBenzel** [Tunnelblick/Tunnelblick#581]
not getting thru to down anything
This site can’t be reachedgithub-production-release-asset-2e65be.s3.amazonaws.com’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

tested different browsers etc.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by MichealBenzel** [comment]
I have tried
https://github.com/Tunnelblick/Tunnelblick/releases/tag/v3.8.1
and
https://tunnelblick.net/downloads.html

**Comment by jkbullard** [comment]
They work fine for me in the northeast USA.

This is likely to be a GitHub or AWS geographic-specific problem. It will have to be fixed by them.

Send an email to developers@tunnelblick.net to get a link to an alternate download site.

**Comment by jkbullard** [comment]
This problem was apparently due to an Amazon Web Services outage. See [Bezos DDoS'd: Amazon Web Services' DNS systems knackered by hours-long cyber-attack](https://www.theregister.co.uk/2019/10/22/aws_dns_ddos/)
