### ISSUE TITLE
Tunnelblick does not restore custom dns after disconnecting

### ISSUE THREAD

**Issue by pot1ch3** [Tunnelblick/Tunnelblick#588]
Hi Guys,

I use as default configuration custom dns on mac Catalina (Google Public DNS).
When I connect to the VPN and disconnect, tunneblick does not restore Google DNS but 192.168.1.1. So I need to update manually to Google DNS in network settings each time I'm using the VPN =(

How to fix the problem and restore Google DNS when disconnecting VPN? 

Thanks

**Comment by jkbullard** [comment]
@pot1ch3 - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
