### ISSUE TITLE
MacOS Catalina version 10.15.0 is not available

### ISSUE THREAD

**Issue by MrWangSoul** [Tunnelblick/Tunnelblick#590]
MacOS Catalina version 10.15.0 is not available

**Comment by MrWangSoul** [comment]
32-bit applications will not be supported during macOS Catalina

**Comment by jkbullard** [comment]
> MacOS Catalina version 10.15.0 is not available

That has nothing to do with Tunnelblick. Current releases of Tunnelblick work on all versions of macOS from 10.7.5 up.

> 32-bit applications will not be supported during macOS Catalina

Tunnelblick is a 64-bit application.
