### ISSUE TITLE
2FA login not possible via keyboard-only navigation

### ISSUE THREAD

**Issue by chbndrhnns** [Tunnelblick/Tunnelblick#591]
**Describe the bug**
I would like to copy and paste login data from my password manager into the login dialog. For this, I need to switch forth and back between login dialog and password manager. The login dialog is not toggable via cmd+tab and thus cannot become the active window for pasting.

I need to paste password and TOTP token separately.

**To Reproduce**
1. Go to menu
2. Click on any available profile
3. Go to other app to copy password
4. Try to activate login window with the keyboard

**Expected behavior**
The login dialog can be activated using cmd+tab to allow for keyboard-only login. 

**Screenshots**

**Additional context**

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
You're correct. Although it behaves like an application in some ways, technically Tunnelblick is not an application: it does not appear in the Dock and cannot be activated with Command-Tab.
