### ISSUE TITLE
MacPorts xcodebuild fails to build with missing Sparkle/SUUpdater.h

### ISSUE THREAD

**Issue by essandess** [Tunnelblick/Tunnelblick#592]
I'm trying to create a MacPorts port of Tunnelblick. See https://github.com/macports/macports-ports/pull/6051

The `xcodebuild` is failing to find the header `Sparkle/SUUpdater.h`.

Yet the build process creates this file:
```
find /opt/local/ports/aqua/tunnelblick/work/Tunnelblick-3.8.1/ -name 'SUUpdater.h'
/opt/local/ports/aqua/tunnelblick/work/Tunnelblick-3.8.1//third_party/build/sparkle/Sparkle/SUUpdater.h
```

This appears to be a simple missing `-I` flag somewhere for `clang`, but I'm not sure  where.

Error:
```
:info:build     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -gmodules -Wno-trigraphs -fpascal-strings -Os -fno-common -Wmissing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-format -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-parameter -Wno-unused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wno-pointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wno-protocol -Wno-deprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -iquote /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Tunnelblick-generated-files.hmap -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Tunnelblick-own-target-headers.hmap:info:build     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-macos10.14 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -gmodules -Wno-trigraphs -fpascal-strings -Os -fno-common -Wmissing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-format -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-parameter -Wno-unused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wsign-compare -Wno-shorten-64-to-32 -Wno-pointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fasm-blocks -fstrict-aliasing -Wno-protocol -Wno-deprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -iquote /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Tunnelblick-generated-files.hmap -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Tunnelblick-own-target-headers.hmap -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Release/include -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/DerivedSources-normal/x86_64 -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/DerivedSources/x86_64 -I/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/DerivedSources -Wall -Wextra -Wstrict-overflow -F/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Release -F/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/third_party -F/opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/third_party/products/sparkle -include /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/SharedPrecompiledHeaders/SharedPrecompiledHeaders/647661451031238688/Tunnelblick_Prefix.pch -MMD -MT dependencies -MF /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Objects-normal/x86_64/MenuController.d --serialize-diagnostics /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Objects-normal/x86_64/MenuController.dia -c /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/MenuController.m -o /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/build/Tunnelblick.build/Release/Tunnelblick.build/Objects-normal/x86_64/MenuController.o
:info:build /opt/local/var/macports/build/_opt_local_ports_aqua_tunnelblick/tunnelblick/work/Tunnelblick-3.8.1/tunnelblick/MenuController.m:53:9: fatal error: 'Sparkle/SUUpdater.h' file not found
:info:build #import "Sparkle/SUUpdater.h"
:info:build         ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by essandess** [comment]
Possibly related: https://github.com/Tunnelblick/Tunnelblick/issues/530

**Comment by jkbullard** [comment]
Is MacPorts building on macOS 10.11.6 and Xcode 7.3.1? That's the only supported build environment. See `Building Tunnelblick from Source Code.markdown` and `third_party/README.txt` in the source code.

I can build Tunnelblick itself (but not the third-party stuff) on macOS 10.14.6 and Xcode 10.3, but those builds don't get tested much; I'm usually just checking for something very specific.

**Comment by essandess** [comment]
This is on macOS 10.14 and Xcode 11.0.0.

The build looks mostly successful, except for this `-I` glitch.

Those versions—macOS 10.11.6 and Xcode 7.3.1—are really, really old and no longer supported.

Is there a reason not to build on an up-to-date environment?

**Comment by jkbullard** [comment]
@essandess wrote:
> Is there a reason not to build on an up-to-date environment?

 1. Like you, I haven't been able to get the third-party software to build without error.

 2. I've seen odd problems with the third-party binaries built on macOS 10.11.6 with Xcode 7.3.1, and the rest of Tunnelblick built on later versions of macOS/Xcode.

And I've never found the time to investigate either one.

So if you can help, that would be great!

**Comment by essandess** [comment]
Sure. Let’s start with Sparkle.

First off, this repo uses it’s own zipped copy of a three-year-old Sparkle version: https://github.com/Tunnelblick/Tunnelblick/blob/master/third_party/sources/Sparkle-077c64419f9460263bad99ab24dff962a103b1e2.zip

Best practice is to use a subrepo cloned from a tagged release: https://github.com/sparkle-project/Sparkle/releases. I would even call this a security issue because Sparkle/GitHub should be vouching for the code, not this repo. 

Questions:
* Does this code have the important security fix after Sparkle 1.13.1? https://sparkle-project.org/documentation/security/ Without a tagged version, it’s really hard to tell
* Why is Tunnelblick not using the latest version 1.22?
* Why is Tunnelblick not using a cloned subrepo off Sparkle?

**Comment by jkbullard** [comment]
@essandess - The answer to the question "why does Tunnelblick…" is usually "because Tunnelblick has been around for many years and nobody has changed what works."

For example, Tunnelblick was around when Internet access was often spotty, and before GitHub existed (in fact, before git itself existed). So including a copy of all dependancies in the Tunnelblick source code itself means nothing needs to be downloaded at build time. So a build machine can be isolated from the Internet, which is a security feature.

> Does this code have the important security fix after Sparkle 1.13.1? https://sparkle-project.org/documentation/security/ Without a tagged version, it’s really hard to tell

Yes. Tunnelblick's copy of Sparkle includes that fix because it is taken from a later commit.

The Tunnelblick source code includes Sparkle-077c64419f9460263bad99ab24dff962a103b1e2.zip, which is a copy of the Sparkle master branch at that commit. Tunnelblick's build process then patches that Sparkle source code with a series of patches, contained in Tunnelblick's third_party/sources/patches/sparkle folder.

That's Tunnelblick's standard build process: to include source code (which can be compared to some official source code to make sure it is "correct"), and then patch it using .diff files.

> Why is Tunnelblick not using the latest version 1.22?

Because Tunnelblick's version of Sparkle has an additional security feature that Sparkle has rejected: appcasts and release notes are each digitally signed with expiring signatures.

> Why is Tunnelblick not using a cloned subrepo off Sparkle?

Because it became too much work to keep Tunnelblick's patches to Sparkle working with each new release of Sparkle.

**Comment by essandess** [comment]
> @essandess - The answer to the question "why does Tunnelblick…" is usually "because Tunnelblick has been around for many years and nobody has changed what works." 

Okay thank you.

> Tunnelblick's version of Sparkle has an additional security feature that Sparkle has rejected: appcasts and release notes are each digitally signed with expiring signatures.

Ugh for Sparkle. But okay:
* I still suggest patching a subrepo from a tagged release, rather than including a zip file.
* There’s a lot of potential downsides to freezing updates to a years-old branch. What bugand security fixes aren’t in there?
* Do the patches in https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/patches/sparkle work on the latest Sparkle version 1.22?

One example to consider: I keep around a fork of dovecot/core that includes an APNS plugin: https://github.com/essandess/core/tree/apns. Whenever dovecot updates, I just make sure that my fork can be merged, make any necessary mods in my fork, then rebase the fork to the latest version. This keeps the modified fork up-to-date, and provides a really simple way to generate patch files.

If Tunnelblick depends on a modded fork of Sparkle, then I’d suggest keeping your own modded fork, use a subrepo to point Tunnelblick to that fork, and use git to rebase and update the fork when necessary.

Before chasing around three-year-old rabbit Sparkle version with the compile error above, I’d like to make sure that there’s not a straightforward path to getting to a the latest updated Sparkle that appears to have lots of bugfixes beyond the code in this repo. That may make the issue go away entirely, or probably introduce new issues. But at least Tunnelblick will be up-to-date on its dependencies.

**Comment by essandess** [comment]
> including a copy of all dependancies in the Tunnelblick source code itself means nothing needs to be downloaded at build time. So a build machine can be isolated from the Internet, which is a security feature.

If you take the fork approach described above, then `git clone --recursive` takes care of all that automatically. You can generate an offline tar archive of source that includes everything you need, but managed with convenient and powerful git tools.

**Comment by essandess** [comment]
> it became too much work to keep Tunnelblick's patches to Sparkle working with each new release of Sparkle.

Also, if you take the fork approach described above, then it’s simple to just single-step from the workIng version three years ago through each Sparkle tagged release to identify where the breakages happen. You may be able to get to a much more recent update without any code changes just by issuing a few rebase + test build commands.

**Comment by jkbullard** [comment]
@essandess wrote:
> If Tunnelblick depends on a modded fork of Sparkle, then I’d suggest keeping your own modded fork, use a subrepo to point Tunnelblick to that fork, and use git to rebase and update the fork when necessary.

Sorry, but I don't have the time do do that, or to maintain it if someone else were to do a PR to do it.

**Comment by essandess** [comment]
Do you know what causes the missing `-I/path/to/Sparkle/SUUpdater.h` flag in Xcode’s call to `clang`, listed in full in the first comment?

**Comment by jkbullard** [comment]
@essandess wrote:
> Do you know what causes the missing `-I/path/to/Sparkle/SUUpdater.h` flag in Xcode’s call to `clang`, listed in full in the first comment?

No, sorry, I don't.

**Comment by jkbullard** [comment]
Tunnelblick now builds on macOS 10.14.6 with Xcode 10.3. An additional step is required to isntall the kernel headers, see https://github.com/Tunnelblick/Tunnelblick/issues/530#issuecomment-489375237.
