### ISSUE TITLE
Configuration import/duplicate/add. The installation or repair took too long or failed.

### ISSUE THREAD

**Issue by PeterBrain** [Tunnelblick/Tunnelblick#593]
**Bug description**
This bug occurs when I am trying to **import** a new, **duplicate** an existing or while **making the configuration private/shared**. Weird thing is, that I can edit an existing configuration.
Checked the configuration files several time, tried different ones and even the backed up ones that are imported already.

**Steps to reproduce**
1. Click on the configuration file you want to import
2. Select installation scope (all, only me)
3. Type in password to install configuration file
4. See error (The installation or repair took too long or failed.)
5. In the error there are two options: either try it again (did that approx 10.000 times!) or quit tunnelblick

**Expected behavior**
Obviously there shouldn't be this error. Instead, the configuration should be imported/duplicated/made shared or private and be ready to be used.

**Things i tried**
* [x] Reinstall Tunnelblick
  * [x] 3.8.0 (i guess... can't say anymore, because I updated to 3.8.1 immediately)
  * [x] 3.8.1 (build 5400)
  * [x] 3.8.2beta03 (build 5430)
* [x] tried different configuration files + those that work on windows machines
* [x] Disk Utility -> Ran First Aid on all volumes without any errors
* [x] restart machine several times
* [ ] try it on a different macOS Machine (don't have another machine)
* [ ] reinstall macOS (I don't have time for this one)
* [x] virtual machine with macOS 10.14.5 and tunnelblick (this one works)
* [ ] virtual machine with macOS 10.15.x and tunnelblick

**Additional context**
There was a similar issue at the beginning of summer (#559), but this exact one was about the installation of Tunnelblick, which is totally fine now.

**Diagnostic information**
<details>
<summary><small>macOS machine</small></summary>
<pre>
MacBook Pro 2018
macOS Catalina 10.15.2 (19C57)
</pre>
</details>

<details>
<summary><small>all messages</small></summary>
<pre>
default	17:09:53.951504+0100	runningboardd	Acquiring assertion targeting executable<Tunnelblick(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:163] with description <RBSAssertionDescriptor; frontmost:9705; ID: 305-163-1072; target: 9705> attributes = {
    <RBSDomainAttribute: 0x7f9df7023620; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	17:09:53.951653+0100	runningboardd	Assertion 305-163-1072 (target:executable<Tunnelblick(501)>) will be created as active
default	17:09:53.952703+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:09:53.953191+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractiveFocal
default	17:09:53.953576+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:09:53.953810+0100	runningboardd	Finished acquiring assertion 305-163-1072 (target:executable<Tunnelblick(501)>)
default	17:09:54.498074+0100	Tunnelblick	SetFrontProcess: asn=0x0-0xf60f6 options=1
default	17:09:54.653844+0100	runningboardd	Invalidating assertion 305-163-1072 (target:executable<Tunnelblick(501)>) from originator 163
default	17:09:54.692512+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:09:54.692573+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractive
default	17:09:54.692729+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:09:59.848656+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Applications/Tunnelblick.app' [9705] for authorization created by '/Applications/Tunnelblick.app' [9705] (13,0) (engine 125)
default	17:09:59.870414+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Applications/Tunnelblick.app' [9705] for authorization created by '/Applications/Tunnelblick.app' [9705] (12,0) (engine 126)
default	17:09:59.883986+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Applications/Tunnelblick.app' [9705] for authorization created by '/Applications/Tunnelblick.app' [9705] (12,0) (engine 127)
default	17:09:59.885329+0100	Tunnelblick	AuthorizationExecuteWithPrivileges and AuthorizationExecuteWithPrivilegesExternalForm are deprecated and functionality will be removed soon - please update your application
default	17:09:59.926546+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/usr/libexec/security_authtrampoline' [9798] for authorization created by '/Applications/Tunnelblick.app' [9705] (3,0) (engine 128)
default	17:09:59.928229+0100	security_authtrampoline	executing /Applications/Tunnelblick.app/Contents/Resources/installer
default	17:09:59.983345+0100	Tunnelblick	SetFrontProcess: asn=0x0-0xf60f6 options=1
default	17:09:59.983966+0100	runningboardd	Acquiring assertion targeting executable<Tunnelblick(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:163] with description <RBSAssertionDescriptor; frontmost:9705; ID: 305-163-1081; target: 9705> attributes = {
    <RBSDomainAttribute: 0x7f9df7711de0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	17:09:59.984227+0100	runningboardd	Assertion 305-163-1081 (target:executable<Tunnelblick(501)>) will be created as active
default	17:09:59.986052+0100	runningboardd	Finished acquiring assertion 305-163-1081 (target:executable<Tunnelblick(501)>)
default	17:09:59.986325+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:09:59.987061+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractiveFocal
default	17:09:59.987844+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:10:00.019139+0100	runningboardd	Invalidating assertion 305-163-1081 (target:executable<Tunnelblick(501)>) from originator 163
default	17:10:00.094172+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:10:00.094434+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractive
default	17:10:00.094607+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:10:00.346914+0100	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier net.tunnelblick.tunnelblick, type: 0: 0x7fd69e5191c0 at /Applications/Tunnelblick.app
default	17:10:00.470741+0100	Tunnelblick	SetFrontProcess: asn=0x0-0xf60f6 options=0
default	17:10:02.031186+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Applications/Tunnelblick.app' [9705] for authorization created by '/Applications/Tunnelblick.app' [9705] (12,0) (engine 129)
default	17:10:02.032319+0100	Tunnelblick	AuthorizationExecuteWithPrivileges and AuthorizationExecuteWithPrivilegesExternalForm are deprecated and functionality will be removed soon - please update your application
default	17:10:02.067509+0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/usr/libexec/security_authtrampoline' [9799] for authorization created by '/Applications/Tunnelblick.app' [9705] (3,0) (engine 130)
default	17:10:02.069117+0100	security_authtrampoline	executing /Applications/Tunnelblick.app/Contents/Resources/installer
default	17:10:02.122464+0100	Tunnelblick	SetFrontProcess: asn=0x0-0xf60f6 options=1
default	17:10:02.123059+0100	runningboardd	Acquiring assertion targeting executable<Tunnelblick(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:163] with description <RBSAssertionDescriptor; frontmost:9705; ID: 305-163-1086; target: 9705> attributes = {
    <RBSDomainAttribute: 0x7f9df77118e0; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	17:10:02.123212+0100	runningboardd	Assertion 305-163-1086 (target:executable<Tunnelblick(501)>) will be created as active
default	17:10:02.128304+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:10:02.128885+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractiveFocal
default	17:10:02.129337+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:10:02.139075+0100	runningboardd	Finished acquiring assertion 305-163-1086 (target:executable<Tunnelblick(501)>)
default	17:10:02.148988+0100	runningboardd	Invalidating assertion 305-163-1086 (target:executable<Tunnelblick(501)>) from originator 163
default	17:10:02.245402+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring jetsam update because this process is not memory-managed
default	17:10:02.245771+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Set darwin role to: UserInteractive
default	17:10:02.246014+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Ignoring GPU update because this process is not GPU managed
default	17:10:04.089220+0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:73A71232-B86F-458B-BE2C-ADD2756F25D1 pid:9705 process:Tunnelblick type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	17:10:04.089905+0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:280C62BD-F99D-4BB9-B8B8-52D2E26853D0 pid:9705 process:Tunnelblick type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	17:10:04.097858+0100	runningboardd	[executable<Tunnelblick(501)>:9705] Death sentinel fired!
default	17:10:04.101092+0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Tunnelblick, _appTrackingState = 2
default	17:10:04.101006+0100	runningboardd	Invalidating assertion 305-163-976 (target:executable<Tunnelblick(501)>) from originator 163
default	17:10:04.208070+0100	runningboardd	Removing process: [executable<Tunnelblick(501)>:9705]
default	17:10:04.213107+0100	runningboardd	Removing assertions for terminated process: [executable<Tunnelblick(501)>:9705]
</pre>
</details>

<details>
<summary><small>system.log</small></summary>
<pre>
Dec 26 17:09:54 MacBook-Pro Tunnelblick[9705]: Converting/Installing /Users/peterbrain/Desktop/gg-peterbrain-mbp-2018-universal.ovpn: Converted OpenVPN configuration
Dec 26 17:09:59 MacBook-Pro Tunnelblick[9705]: Tunnelblick needs to perform an action that requires a computer administrator's authorization.
Dec 26 17:09:59 MacBook-Pro Tunnelblick[9705]: Beginning installation or repair
Dec 26 17:09:59 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.security_authtr.9798): Failed to bootstrap path: path = /usr/libexec/security_authtrampoline, error = 108: Invalid path
Dec 26 17:09:59 MacBook-Pro Tunnelblick[9705]: installer reported failure: /Applications/Tunnelblick.app/Contents/Resources/installer: (
	    1,
	    "/Users/peterbrain/Library/Application Support/Tunnelblick/Configurations/gg-peterbrain-mbp-2018-universal.tblk",
	    "/private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/Tunnelblick-k9RvHI/gg-peterbrain-mbp-2018-universal.tblk"
	)
Dec 26 17:10:02 MacBook-Pro Tunnelblick[9705]: Retrying execution of installer
Dec 26 17:10:02 MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.security_authtr.9799): Failed to bootstrap path: path = /usr/libexec/security_authtrampoline, error = 108: Invalid path
Dec 26 17:10:02 MacBook-Pro Tunnelblick[9705]: installer reported failure: /Applications/Tunnelblick.app/Contents/Resources/installer: (
	    0,
	    "/Users/peterbrain/Library/Application Support/Tunnelblick/Configurations/gg-peterbrain-mbp-2018-universal.tblk",
	    "/private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/Tunnelblick-k9RvHI/gg-peterbrain-mbp-2018-universal.tblk"
	)
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: Installation or repair failed; Log:
	Tunnelblick installer started 2019-12-26 17:09:59.937905. 3 arguments: 0x0001
	     /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations/gg-peterbrain-mbp-2018-universal.tblk
	     /private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/Tunnelblick-k9RvHI/gg-peterbrain-mbp-2018-universal.tblk
	getuid() = 501; getgid() = 20; geteuid() = 0; getegid() = 20
	Changed permissions from 755 to 750 on /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations
	Apparent symlink attack detected: Symlink is at /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations, full path being tested is /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations
	Tunnelblick installer started 2019-12-26 17:10:02.079979. 3 arguments: 0x0000
	     /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations/gg-peterbrain-mbp-2018-universal.tblk
	     /private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/Tunnelblick-k9RvHI/gg-peterbrain-mbp-2018-universal.tblk
	getuid() = 501; getgid() = 20; geteuid() = 0; getegid() = 20
	Changed permissions from 755 to 750 on /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations
	Apparent symlink attack detected: Symlink is at /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations, full path being tested is /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: Terminating because of error; stack trace: (
		0   Tunnelblick                         0x000000010f07e345 callStack + 56
		1   Tunnelblick                         0x000000010f01626f -[MenuController terminateBecause:] + 99
		2   Tunnelblick                         0x000000010f020244 -[MenuController runInstaller:extraArguments:usingSystemAuth:installTblks:] + 1268
		3   Tunnelblick                         0x000000010f046226 +[ConfigurationManager copyConfigPath:toPath:usingSystemAuth:warnDialog:moveNotCopy:noAdmin:] + 770
		4   Tunnelblick                         0x000000010f04723e -[ConfigurationManager doUninstallslReplacementsInstallsSkipConfirmMsg:skipResultMsg:] + 1709
		5   Tunnelblick                         0x000000010f048c1e -[ConfigurationManager installConfigurations:skipConfirmationMessage:skipResultMessage:notifyDelegate:disallowCommands:] + 3067
		6   Tunnelblick                         0x000000010f048c8f -[ConfigurationManager installConfigurations:skipMessages:notifyDelegate:disallowCommands:] + 77
		7   Tunnelblick                         0x000000010f04e234 +[ConfigurationManager installConfigurationsShowMessagesNotifyDelegateOperation:] + 93
		8   Foundation                          0x00007fff350cd788 __NSThread__start__ + 1064
		9   libsystem_pthread.dylib             0x00007fff6a292e65 _pthread_start + 148
		10  libsystem_pthread.dylib             0x00007fff6a28e83b thread_start + 15
	)
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: Could not copy configuration file /private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/Tunnelblick-k9RvHI/gg-peterbrain-mbp-2018-universal.tblk to /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations/gg-peterbrain-mbp-2018-universal.tblk
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: cleanup: Entering cleanup
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: synchronized user defaults
Dec 26 17:10:03 MacBook-Pro Tunnelblick[9705]: Set 'expect disconnect 0 ALL'
Dec 26 17:10:04 MacBook-Pro Tunnelblick[9705]: Finished shutting down Tunnelblick; allowing termination
</pre>
</details>

<details>
<summary><small>tunnelblickd.log</small></summary>
<pre>
Dec 26 17:10:03  tunnelblickd[9800] <Debug>: approximateLastKnownReboot = 1577354544.237030; approximateMostRecentReboot = 1577354544.259232; difference = 0.022202
Dec 26 17:10:03  tunnelblickd[9800] <Debug>: This reboot time is approximately the same as the last reboot time; not first run after rebooting
Dec 26 17:10:03  tunnelblickd[9800] <Debug>: tunnelblickd invoked but not first run after reboot
Dec 26 17:10:03  tunnelblickd[9800] <Debug>: Started net.tunnelblick.tunnelblick.tunnelblickd
Dec 26 17:10:03  tunnelblickd[9800] <Info>: Created new temporary directory /var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/net.tunnelblick.tunnelblickd-6aEyeE
Dec 26 17:10:03  tunnelblickd[9800] <Info>: Removed temporary directory /private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/net.tunnelblick.tunnelblickd-6aEyeE
Dec 26 17:10:03  tunnelblickd[9800] <Info>: Created new temporary directory /var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/net.tunnelblick.tunnelblickd-9nx1f8
Dec 26 17:10:03  tunnelblickd[9800] <Info>: Removed temporary directory /private/var/folders/y4/44qxhx1n22vd1357rr_tlyxw0000gn/T/net.tunnelblick.tunnelblickd-9nx1f8
</pre>
</details>

**Comment by jkbullard** [comment]
@PeterBrain - Here's a relevant error message from the log:
> Apparent symlink attack detected: Symlink is at /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations, full path being tested is /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations

This means that Tunnelblick saw that there was a symlink at /Users/peterbrain/Library/Application Support/Tunnelblick/Configurations.

For security reasons, Tunnelblick does not allow symlinks in paths to any of the files that it needs to secure.

**Comment by PeterBrain** [comment]
Well, that was an easy fix. Rolled back the Configurations folder and deleted that symlink. Turns out [Mackup](https://github.com/lra/mackup) created that symlink.

Thank you for helping @jkbullard!
