### ISSUE TITLE
osascript examples not working

### ISSUE THREAD

**Issue by pacmac** [Tunnelblick/Tunnelblick#595]
on Catalina, unable to get any osacript to work with tunnelblik
```
osascript -e "tell application /Applications/Tunnelblick.app" -e "connect myvpn" -e "end tell"

42:43: syntax error: Expected end of line but found unknown token. (-2741)
```

**Comment by jkbullard** [comment]
@pacmac - Thanks. I've fixed it.

The path to Tunnelblick and the configuration name must be in quotes and the quotes must be properly escaped for the shell:

<code>
osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "connect \"configuration-name\"" -e "end tell"
</code>

**Comment by pacmac** [comment]
Thanks so much for helping:

Just tried this and was not disconnected:

 ```
osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "disconnect \"all\"" -e "end tell"
false
```

**Comment by jkbullard** [comment]
You need to not quote "all". What you did was a command that tries to disconnect a configuration named "all". You want

<code>
osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "disconnect all" -e "end tell"
false</code>
