### ISSUE TITLE
Disable IPv6 option not working on tun unless dhcp-option is defined

### ISSUE THREAD

**Issue by ruippeixotog** [Tunnelblick/Tunnelblick#596]
**Describe the bug**
IPv6 is not being disabled when I connect to my VPN, even though I have the option checked and I connect to the server through IPv4.

After reading `client.up.tunnelblick.sh`, this seems to be happening because `$foreign_option_1` is not defined. Adding `dhcp-option DNS 8.8.8.8` (or in fact any valid or invalid entry that leads to that Bash variable being defined) makes Tunnelblick disable IPv6 as expected.

**To Reproduce**
Here is my redacted client config:

```
client
dev tun
proto tcp
remote <server_host_ipv4> <server_port>
nobind
persist-key
persist-tun
compress lzo
verb 3

-----BEGIN CERTIFICATE-----
(...)
```

When I try to connect, I get the following in logs:

```
(...)
22:53:13 *Tunnelblick:  NOTE: No network configuration changes need to be made.
22:53:13 *Tunnelblick:  WARNING: Will NOT monitor for other network configuration changes.
22:53:13 *Tunnelblick:  WARNING: Will NOT disable IPv6 settings.
(...)
```

IPv6 is not disabled, even though it should. When I add the "foreign" option as I mentioned above this message doesn't show anymore.

**Comment by jkbullard** [comment]
@ruippeixotog - Thanks for your report and your analysis.

Some functions are only performed if the up and down scripts run to completion, and having no $foreign_option_1 causes the up script to terminate early. I'll look into fixing that.

**Comment by fsamier** [comment]
I know it's a quite old issue, but it seems to be still present in the last stable release (`3.8.8g (build 5779.3)`). The workaround proposed by @ruippeixotog works but I don't feel confident in modifying my corporate VPN configuration, would it be possible to consider a fix?

**Comment by jkbullard** [comment]
I'll look into it and post back here

**Comment by jkbullard** [comment]
@fsamier - Can you send the diagnostic info (from following the instructions at[Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html)) to developers@tunnelblick.net? It is _possible_ it would be very easy to implement this, but I need to check something and don't have a configuration handy that causes the problem.

**Comment by fsamier** [comment]
Thanks a lot for your reply! I'll send you the diagnostic as soon as I'm back home (I'm not sure the VPN behaves the same when using office network)

**Comment by fsamier** [comment]
@jkbullard E-mail sent, sorry again for the delay

**Comment by jkbullard** [comment]
@fsamier – Thanks. It won't be as easy as I had hoped, but I will see if I can get this into the next beta.

**Comment by jkbullard** [comment]
To @ruippeixotog, @fsamier, and anyone else interested in this:

A pre-beta version of Tunnelblick is available for testing. It allows the following even if no network changes are being made when connecting the VPN:
 * Disabling IPv6;
 * Disabling secondary network interfaces; and
 * Monitoring the network configuration.

To get a link to download it, email developers@tunnelblick.net.
