### ISSUE TITLE
VPN Details broken

### ISSUE THREAD

**Issue by ZhangPuXi** [Tunnelblick/Tunnelblick#597]
**Describe the bug**
The VPN Details item in menu is broken.

**To Reproduce**
1. Open tunnelblick.
2. Click on tunnelblick icon.
3. Click VPN Details item.
4. TunnelBlick quit.

**Additional context**
System: macOS Catalina version 10.15.2
TunnelBlick: 3.7.7

**Comment by jkbullard** [comment]
@ZhangPuXi  Try using Tunnelblick 3.8.1 build 5400, which was released 2019-09-11.

**Comment by ZhangPuXi** [comment]
@jkbullard I update to 3.8.2beta03 and it works well. Thanks for your help.
