### ISSUE TITLE
Add the ability to run a command before/after vpn connection

### ISSUE THREAD

**Issue by daco-tech** [Tunnelblick/Tunnelblick#598]
**Describe the bug**
This is not a bug. Is a feature request to allow user to run a command before start the VPN connection, and to run another command after VPN disconnection.

**To Reproduce**
1. Go to 'VPN Connection Settings'
2. Click on 'Command Execution'
3. Scroll down to 'Add command and when it should be executed'
4. Connect with the VPN as usual.

**Expected behavior**
The before command is executed before start the VPN connection, and the finish command is executed after the VPN connection disconnects.

**Additional context**
Avoid manual obfsproxy connection before start the VPN, and terminate the program with killall after disconnection.

**Comment by jkbullard** [comment]
We won't do this. Tunnelblick provides this functionality via it's scripts mechanism, which also provides several other points at which a command can be run. Just include scripts named "pre-connect.sh" and/or "post-disconnect.sh" with your command(s) in the Tunnelblick VPN configuration. See [Using Scripts](https://tunnelblick.net/cUsingScripts.html) for details.
