### ISSUE TITLE
Uninstaller fails when system contains "/Users/Root" path

### ISSUE THREAD

**Issue by AbeWoodWing** [Tunnelblick/Tunnelblick#604]
**Describe the bug**
On Mac OS, when attempting to use the uninstaller to remove an older version, the uninstall will fail if /Users/Root exists, with no good error message to troubleshoot with. 

**To Reproduce**
1. Create /Users/Root if you do not have one
2. Run the uninstaller
3. Run the Test uninstall

**Expected behavior**
The uninstall succeeds or prints a better error

**Current Error**
Error: uninstall_tb_user_keychain_items must not be run as root

**Additional context**
My system had some old preference files from Adobe under the /Users/Root path, of which I never created and were just old lingering files. This confused the uninstaller into thinking it was taking actions of the "root" user (id 0), which it has code to prevent the uninstall of keychain items under the root user.

**Code at issue**
```bash
for user in $( dscl . list /users ) ; do
  if [ "${user:0:1}" != "_" -a -e "/Users/${user}" ] ; then
```

```bash
uninstall_tb_user_keychain_items()
{
  if [ "$EUID" != "" ] ; then
	if [ "$EUID" = "0" ] ; then
	  log "Error: uninstall_tb_user_keychain_items must not be run as root"
	  exit 0
	fi
  else
	if [ "$(id -u)" != "" ]; then
	  if [ "$(id -u)" = "0" ]; then
		log "Error: uninstall_tb_user_keychain_items must not be run as root"
		exit 0
	  fi
```

**Comment by jkbullard** [comment]
@AbeWoodWing - Thank you! Both for reporting this problem and for giving such a detailed explanation and analysis.

I plan to skip processing /User/Root but issue a warning if it exists.
