### ISSUE TITLE
On new vpn session local network devices will be disconnected

### ISSUE THREAD

**Issue by paxter** [Tunnelblick/Tunnelblick#609]
Version: 3.8.1 (build 5400)
OS: MacOS Mojave (10.14.6)

Everytime I'm starting a new vpn session with tunnelblick my local mounted network devices will be unavailable and I'm forced to re-mount them. I used tunnelblick for years and on earlier versions this never happened. But this could also be a OS problem. I used El Capitan for years and this issue newly appears since I'm on Mojave.

And another  thing I could observe: If I reconnect my local network devices while I'm using the vpn session and close the vpn session, all local network devices are still correctly accessable. Looks like this issue only works in one direction.

Let me know if you need further information.

**Comment by jkbullard** [comment]
First, do I understand correctly that you updated Tunnelblick to 3.8.1 and macOS to Mojave? And that you didn't try this with your old version of Tunnelblick on Mojave or with 3.8.1 on El Capitan? So you're not sure if it is Tunnelblick or Mojave?

Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by paxter** [comment]
> And that you didn't try this with your old version of Tunnelblick on Mojave or with 3.8.1 on El Capitan?

I don't know which Tunnelblick version I used before and I don't own an El Capitan version anymore.

The left window on the screenshot appears around 3 seconds after the last message in the log window on the right. By the way, the other way around my local network devices won't be disconnected (reconnect them on a active vpn session and stop the vpn session).

![screenshot](https://user-images.githubusercontent.com/5040710/77214339-f6a5da00-6b0e-11ea-8cbe-a96ca2502e66.png)

[tunnelblick_debug_log.txt](https://github.com/Tunnelblick/Tunnelblick/files/4362172/tunnelblick_debug_log.txt)

Please let me know if you got the debug log. I'm not sure if I removed all sensitive data.

**Comment by jkbullard** [comment]
@paxter - Try not disabling IPv6 on the "Settings" tab.

**Comment by paxter** [comment]
Thanks a lot. Looks like it's working. I can start a vpn session without disconnecting my local network devices now. :)

**Comment by paxter** [comment]
I don't know if this is a bug or not. So it's your choice to close this issue. Thanks for your fast support and replies.

**Comment by jkbullard** [comment]
It's not a bug. Local devices often communicate using IPv6, so if you disable it, they won't work.
