### ISSUE TITLE
Various Mistakes in German Localisation

### ISSUE THREAD

**Issue by ksaerdna** [Tunnelblick/Tunnelblick#613]
There are some of typos in the German localisation, mainly incorrect use of a space as a compound noun separator. In German this is called "Deppenleerzeichen" or ironically "Deppen Leer Zeichen".

Further, there are some unpleasant anglicisms, colloquial language and some unnecessary words.

This

	Dies könnte bedeuten, dass ihr VPN nicht korrekt konfiguriert ist.

should be

	Dies könnte bedeuten, dass Ihr VPN nicht korrekt konfiguriert ist.

. Note the upper case "I".

This

	Standard Icon

should be

	Standard-Icon

. Note the missing hyphen.

This

	... wenn der Mauszeiger über dem Tunnelblick Icon ist

should be

	... wenn der Mauszeiger über dem Tunnelblick-Icon ist

. Note the missing hyphen.

This

	Prüfen ob die scheinbare ....

should be

	Prüfen, ob die scheinbare ....

. Note the missing comma.

This

	Adminmodus

should be

	Administrator-Modus

. The current translation is highly colloquial.

This

	Tunnelblick 3.3 Icon

should be

	Tunnelblick-3.3-Icon

. Note the missing hyphen.

This:

	Updates

should be

	Neue Programmversionen

. Note the unpleasant anglicism.

This

	... Suche nach Updates ...

should be

	... Suche nach neuen Versionen ...

. Note the unpleasant anglicism.

This

	Automatisch nach Updates suchen

should be

	Automatisch nach neuen Versionen suchen

or better

	Automatisch suchen

. Note that the left side also mentions the "updates", so it's unnecessary to repeat the word.

This

 	Bei Updates auch Beta Versionen berücksichtigen

should be

 	Auch Beta-Versionen berücksichtigen

. Note the missing hyphen and that the left side also mentions the "updates", so it's unnecessary to repeat the word.

This

	Alle OpenVPN Prozesse beenden

should be

	Alle OpenVPN-Prozesse beenden

. Note the missing hyphen.

This

	Tunnelblick Konfigurationen exportieren

should be

	Tunnelblick-Konfigurationen exportieren

. Note the missing hyphen.

**Comment by jkbullard** [comment]
Thanks for your report.

We'd love to have help with translations. To volunteer, please email developers@tunnelblick.net.

**Comment by ksaerdna** [comment]
More ones:

> Falls nicht ausgewählt, wird Tunnelblick nicht prüfen ob die IP-Adresse sich ändert und nicht warnen, falls die öffentliche IP-Adresse sich nach der Verbindung des VPNs nicht ändert.

must be (note the missing commas and the wrong future tense, which is English, not German):

> Falls nicht ausgewählt, prüft Tunnelblick nicht, ob sich die IP-Adresse ändert, und warnt nicht, falls sich die öffentliche IP-Adresse nach der Verbindung des VPNs nicht ändert.

Besides, the new position of the reflexive pronoun „sich“ makes the sentence more elegant.


> Das Deaktivieren von IPv6 wird oft empfohlen, da viele VPN Konfigurationen...

must be

> Das Deaktivieren von IPv6 wird oft empfohlen, da viele VPN-Konfigurationen...

Note the missing hyphen.


> Falls nicht markiert , wird IPv6 nicht deaktiviert.

must be

> Falls nicht markiert, wird IPv6 nicht deaktiviert.

There is just a wrong space.


> Dieses Kontrollkästchen ist deaktiviert, wenn man "TAP" Verbindungen...

must be

> Dieses Kontrollkästchen ist deaktiviert, wenn man „TAP“-Verbindungen...

Note again the missing hyphen.


> ... IPv4-Traffic ...

is an ugly anglicism, and there is a much more precise German word:

> ... IPv4-Datenverkehr ...


> Diese Checkbox ist deaktiviert wenn 'DNS/WINS einstellen' ...

should be

> Diese Checkbox ist deaktiviert, wenn „DNS/WINS einstellen“ ...

. Note the missing commas and the wrong apostrophes. German quotation marks generally should be „“ and neither "" (English) nor ''. Single quotations are only used as second-level-quotations.

And generally there are more help texts using future tense (English) instead of simple present tense (German), these should also be corrected.

**Comment by ksaerdna** [comment]
In case I get direct access to the texts, I will gladly do all the editing for the project so that my changes must only be reviewed instead of copying the corrections tediously word by word.

**Comment by jkbullard** [comment]
@ksaerdna - Thanks again. We'd love to have help with translations. To volunteer, please email developers@tunnelblick.net.

**Comment by ksaerdna** [comment]
done, as suggested

**Comment by jkbullard** [comment]
@ksaerdna - Great! Thank you.
