### ISSUE TITLE
Categorize configurations in folders?

### ISSUE THREAD

**Issue by chucker** [Tunnelblick/Tunnelblick#614]
**Describe the bug**
The left pane in the Preferences → Configurations tab is already an outline view. However, it doesn't seem to be possible to have any other heading than the "Configurations" root node.

It'd be cool if I could have folders (a single hierarchy level would be plenty) within which to place configurations, such as to move some to an archive, separate between work and personal, etc.

**Comment by jkbullard** [comment]
@chucker - If I understand you correctly, you are requesting:
 1. To have a hierarchical organization of configurations (as if they were in folders); and

 1. To be able to have Tunnelblick display only part of the hierarchy (one particular folder).

Tunnelblick supports (somewhat, see below) the first but not the second. You can have configurations in a folder hierarchy and show or hide the contents of any folder, but the display always shows the entire hierarchy.

For example, if you all of your configurations in two folders named "Home" and "Office", you can have Tunnelblick show
<pre>
     Configurations
          &#9654;Home
          &#9654;Office
</pre>
if you click the &#9654; to the left of "Home", you will see
<pre>
     Configurations
          &#9660;Home
               First configuration in "Home" folder
               Second configuration in "Home" folder
               .
               .
               .
          &#9654;Office
</pre>
but you can't double-click on "Home" and have Tunnelblick show
<pre>
     &#9660;Home
          First configuration in "Home" folder
          Second configuration in "Home" folder
          .
          .
          .
</pre>
By "somewhat" above, I mean that Tunnelblick can display the hierarchy, but it cannot create or modify the hierarchy or move configurations within the hierarchy except when you install a Tunnelblick VPN Configuration that contains nested configurations, as described below. You can create and modify the hierarchy and move configurations around within that hierarchy using Finder, but there are some "catches":
 * You can do this only for "private" configurations, not for "shared configurations";
 * Tunnelblick must not be running when you create or delete folders or move configurations; 
 * When you move a configuration using Finder, all Tunnelblick settings for the configuration are lost; and
 * After making changes, a computer administrator's authorization will be required the next time Tunnelblick is launched.

Private configurations are stored in ~/Library/Application Support/Tunnelblick/Configurations.

Note: if you have a [Tunnelblick VPN Configuration](https://tunnelblick.net/cPkgs.html) which contain [nested configurations](https://tunnelblick.net/cPkgs.html#nested-configurations) in a folder hierarchy, you can have Tunnelblick set up the hierarchy and install the nested configurations in that hierarchy all at once by installing the configuration normally: drag and drop it onto the Tunnelblick icon in the menu bar, or onto the list of configurations in the left side of the "Configurations" panel of Tunnelblick's "VPN Details" window.

**Comment by chucker** [comment]
>If I understand you correctly, you are requesting:
>
>To have a hierarchical organization of configurations (as if they were in folders); and
>
>To be able to have Tunnelblick display only part of the hierarchy (one particular folder).

No, I was just asking for any hierarchy at all, and said as an aside that even just one level would be quite useful.

Anyway, thanks a ton for the detailed explanation! Losing settings is a bit of a bummer*, but quitting Tblk, making folders in Finder, and relaunching Tblk worked fine.

The nested configurations approach is kind of overkill for me, as this is just for my own computer (most others use these networks from Windows).

*) One of the use cases I saw for this was to have a _Archive folder where I leave old configurations as is; this runs counter to that hope. :)

**Comment by jkbullard** [comment]
> Losing settings is a bit of a bummer

I agree. As a first step, I'm looking at allowing one to "rename" a configuration file to move it to another folder. (Renaming preserves settings but as I recall, doesn't preserve saved Keychain items like usernames and passwords.) That might be almost trivial to implement – if it works at all!

> Are there any plans to have a GUI for this process? Would there be interest in a pull request? The Finder has "New Folder with Selection (n items)" in its Action menu; Tunnelblick could do the same, and simply relaunch afterwards.

There are not any specific plans, but it would also be good to:
 * Allow drag-and-drop of configurations and folders in the list
 * Display folders with no configurations in them.
 * Delete folders (including the configurations in them).

All of this is made much more complicated by the fact that the list is actually an aggregation of configurations from up to three separate sources, each stored in a separate file hierarchy: private configurations, shared configurations, and deployed configurations.

So although a PR would be welcome, I think it would be a huge amount of work. I may try tackling this myself, one piece at a time.

**Comment by jkbullard** [comment]
@chucker - I've implemented a couple parts of this (more to come):
 * Copy or move configuration(s) to a new folder via action (gear) menu commands.
 * Copy or move individual configurations to/from folders via drag/drop.
 * Folders may be nested arbitrarily deep.
 * Renaming, copying, or moving will preserve or copy settings and any username, password, or passphrase saved in the macOS KeyChain.

All this will be included in the next beta release, due soon.

**Comment by chucker** [comment]
Very nice!
