### ISSUE TITLE
Segmentation fault 11 happened, generated a dump and prompted quit

### ISSUE THREAD

**Issue by WoodpeckerBaby** [Tunnelblick/Tunnelblick#615]
## Describe the bug

`fatal signal Segmentation fault (11) on main thread`, generated dump and prompted quit

## To Reproduce

This would be difficult to reproduce, like all segfault 11 issues. I have no clue why it happened.

I was renaming lots of config files in the app UI, modifying some ovpn within the app, testing connections, etc. 

[Tunnelblick.Error.Data.log](https://github.com/Tunnelblick/Tunnelblick/files/4424134/Tunnelblick.Error.Data.log)
[Console.log](https://github.com/Tunnelblick/Tunnelblick/files/4422214/Console.log)

**Comment by WoodpeckerBaby** [comment]
## An update with new files 
[Tunnelblick crash - Apple Report Autogen.log](https://github.com/Tunnelblick/Tunnelblick/files/4424106/Tunnelblick.crash.-.Apple.Report.Autogen.log)
[Console2.Log](https://github.com/Tunnelblick/Tunnelblick/files/4424107/Console2.Log)
<details>
<summary>A screenshot of Apple Keychain showing app password relavant to Tunnelblick.</summary>

### "Common" does present and has the right info, but always not found by the app for some reason

<img width="1223" alt="Screen Shot 2020-04-03 at 6 36 29 AM" src="https://user-images.githubusercontent.com/14303318/78306589-5d4adf00-7576-11ea-9977-0df3c856d565.png">
</details>

**Comment by jkbullard** [comment]
This is fixed in Tunnelblick 3.8.6a and 3.8.7beta02.
