### ISSUE TITLE
Problem with IPV6 DNS when "disable ipv6" is checked

### ISSUE THREAD

**Issue by atoy40** [Tunnelblick/Tunnelblick#616]
**Describe the bug**

When you have an OpenVPN server configuring IPV6 inside the tunnel, and giving only an IPV6 DNS server, there is a problem if the "disable ipv6" checkbox is checked (default).
Tunnelblick get the DNS option correctly :
```
10:41:26 *Tunnelblick:  Retrieved from OpenVPN: name server(s) [ 2001:660:xxxx:6::d2 ], domain name [ xxxxxx.fr ], search domain(s) [ ], and SMB server(s) [ ]
10:41:28 *Tunnelblick:  DNS servers '2001:660:xxxx:6::d2' will be used for DNS queries when the VPN is active
```
But at the end of the connection process, an error popup appears about DNS problem, and the log contains :
```
2020-04-04 10:41:28.815246 *Tunnelblick: Warning: No DNS servers have been specified.
```

However, the IPV6 tunnel is working perfectly, and you can query the DNS manually without any problem :
```dig @2001:660:6701::XXXX www.google.com``` reply perfectly. But without forcing the DNS address in the command line, it's not able to resolve.

If you go to the OSX control panel and into the network configuration panel, you can see the IPV6 dns listed in the DNS tab.

But at the end, DNS queries don't works. The only way to fix it it to uncheck "disable ipv6". For sure it seems obvious to uncheck it, but it's not very intuitive because if you let it check, everything about IPV6 works except for DNS resolutions.

**To Reproduce**
1. configure you server for IPV6 and push only an IPV6 DNS server
2. have "disable ipv6" checked on the tunnelblick client

Tunnelblick 3.8.2 (build 5480)
OSX Catalina

Anthony.

**Comment by jkbullard** [comment]
@atoy40 - Thanks for your report.

> However, the IPV6 tunnel is working perfectly, and you can query the DNS manually without any problem :<br>
<code>dig @2001:660:6701::XXXX www.google.com</code> reply perfectly. But without forcing the DNS address in the command line, it's not able to resolve.

If IPv6 is disabled, DNS via IPv6 will not work via the normal macOS network stack. However, "dig", "ping", and some other command line tools do not use the normal macOS network stack. So you cannot rely on them to determine if IPv6 is working.

> The only way to fix it it to uncheck "disable ipv6". For sure it seems obvious to uncheck it, but it's not very intuitive…

It's also not very friendly.

Tunnelblick already skips disabling IPv6 if the VPN server has an IPv6 server address. Perhaps Tunnelblick should also skip disabling IPv6 if all DNS servers have IPv6 addresses.

**Comment by atoy40** [comment]
> @atoy40 - Thanks for your report.
> 
> > However, the IPV6 tunnel is working perfectly, and you can query the DNS manually without any problem :
> > `dig @2001:660:6701::XXXX [www.google.com](http://www.google.com)` reply perfectly. But without forcing the DNS address in the command line, it's not able to resolve.
> 
> If IPv6 is disabled, DNS via IPv6 will not work via the normal macOS network stack. However, "dig", "ping", and some other command line tools do not use the normal macOS network stack. So you cannot rely on them to determine if IPv6 is working.
> 

Sure, the dig example was just to notify the "layer 3" ipv6 stack was working perfectly in my openvpn config.

> > The only way to fix it it to uncheck "disable ipv6". For sure it seems obvious to uncheck it, but it's not very intuitive…
> 
> It's also not very friendly.
> 
> Tunnelblick already skips disabling IPv6 if the VPN server has an IPv6 server address. Perhaps Tunnelblick should also skip disabling IPv6 if all DNS servers have IPv6 addresses.

Yes, but even if you have a mix of v4 and v6 dns server, until you uncheck the box, ipv6 dns servers will never be used.

Anthony.

**Comment by jkbullard** [comment]
@atoy40 - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
