### ISSUE TITLE
Informative tooltips are editable by user

### ISSUE THREAD

**Issue by ctrlaltca** [Tunnelblick/Tunnelblick#619]
**Describe the bug**
When hovering most of the options available on the vpn settings, an informative tooltip will popup with an extended description of the option.
These tooltips can be edited by the user.

**To Reproduce**
1. Go to the "settings" tab of a vpn configuration
2. Hover an option and wait for the tooltip to appear
2. Click on the tooltip, you'll see the cursor appear
3. Edit the tooltip contents.

**Expected behavior**
I'm not sure this this an expected feature, I guess it's a minor bug where the tooltip textarea is not set readonly.

**Screenshots**
![Schermata 2020-04-21 alle 10 32 07](https://user-images.githubusercontent.com/1631111/79844246-b6f73a00-83bb-11ea-9193-9831d0dd3749.png)

**Comment by jkbullard** [comment]
@ctrlaltca - Thanks!

If it actually kept the edit, I could try to claim it's a feature so that users can annotate the help themselves.

But, it's a bug. Thanks for finding and reporting it.
