### ISSUE TITLE
OpenSSL vulnerabilities

### ISSUE THREAD

**Issue by hhettiarachchi** [Tunnelblick/Tunnelblick#621]
OpenSSL version used by TunnelBlick 3.8.2 (OpenSSL 1.1.1e) is vulnerable for this DoS attacks.

https://www.us-cert.gov/ncas/current-activity/2020/04/22/openssl-releases-security-update

The fixed version needs to be integrated into the Tunnelblick.

**Comment by jkbullard** [comment]
@hhettiarachchi - That isn't necessary.

[According to one of the OpenVPN developers](https://sourceforge.net/p/openvpn/mailman/message/36988332/) and confirmed by my research, OpenVPN does not use the `SSL_check_chain()` OpenSSL function that is involved in the problem. Tunnelblick does not use OpenVPN directly at all.
