### ISSUE TITLE
[feature request] allow to switch between VPN

### ISSUE THREAD

**Issue by vanyakosmos** [Tunnelblick/Tunnelblick#623]
Instead of just warning about consequences of running two connection - allow user to switch VPNs (disconnect from old one and connect to selected)

![Untitled](https://user-images.githubusercontent.com/16745500/81796631-61273500-9516-11ea-8d0b-e915c9437ca5.png)

**Comment by jkbullard** [comment]
We're not going to do this because it is useful in few situations.

**Comment by ignlg** [comment]
Even when I understand that every feature request is subjective, this feature is very relevant, even critical if leaks are critical, in some use case. From my experience, I bring two use cases that need this feature:

1. Switching countries.
2. Switching access to private services.

1. The first one is common in my social circle, even among non-technical fellows. They use it to access content locked by country. An example use case is when they/we live in a different country and need access to content locked to or blocked by the country where we live, the country of origin, another country. Could be streaming services, like local TVs, or governmental bureaucratic proceedings.

2. The second one is more job specific and, as I work with different clients (customers) with different security needs, one common use case is that each company has a VPN to access services. Switching projects means switching VPNs.

I know that not everyone has these needs, but that does not invalidate that the need is there and how important is for those affected by it. I agree with @jkbullard, and that implementation looks great to me.

**Comment by jkbullard** [comment]
@ignlg -
 1. What is the implementation that looks great to you?
 2. Why is it necessary to prevent leaks when switching VPNs?

**Comment by ignlg** [comment]
@jkbullard -

1. To add the option to switch VPN instead of establish multiple connections to the multiple connection modal.

2. The amount of time exposed without VPN can be significant doing the switch manually, and for some users this exposure is unlikely wanted. Personally my current process is: Disconnect the interface, disconnect VPN, connect VPN (with connection error) and connect back the interface, so the exposure is as low as possible.

From a user experience perspective, I have found the switching feature in other VPN applications, including OpenVPN (iOS and Android), ProtonVPN (iOS and Android), and Viscosity (macOS).

**Comment by jkbullard** [comment]
If you're using VPNs to bypass geographic restrictions, why do you care about leaks? You connect the VPN for the UK to watch the BBC, then disconnect it and connect the VPN for the USA to watch something. Why do you care about leaks?

**Comment by ignlg** [comment]
Let's say that we keep the leak possibility aside. I will redefine the feature request as:

> The ability to switch VPNs without manually disconnecting, waiting for the disconnection, and manually connecting to another one.

And I add the list of applications already mentioned as examples of popular applications with such feature, backing that the feature is common or standard among VPN GUI applications and would be a great addition to Tunnelblick.

You are right that my first request could be rejected as biased by personal needs. Hopefully this adds more contrastable data to it.
