### ISSUE TITLE
Why build different versions of openvpn？

### ISSUE THREAD

**Issue by shh230** [Tunnelblick/Tunnelblick#624]
**Describe the bug**
I read source code, find build three versions of openvpn. Why?

**Expected behavior**
Hope to help explain why build different versions of openvpn. This is to adapt to different macos？If yes, can you introduce the different versions of macos corresponding to openvpn？

**Screenshots**
![image](https://user-images.githubusercontent.com/38716757/83217891-62579380-a19f-11ea-9d30-4751fca96b6e.png)

**Comment by jkbullard** [comment]
We include different versions of OpenVPN to accommodate users with different needs:
 1. Some users need to connect to old OpenVPN servers and thus need OpenVPN 2.3;
 2. Most users can use the current stable release version of OpenVPN (2.4); and
 3. Some users want to test new features in the latest master version of OpenVPN (2.5).

We also include, for each version of OpenVPN, two different SSL libraries. This is a way of ensuring compatibility (for example, when a new version of OpenSSL removes some types of encryption) and security (if one SSL library has a vulnerability, often the other doesn't).
