### ISSUE TITLE
How does Tunnelblick run openvpn? After reading it for a long time in the source code, there is no clue, can you introduce it?

### ISSUE THREAD

**Issue by shh230** [Tunnelblick/Tunnelblick#627]
How does Tunnelblick run openvpn? After reading it for a long time in the source code, there is no clue, can you introduce it?

**Comment by jkbullard** [comment]
There are two different ways:

 1. To run OpenVPN as the user (for example, to use the --version option to get the version number), Tunnelblick just runs OpenVPN as a task. It does that via the runTool() routine in helper.m, which is located in the Xcode "Common" group.

 2. To run OpenVPN as root (for example, to start a VPN connection attempt), Tunnelblick sends a command to it's tunnelblickd  launch daemon, which runs as root. tunnelblickd then uses it's own similar runTool() routine to run OpenVPN. tunnelblickd is located in the Xcode "Other Sources" group.

**Comment by shh230** [comment]
1. I found the first way. How does it communicate with OpenVPN? Through socket?
2. Then how to run OpenVPN as root, I did not find this way.

**Comment by jkbullard** [comment]
Tunnelblick communicates with OpenVPN via the management interface, through a socket.

Read the code in tunnelblickd that calls runTool() to start OpenVPN. It sets up the uid, gid, etc. and then starts OpenVPN.

Why are you asking these questions? Are you just curious, or is there something specific you want to do with OpenVPN?

**Comment by shh230** [comment]
Thanks, I want to add a parameter to verify the device on this basis.
