### ISSUE TITLE
Kernel panic after macbook sleeps - Failure code:: 0x00000004 00000014

### ISSUE THREAD

**Issue by tajchert** [Tunnelblick/Tunnelblick#628]
**Describe the bug**
Kernel panic after Macbook Pro sleeps overnight. I had to force restart machine.

**To Reproduce**
1.  Have Tunelblick open and VPN connected
2. Lock computer
3. Macbook sleeps
4. Wake up - it is imposible, hard restart using button is needed.
5. Got popup with stacktrace "Your computer was restarded because of a problem"

**Expected behavior**
5. Macbook wakes as it should do.

**Screenshots**
![image](https://user-images.githubusercontent.com/2962633/83940612-c7d20280-a7e5-11ea-817f-c2ba036bcd9c.png)

**Additional context**
`panic(cpu 0 caller 0xffffff801e29167c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOSkywalkFamily. Thread 0x2b3c7.
Failure code:: 0x00000004 00000014

Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff9249953900 : 0xffffff801dc458f8 
0xffffff924937ba10 : 0xffffff801db413f1 
0xffffff924937ba80 : 0xffffff801db3fc2f 
0xffffff924937bad0 : 0xffffff801db01101 
0xffffff924937bb10 : 0xffffff801db2659b 
0xffffff924937bb60 : 0xffffff801e273c88 
0xffffff924937bbc0 : 0xffffff801e27388a 
0xffffff924937bc10 : 0xffffff7f9e4b5c1b 
0xffffff924937bd20 : 0xffffff7f9e4b40b7 
0xffffff924937bd40 : 0xffffff7f9e4b3fb8 
0xffffff924937bd60 : 0xffffff7f9e4b3930 
0xffffff924937bd90 : 0xffffff801e22fae8 
0xffffff924937bdf0 : 0xffffff7f9e4b4a02 
0xffffff924937be00 : 0xffffff801e214d8a 
0xffffff924937bea0 : 0xffffff801e2146b4 
0xffffff924937bec0 : 0xffffff801db61565 
0xffffff924937bf40 : 0xffffff801db61091 
0xffffff924937bfa0 : 0xffffff801dac513e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOSkywalkFamily(1.0)[39D13BE0-9833-3842-B547-1FBE79ABDAD8]@0xffffff7f9e49c000->0xffffff7f9e4e2fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[8119788F-2497-3C32-8325-C8B8D843BB31]@0xffffff7f9e465000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x000000001d800000
Kernel text base: 0xffffff801da00000
__HIB  text base: 0xffffff801d900000
System model name: MacBookPro14,3 (Mac-551B86E5744E2388)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 12694096421680
last loaded kext at 7625582953330: net.tunnelblick.tun	5300.3 (addr 0xffffff7fa2d0b000, size 36864)
last unloaded kext at 7633860127091: net.tunnelblick.tun	5300.3 (addr 0xffffff7fa2d0b000, size 28672)
loaded kexts:
com.intel.kext.intelhaxm	7.5.1
com.objective-see.lulu	1.2.3
com.checkpoint.cpfw	1.0
>usb.!UHostBillboardDevice	1.0
|SCSITaskUserClient	422.120.3
>usb.realtek8153patcher	5.0.0
@filesystems.smbfs	3.4.3
>AudioAUUC	1.70
@fileutil	20.036.15
>!AHIDALSService	1
>X86PlatformShim	1.0.0
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
@filesystems.autofs	3.0
>!AHDAHardwareConfigDriver	283.15
>!AHDA	283.15
@kext.AMDRadeonServiceManager	3.0.9
>!AUpstreamUserClient	3.6.8
@kext.AMDFramebuffer	3.0.9
@kext.AMDRadeonX4000	3.0.9
>!AGraphicsDevicePolicy	5.2.4
@AGDCPluginDisplayMetrics	5.2.4
>!AHV	1
|IOUserEthernet	1.0.1
>AGDCBacklightControl	5.2.4
>!A!IKBLGraphics	14.0.6
>!ABacklight	180.3
|IO!BSerialManager	7.0.5f6
>!A!IPCHPMC	2.0.1
>pmtelemetry	1
@Dont_Steal_Mac_OS_X	7.0.0
>!AMuxControl	5.2.4
@kext.AMD9500!C	3.0.9
>!A!ISlowAdaptiveClocking	4.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
>!AEmbeddedOSSupportHost	1
>eficheck	1
>SMCMotionSensor	3.0.4d1
>!AThunderboltIP	3.1.4
>!AFIVRDriver	4.1.0
>!A!IKBLGraphicsFramebuffer	14.0.6
>!AMCCSControl	1.14
>!AGFXHDA	100.1.428
>!AFileSystemDriver	3.0.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!ATopCaseHIDEventDriver	3430.1
>AirPort.BrcmNIC	1400.1.1
@filesystems.apfs	1412.120.2
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ARTC	2.0
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>!UMergeNub	900.4.2
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.acm	5.0.0
>usb.serial	6.0.0
>usb.!UHub	1.2
@kext.triggers	1.0
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
@kext.AMDRadeonX4100HWLibs	1.0
@kext.AMDRadeonX4000HWServices	3.0.9
|IOAVB!F	850.1
>!ASSE	1.0
>!ABacklightExpert	1.1.0
|IO!BHost!CUARTTransport	7.0.5f6
|IO!BHost!CTransport	7.0.5f6
>!AGraphicsControl	5.2.4
@!AGPUWrangler	5.2.4
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
@kext.AMDSupport	3.0.9
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>!AHDA!C	283.15
|IOHDA!F	283.15
>!ASMBusPCI	1.0.14d1
>!AThunderboltEDMSink	4.2.3
>!AThunderboltDPOutAdapter	6.2.6
@!AGraphicsDeviceControl	5.2.4
|IOAccelerator!F2	438.5.4
>!ASMBus!C	1.0.18d1
|IONDRVSupport	576.1
|IOGraphics!F	576.1
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>!UAudio	323.1
>usb.!UiBridge	1.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
>!AActuatorDriver	3440.1
>!AHIDKeyboard	209
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.5f6
|IO!B!F	7.0.5f6
|IO!BPacketLogger	7.0.5f6
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>!AHSSPIHIDDriver	59
>!AHSSPISupport	59
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOSkywalk!F	1
>!A!ILpssSpi!C	3.0.60
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AThunderboltPCIDownAdapter	2.5.4
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!AThunderboltNHI	5.8.6
>!AHPM	3.4.4
|IOThunderbolt!F	7.6.1
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssGspi	3.0.60
>!A!ILpssI2C	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.121.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
`

**Diagnostic information**
Macbook Pro 15-inch 2017, macOS Catalina 10.15.5 (however it happen before as well).

**Comment by jkbullard** [comment]
Thanks for your report. Please eliminate your reliance on Tunnelblick's tun kext, then restart your computer. That will eliminate Tunnelblick kexts as a possible cause of the problem and is a good idea in any case (the latest few beta versions of Tunnelblick pop up a notice that you should do this to prepare for future versions of macOS). See [The Future of Tun and Tap VPNs on macOS](https://tunnelblick.net/cTunTapConnections.html), particularly the section on [How to modify a 'tun' VPN so it will continue to work](https://tunnelblick.net/cTunTapConnections.html#how-to-modify-a-tun-vpn-so-it-will-continue-to-work).

There is nothing else in the report to indicate that Tunnelblick is involved, but you could try changing settings so Tunnelblick does not disconnect your VPN on sleep and reconnect it on wake, on Tunnelblick's "Advanced" settings page.

Apparently, macOS Catalina (10.15.4, at least) has a lot of panics. See [Some Users Experiencing System Crashes on macOS 10.15.4, Especially During Large File Transfers](https://www.macrumors.com/2020/04/06/macos-10-5-4-kernel-panic-crashing-issues/).

**Comment by guyzmo** [comment]
I've started to have the same crashes recently, weirdly that's only since I started using 15.15.5.

I do understand this is EOL, I'll RTFM and switch away. But for the record, here's a typical (and very consistent) crash:

```
panic(cpu 0 caller 0xffffff80020c2c5f): assertion failed: ifp->if_allhostsinm == NULL, file: /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.121.2/bsd/net/dlil.c, line: 7965
Backtrace (CPU 0), Frame : Return Address
0xffffff92082e31a0 : 0xffffff800191f5cd 
0xffffff92082e31f0 : 0xffffff8001a58b05 
0xffffff92082e3230 : 0xffffff8001a4a68e 
0xffffff92082e3280 : 0xffffff80018c5a40 
0xffffff92082e32a0 : 0xffffff800191ec97 
0xffffff92082e33a0 : 0xffffff800191f087 
0xffffff92082e33f0 : 0xffffff80020c27cc 
0xffffff92082e3460 : 0xffffff80020c2c5f 
0xffffff92082e3470 : 0xffffff8001bf9bc9 
0xffffff92082e3590 : 0xffffff7f850e1767 
0xffffff92082e36a0 : 0xffffff7f850e4d14 
0xffffff92082e3740 : 0xffffff7f850e1d2a 
0xffffff92082e3790 : 0xffffff7f850e37b7 
0xffffff92082e37e0 : 0xffffff7f850e36ca 
0xffffff92082e3810 : 0xffffff8001bbbf5b 
0xffffff92082e3870 : 0xffffff8001bb0c9a 
0xffffff92082e38c0 : 0xffffff8001ba3a71 
0xffffff92082e3940 : 0xffffff8001b8c4e6 
0xffffff92082e3ba0 : 0xffffff8001b8cfee 
0xffffff92082e3f40 : 0xffffff8001f87097 
0xffffff92082e3fa0 : 0xffffff80018c6206 
      Kernel Extensions in backtrace:
         net.sf.tuntaposx.tap(1.0)[23FDB715-3D0D-3A26-ACBA-E3794C231CB7]@0xffffff7f850e0000->0xffffff7f850e6fff

BSD process name corresponding to current thread: tincd

Mac OS version:
19F101

Kernel version:
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
Kernel UUID: 54F1A78D-6F41-32BD-BFED-4381F9F6E2EF
Kernel slide:     0x0000000001600000
Kernel text base: 0xffffff8001800000
__HIB  text base: 0xffffff8001700000
System model name: MacBookPro13,2 (Mac-66E35819EE2D0D05)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 685950101217968
last loaded kext at 6201694089564: >usb.cdc.acm	5.0.0 (addr 0xffffff7f848f2000, size 36864)
loaded kexts:
net.sf.tuntaposx.tun	1.0
net.sf.tuntaposx.tap	1.0
...
```

**Comment by jkbullard** [comment]
@guyzmo wrote:
> I've started to have the same crashes recently, weirdly that's only since I started using 15.15.5.

What is "15.15.5"? There's no such version of macOS or Tunnelblick.

>      Kernel Extensions in backtrace:
>         net.sf.tuntaposx.tap(1.0)[23FDB715-3D0D-3A26-ACBA-E3794C231CB7]@0xffffff7f850e0000->0xffffff7f850e6fff
> ...
> loaded kexts:
> net.sf.tuntaposx.tun	1.0
> net.sf.tuntaposx.tap	1.0

net.sf.tuntaposx.tap and net.sf.tuntaposx.tap are not Tunnelblick kexts, or at least haven't been for many years. Our kexts have bundle-ids of net.tunnelblick.tap and net.tunnelblick.tun.

So what does this crash have to do with Tunnelblick?
