### ISSUE TITLE
Tunnelblick: An error occurred fetching IP address

### ISSUE THREAD

**Issue by yousefal7** [Tunnelblick/Tunnelblick#630]
**Describe the bug**
Hi i face this problem when try to connecting and i use mac OS Catalina 10.15.5

**Diagnostic information**
       add net 128.0.0.0: gateway 10.54.15.1
                           11:05:31 *Tunnelblick:  **********************************************
                           11:05:31 *Tunnelblick:  Start of output from client.up.tunnelblick.sh
                           11:05:34 *Tunnelblick:  NOTE: No network configuration changes need to be made.
                           11:05:34 *Tunnelblick:  WARNING: Will NOT monitor for other network configuration changes.
                           11:05:34 *Tunnelblick:  DNS servers '8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220' were set manually
                           11:05:34 *Tunnelblick:  DNS servers '8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220' will be used for DNS queries when the VPN is active
                           11:05:34 *Tunnelblick:  The DNS servers include only free public DNS servers known to Tunnelblick.
                           11:05:34 *Tunnelblick:  Flushed the DNS cache via dscacheutil
                           11:05:34 *Tunnelblick:  /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                           11:05:34 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
                           11:05:34 *Tunnelblick:  Not notifying mDNSResponderHelper that the DNS cache was flushed because it is not running
                           11:05:34 *Tunnelblick:  End of output from client.up.tunnelblick.sh
                           11:05:34 *Tunnelblick:  **********************************************
2020-06-22 11:05:34.314155 Initialization Sequence Completed
2020-06-22 11:05:34.314290 MANAGEMENT: >STATE:1592813134,CONNECTED,SUCCESS,

2020-06-22 11:05:34.628401 *Tunnelblick: DNS address 208.67.220.220 is being routed through the VPN
2020-06-22 11:05:34.649941 *Tunnelblick: DNS address 208.67.222.222 is being routed through the VPN
2020-06-22 11:05:34.757056 *Tunnelblick: DNS address 8.8.4.4 is being routed through the VPN
2020-06-22 11:05:34.870528 *Tunnelblick: DNS address 8.8.8.8 is being routed through the VPN
2020-06-22 11:06:18.208290 *Tunnelblick: After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
2020-06-22 11:06:58.710523 *Tunnelblick: An error occurred fetching IP address information using the ipInfo host's IP address after connecting

Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
These are the two critical entries:
> After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
> An error occurred fetching IP address information using the ipInfo host's IP address after connecting

The first means that DNS is not working; the second means that using IP addresses directly is not working either.

Neither of these have to do with Tunnelblick itself.

When they happen together in a new VPN setup, they usually mean that routing is not being set up properly (that is, the OpenVPN configuration or OpenVPN options pushed by the OpenVPN server are wrong). Consult OpenVPN sources for help (see our [Support page](https://tunnelblick.net/support.html)).

There are other possibilities, too, including:
 * Your OpenVPN server is not working properly.
 * There is a firewall between you and the Internet that is blocking access to VPN traffic. (Perhaps your ISP, the Great Firewall of China or an equivalent, etc.)

**Comment by yousefal7** [comment]
if you mean to use vpn i used Celo vpn but the error message came 

                           03:28:09 *Tunnelblick:  **********************************************
                           03:28:09 *Tunnelblick:  Start of output from client.up.tunnelblick.sh
                           WARNING: $route_vpn_gateway is empty
                           03:28:11 *Tunnelblick:  Not using DHCP because tap0 already has an IP configuration (10.54.15.100). route_vpn_gateway = ''
                           03:28:11 *Tunnelblick:  NOTE: No network configuration changes need to be made.
                           03:28:11 *Tunnelblick:  WARNING: Will NOT monitor for other network configuration changes.
                           03:28:11 *Tunnelblick:  DNS servers '91.207.172.219 91.207.172.219' were set manually
                           03:28:11 *Tunnelblick:  DNS servers '91.207.172.219 91.207.172.219' will be used for DNS queries when the VPN is active
                           03:28:11 *Tunnelblick:  NOTE: The DNS servers do not include any free public DNS servers known to Tunnelblick. This may cause DNS queries to fail or be intercepted or falsified even if they are directed through the VPN. Specify only known public DNS servers or DNS servers located on the VPN network to avoid such problems.
                           03:28:11 *Tunnelblick:  Flushed the DNS cache via dscacheutil
                           03:28:11 *Tunnelblick:  /usr/sbin/discoveryutil not present. Not flushing the DNS cache via discoveryutil
                           03:28:11 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
                           03:28:11 *Tunnelblick:  Not notifying mDNSResponderHelper that the DNS cache was flushed because it is not running
                           03:28:11 *Tunnelblick:  End of output from client.up.tunnelblick.sh
                           03:28:11 *Tunnelblick:  **********************************************
2020-06-23 03:28:11.458481 Initialization Sequence Completed
2020-06-23 03:28:11.458640 MANAGEMENT: >STATE:1592872091,CONNECTED,SUCCESS,10.54.15.100,209.133.193.243,33398,172.16.0.3,62875
2020-06-23 03:28:11.679077 *Tunnelblick: Warning: DNS server address 91.207.172.219 is not a public DNS server known to Tunnelblick and is not being routed through the VPN
2020-06-23 03:28:17.918231 *Tunnelblick: This computer's apparent public IP address (91.207.172.220) was unchanged after the connection was made
2020-06-23 03:27:56.820778 *Tunnelblick: openvpnstart starting OpenVPN

**Comment by jkbullard** [comment]
You need to contact your VPN service provider, Celo VPN.

**Comment by d3vilh** [comment]
have the same problem on M1 Mac when trying to connect to my own OVPN server, with Tunnelblick 3.8.8beta04 (build 5800)

```
2022-06-21 19:45:52.732399 *Tunnelblick: After 30.0 seconds, gave up trying to fetch IP address information using the ipInfo host's name after connecting.
2022-06-21 19:46:30.856430 *Tunnelblick: An error occurred fetching IP address information using the ipInfo host's IP address after connecting
```
When I using original OVPNConnect everything works just fine.

**Comment by d3vilh** [comment]
> When I using original OVPNConnect everything works just fine.

OK, I got this fixed by simple reboot after the OVPN-Connect uninstall. 
Now Tunnelblick works fine.
