### ISSUE TITLE
Permissions Check Broken on macOS Big Sur Beta

### ISSUE THREAD

**Issue by tmthecoder** [Tunnelblick/Tunnelblick#632]
I've recently installed the Big Sur beta, and similar to that of Catalina, I get an insecure /tmp folder issue on Tunnelblick's startup check. Everything else still does work.

To reproduce, launch Tunnelblick under the Beta of macOS Big Sur.

The expected behavior was to launch Tunnelblick as expected. 

Here is a screenshot of the error:
<img width="401" alt="Screen Shot 2020-06-23 at 3 48 15 PM" src="https://user-images.githubusercontent.com/50885454/85452514-f5020d00-b568-11ea-85a9-538c20c41de8.png">

Here is the output from the command: `ls -l@ed /tmp ; ls -l@ed /private/tmp`:

`lrwxr-xr-x@ 1 root  wheel  11 Jan  1 03:00 /tmp -> private/tmp
	com.apple.rootless	 0`
`drwxrwxrwt  10 root  wheel  320 Jun 23 15:42 /private/tmp`

Let me know if I need to provide any other info.

On a separate note, how will this app be made for the new ARM Macs as the current build is on Xcode 7.3.1 on macOS 10.11.16?

Happy to help in any way I can.

**Comment by jkbullard** [comment]
@tmthecoder - Thanks. Apple strikes again. After having a group owner ID of wheel (0) on macOS 10.0 through 10.14, they switched to a group owner ID of admin (80) on 10.15, and now they've apparently switched back to wheel (0) on 11.0. I'm currently testing a fix for this.

Tunnelblick won't be made with Universal binaries until we can get it working properly when built with Xcode 12 — if we _ever_ get it working properly.

**Comment by tmthecoder** [comment]
@jkbullard 
It's not a pressing issue on my end since I can click past, but I just thought I'd give a heads up for the future. 

Regarding Universal Binaries, I can try to see if Tunnelblick builds on the Xcode 12 beta, but the most I can do is build it without signing as you've said Tunnelblick is signed using a custom signing process.

**Comment by jkbullard** [comment]
See #633 for discussion of building Tunnelblick on Xcode 12. This Issue is for the /tmp permissions problem.

**Comment by janstieler** [comment]
Hi,
I have the same problem on MacOs High Sierra 10.13.6.
Here I have also wheel. I'm not sure if this is really a security problem?
How can I solve this under 10.13?

**Comment by jkbullard** [comment]
@janstieler - See [System Folder Security](https://tunnelblick.net/cSystemFolderNotSecure.html).
