### ISSUE TITLE
Tunnelblick binaries built on Xcode 12 crash too often

### ISSUE THREAD

**Issue by jkbullard** [Tunnelblick/Tunnelblick#633]
There isn't a problem building Tunnelblick on Xcode 12 as far as I know.

But the binaries built on Xcode 8 through Xcode 11 crash weirdly too often, and I assume binaries built on Xcode 12 will, too.

The crashes could be caused by memory corruption, and they occur rarely enough in binaries built with Xcode 7 (once per several hundreds of thousands of hours of use) that I haven't been working too hard to try to fix them.

When built with Xcode 8 or higher the crashes happens much more often -- more like once per hundred or thousand hours of use. That's not acceptable to me.

Either way, the crashes happen so rarely it's hard to debug; so far I haven't been able to figure it out.

(By "hours of use" I mean actively using the UI, not just having Tunnelblick running in the background doing nothing or only running an active VPN.)

**Comment by tmthecoder** [comment]
@jkbullard How did you come to test the binaries on Xcode 8-11? I'm assuming it is just keeping tunnelblick's UI active or does one need to be actively clicking through the UI?

**Comment by jkbullard** [comment]
@tmthecoder - Beta testers have used binaries built on Xcode 8-11. By using the number of beta testers using a particular version and the number of crashes they report, we get a crude idea of the frequency. The users are just using it normally.

**Comment by jkbullard** [comment]
This problem has been fixed in Tunnelblick 3.8.6a and 3.8.7beta02.
