### ISSUE TITLE
up-suffix.sh not executing

### ISSUE THREAD

**Issue by pacmac** [Tunnelblick/Tunnelblick#634]
I read through the instructions and thought I understood, but maybe not.

This is my up-suffix.sh (chmod +x) and is located in the /Contents/Resources Folder

```
#!/bin/bash -e

echo "@@@@@ START up-suffix.sh @@@@@"
~/scripts/bash/mobile-dns;
echo "@@@@@ END up-suffix.sh @@@@@"
```

This script calls another script which performs dns updates and adds ip addres to UFW, the script works fine when executed from the command line, but I see no evidence of it and no errors showing during the connect process.

What am I doing wrong ??

**Comment by jkbullard** [comment]
The up-prefix.sh script runs as root.

Does your up-prefix.sh work from the command line using sudo? Probably not.

Your script accesses "~/scripts/bash/mobile-dns", which would be interpreted as "/Users/**root**/scripts/bash/mobile-dns", which probably doesn't exist.

For security reasons, it is a really bad idea for your script to call other scripts. Such "external" scripts will not be checked by Tunnelblick for security, and in any case they should not be used unless they are owned by root and can only be modified by root.

**Comment by diginfo** [comment]
Thanks for helping.

Right now all I want to achieve is to see the output from connected.sh in the logs post connection, as right now I see nothing and have no idea whether the script is even being called.

```
#!/bin/bash -e
echo "@@@@@ START connected.sh @@@@@"
echo "@@@@@ END connected.sh @@@@@"
```

Once that works I can resolve path issues etc.

These scripts update my dynamic IP address in linode domain manager and work from the console.

But the problem with locating my scripts in the tunnelblik folder is that I am duplicating scripts that already exist in my /scripts folders and it means that I have to modify both script files instead of just my source.

This is on my laptop and I am the only user so I am not so concerned about script locations in terms of security

**Comment by jkbullard** [comment]
Note that connected.sh runs as root.

Output from connected.sh should appear in the Tunnelblick log (in Tunnelblick's VPN Details window).

If the script returned with an error status of zero, the output should look something like this:

The 'connected' script succeeded
_`<output from connected.sh stdout`>
`<output from connected.sh stderr`>_

If the script returned with a non-zero error status of _NNN_ (from exit _NNN_, for example), the output should look something like this:

The 'connected' script failed; openvpnstart 'connected' returned error _NNN_
_`<output from connected.sh stdout`>
`<output from connected.sh stderr`>_

If the connected.sh script cannot be run, the _NNN_ and _`<output…_ may be replaced with an error code from Tunnelblick and a message from Tunnelblick describing the problem.

If you can't find the output in the Tunnelblick log, you could change your script to:
<pre>
#!/bin/bash -e
echo "@@@@@ START connected.sh @@@@@" >> /tmp/tunnelblick-connected-sh-output.txt
echo "@@@@@ END connected.sh @@@@@"   >> /tmp/tunnelblick-connected-sh-output.txt
</pre>
and look in /tmp for _tunnelblick-connected-sh-output.txt_ to see if the script was executed.

**Comment by diginfo** [comment]
Thanks so much for helping.

I have looked through the online documentation (numerous times) to try and determine the correct paths, but it appears that these paths may have changed in later releases.

I also looked at various stackoverflow posts to try and determine where and how to do this based on the current version, based on other users attempts.

As per one of the TB online instrucions, I have tried putting a connected.sh file inside the folder:

'/Library/Application Support/Tunnelblick/Users/myuid/myvpn.tblk/Contents/Resources/connected.sh'

And chmod +x, I can execute the script successfully from the command line.

When the connection starts I am prompted by TB to accept config changes, enter passsword, the file I created is then deleted and no evidence in the logs that the file ever executed.

In the script have tried echoing just to stdout and also echo > /tmp.test.txt - no evidence at all that the scripts was ever called.

So I then created the same file in:

/Applications/Tunnelblick.app/Contents/Resources/connected.sh

Nothing gets executed.

So then created Deploy folder:

/Applications/Tunnelblick.app/Contents/Resources/Deploy/connected.sh

Nothing gets executed.

Been using tunnelblick for years, it's really great, but it would be very helpful if a updated procedure can be added just to add a simple connected.sh script to be executed by a profile including the paths needed as there are so many different locations of Tunnelblick files and application support files etc etc, it's quite confusing to easily understand where to put these.

I have no problem whatsoever in writing bash scripts, the main problem here is knowing exactly where they should be located :-)

**Comment by jkbullard** [comment]
@diginfo - I'm sorry you are having so much trouble with this.

**Please don't fiddle with Tunnelblick's folders**; they are for Tunnelblick's use, not yours. You shouldn't need to access them and they are subject to change.

Using Scripts](https://tunnelblick.net/cUsingScripts.html) says:
> The scripts will be executed automatically if they are included in the Tunnelblick VPN Configuration (".tblk"). For more information, see [Creating and Installing a Tunnelblick VPN Configuration](https://tunnelblick.net/cConfigT.html#creating-and-installing-a-tunnelblick-vpn-configuration) and [Multi-factor and Two-factor Authentication](https://tunnelblick.net/cMultiFactorAuthentication.html).

[Creating and Installing a Tunnelblick VPN Configuration](https://tunnelblick.net/cConfigT.html#creating-and-installing-a-tunnelblick-vpn-configuration) says:

> To create a Tunnelblick VPN Configuration:
>
> 1. Create a folder anywhere (on your Desktop works well);
> 2. If you have only one OpenVPN configuration file, name the folder with the name you want the configuration known by in Tunnelblick. (Otherwise, each configuration will be known in Tunnelblick by the name of the OpenVPN configuration file that it is based on);
> 3. Copy all the files related to the configuration(s) into the folder (see [Files Contained in a Tunnelblick VPN Configuration](https://tunnelblick.net/cConfigT.html#files-contained-in-a-tunnelblick-vpn-configuration), below);
> 4. Add an extension of ".tblk" at the end of the folder name. When you do this the icon for the folder will change to an icon for a Tunnelblick VPN Configuration.
> 5. Drag and drop the folder's new icon onto the Tunnelblick icon in the menu bar to install it.

[Files Contained in a Tunnelblick VPN Configuration](https://tunnelblick.net/cConfigT.html#files-contained-in-a-tunnelblick-vpn-configuration) says:

> The files that should be contained in a Tunnelblick VPN Configuration (the "files related to the connection" above) should all be "plain text" files:
>
> * One or more OpenVPN configuration files (.ovpn or .conf files).
> * Any certificate or key files for the configurations (.key, .crt, .pem, .cer, .der, .p12, .p7b, .p7c, and .pfx files); and
> * Any script files for the configurations. Script files must must have a .sh extension so that Tunnelblick can secure them and use them properly.

<hr>

You wrote:
> As per one of the TB online instrucions, I have tried putting a connected.sh file inside the folder:<br>
'/Library/Application Support/Tunnelblick/Users/myuid/myvpn.tblk/Contents/Resources/connected.sh'

If by "TB online instructions", you mean something on the Tunnelblick website, please post the URL so I can fix it. As I wrote above, you should never have to do anything with Tunnelblick folders directly.

**Comment by jkbullard** [comment]
@diginfo wrote:
> Also, this folder does not exist:
>
> ~/Library/Application Support/Tunnelblick/Configurations

If that folder does not exist when Tunnelblick is launched, Tunnelblick will create it.

Note that:
 * The "~" at the start of the path refers to your home directory, for example, `/Users/YOUR_USERNAME/`.)
 * Because there is a space between 'Application' and 'Support', when using the command line you must prefix the space with a backslash, e.g. `~/Library/Application\ Support/Tunnelblick/Configurations`

**Comment by diginfo** [comment]
Thanks yes I know about paths and home folders etc etc, I just copy and pasted from the console to save some time.

I really dont need help with linux / osx usage etc etc, it's specific to TB - I've been doing computers since 1978 !

**Comment by jkbullard** [comment]
But you're not seeing a folder at `~/Library/Application Support/Tunnelblick/Configurations`?

I was wrong earlier about when the folder is created. It is created (if it doesn't exist) each time Tunnelblick installer is run, not every time Tunnelblick is launched. The installer is run when Tunnelblick is installed, any configuration is installed, or when something is "secured". But unless you deleted it, it should have been created when you installed Tunnelblick.

If you've been mucking about in Tunnelblick's folders, I suggest you [completely uninstall Tunnelblick](https://tunnelblick.net/cUninstall.html) and start over.

**Comment by diginfo** [comment]
I already have many vpn connections and they all work great, all that I want to do is whenever ANY of them connect, they call a script that does port knock on one of my boxes and update a dns A record using a script that I currently call directly from the console manually.

I also created a Javascript Booklet for chrome which also works to update by dyn ip, but I am really trying to automate it as I am not at home and disconnects are very frequent.

**Comment by diginfo** [comment]
Oops:

`But you're not seeing a folder at ~/Library/Application Support/Tunnelblick/Configurations?`

Yes, that folder is there, sorrie but I have been doing this for several days now on and off and have got a little careless

That folder contains all of my vpn-xxx.tblk configs.

I have not messed or changed the folder structure (other than adding and removing Deploy for testing)

**Comment by diginfo** [comment]
OK, just managed to get a script executing, will update later when I have figured it all out.

Thanks so much for your patience.

**Comment by diginfo** [comment]
I now have an upscript that is executing in:

`'/Library/Application Support/Tunnelblick/Users/xxx/xxxxx.tblk/Contents/Resources'`

But I am unable to delete or edit it even as sudo, I have changed the file and even deleted it completely 3 times, but the original file that we created, updated and deleted over 1 hour is still being called, it seems impossible to delete this file.

Even tried quitting tunnelblick, but as soon as it restarts it restores the original, un-modified and un-deleted file.

Not having much success.

Also created a new config folder with .ovpn file and connected.sh and tried dragging them both to the icon or list of existing configs, but they wont drop, tried dropping the folder containing the files and both the files without the folder, neither will copy to the icon or existing config list, the only file it will accept is the .ovpn file on it's own.

**Comment by diginfo** [comment]
OK, critical thing is to add .tblk extension to the config folder and then import no problem.

But can I edit and exist an existing config or do I have to delete and re-add it again ?

**Comment by diginfo** [comment]
I deleted the configuration, modified my original folder and re-imported it again and it still picks up the old script file, despite the fact that I modified it after deletion, and re-imported with the new script file.

Seems that one I use a config name it cannot be re-used again, and will always pick up the original configs. from when it was initially created.

**Comment by jkbullard** [comment]
> I now have an upscript that is executing in:
> 
> '/Library/Application Support/Tunnelblick/Users/xxx/xxxxx.tblk/Contents/Resources'
>
> But I am unable to delete or edit it even as sudo, I have changed the file and even deleted it completely 3 times, but the original file that we created, updated and deleted over 1 hour is still being called, it seems impossible to delete this file.
>
> Even tried quitting tunnelblick, but as soon as it restarts it restores the original, un-modified and un-deleted file.

### To repeat: DO NOT FIDDLE WITH TUNNELBLICK'S FILES.

Do not access them, do not assume your scripts execute in a particular place, etc., etc.

> OK, critical thing is to add .tblk extension to the config folder and then import no problem.

In other words, follow the [instructions I gave earlier and which appear in our documentation](https://github.com/Tunnelblick/Tunnelblick/issues/634#issuecomment-653291237).


> But can I edit and exist an existing config… ?

You cannot fiddle with the files inside a .tblk. _(Well, you can, but as you've seen, it doesn't work.)_

You can edit an existing OpenVPN configuration file:
 1. Click to select a configuration in the list on the left side of the "Configurations" tab of Tunnelblick's "VPN Details" window.
 1. Click the little "gear" icon at the bottom of the list, then click on "Edit OpenVPN Configuration File…".

The file will open in TextEdit. Make changes and save the file (you may close the editing window but need not do so).

The next time you try to connect the configuration, Tunnelblick will ask for authorization from a computer administrator so it can secure the configuration. After it has been secured you should be able to connect it.


> or do I have to delete and re-add it again ?

You can just reinstall a modified version of the .tblk, you don't need to delete the original first. If it has the same name, the old version will be updated. Or if it has a different name but both the original and the modified version include Info.plist files with the same bundle identifier, the modified version will replace the original.

**Comment by diginfo** [comment]
You can edit an existing OpenVPN configuration file: Click to select a configuration in the list on the left side of the "Configurations" tab of Tunnelblick's "VPN Details" window.

Thanks, yes I know that, I mean I cannot change the script file that was imported together with the .ovpn file, I know how to edit the vpn config using tunnelblick, I have been using tunnelblick for  several years.

My problems are 100% related to calling and modifying scripts.

My only goal here is to call a script file located in my /Users/myname/scripts/ folder and then do some port knocking and A record DNS updates, those scripts (and dozens of others) all work 100% of the time every time what I call them using cron or via. the console etc etc etc.

Spent about 6 hours on and off today on this, probably wont persist much longer and will revert to timed cron jobs and manual script executions.

Thanks for helping though, I do appreciate it.

**Comment by diginfo** [comment]
So I created a up-suffix.sh file and imported it together with the .ovpn in a folder with extension .tblk and dropeed it on the icon. That worked and the script only echos out to stdout so I can at least be sure it is being called and it is echoing so it's being called.


Then I need to edit this script file so it makes my actual script calls, instead of just sending debug echos, and that's what I cannot do. Once that script file was created and added together with the .ovpn file and dropped onto the icon, there seems to be no way at all of changing the SCRIPT (not the .conf file)

**Comment by jkbullard** [comment]
I'm sorry you're spending so much time on something that is actually very easy. It would help if you read the documentation and followed the instructions on our website : )

> Then I need to edit this script file so it makes my actual script calls, instead of just sending debug echos, and that's what I cannot do. Once that script file was created and added together with the .ovpn file and dropped onto the icon, there seems to be no way at all of changing the SCRIPT (not the .conf file)

That is exactly correct. Don't try to edit **TUNNELBLICK'S COPY OF THE SCRIPT FILE**. _(That's an example of what I said you should not do: fiddle with Tunnelblick's folders.)_

You should edit **THE SCRIPT YOU CREATED** by following [the instructions above](https://github.com/Tunnelblick/Tunnelblick/issues/634#issuecomment-653291237). That is, edit the script file that is inside of the .tblk on your Desktop (or wherever you created it).

Then reinstall the .tblk (as I wrote earlier earlier):

> You can just reinstall a modified version of the .tblk, you don't need to delete the original first. If it has the same name, the old version will be updated. Or if it has a different name but both the original and the modified version include Info.plist files with the same bundle identifier, the modified version will replace the original.

**Comment by diginfo** [comment]
Thanks, hopefully final question, can I have every vpn config call the same single script file so that I do not have to create identical scripts, one for each connection ?

Once a connection is made by any configuration, and it's connected, then call the script ?

**Comment by jkbullard** [comment]
No, there's not a Tunnelblick mechanism to "run the script at _some path_ whenever _some specified thing happens_ to any configuration/connection".

You can include the following identical script in each .tblk:
<pre>
     #!/bin/bash
     /path/to/a/common/script/somewhere
</pre>

And you would have only one copy of the script that does all the work. Changes to that script would affect all configurations.

But, as I wrote earlier:
> For security reasons, it is a really bad idea for your script to call other scripts. Such "external" scripts will not be checked by Tunnelblick for security, and in any case they should not be used unless they are owned by root and can only be modified by root.

**Comment by pacmac** [comment]
can I use aliases in a config folder:

```
vpn.1.tblk
  - conf.ovpn
  - up-prefix.sh

vpn.2.tblk
  - conf.ovpn
  - up-prefix.sh << aliased to xvpn1.tblk/up-prefix.sh
```

**Comment by jkbullard** [comment]
I'm not sure about aliases. I don't think you can use symlinks because I think Tunnelblick would detect that as a possible symlink attack.

Try it and see.

But if it works, it's probably a bug. Tunnelblick should detect and reject it, or possibly copy the contents of the target of the symlink or alias into the up-prefix.sh of the configuration it creates when you install the configuration.

**Comment by pacmac** [comment]
No, they wont work, just confirmed that.

Anyway, thanks, I finally have a nicely organised and rebuilt config, and my port knock and dns A update are working flawlessly.

All the ip-prefix.sh scripts are copied into the site folders separately, but all call the same startup script, which although you dont like it, makes developing and enhancing my knock/dns script as simple as all my other scripts which are all located together.

I am the only user of my macbook so not concerned as I would be on a shared resource.

Thanks again.

**Comment by jkbullard** [comment]
You're welcome. I'm sorry you had such a difficult time with this.

**Comment by pacmac** [comment]
Before putting this to rest, I have a suggestion that I think would make config / re-config a bit easier.

The problem comes from the fact that my source folders that contain the ovpn.conf and script files only has an extension .tblk for it to be able to be imported.

That led to confusion over which folders were actual tunnelblick run folders and which ones were just my source folders since they both have .tblk extensions.

So my suggestion is to allow another extension (.tblc ?) which is a configuration type extension that tunnelblick would accept as a drop folder, but which was a different extension and therefore recognisable as config folders rather than run folders.

An icon could be designed for the config folders to show that it's a setting and not a run extension, I think that would be pretty good :-)
