### ISSUE TITLE
How to monitor OpenVPN to get bytecount？

### ISSUE THREAD

**Issue by shh230** [Tunnelblick/Tunnelblick#635]
How to monitor OpenVPN to get bytecount？

How to pass in port and local host (127.0.0.1) to monitor OpenVPN？

**Expected behavior**
I hope to understand how to get the return data of OpenVPN through local host and port

**Screenshots**
![image](https://user-images.githubusercontent.com/38716757/86197208-7f5cf900-bb87-11ea-9a52-4e3a1d47d9ca.png)

**Comment by jkbullard** [comment]
You would need to:
 * Read the Tunnelblick source code to see how it connects as an OpenVPN "management client" to the running instance of OpenVPN. It's complicated. Start by looking at the `hookupToRunningOpenVPNs` method in MenuController.m.

 * Create your own OpenVPN "management client". It will handle messages to and from the running instance of OpenVPN. See OpenVPN documentation for details on that.

 * Have your management client connect to the running instance of OpenVPN.

**Comment by shh230** [comment]
Thanks! I have solved this problem.
```
--management ip port [pass] : Enable a TCP server on ip:port to handle
                  management functions.  pass is a password file
                  or 'stdin' to prompt from console.
                  To listen on a unix domain socket, specific the pathname
                  in place of ip and use 'unix' as the port number.

--management-hold : Start OpenVPN in a hibernating state, until a client
                    of the management interface explicitly starts it.
```
