### ISSUE TITLE
How does OpenVPN depend on openssl in the project?

### ISSUE THREAD

**Issue by shh230** [Tunnelblick/Tunnelblick#638]
**Describe the bug**
How does OpenVPN depend on openssl in the project?

**Expected behavior**
How does OpenVPN depend on openssl in the project?

**Screenshots**
![image](https://user-images.githubusercontent.com/38716757/87636142-d3183680-c772-11ea-933e-fc594d0b0864.png)

**Additional context**
My build OpenVPN depends on the openssl in the computer, how does the OpenVPN in Tunnelblick depend on the openssl in the project?

**Comment by jkbullard** [comment]
Older versions of macOS and OS X often have out-of-date SSL commands and libraries. The commands and libraries do not include the latest ciphers. By including SSL libraries in OpenVPN, Tunnelblick allows older systems to use the latest ciphers.

Tunnelblick includes multiple versions of OpenVPN, and each version of OpenVPN may include more than one build, each one with a different SSL library. Including multiple versions of OpenVPN with different SSL libraries gives Tunnelblick the ability to connect to VPN servers that require specific versions of OpenVPN.

Tunnelblick does this by building SSL libraries (various versions of LibreSSL and OpenSSL) and then statically linking those libraries into our versions of OpenVPN.
