### ISSUE TITLE
The download is too slow, can you provide other download link?

### ISSUE THREAD

**Issue by zhangchunsheng** [Tunnelblick/Tunnelblick#642]
The download is too slow, can you provide other download link?

![image](https://user-images.githubusercontent.com/831839/92495801-f074f880-f229-11ea-990b-ee95db340e70.png)

**Comment by jkbullard** [comment]
No, sorry, you'll just have to wait. Our website links redirect to GitHub, which usually redirects to AWS.

GitHub is reporting problems with some of its assets; see [GitHub Status](https://www.githubstatus.com/).
