### ISSUE TITLE
Client disconnects

### ISSUE THREAD

**Issue by VPelmeSHko** [Tunnelblick/Tunnelblick#643]
**Describe the bug**
Client disconnects
MacOS users got disconnected but Windows and Linux users with same config can connect without any issues

client.log
[client.log](https://github.com/Tunnelblick/Tunnelblick/files/5282863/client.log)

client.ovpn
[user1.ovpn.txt](https://github.com/Tunnelblick/Tunnelblick/files/5282861/user1.ovpn.txt)

server.conf
[server.conf.txt](https://github.com/Tunnelblick/Tunnelblick/files/5282881/server.conf.txt)

**Comment by jkbullard** [comment]
1. You have set up Tunnelblick to use a very old version of OpenVPN (2.3.18) with a very old version of OpenSSL (1.0.2u). These old versions are no longer supported by OpenVPN and OpenSSL and are included in Tunnelblick only to connect to OpenVPN servers using very old versions of OpenVPN (typically that occurs in old devices such as routers). Does the problem connecting happen when you use the default version of OpenVPN (2.4.9) with OpenSSL 1.1.1?

 2. These lines:
```
2020-09-22 01:05:06.000000 /sbin/ifconfig utun4 10.8.0.6 10.8.0.6 netmask 255.255.255.0 mtu 1500 up
2020-09-22 01:05:06.000000 MANAGEMENT: Client disconnected
2020-09-22 01:05:06.000000 Mac OS X ifconfig failed: could not execute external program
```
indicate that Tunnelblick (OpenVPN's management client) was forcibly disconnected from OpenVPN after OpenVPN tried to execute an ifconfig command and failed. It's possible that either of these error messages is actually caused by the problem that the other describes, or perhaps some "security" software on your Mac forcibly disconnected Tunnelblick and/or forced the ifconfig to fail.

**Comment by VPelmeSHko** [comment]
Actually I didn't set it up, just use what tunnelblick comes with. I have more then 10 Macs with that issue, 3 weeks before Macs works well, but something happened from that time. I didn't change the server config and Windows and Linux users are able to connect to the server but not Mac

**Comment by jkbullard** [comment]
Tunnelblick does not default to use 2.3.18. It defaults to use 2.4.9. And the "client.log" shows that 2.3.18 was specified by the user.

You have Cisco kext that might be interfering with the connection. (I doubt the Google Drive kext is interfering.)

Does OpenVPN 2.4.9 help or do you get the same error?

**Comment by VPelmeSHko** [comment]
I've updated the server to OpenVPN 2.4.7 and got the same error. In same time other proprietary client successfully connects to this VPN server with same config. Removing Google Drive didn't fix the issue.

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by VPelmeSHko** [comment]
Hello, @jkbullard 
Please check attached log
[tunnelblick.log](https://github.com/Tunnelblick/Tunnelblick/files/5376293/tunnelblick.log)

**Comment by jkbullard** [comment]
@VPelmeSHko - Tunnelblick is still set up to use OpenVPN 2.3.18, which is a very old version. Does 2.4.9 help with this problem?

**Comment by VPelmeSHko** [comment]
@jkbullard I've already tested it by upgrading my OpenVPN server to 2.4.7 version and it's not fixed the issue

**Comment by jkbullard** [comment]
@VPelmeSHko You keep mentioning the server, but I doubt that's the problem and have never suggested that you do anything with the server.

For the third time, please change the version of OpenVPN that **Tunnelblick** is using.

**Comment by VPelmeSHko** [comment]
@jkbullard Can you guide me how to do that on Mac?

**Comment by jkbullard** [comment]
@VPelmeSHko - Sure:
 1. If Tunnelblick is not running, launch it.
 2. Click on the Tunnelblick icon in the menu bar. A drop-down menu will appear. Click on "VPN Details…" and the drop-down menu will disappear and a new window will open. (The window's title will vary but will end with "Tunnelblick".)
 4. Click on the large "Configurations" button at the top left of the window.
 5. Click to select the configuration that you want to change -- yours is apparently named "VPN".
 6. Click on the "Settings" tab.
 7. Click on "2.3.18 - Openssl-1.0.2u" to the right of "OpenVPN version". A menu will appear. Click on the top entry, which starts with the word "Default". The menu will disappear and the setting will have changed.

**Comment by VPelmeSHko** [comment]
Hello, @jkbullard, got the same result
[tunnelblick.2.4.9.log](https://github.com/Tunnelblick/Tunnelblick/files/5383152/tunnelblick.2.4.9.log)
