### ISSUE TITLE
An error occured fetching IP address information before connecting

### ISSUE THREAD

**Issue by jcarroll-mediafly** [Tunnelblick/Tunnelblick#645]
**Describe the bug**
I updated to 3.8.3a and whenever I attempt to connect to any of my configured vpns I see the above error. While I'm able to successfully connect I figured since it presents the warning every time I'd share to see if there is possibly a bigger issue at hand.

**To Reproduce**
1. Connect to any configured VPN you have set up
2. A new window pops up with the warning described above

**Expected behavior**
Ideally no warnings / errors occur

**Screenshots**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/19555612/95474266-8a73b200-094a-11eb-8a52-4c831f1579bd.png">

**Additional context**
I can connect to https://tunnelblick.org/ipinfo just fine. I see the IP results and everything looks normal. Some of my research of this issue I saw people had reported issues connecting to https://tunnelblick.org/ipinfo was the cause. But I seem to connect just fine.

**Diagnostic information**
Oct  8 09:27:01 Tunnelblick[580]: currentIPInfo(Name):  Response data was too long (322 bytes)
Oct  8 09:27:01 Tunnelblick[580]: An error occurred fetching IP address information before connecting
Oct  8 09:27:06 Tunnelblick[580]: Set 'expect disconnect 1 -SLibrary-SApplication Support-STunnelblick-SUsers-Sjoe-SOffice-Dtblk-SContents-SResources'
Oct  8 09:27:54 Tunnelblick[580]: Cleared 'expect disconnect 0 -SLibrary-SApplication Support-STunnelblick-SUsers-Sjoe-SOffice-Dtblk-SContents-SResources'

**Comment by jkbullard** [comment]
Thanks for reporting this. And thank you VERY MUCH for including the diagnostic info. That made it very easy to find the problem with the website.

It should be fixed now.
