### ISSUE TITLE
Failure to connect to VPN, due to update to Mac BigSur

### ISSUE THREAD

**Issue by Yanved** [Tunnelblick/Tunnelblick#651]
I am not able to connect to VPN since I updated my Mac to BigSur. 
The Support tells me to update to the latest version of Tunnelblick, but it makes no difference.
This is the failure-code:
2020-11-16 17:16:56.220674 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:5: register-dns (2.4.9)

**Comment by jkbullard** [comment]
"register-dns" is not a recognized option in OpenVPN version 2.4.9 for macOS. (I think it is a Windows-only option but am not absolutely certain of that.)

You should contact your VPN service provider for help with this issue, or post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
