### ISSUE TITLE
Tunnelblick OpenVPN connection will drop every 20-40 Minutes on m1 cpu machine

### ISSUE THREAD

**Issue by Optic00** [Tunnelblick/Tunnelblick#652]
**Describe the bug**
I got a Mac mini m1 and tunnelblick will drop the vpn connection every 20-40 minutes. The same config works for hours on another machine with the same version, same config and same Mac OS version (intel instead of m1)

**To Reproduce**
connect to vpn on Mac m1 and wait till it drops

**Diagnostic information**
2020-11-23 20:45:55.268795 event_wait : Interrupted system call (code=4)
2020-11-23 20:45:55.280918 SIGUSR1[hard,] received, process restarting

extended diagnosis doesn't give much more than this.

**Comment by Optic00** [comment]
compiled Tunnelblick 3.8.5beta01 (build 5610) with Xcode for apple/arm (switched out sparkle framework with newer with arm) and it has been running without issues for 1 hour+. Openvpn still shows running as intel binary, I am not that much of a developer so I don't know how to change that (happy enough I got it compiled).

**Comment by Optic00** [comment]
update: testing the latest beta release right now (Tunnelblick 3.8.5beta01 (build 5610)) and the tunnels has been steady for 2hours+ now. Problem seems to be stable Tunnelblick 3.8.4 & m1 cpu.
--

**Comment by jkbullard** [comment]
@Optic00 - Thank you for the updates to this issue.

It's hard to understand how there can be a difference in behavior between 3.8.4 and 3.8.5beta01. The only difference in the source code of the two versions is the two files which contain that information, and the binaries are produced by a script. There are two places where different code is executed depending on whether it is a stable version vs. a beta version: (1) setting up the "Check for updates to beta versions" checkbox, and (2) setting up the URL for automatic update checks.

Could you install the stable version again (just install on top of the beta) to see if the problem starts happening again?

**Comment by jkbullard** [comment]
@Optic00 - Upon further reflection, the main difference as I understand it is that you built your own beta version which is working, and used the pre-built binary of the stable version which is not working.

The difference is mostly in the build environment and that it is running as native ARM code.

**Comment by Optic00** [comment]
@jkbullard I first used 3.8.4 which I had problems with, than compiled 3.8.5.beta01 on arm (except for openvpn) which worked without issues, than switched to the downloaded version of 3.8.5.beta01 (intel) also no problem. I am now testing 3.8.4 again to reproduce the connection drops (same version as on my intel map).

**Comment by Optic00** [comment]
I cannot reproduce the disconnects, I have reverted back to 3.8.4 from the stable download on the website and the connection has been up for 1.5 hours and running RDP. When the disconnects happened I also had a site2site running and tested my intel mpb to cross test and I worked without a hiccup. I will leave 3.8.4 release on for now and see if I find anything else.
