### ISSUE TITLE
Hope to support M1！！！

### ISSUE THREAD

**Issue by a123993930** [Tunnelblick/Tunnelblick#656]
**Describe the bug**
M1  is not supported

**Comment by jkbullard** [comment]
Please see [Tunnleblick and Apple Silicon](https://tunnelblick.net/cAppleSilicon.html).

**Comment by johnpanos** [comment]
Is there any information on what needs to get done to support M1? I use TunnelBlick a lot and I have a M1 Mac, and was thinking about dedicating some time to seeing if I can help out.

**Comment by jkbullard** [comment]
Tunnelblick already works on an M1 under Rosetta 2 (except for the system extensions, which may never work).

To get it to run in native mode on an M1, two things need to be done:
 1. Get Tunnelblick and the third-party libraries it is static-linked to building on macOS 10.16 "Catalina" or 10.17/11.0 "Big Sur" using Xcode 12 or Xcode 13.
 2. Test the result.

We are in the process of doing # 1, and when it is complete will be asking for volunteers to do # 2 both in this issue and in the [Tunnelblick Announce](https://groups.google.com/g/tunnelblick-announce) Google Discussion Group. (That group is a low-volume group, usually fewer than one per week.)

We will be publishing a new branch for working on this in the near future and will announce it both in this Issue and in the Tunnelblick Announce group.

**Comment by jim-lake** [comment]
Got this working local, added a PR: #660

**Comment by jkbullard** [comment]
We're looking for volunteers to test new M1-compatible (we hope) kexts on M1 Macs.

The process of installing the kexts is not pleasant. For this testing, use [Kext-Droplet-Big-Sur](https://github.com/chris1111/Kext-Droplet-Big-Sur) to load the kexts, which involves three restarts of your computer, then try it out in Tunnelblick 3.8.5beta02.

Email developers@tunnelblick.net to get a link to download the new kexts. Please let us know which M1 Mac you have and what version of macOS Big Sur you will be using (for example, "11.0.1", "11.1", or "11.2 beta").

**Comment by alpercoskun** [comment]
beta 3 was a full universal binary, and it was worked well on my setup... i hope we will have an universal binary soon, let me know if you still need testing.

**Comment by djcristi** [comment]
i can also test on m1 with monterey

**Comment by jkbullard** [comment]
@djcristi - Thanks, but we finished testing a long time ago. The current stable and beta versions of Tunnelblick are universal, that is, they include both Intel and Apple Silicon binaries and there have not been any problems reported.

So I'm closing this issue.
