### ISSUE TITLE
bigsur can not use v3.8.5beta2

### ISSUE THREAD

**Issue by jianghaiyu** [Tunnelblick/Tunnelblick#657]
when macos <bigsur can use ,but bigsur can not;
2020-12-15 20:54:51.827049 Tried opening /dev/tap100 (failed): No such file or directory (errno=2)

[lots of similar or identical entries omitted]

2020-12-15 20:54:51.829402 Tried opening /dev/tap255 (failed): No such file or directory (errno=2)
2020-12-15 20:54:51.829440 MANAGEMENT: Client disconnected
2020-12-15 20:54:51.829448 Cannot allocate TUN/TAP dev dynamically
2020-12-15 20:54:51.829455 Exiting due to fatal error

this is log,this qa how to solve

**Comment by jkbullard** [comment]
Please see [Tunnelblick on macOS Big Sur](https://tunnelblick.net/cBigSur.html).

If that doesn't help, please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by tyc85** [comment]
Hi, I am facing similar issue on Big Sur with Apple M1. I tried Tunnelblick 3.8.5beta02 (build 5620). I saw the OP issue when SIP enabled on Big Sur 11.0.1. Now with SIP disabled on both 11.0.1 and 11.1: 
```
2020-12-21 01:43:49.645707 *Tunnelblick: macOS 11.1 (20C69); Tunnelblick 3.8.5beta02 (build 5620); prior version 3.8.4a (build 5601)
2020-12-21 01:43:49.955051 *Tunnelblick: Attempting connection with client using shadow copy; Set nameserver = 769; monitoring connection
2020-12-21 01:43:49.956348 *Tunnelblick: openvpnstart start client.tblk 65202 769 0 1 0 1098098 -ptADGNWradsgnw 2.4.10-openssl-1.1.1i
2020-12-21 01:44:00.067464 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
openvpnstart log:
     Failed to load 'tap-notarized.kext'; status = -603947007
     
     Failed to load 'tap-notarized.kext'; status = -603947007
     
     Failed to load 'tap-notarized.kext'; status = -603947007
     
     Failed to load 'tap-notarized.kext'; status = -603947007
     
     Failed to load 'tap-notarized.kext'; status = -603947007
     
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. (It was not loaded even though the system said it was loaded.)
```

**Comment by guihouchang** [comment]
> Hi, I am facing similar issue on Big Sur with Apple M1. I tried Tunnelblick 3.8.5beta02 (build 5620). I saw the OP issue when SIP enabled on Big Sur 11.0.1. Now with SIP disabled on both 11.0.1 and 11.1:
> 
> ```
> 2020-12-21 01:43:49.645707 *Tunnelblick: macOS 11.1 (20C69); Tunnelblick 3.8.5beta02 (build 5620); prior version 3.8.4a (build 5601)
> 2020-12-21 01:43:49.955051 *Tunnelblick: Attempting connection with client using shadow copy; Set nameserver = 769; monitoring connection
> 2020-12-21 01:43:49.956348 *Tunnelblick: openvpnstart start client.tblk 65202 769 0 1 0 1098098 -ptADGNWradsgnw 2.4.10-openssl-1.1.1i
> 2020-12-21 01:44:00.067464 *Tunnelblick: 
> 
> Could not start OpenVPN (openvpnstart returned with status #247)
> 
> Contents of the openvpnstart log:
> openvpnstart log:
>      Failed to load 'tap-notarized.kext'; status = -603947007
>      
>      Failed to load 'tap-notarized.kext'; status = -603947007
>      
>      Failed to load 'tap-notarized.kext'; status = -603947007
>      
>      Failed to load 'tap-notarized.kext'; status = -603947007
>      
>      Failed to load 'tap-notarized.kext'; status = -603947007
>      
>      Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. (It was not loaded even though the system said it was loaded.)
> ```

The same

**Comment by jkbullard** [comment]
@guihouchang  - Please see [Tunnelblick on macOS Big Sur](https://tunnelblick.net/cBigSur.html).

**Comment by guihouchang** [comment]
> @guihouchang - Please see [Tunnelblick on macOS Big Sur](https://tunnelblick.net/cBigSur.html).

I can not browse In China  [Tunnelblick on macOS Big Sur](https://tunnelblick.net/cBigSur.html). Can you tell me how to do?

**Comment by jkbullard** [comment]
@guihouchang - You cannot connect a Tap configuration with Tunnelblick on macOS Big Sur. We plan to release a version of Tunnelblick that can connect a Tap configuration on macOS Big Sur, but it will require you to do a lot of work to install the system extension that Tunnelblick needs, and I do not know when we will release such a version..

**Comment by jkbullard** [comment]
@guihouchang - You might be able to use the Tunnelblick website mirror at https://tunnelblick.github.io/

The link to the Big Sur page there is https://tunnelblick.github.io/cBigSur.html

The page about Apple Silicon Macs (MI Macs) is at https://tunnelblick.github.io/cAppleSilicon.html

You might also be interested in The Future of Tun and Tap VPNs on macOS at https://tunnelblick.github.io/cTunTapConnections.html
