### ISSUE TITLE
Authentication failed if we set the passphrase without hide it

### ISSUE THREAD

**Issue by polak785** [Tunnelblick/Tunnelblick#658]
**Describe the bug**
The authentication failed when we set the passphrase without hide it.

**To Reproduce**
1. Add the new VPN access with a protected key
2. Connect the VPN
3. It prompt to put the passphrase
4. Click on the eye icon to see the passphrase
5. Write the passphrase
6. Validate
7. The windows "Authentication failed" (username or password have not been accepted by the remote server) appears
8. Click on "Try again"
9. Click on "Delete passphrase..."
10. The passphrase is still here, click on the eye icon to hide it
11. Validate and it's work

**Expected behavior**
The authentication should not failed if we see the passphrase

**Additional context**
macOS Catalina 10.15
Tunnelblick 3.8.4

(sorry for my english)

**Comment by polak785** [comment]
Hello,

Any update on this please?

**Comment by jkbullard** [comment]
@polak785 - Thank you for asking about an update to this Issue.

I apologize - I missed the original report of the problem. I will look into it and reply back here.

**Comment by jkbullard** [comment]
@polak785 - Thanks for your patience. The fix for this will be included in the next beta release of Tunnelblick.

**Comment by polak785** [comment]
Thank you very much :+1:
