### ISSUE TITLE
How to disable warning dialog "DNS server address is not a public address"

### ISSUE THREAD

**Issue by clementyau** [Tunnelblick/Tunnelblick#662]
I am on macOS Big Sur 11.1 with Tunnelblick 3.8.4a (build 5601). Whenever I connect to VPN I get this warning dialog. How do I disable this warning? The dialog only has a single button "OK". Thanks.

"One or more possible problems with DNS were found:
DNS server address 10.0.2.1 is not a public IP address and is not being routed through the VPN."

**Comment by jkbullard** [comment]
@clementyau - Try the latest beta version of Tunnelblick. According to the [release notes](https://tunnelblick.net/cRlsNotes.html#version-3.8), it
> • Fixes a problem that hid some "'do not warn about this again' checkboxes.

**Comment by clementyau** [comment]
Thank you @jkbullard installed beta issue has been resolved.
