### ISSUE TITLE
Does Tunnelblick under test support the use of Tap VPN on Apple Silicon?

### ISSUE THREAD

**Issue by Hambaobao** [Tunnelblick/Tunnelblick#665]
I have read your instructions on the use of Tun VPN and Tap VPN on Apple Silicon. If Tap VPN will be enable after loading the system extensions with kext-droplet, I can help with testing.

**Comment by linyi-0** [comment]
可以留个联系方式吗，我使用tun到模式，连接成功了，但是我配置到地址，还是访问不了。

**Comment by Hambaobao** [comment]
> 可以留个联系方式吗，我使用tun的模式，连接成功了，但是我配置的地址还是访问不了。

I’m not very clear, because I’m using Tap VPN and it’s not working yet. You can open a new issue to report the problem to the developer with diagnostic information.

**Comment by linyi-0** [comment]
> > 可以留个联系方式吗，我使用tun的模式，连接成功了，但是我配置的地址还是访问不了。
> 
> I’m not very clear, because I’m using Tap VPN and it’s not working yet. You can open a new issue to report the problem to the developer with diagnostic information.

okay, thank you

**Comment by jkbullard** [comment]
@Hambaobao - To help with testing Tunnelblick on an Apple Silicon (M1) Mac, please see the last paragraph of [Tunnelblick and Apple Silicon](https://tunnelblick.net/cAppleSilicon.html):
> We're looking for volunteers to test new M1-compatible (we hope) system extensions (kexts) on M1 Macs. For this round of testing, you need to be comfortable using the command line and use Kext-Droplet-Big-Sur to load the kexts, which involves three restarts of your computer, then try them out in Tunnelblick 3.8.5beta02. Email developers@tunnelblick.net to get a link to download the new kexts. Please let us know which M1 Mac you have and what version of macOS Big Sur you will be using (for example, "11.0.1", "11.1", or "11.2 beta").
