### ISSUE TITLE
Don't ask username and password

### ISSUE THREAD

**Issue by JekaScouser** [Tunnelblick/Tunnelblick#671]
Don't ask username and password. 
Config file have auth-user-pass

Tunnelblick 3.8.5beta05 (build 5650)
Big Sur 11.2.3, Apple M1

**Comment by jkbullard** [comment]
`auth-user-pass` _without anything else_ tells OpenVPN to ask Tunnelblick to ask the user for the username/password.

If your configuration files has an `auth-user-pass` option that specifies a file containing a username and password and it is set up properly, Tunnelblick will not ask for the username and password.

But it must be set up properly:
 * The filename must have an extension of ".key" (so Tunnelblick will secure it properly).
 * The OpenVPN configuration file must contain a line with "`auth-user-pass` _filename_", where _filename_ is the name of the file, including the .key extension.
 * The file must be contained within a "Tunnelblick VPN Configuration" (.tblk).
 * The .tblk must be installed by dragging/dropping.

Simple instructions for doing this for most configurations are:

1. Create a new, empty folder on your Desktop (leave the name as "untitled folder")
2. Copy your OpenVPN configuration file into the folder.
3. Rename the OpenVPN configuration file in the folder to have a ".ovpn" extension if it doesn't already have one.
3. Edit the OpenVPN configuration file in the folder to include a line containing "`auth-user-pass username_password.key`".
3. Copy your username/password file into the folder.
4. Rename the username/password file to "username_password.key".
5. Copy any other files needed by the configuration into the folder. (For example, certificate and key files and scripts. Be sure the filenames have the standard ".crt", ".key", or ".sh" extensions.)
6. Rename the folder to be _NAME_.tblk, where _NAME_ is the name you want the configuration to have.
7. Drag/drop  _NAME_.tblk onto the Tunnelblick icon in the menu bar to install the configuration.

For more details, see [Tunnelblick VPN Configurations](https://tunnelblick.net/cConfigT.html), [Tunnelblick VPN Configurations Details](https://tunnelblick.net/cPkgs.html), and the [OpenVPN man page](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/).

**Comment by JekaScouser** [comment]
auth-user-pass without anything else tells OpenVPN to ask Tunnelblick to ask the user for the username/password.
It's not working. Tunnelblick don't ask username and password. Config file have auth-user-pass. OpenVPN on android and ios devices working correctly with this config file

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at Read Before You Post (https://tunnelblick.net/cBeforeYouPost.html).
