### ISSUE TITLE
3.8.6beta02 (build 5690) can't connect with credentials in keychain

### ISSUE THREAD

**Issue by cpm1** [Tunnelblick/Tunnelblick#679]
**Describe the bug**
After updating to 3.8.6beta02 (build 5690) I can't connect to our company VPN anymore. Up to beta01 everything worked perfect. It seems as beta02 can't find the user/password in the keychain anymore for whatever reason and waits forever. Deleting the credentials from the keychain lets beta02 ask for them and - after providing them - connect perfectly. Next time, if credentials were saved to the keychain, it waits again ad infinitum for the credentials. Connection always succeeds with manually provided credentials.

**To Reproduce**
1) Click Connect with credentials in keychain
2) "Waiting for password"
3) Nothing happens even after minutes of waiting
4) Click disconenct
5) See error in log

Remove credentials from keychain.

1) Click connect
2) Provide credentials, tick "save in keychain" for user and password
3) Observe successful connection
4) Disconnect
5) Click connect again
6) Watch "Waiting for password" status ad infinitum ...

**Expected behavior**
Successful connection to VPN with credentials stored in keychain

**Diagnostic information**
[tunnelblick.log](https://github.com/Tunnelblick/Tunnelblick/files/6356850/tunnelblick.log)

**Comment by cpm1** [comment]
Addendum: it seems only fetching the password from keychain is an issue. With saved username and *manually* provided password, connection is established successfully.

**Comment by Vladx71** [comment]
same here since the last MacOS update

**Comment by jkbullard** [comment]
Thanks for your report. Please try Tunnelblick 3.8.5a and report back whether or not that works.

**Comment by winkelement** [comment]
I'm having the same issue.

This is what is logged for keychain access when trying to connect when only the username was saved in the keychain (works, i'm asked for password):
![tblck_username_only](https://user-images.githubusercontent.com/3525191/115708191-f8744980-a36f-11eb-9a09-f7d8c4ec319e.png)
This is what is logged for keychain access when trying to connect when username _and_ password were saved in the keychain (don't work, "Waiting for password"):
![tblck_username_password](https://user-images.githubusercontent.com/3525191/115708219-0033ee00-a370-11eb-9ff9-e0b1284138a0.png)

Seems to me the password is not read from the keychain (although it is there, i have 2 entries, one for username, one for password).

**Comment by jkbullard** [comment]
@Vladx71 , @winkelement , and all others with this problem:
 * Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html), just as @cpm1 did. (It is best to attach the log, rather than posting it inline.)
 * Please report whether or not Tunnelblick 3.8.5a fixes the problem.

**Comment by machedberg** [comment]
I reinstalled Tunnelblick 3.8.5a and now it works again

**Comment by cpm1** [comment]
Confirmed, 3.8.5a works as expected.

**Comment by Jiriteach** [comment]
I have experienced this on 3.8.6b02 as well. Working fine in 3.8.6b01.

**Comment by jkbullard** [comment]
This problem should be fixed via 236355d655a5bbb51936efcf3f6304abcb9369ac, which is included in Tunnelblick 3.8.6beta03, available via update on the "Preferences" panel. (Put a check in "Check fro updates to beta versions", then click the "Check Now" button.)

**Comment by cpm1** [comment]
Confirmed, 3.8.6beta03 is working as expected again. Thank you!
