### ISSUE TITLE
Existing local DNS server is erronously routed over the VPN

### ISSUE THREAD

**Issue by rawtaz** [Tunnelblick/Tunnelblick#681]
**Describe the bug**

Consider the following simple setup:
- Client gets LAN IP address 192.168.0.100 from DHCP.
- Local network is 192.168.0.0/24, router at 192.168.0.1.
- Client gets DNS server 192.168.176.251 from DHCP.

Then the client connects to an OpenVPN server as per the following:
- Client gets 192.168.2.100 on the VPN.
- VPN server tells client that it should route networks 192.168.0.0/16 over the VPN.
- Client adds a route for 192.168.0.0/16 through the VPN gateway accordingly.
- Client also adds a route for its LAN router at 192.168.0.1/32 directly through its LAN interface.

All is well, except the problem that the client's DNS servers aren't reachable, because it routes to them over the VPN, but they are not behind the VPN. Instead the client's DNS servers are reachable directly through the LAN router.

**To Reproduce**
I believe the above summary explains the setup needed to reproduce the problem. This is on macOS 10.14.6 with Tunnelblick 3.8.5a (build 5671).

**Expected behavior**
The client should route requests for the DNS server 192.168.176.251 through its LAN router 192.168.0.1 instead of through the VPN, *because the DNS server was present before the VPN was brought up and should therefore be considered part of the things that need to be explicitly routed outside of the VPN*.

**Screenshots**
N/A

**Additional context**
As mentioned above, the fact that the DNS server, even though it's not part of the LAN, is such a core piece of the network configuration and its setting was present before the VPN was brought up, makes it a candidate for explicit routing outside of the VPN (the process that's done for the purpose of keeping the basic network connectivity working).

It would be different if the VPN server told the client to route *all* traffic through the VPN, or the VPN client had such a setting itself. But in this case it's obvious that the already existing DNS server configuration should not be routed over the VPN.

**Diagnostic information**
N/A, but let me know if there's anything you need!

**Comment by jkbullard** [comment]
I'm closing this because the example setup that was given does not set up OpenVPN properly for the situation.

OpenVPN allows complete control over what DNS is used, Tunnelblick does whatever OpenVPN tells it to, and OpenVPN does whatever the client configuration and the server tells it to do. So whoever sets up the VPN controls what should be done with DNS.

The most common way to controls DNS when the VPN is active is by using OpenVPN's `--dhcp-option` on the [OpenVPN man page](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage).

**Comment by rawtaz** [comment]
@jkbullard If OpenVPN just does what the client and server says, then how come it adds an explicit route for the LAN router so it doesn't go over the VPN? This shows that there has to be some exceptions to "just doing what you're told", simply because otherwise nothing would work.

The VPN or the VPN server does not know about and should not know about or be concerned about what LAN infrastructure the client has, so the suggestion to use `--dhcp-option` is not applicable.

**Comment by TinCanTech** [comment]
@rawtaz Who-ever is responsible for your VPN, set it up incorrectly. If you require an explicit route for your DNS then you add it.  The same problem would occur using Openvpn, so this has nothing todo with Tunnelblick.

**Comment by jkbullard** [comment]
The VPN setup you are trying to create is not secure, so there is no reason to have it happen by default.

It is not secure because it doesn't protect DNS queries from interception and/or spoofing.

The only way to secure DNS is to route DNS queries through the VPN server itself. It isn't even sufficient to route them through a DNS server which is on the VPN's LAN, because of cache poisoning attacks.

**Comment by rawtaz** [comment]
@TinCanTech In what way is it setup incorrectly? Again, the VPN provider has no idea if the client is on 192.168.x or 10.x or any other internal network. So how should the configure this differently to do it properly?

**Comment by rawtaz** [comment]
@jkbullard We're not talking about security here though :) That's a different topic. What we're discussing here is brining the VPN up in a way that doesn't stop the local network from working (as mentioned before, the settings for the VPN are not to route everything over the VPN, so it's expected that networks other than what's behind the VPN should still be handled locally, and in that contexts local gateways/routers and also DNS servers which are both required for the basic network infrastructure to work should of course have precedence over routes presented by the VPN server).

**Comment by TinCanTech** [comment]
@rawtaz This is not the place to discuss your problem. You can contact me privately tincantech <at> protonmail dot com -- Or take the question to the openvpn-users mailing list.

@jkbullard If you want to delete this comment then I do understand.

**Comment by jkbullard** [comment]
@rawtaz - I'm _always_ talking about security.

**Comment by rawtaz** [comment]
@jkbullard That's great, but the security aspects of how to use a VPN is not what this topic is about. This VPN is simply not meant to provide DNS for the user, nor is it meant to be used for encrypting the client's communication out on the Internet. It's sole purpose is providing access to some services on a remote network, and that's different from the security aspect you are so rightfully concerned about in general.

I guess you are simply not interested in hearing more about this, so what point is there to continue the discussion.
