### ISSUE TITLE
Tunnelblick 3.8.5a not working on M1

### ISSUE THREAD

**Issue by stefanalexandru02** [Tunnelblick/Tunnelblick#682]
I've tried to install both the Tunnelblick 3.8.5a and 3.8.6beta03 from the website on an M1 mac but the package only seems to contain an intel executable as the app never runs natively (checking in Activity Monitor the Tunnelblick apps is still running under Rosetta).

Where could I download a universal M1 binary for Tunnelblick?

**Comment by jkbullard** [comment]
Current versions of Tunnelblick are "mixed": the Tunnelblick application itself is an Intel-only binary that must be run under Rosetta on M1 Macs. The OpenVPN binaries that Tunnelblick contains and uses to establish VPN connections, however, are universal and run natively on either M1 or Intel Macs.

**Comment by jkbullard** [comment]
Tunnelblick 3.8.6a and 3.8.7beta02 are Universal; everything runs as native code on Intel and M1 processors.
