### ISSUE TITLE
Tunnelblick option to activate when computer starts 

### ISSUE THREAD

**Issue by iradization** [Tunnelblick/Tunnelblick#683]
I've read about the option to auto-connect when computer starts. meaning that the VPN will be up and running even before user was already logged-in. The option is relevant for my needs since it enable me to have access to my LDAP server when login with domain based account, and the LDAP server should also be accessible through the VPN. 

However, i wanted to know more about how it's done... I guess that the openVPN can run as launchDaemon so it doesn't need user context.. but how does the credentials are provided in this case ? are they kept inside the keychain ? and if yes, so which one (i guess it's not login keychain as it belongs to each user). 

Thanks !

**Comment by jkbullard** [comment]
The credentials must be provided via an OpenVPN mechanism such as its `--auth-user-pass` option, which can provide the username and password in a file. The file should have an extension of ".key" so Tunnelblick will know how it should be secured when included in a Tunnelblick VPN Configuration.

Note that only "shared" (not "private") configurations may be set to connect when the computer starts.

**Comment by iradization** [comment]
I see, so in order to authenticate against the openVPN GW on user-less mode, one should provide a file that includes the user credentials in order to login with ".key" suffix so it'll be securely treated, but it's still a plain text from what I understand... Perhaps I can set the privileges and prevent read permission from privileged users/processes or maybe I can encrypt the file os that only openVPN client have the key ?

and what if I eventually login with different user than what is written in the password file, does openVPN know how to switch users seamlessly ?

**Comment by jkbullard** [comment]
1. Tunnelblick takes care of the permissions on its files., including .key files, to make sure they are only readable by appropriate processes.
2. If you encrypt the file, OpenVPN will no be able to read it.
3. What switch of users is necessary? Are you saying that user A must log in using a different VPN connection than user B? Why is the identity of the logged-in user tied to the identity of the OpenVPN credentials used to access the LDAP server?

**Comment by iradization** [comment]
Hi, 

regarding comment No. 3, I thought that it's wise to couple between the logged-in user and the VPN provided credentials. This will able the IT to control user traffic from the vpn gateway, in terms of user monitoring, auditing and access management to organizational services.

**Comment by jkbullard** [comment]
You could have a login script which disconnects the original VPN (which was started when the computer starts) and connects the user's VPN, and a logout script which disconnects the user's VPN and connects the original VPN. (While a user is logged in, you can connect/disconnect VPNs using Tunnelblick, which can be scripted with AppleScript. See [AppleScript Support](https://tunnelblick.net/cAppleScriptSupport.html) for details.)

Another (better?) solution would be to have the login mechanism tell your network infrastructure the user's identity. Your network infrastructure can then do the appropriate monitoring, auditing, and access management. So you just have the one VPN (which could, if you want, be one VPN per client computer).

**Comment by iradization** [comment]
Hmmm... your last proposal sounds very interesting as doesn't require switching VPNs accounts. I've read about the authorizationRight of loginwindow one can see the stages by reading from `system.login.console`. The mechanism that ask the user to provide credentials should be  `loginwindow:login`... so what i need is modify the list of mechanisms and add another mechanism that intercept the credentials and use them to auto login to my VPN service... but this should be done prior to the local authentication using those credentials (since it'll require active-directory that can only be accessible through the vpn). Do you think this approach can work ?

**Comment by jkbullard** [comment]
That doesn't have much to do with Tunnelblick, so I think you should ask OpenVPN experts about how to do what you want. You can find some link to OpenVPN resources at [https://tunnelblick.net/support.html](https://tunnelblick.net/support.html)
