### ISSUE TITLE
Tunnelblick and WARP issue

### ISSUE THREAD

**Issue by freeball155** [Tunnelblick/Tunnelblick#691]
Hello.

Tunnelblick does not work if WARP (Cloudflare VPN) was used before. Tunnelblick hangs up in "waiting for daemon process" state. Restarting the Tunnelblick, disabling the WARP does not help. Only rebooting the computer helps. 

I'm not sure when it started, but it worked fine for a while. I could use WARP, then Tunnelblick, or vice versa, in any sequence and combination.

MacOS 11.5 (11.4 has the same problem)
Tunnelblick 3.8.5a (build 5671)
WARP 1.5.463.0

Log:
2021-07-27 11:13:37.187228 *Tunnelblick: macOS 11.5 (20G71); Tunnelblick 3.8.5a (build 5671); prior version 3.8.5 (build 5670)
2021-07-27 11:13:37.509091 *Tunnelblick: Attempting connection with ZZZ using shadow copy; Set nameserver = 769; monitoring connection
2021-07-27 11:13:37.510154 *Tunnelblick: openvpnstart start ZZZ.tblk 49710 769 0 1 0 34652464 -ptADGNWradsgnw 2.4.11-openssl-1.1.1k
2021-07-27 11:13:38.139531 *Tunnelblick: openvpnstart log:
     OpenVPN started successfully.
     Command used to start OpenVPN (one argument per displayed line):
          /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.4.11-openssl-1.1.1k/openvpn
          --daemon
          --log /Library/Application Support/Tunnelblick/Logs/-SUsers-Ssb-SLibrary-SApplication Support-STunnelblick-SConfigurations-SZZZ.tblk-SContents-SResources-Sconfig.ovpn.769_0_1_0_34652464.49710.openvpn.log
          --cd /Library/Application Support/Tunnelblick/Users/sb/ZZZ.tblk/Contents/Resources
          --machine-readable-output
          --setenv IV_GUI_VER "net.tunnelblick.tunnelblick 5671 3.8.5a (build 5671)"
          --verb 3
          --config /Library/Application Support/Tunnelblick/Users/sb/ZZZ.tblk/Contents/Resources/config.ovpn
          --setenv TUNNELBLICK_CONFIG_FOLDER /Library/Application Support/Tunnelblick/Users/sb/ZZZ.tblk/Contents/Resources
          --verb 3
          --cd /Library/Application Support/Tunnelblick/Users/sb/ZZZ.tblk/Contents/Resources
          --management 127.0.0.1 49710 /Library/Application Support/Tunnelblick/bhpbilpemolghgnkhhkkldlodgaaljhinnlebnac.mip
          --management-query-passwords
          --management-hold
          --script-security 2
          --route-up /Applications/Tunnelblick.app/Contents/Resources/client.up.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw
          --down /Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh -9 -d -f -m -w -ptADGNWradsgnw

Screenshot:
<img width="284" alt="Screenshot 2021-07-27 at 11 14 01" src="https://user-images.githubusercontent.com/4979885/127120377-2d084aed-fa40-4fb2-aa04-a0a49219ef82.png">

**Comment by jkbullard** [comment]
Thanks for your report. Please post the Tunnelblick "Diagnostic Info" as obtained by the procedure described in [Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by freeball155** [comment]
Thanks you for your reply.
Sorry, I didn't know about this procedure.
I will attach two "Diagnostic Info" files. The "normal" was collected after successful connection. The "fail" is for the same connection profile, but before it I started and stoped the WARP.
[normal_diag_info.txt](https://github.com/Tunnelblick/Tunnelblick/files/6885074/normal_diag_info.txt)
[fail_diag_info.txt](https://github.com/Tunnelblick/Tunnelblick/files/6885075/fail_diag_info.txt)

**Comment by jkbullard** [comment]
Thanks. Tunnelblick is unable to communicate with the instance of OpenVPN that it created to run the VPN. The only thing I can think of is that WARP is not cleaning up after itself completely, and is leaving something around that is interfering with the communication.

**Comment by vveider** [comment]
Confirming the problem.
Is there any workaround?

**Comment by freeball155** [comment]
> Confirming the problem.
> Is there any workaround?

No.
I reported the problem to Cloudflare via "Send feedback" (ID 207018, but I have no idea where to look at it). There was no answer.

**Comment by vveider** [comment]
Tried everything but only restart help :(

**Comment by nguyenthetoan** [comment]
try this command `sudo ifconfig lo0 -alias 192.0.2.2` 
ref: https://apple.stackexchange.com/a/426159

**Comment by freeball155** [comment]
> try this command `sudo ifconfig lo0 -alias 192.0.2.2`
> ref: https://apple.stackexchange.com/a/426159

This is it. Thanks.
I have sent another feedback to the Cloudflare with this link. Maybe someday they will fix it.

**Comment by debrunet** [comment]
This issue has been fixed in Cloudflare WARP version 1.6.27.0, released today.
