### ISSUE TITLE
Can't connect in Big Sur 11.5.1

### ISSUE THREAD

**Issue by tkasci** [Tunnelblick/Tunnelblick#692]
**Describe the bug**
After updating to Big Sur 11.5.1, I can't connect using my usual VPN profile. Before the update, it worked. Normally, I would have to enable the system extension in the system's safety settings, but the button does not show up. Attempting to connect repeatedly does not help. Removing and reinstalling the profile didn't help. I also tried to uninstall and reinstall Tunnelblick, but the error persists. 

**To Reproduce**
Connect using the profile shown in the attachment. Can't be reproduced externally as you need an account.

**Expected behavior**
Tunnelblick connects to the VPN normally. 

**Diagnostic information**

Log:
```
2021-08-10 08:26:05.957020 *Tunnelblick: macOS 11.5.1 (20G80); Tunnelblick 3.8.6beta05 (build 5706); prior version 3.8.6beta03 (build 5700)
2021-08-10 08:26:06.414294 *Tunnelblick: Attempting connection with vpn-profile-uni-greifswald using shadow copy; Set nameserver = 769; monitoring connection
2021-08-10 08:26:06.414940 *Tunnelblick: openvpnstart start vpn-profile-uni-greifswald.tblk 52865 769 0 1 0 34652530 -ptADGNWradsgnw 2.5.3-openssl-1.1.1k
2021-08-10 08:26:06.463930 *Tunnelblick: openvpnstart starting OpenVPN
2021-08-10 08:26:26.524263 *Tunnelblick: 

Could not start OpenVPN (openvpnstart returned with status #247)

Contents of the openvpnstart log:
openvpnstart log:
     Failed to load the tap kext; status = -603946989
     
     Failed to load the tap kext; status = -603946989
     
     Failed to load the tap kext; status = -603946989
     
     Failed to load the tap kext; status = -603946989
     
     Failed to load the tap kext; status = -603946989
     
     Unable to load net.tunnelblick.tun and/or net.tunnelblick.tap kexts in 5 tries. (It was not loaded even though the system said it was loaded.)
```

VPN profile:
```

client
dev              tap
proto            udp
persist-tun
remote           vpn.uni-greifswald.de
nobind
persist-key
verify-x509-name vpn.uni-greifswald.de name
ca               T-Telesec-GlobalRoot-Class2.pem
cipher           AES-256-CBC
auth             SHA256
auth-user-pass
compress         lzo

```

**Comment by jkbullard** [comment]
Please see [Installing System Extensions](https://tunnelblick.net/cKextsInstallation.html).

If you need further help, please post the diagnostic info produced by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
