### ISSUE TITLE
Check IP Change setting gone - after no ip change was detected

### ISSUE THREAD

**Issue by frankofno** [Tunnelblick/Tunnelblick#693]
Tunnelblick 3.8.5a (build 5671)
macOS 10.15.7

Connecting to a server with the setting
"Check if the apparent public IP address changed after connecting"
and there is no IP change detected, the setting / check mark is disabled. So no more IP change check after the 1st time.
The setting should not be changed, after it successfully encountered no IP change.

Screenshot:

![Screenshot 2021-08-18 at 03 10 36](https://user-images.githubusercontent.com/35775329/129820727-1db2a129-e4bd-4258-b5b3-099b70df5c85.png)

**Comment by jkbullard** [comment]
Usually an IP change is a function of the configuration and what the server "pushes" to the client computer, so if it changes five times, that's good evidence that it will continue to happen.

To lighten the load on the tunnelblick.com server, Tunnelblick pops up a window warning that it is disabling the check after successfully detecting an IP change the last five times a configuration was connected. You can re-enable the check manually if you want to keep checking.
