### ISSUE TITLE
Settings are all readonly (disabled) after dropping first .ovpn file

### ISSUE THREAD

**Issue by aaronclawrence** [Tunnelblick/Tunnelblick#695]
**Describe the bug**

**To Reproduce**
1. Install a fresh copy of Tunnelblick 3.8.5a (build 5671) - OR - delete all configurations
2. Drag and drop a .ovpn file into the configurations window
3. Click on the settings tab
4. All the settings controls are disabled and can't be changed.

Workaround: Quit Tunnelblick and restart. Settings can then be changed.

**Expected behavior**
The settings are available for editing immediately after dropping the .ovpn file.

**Screenshots**
![image](https://user-images.githubusercontent.com/19336313/130530228-c5f7a2dd-bc78-4b51-b1b9-50b074b5b151.png)

**Diagnostic information**
Not really relevant as this is just a GUI issue

macOS Catalina on MacBook Pro mid 2012

**Comment by jkbullard** [comment]
Thanks.

This was fixed in 9e7d5b94f6e2f81381ce2b9dcd2b4e9d860373de, as noted at [this discussion](https://groups.google.com/g/tunnelblick-discuss/c/Ublp5-E7AlE).

**Comment by aaronclawrence** [comment]
Nice, thank you.
