### ISSUE TITLE
install on macOS11.5.2 failed

### ISSUE THREAD

**Issue by 1797890817** [Tunnelblick/Tunnelblick#696]
**Describe the bug**
Installed using Tunnelblick_3.8.6beta06_build_5707.dmg, but failed！

**To Reproduce**
1. Experience in mounting dmg;
2. Follow the prompts to double-click the icon to install.

**Expected behavior**
Looking forward to normal installation

**Screenshots**
![截图](https://user-images.githubusercontent.com/22413874/130555214-42c3107c-d434-4c16-8794-ec71fc773702.png)

**Desktop (please complete the following information):**
 - OS: [macOS 11.5.2 intel CPU]

**Comment by jkbullard** [comment]
Your /Applications folder has an incorrect owner. It should be owned by "root:admin" (0:80) but your owner is yourself (501: I don't know).

You can correct it in Terminal as described in  [System Folder Security](https://tunnelblick.net/cSystemFolderNotSecure.html).

**Comment by 1797890817** [comment]
Thank you, it has been solved!
