### ISSUE TITLE
How to excute this program?

### ISSUE THREAD

**Issue by robotcll** [Tunnelblick/Tunnelblick#697]
I can't find any dmg or excutive files in the zip file.

**Comment by jkbullard** [comment]
This GitHub site's main purpose is to distribute the Tunnelblick source code.

Most people download a .dmg from [Tunnelblick's official website](https://tunnelblick.net).

You'll also find documentation and troubleshooting help there. I recommend that you start by reading [What is Tunnelblick?](https://tunnelblick.net/cWhatIs.html) and [What Else You Need](https://tunnelblick.net/cWhatElse.html).
