### ISSUE TITLE
vpn is connected, but ping is faild.

### ISSUE THREAD

**Issue by zw-zhuangwei** [Tunnelblick/Tunnelblick#699]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zw-zhuangwei** [comment]
vpn可以正常连接的
![image](https://user-images.githubusercontent.com/21988339/134489975-4a75ece9-5c0e-4136-ba7f-12026a51638e.png)
但是ping不通
![image](https://user-images.githubusercontent.com/21988339/134490086-8b05e692-c28d-46a3-82f8-e9772cb98ab5.png)

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).
