### ISSUE TITLE
once reboot I must reinstall tuntap kernel extension

### ISSUE THREAD

**Issue by Oliver0624** [Tunnelblick/Tunnelblick#703]
**Description**
When I restart my mac, the tuntap kernel extension must be reinstalled, or my n2n program cannot open the tap device.

**To Reproduce**
1. reboot
2. execute edge under the terminal.
3. its logs show that it cannot open tap device /dev/tap1 through /dev/tap254

**Logs**
```
root@LC-MacBook-Air n2n-origin-edge # ./edge -c lc -I id-10 -l 118.1
95.196.98:7654 -vvvv -f
29/Oct/2021 14:24:47 [edge_utils.c:3840] adding supernode = 118.195.196.98:7654
29/Oct/2021 14:24:47 [edge.c:1073] starting n2n edge 2.9.0.r1.86c16be Oct 29 2021 10:56:50
29/Oct/2021 14:24:47 [edge.c:1079] using compression: none.
29/Oct/2021 14:24:47 [edge.c:1080] using null cipher.
29/Oct/2021 14:24:47 [edge_utils.c:351] number of supernodes in the list: 1
29/Oct/2021 14:24:47 [edge_utils.c:353] supernode 0 => 118.195.196.98:7654
29/Oct/2021 14:24:47 [edge_utils.c:426] WARNING: encryption is disabled in edge
29/Oct/2021 14:24:47 [edge_utils.c:442] successfully created resolver thread
29/Oct/2021 14:24:47 [edge.c:1112] domain socket is 5.
29/Oct/2021 14:24:47 [edge.c:1153] automatically assign IP address by supernode
29/Oct/2021 14:24:47 [edge.c:1165] skip PING to supernode
29/Oct/2021 14:24:47 [edge_utils.c:1308] send REGISTER_SUPER to [118.195.196.98:7654]
29/Oct/2021 14:24:47 [edge_utils.c:998] try send 81 bytes to en/decrypt process.
29/Oct/2021 14:24:47 [edge_utils.c:1052] sent=99
29/Oct/2021 14:24:47 [edge.c:1225] send REGISTER_SUPER to supernode [118.195.196.98:7654] asking for IP address
29/Oct/2021 14:24:48 [edge_utils.c:3018] ========> read 66 bytes from domain socket ======
29/Oct/2021 14:24:48 [edge_utils.c:2452] Rx N2N_UDP of size 50 from [118.195.196.98:7654]
29/Oct/2021 14:24:48 [edge_utils.c:2701] Rx REGISTER_SUPER_ACK from 00:00:00:00:00:00 [118.195.196.98:7654] (external 113.110.247.144:47799) with 3 attempts left
29/Oct/2021 14:24:48 [edge.c:1236] received REGISTER_SUPER_ACK from supernode for IP address asignment
29/Oct/2021 14:24:48 [tuntap_osx.c:54] ERROR: Unable to open any tap devices /dev/tap0 through /dev/tap254. Is this user properly authorized to access those descriptors?
29/Oct/2021 14:24:48 [tuntap_osx.c:55] ERROR: Please read https://github.com/ntop/n2n/blob/dev/doc/Building.md
```

**Hardware**
 MacBook Air 2020 (M1)

**OS Version**
 macOS 12.0.1 Monterey

**Comment by jkbullard** [comment]
Note: The problem a user reported in the [separate discussion](https://groups.google.com/u/1/g/tunnelblick-discuss/c/liIaSq9c81w) which I [referred to above](https://github.com/Tunnelblick/Tunnelblick/issues/703#issuecomment-954645676) is in fact a bug in Tunnelblick, not macOS. The bug will be fixed in the next release of Tunnelblick.

**Comment by jkbullard** [comment]
@Oliver0624 - You may be able to use Tunnelblick 3.8.5a, which doesn't have the problem described in the discussion noted above.

**Comment by jkbullard** [comment]
Tunnelblick 3.8.7beta03, which was just released, may fix this problem. Use it to uninstall and then re-install the kexts.

**Comment by bytegetter** [comment]
I have the same issue on a M1 Mac Mini. No Problem with a Intel Macbook Pro. Both running Big sure.

**Comment by jkbullard** [comment]
@bytegetter - What version of Big Sur is running on the Mac mini? Have you installed the kexts using the [Instructions](https://tunnelblick.net/cKextsInstallation.html#m1-big-sur)?

**Comment by bytegetter** [comment]
@jkbullard Big Sur 11.6.1, not upgraded to Montery du incompatibility of starface (VoIP). 

I´ve used the instructions for the first install. 

Now, after every reboot, I need to remove and reinstall the tuntap-Device to use it (I use it for tinc).

I´m owning a unused Macbook M1 13". I´ve you want I can try this on this Machine.

A Intel-based virtualized Bug Sur did work.

**Comment by jkbullard** [comment]
I believe you, but it didn't/doesn't happen to me on my M1s running 11.6.1 or 12.0.1, so there's not much I can do to find or fix this problem.

But you might look at old posts here and in the [Tunnelblick Discussion Group](https://groups.google.com/g/tunnelblick-discuss) about problems loading kexts when Catalina (or maybe Big Sur?) first came out. There's some kind of macOS system database that can get messed up and clearing it solves some of these kinds of problems.

**Comment by jkbullard** [comment]
If you're not using Tunnelblick at all, maybe you need to LOAD the kexts before you use tinc, not INSTALL them. Installing is a one-time thing; loading must be done each time you need to use them. (Installing also loads them.)

Tunnelblick loads them automatically each time it connects a configuration that needs them, and unloads them after disconnecting the configuration.

I haven't tried the following commands, but they should work:

To LOAD the kexts via command line (sudo not required but the kexts must already be installed):
     /Applications/Tunnelblick.app/Contents/Resources/openvpnstart loadKexts BITMASK
where BITMASK is 1 to load the TUN kext, 2 to load the TAP kext, or 3 to load both

To UNLOAD the kexts via command line (sudo not required but the kexts must already be installed):
     /Applications/Tunnelblick.app/Contents/Resources/openvpnstart unloadKexts BITMASK
where BITMASK is 1 to unload the TUN kext, 2 to unload the TAP kext, or 3 to unload both


To INSTALL the kexts via command line:
     sudo /Applications/Tunnelblick.app/Contents/Resources/installer 128

To UNINSTALL the kexts via command line:
     sudo /Applications/Tunnelblick.app/Contents/Resources/installer 256

**Comment by bytegetter** [comment]
/Applications/Tunnelblick.app/Contents/Resources/openvpnstart loadKexts 3 works for me.

**Comment by jkbullard** [comment]
To **summarize**

The problem @bytegetter was having was a problem loading the system extensions:
 * Tunnelblick's kernel extensions do not load by themselves at system startup (by design); and
 * @bytegetter does not use Tunnelblick, which automatically loads them whenever they are needed and automatically unloads them when they are not needed;

so @bytegetter  needed to manually load them, which can be done with the command:

`/Applications/Tunnelblick.app/Contents/Resources/openvpnstart loadKexts 3`

If @Oliver0624 is not using Tunnelblick, he/she may also need to load/unload the kernel extensions manually (in addition to using Tunnelblick 3.8.7beta03 or later, which fixes a separate problem @Oliver0624 had loading/unloading kernel extensions on macOS Monterey).

Because installing the extensions leaves them loaded (in macOS Big Sur and higher?), the problem was also solved by reinstalling the extensions after each boot.

**Comment by bytegetter** [comment]
Script for tinc:
```
marc@Mac-mini-2021-von-Marc !Scripte % cat tinc2    

/Applications/Tunnelblick.app/Contents/Resources/openvpnstart loadKexts 3
sudo /opt/homebrew/sbin/tincd -n MeinTincVPN -k
sudo rm /usr/local/var/homebrew/linked/tinc/var/run/tinc.MeinTincVPN.pid 
sudo /opt/homebrew/sbin/tincd -n MeinTincVPN $1 $2
```
