### ISSUE TITLE
(dutch) Warning not very readable in darkmode on macOS  12.0.1 (Monterey) 3.8.7beta03 (build 5740)

### ISSUE THREAD

**Issue by bfanger** [Tunnelblick/Tunnelblick#704]
<img width="617" alt="Schermafbeelding 2021-11-01 om 10 48 19" src="https://user-images.githubusercontent.com/207248/139653585-19f34cfe-5e67-4242-92c7-8fdf3ffc55cf.png">

**Comment by jkbullard** [comment]
@bfanger - Thanks for reporting this problem. Note that it affects Tunnelblick on all versions of macOS. The fix will be included in the next beta release.
