### ISSUE TITLE
Typo in the about section of the repo

### ISSUE THREAD

**Issue by etienne-martin** [Tunnelblick/Tunnelblick#705]
Tunnelbick instead of Tunnelblick:

![image](https://user-images.githubusercontent.com/9700213/140522078-71ccfa37-2605-423c-9bdb-7543d48f4dd9.png)

**Comment by jkbullard** [comment]
@etienne-martin - Thanks!

I've fixed it. Amazing to me that nobody else noticed this for the past 6 years!
