### ISSUE TITLE
How to fix: Error in ProcessFile(): 'Not authorized to send Apple events to Finder.' (-1743) 

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#711]
**Describe the bug**
Hi guys,

I am compiling Tunnelblick version from the source code. I have signed uninstaller application.
Then I get an below error: 
Error in ProcessFile(): 'Not authorized to send Apple events to Finder.' (-1743) 

when I click [Run] button of the app. 

This error message shows only on MACOS Big Sur and Monterey.

Can you suggest me on what I am missing ?

Thanks.

**Comment by jkbullard** [comment]
See [Errors When Uninstalling](https://tunnelblick.net/cUninstall.html#errors-when-uninstalling).
