### ISSUE TITLE
Create virtual network interface on mac os Big Sur

### ISSUE THREAD

**Issue by DoudFPV** [Tunnelblick/Tunnelblick#714]
Hi,

for one project I need to create one virtual interface on mac OS. 
I simply need to "mount" in virtual network interface named "tun0" or "sl0".
On mac os catalina, tuntap work very well : http://tuntaposx.sourceforge.net/development.xhtml
but it doesn't works on Bug sur.

tuntaposx refer to Tunnelblick to add the virtual interface for mac os version doesn't support kernel extension, but I wasn't able to configure Tunnelblick to add a simple network interface (without any link to VPN), can anyone have a suggestion ?

Thanks

**Comment by jkbullard** [comment]
First, on Big Sur or later, you need to install the system extension(s) you need. Tunnelblick can do that, see [Installing System Extensions](https://tunnelblick.net/cKextsInstallation.html).

After you have done that (one time), you need to create tun0 or tap0 when you need it and destroy it when you are done.

Tunnelblick itself does not do that. Instead, OpenVPN creates the tun or tap interface as part of setting up the VPN and destroys it as part of tearing down the VPN.

So I suggest that you look into the OpenVPN source code that creates the tun or tap device.

**Comment by DoudFPV** [comment]
Nice, I will do that, thanks for your help
