### ISSUE TITLE
How to sign Tap and Tun for notarization

### ISSUE THREAD

**Issue by badralb** [Tunnelblick/Tunnelblick#717]
Hello,

Tried to codesign {APP}.app/Contents/Resources/tun-notarized.kext/Contents/MacOS/tun  and {APP}.app/Contents/Resources/tap-notarized.kext/Contents/MacOS/tap
but received an error **"The binary is not signed with a valid Developer ID certificate."** for both Tap and Tun.
Please any suggestion on how to sign Tap and Tun properly with Developer ID certificate?

**Comment by jkbullard** [comment]
You might want to ask Apple tech support for help. The standard "codesign" command works for us.
