### ISSUE TITLE
Why is OpenVPN 'config' option forbidden in Tunnelblick?

### ISSUE THREAD

**Issue by objectionoverruled** [Tunnelblick/Tunnelblick#721]
I marked this as a bug report because of the following:

When I decided to use 'config' option in my configuration, I tested in on an existing Tunnelblick connection file.
I removed some options from the ovpn file, and replaced them with a 'config' /path/to/another.ovpn
It worked.

When I tested importing the tblk with config-containing ovpn file, I was told that "this option is not allowed in Tunnelblick".
But it works when adding to the existing configuration, then, it is allowed!
It is not allowed only at the "configuration converter" step. IDK what exactly is "converted", as the ovpn is pretty simple — I need it to be disassembled into parts because I have many locations, and one common part, which I would like to have unique. This will help updating it, not having to change all the location ovpns.

So why is it not allowed if it, in fact, is?
May it be possible to remove this rule from the converter?

**Comment by objectionoverruled** [comment]
It also shows me 2 (two) modal warnings about "programs which will run as root when you connect to a VPN. These programs are part of the configuration". I press "Install" every time but to no avail. These warnings are triggered by "config" option itself, there are no "programs" (which would be more correct to be related to scripts).

**Comment by jkbullard** [comment]
Tunnelblick does not allow OpenVPN's "config" option for security reasons. Allowing it would allow configurations that are not under Tunnelblick's control to be used and such configurations could run scripts as root. This a "privilege escalation" vulnerability because it would allow standard users to run scripts as root.

**Comment by objectionoverruled** [comment]
Uhm OK, so. Tunnelblick breaks the OpenVPN basic functionality, and doesn't have its own replacement for this functionality. Looks like I have to look for a replacement for Tunnelblick. Sad but not catastrophic, especially Tunnelblick has other annoying bugs, like indefinite reconnect loop after Mac waking.

Of course Tunnelblick could check if "config" option points to external absolute path, or to internal TBLK relative path... But if it's your decision, then let it be it.

Thank you for your work anyway!
