### ISSUE TITLE
Tunnelblick disconnects VPN when lid is closed, even when macbook is plugged into power.

### ISSUE THREAD

**Issue by unphased** [Tunnelblick/Tunnelblick#725]
**Describe the bug**
When the mac lid is closed, as long as power is provided, it is possible to SSH to the machine. This is known as Power Nap. Note also on newer Apple Silicon computers there is also no option available to turn Power Nap off from system preferences. 

The problem is that Tunnelblick will always disconnect the VPN when the lid is closed, so it is not possible to use the VPN network via SSH access on the Mac unless we open the machine's lid or plug in an external monitor.

**To Reproduce**
1. Connect to a VPN with Tunnelblick
2. SSH to computer from another machine
3. Start a `ping` to a network resource behind the VPN on this SSH session
4. Close the mac's lid
5. Note how the ping will immediately begin to fail, yet the SSH session and wifi connectivity to the computer all remain intact. 

**Expected behavior**
A preferences setting to exist to allow us to decide whether we want Tunnelblick to disconnect the VPN while in sleep mode. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1

**Comment by jkbullard** [comment]
Such a preference and a checkbox to control it already exist.

Select the configuration(s) you want the change to apply to in the list on the left side of the Configurations panel of Tunnelblick's "VPN Details" window, then click the "Advanced" button on the "Settings" tab. The "Disconnect when computer goes to sleep" checkbox is on the "Connecting & Disconnecting" tab.
