### ISSUE TITLE
Tunnelblick was not able to load a system extension that is needed to connect to ustc-scc

### ISSUE THREAD

**Issue by TianLeZhao** [Tunnelblick/Tunnelblick#729]
**Tunnelblick was not able to load a system extension that is needed to connect to ustc-scc**

To allow Tunnelblick to install its system extensions, you must allow loading of system software by developer 'Jonathan Bullard'. You can do that on the 'General' tab of 'Security & Privacy' in 'System Preferences'.
If you do not see a button to allow loading of system software by developer 'Jonathan Bullard', try to connect this configuration (which will fail), then look on the 'General' tab of 'Security & Privacy' in 'System Preferences' again.
More information [tunnelblick.net]

It shows that I must allow loading of system software by developer 'Jonathan Bullard', but I had allowed it.

It also have warning:
1. A problem occurred while checking this computer's apparent public IP address.
2. One or more of your configurations will not be able to connect on future versions of macOS.
The configuration(s) require a system extension but future versions of macOS will not allow Tunnelblick to use its system extensions.
The Console Log shows which configurations will not be able to connect.
See The Future of Tun and Tap VPNs on macOS [tunnelblick.net] for more information.
3.This VPN works now, but may not work in a future version of Tunnelblick.
The OpenVPN configuration file for 'ustc-scc' should be updated so it can be used with modern versions of OpenVPN. It contains these OpenVPN options:
• 'comp-lzo' was deprecated in OpenVPN 2.4 and has been or may be removed in a later version
 Tunnelblick will use OpenVPN 2.5.4 - OpenSSL v1.1.1l to connect this configuration.
However, you will not be able to connect to this VPN with future versions of Tunnelblick that do not include a version of OpenVPN that accepts the options.
See the Console log for details.

I hope to know how to solve it.
email:haiwangxingcool@163.com

**Comment by jkbullard** [comment]
Thanks. The problem is that conflicting tun/tap system extensions ("kexts") are already loaded:

```
Non-Apple kexts that are loaded:

Index Refs Address Size Wired Name (Version) UUID 
180 0 0xffffff7f9cd3f000 0x6000 0x6000 net.sf.tuntaposx.tap (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <8 6 5 1>
181 0 0xffffff7f9cd46000 0x6000 0x6000 net.sf.tuntaposx.tun (1.0) 95DD963D-E23D-3B0F-8DE8-A4D2F6BFA5CC <8 6 5 1>

```

They interfere with Tunnelblick loading its own kexts. To use Tunnelblick, you'll have to uninstall them. (I'm not sure of the procedure to do that; try consulting whoever you got them from.)
