### ISSUE TITLE
GitHub Beta Releases Marked as “Latest”

### ISSUE THREAD

**Issue by speedybutters** [Tunnelblick/Tunnelblick#730]
**Describe the bug**
Beta releases of Tunnelblick are not marked as “pre-release” which prevents automated discovery of “stable” and “beta” releases

**To Reproduce**
1. Go to 'https://github.com/Tunnelblick/Tunnelblick/releasea '
2. Observe the latest beta is marked “Latest” rather than “Pre-release”

**Expected behavior**
Latest stable version is tagged “Latest” and betas are marked “Pre-release”

**Comment by jkbullard** [comment]
This has been fixed on all current and old releases.

**Comment by jkbullard** [comment]
@speedybutters - Thanks for reporting this. In addition to fixing it on all current and old releases a couple of weeks ago, our release procedures now include the correct tags automatically, as can be seen by our latest releases of Tunnelblick 3.8.8b and 4.0.0beta06.
