### ISSUE TITLE
Unable to launch on OS X 10.11: "PowerPC applications are no longer supported"

### ISSUE THREAD

**Issue by AlienCowEatCake** [Tunnelblick/Tunnelblick#733]
Hello!

After install Tunnelblick on OS X 10.11, I get an error message:
```
Unable to launch Tunnelblick
An error occurred while trying to launch 10.11/Applications/Tunnelblick.app
```
![Screen Shot 2022-09-01 at 6 10 38 AM](https://user-images.githubusercontent.com/1363547/187802191-15c90b91-de82-46e6-acac-97dc4163a0f6.png)

When I try to launch installed application manually, I get another error:
```
You can’t open the application “Tunnelblick.app” because PowerPC applications are no longer supported.
```
![Screen Shot 2022-09-01 at 6 10 48 AM](https://user-images.githubusercontent.com/1363547/187803787-79a156c4-b444-488b-8cec-5b04ee024c73.png)

According to download page, Tunnelblick should work on 10.10 and higher but it doesn't

 - Device: MacBookPro4,1 (15-inch Early 2008)
 - OS: OS X 10.11.6 (15G22010)
 - Tunnelblick version: 3.8.6a_build_5711, 3.8.7a_build_5770, 3.8.8beta04_build_5800

**Comment by AlienCowEatCake** [comment]
"10.11" is root partition name:
```
$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *512.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS 10.11                   511.3 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
```

Full path to installed Tunnelblick is "/Applications/Tunnelblick.app"

**Comment by AlienCowEatCake** [comment]
After several reboots, the error stopped reproducing. Any versions installs correctly now. It looks like a OS X issue. I'm sorry that I bothering you

**Comment by jkbullard** [comment]
Not a problem. I'm glad it now works for you.
