### ISSUE TITLE
Update Tunnelblick for macOS PPC to newer openssl?

### ISSUE THREAD

**Issue by barracuda156** [Tunnelblick/Tunnelblick#734]
I am interested to update the client for macOS PPC (3.5.25 is the latest, it seems). What is needed for that?

As the very minimum, update to openssl 1.0.2u is due, while 3.5.25 is at 1.0.2p: https://github.com/Tunnelblick/Tunnelblick/releases/tag/v3.5.25
Ideally, we would want openssl 1.1.1, but AFAIK the API is rather different.

openvpn2 builds fine on PPC. All versions of openssl build fine too.

**Comment by jkbullard** [comment]
I think you need to do two things:

1. In third_party/Makefile-common, find "1.0.2p" and change it to "1.0.2u". (It should appear only once.)
2. In third_party/sources, delete "openssl-1.0.2p.tar.gz", and replace it with "openssl-1.0.2u.tar.gz".

Then build. See "Building Tunnelblick from Source Code.markdown" for instructions. (It's in the downloaded source code in the outermost folder.)
