### ISSUE TITLE
Kill switch did not activate when it should have

### ISSUE THREAD

**Issue by hexoic** [Tunnelblick/Tunnelblick#737]
**Describe the bug**
I came back to my laptop to find network on, with a tunnelblick message about a problem with my login.

**To Reproduce**
I'm afraid I'm not sure. I assume there was an issue with my login, but after connecting again (the try logging in with same log in data button) the same issue came up, then I tried a bit later and it worked again. I checked and my vpn's subscription was not running out and was set to auto-renew anyway, so I'm not sure why there was a problem.

**Expected behavior**
The kill switch should activate when the connection to the vpn is disrupted, regardless of the cause.

**Screenshots**
no screenshot but the alert said "the username and password were not accepted by the remote VPN server"

**Additional context**

**Diagnostic information**
since I could not reproduce the issue after the initial two occurrences I could not get the diagnostic info :(
but if it helps, running: *Tunnelblick: macOS 10.9.5 (13F1911); Tunnelblick 3.8.4a (build 5601)

I know this is not a lot to go on, but has me concerned as I had assumed I was safe with the skill switch- but my ip was public and it had not killed the network.

**Comment by jkbullard** [comment]
One time occurrence, not reproducible, not reported by anyone else.
