### ISSUE TITLE
Icon on menu isn't shown 

### ISSUE THREAD

**Issue by hannesa2** [Tunnelblick/Tunnelblick#748]
I run most recent Tunnelblick `3.8.8a (build 5776)` but icon on top mac menu isn't shown.

Even the check "Place near Spotlight icon" is disabled

**Expected behavior**
Icon should be shown

**Screenshots**

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3314607/225569080-bdaae7bb-1dd6-4ad0-a474-6aefb203f1ac.png">

<img width="904" alt="image" src="https://user-images.githubusercontent.com/3314607/225567880-e2046a6a-6136-430c-8175-af4e62e0ee4d.png">

**Desktop (please complete the following information):**
 - OS: MacOS Venture 13.2.1 (22D68 
 - Version Tunnelblick 3.8.8a (build 5776)

**Comment by hannesa2** [comment]
> <img width="866" alt="image" src="https://user-images.githubusercontent.com/3314607/225569080-bdaae7bb-1dd6-4ad0-a474-6aefb203f1ac.png">
This screenshot was done with Shift-control-command-4 and ignores the notch. -sorry- 

> Command and Option keys, and pressing the F1

This helps here
![image](https://user-images.githubusercontent.com/3314607/225592663-a58a8a75-2730-4fff-8642-09d8c8a19b39.png)

You see, it's somehow behind the notch

**Comment by jkbullard** [comment]
Yes. It’s a macOS problem.  If there is an item you don’t need to have displayed you can remove it and then when you can see it, drag the Tunnelblick icon so it is on the right. I think you command-drag to move it but am not sure

**Comment by hannesa2** [comment]
Yes, this helps as a workaround
