### ISSUE TITLE
Install from the Command Line is not working.

### ISSUE THREAD

**Issue by uncharted-user** [Tunnelblick/Tunnelblick#749]
**Describe the bug**
Install from the Command Line is not working as expected. Tunnelblick shows two errors.

**To Reproduce**

1. Create a Tunnelblick VPN Configuration from an OpenVPN configuration file [Instructions](https://tunnelblick.net/cConfigT.html#creating-and-installing-a-tunnelblick-vpn-configuration)
2. To install Tunnelblick VPN Configurations, execute the following command as root: /Applications/Tunnelblick.net/Contents/Resources/installer 0 PATH1 PATH2 where PATH1 is the path to a place to install the configuration:
3. For a "private" configuration, ~/Library/Application Support/Tunnelblick/Configurations/NAME
4. Launch Tunnelblick
5. Try to connect

**Expected behavior**
It was supposed to work similar to import configurations through drag and drop.

**Screenshots**
<img width="508" alt="Screen Shot 2023-03-21 at 4 53 36 AM" src="https://user-images.githubusercontent.com/100132960/227046113-6545bb5a-567d-4af3-9024-6deba3833083.png">
<img width="508" alt="Screen Shot 2023-03-21 at 4 53 49 AM" src="https://user-images.githubusercontent.com/100132960/227046127-c4f21e0e-9748-4d48-93f5-8da9150ce668.png">

**Desktop (please complete the following information):**
 - OS: Monterey 12.6.3
 - Tunnelblick 3.8.8a (build 5776)

**Comment by jkbullard** [comment]
@uncharted-user - Thanks for your report.

New functionality is available in Tunnelblick 4.0.0beta06 which should fix this problem. See the "Install a Tunnelblick VPN Configuration from the Command Line without interaction" section of [Installing and Deleting VPN Configurations](https://tunnelblick.net/cInstallConfigs.html) for details.
