### ISSUE TITLE
port-share does not work after applying your patch 

### ISSUE THREAD

**Issue by arslan823** [Tunnelblick/Tunnelblick#750]

**Comment by jkbullard** [comment]
@arslan823:
1. What "port-share"?
2. In what way doe it not work?
3. What "patch"?
4. Please provide the "Diagnostic Info"

**Comment by jkbullard** [comment]
@arslan823:
1. Are you building from source for Linux after applying the Tunnelblick patches?
2. Is the problem building OpenVPN, or executing Openvpn?
3. Which of the patches do you actually want and need? It isn't clear to me that port-share works with the xorpatch patches, and OpenVPN doesn't support the xorpatch patches.

**Comment by arslan823** [comment]
1. Yes I build from Linux sources after applying the Tunnelblick 
2. All openvpn functions work. but if you use the "port-share x.x.x.x 443" function and the "scramble" function Openvpn redirects all traffic to a split port and not to a VPN client connection. There is an error in the logs:
Non-OpenVPN client protocol detected
SIGTERM[soft,port-share-redirect] received, client-instance exiting.
3. 02-tunnelblick-openvpn_xorpatch-a.diff
03-tunnelblick-openvpn_xorpatch-b.diff
04-tunnelblick-openvpn_xorpatch-c.diff
05-tunnelblick-openvpn_xorpatch-d.diff
06-tunnelblick-openvpn_xorpatch-e.diff

**Comment by jkbullard** [comment]
This is a limitation of the XOR patch. It does not support port sharing.

Port sharing works by OpenVPN detecting the difference between OpenVPN traffic and other traffic.

The XOR patch obfuscates all packets. OpenVPN's port sharing is apparently done before the packets are un-obfuscated, so OpenVPN isn't able to detect that the packets are OpenVPN traffic and it sees them as "Non-OpenVPN client protocol".
