### ISSUE TITLE
Rename LaunchAtLogin.sh to Tunnelblick_LaunchAtLogin.sh

### ISSUE THREAD

**Issue by jackjansen** [Tunnelblick/Tunnelblick#754]
**Is your feature request related to a problem? Please describe.**
Seeing `LaunchAtLogin.sh` in your background login jobs is worrying. Until I finally found out that it's part of Tunnelblick. And not some random phone-home daemon by a third party I don't trust.

**Describe the solution you'd like**
Put an indication in the filename that makes it clear this is part of Tunnelblick.

**Describe alternatives you've considered**
none

**Additional context**
Not Applicable.

**Comment by jkbullard** [comment]
@jackjansen - Thanks. The file was changed from an un-signable shell script to a signed binary named "Tunnelblick-LaunchAtLogin" as suggested in #742 and implemented in 7adb8674b2b232d7a1c3b47d177257d7f309f443, and is available in Tunnelblick 4.0.0beta03 and higher.
