### ISSUE TITLE
No internet after log out/in when tunnelblick was running.

### ISSUE THREAD

**Issue by FrancoTanzarella** [Tunnelblick/Tunnelblick#755]
**Describe the bug**
When I log out/lock my mac with tunnelblick active (connected or not), I don't have any internet when I log back in. The wifi is connected but with no internet.

When I completely shut down tunnelblick before log out, I do not have this issue. Restarting the machine does not help. The only way I found to fix the issue was to delete the following files from my machine and then log out/in.

com.apple.airport.preferences.plist
com.apple.network.identification.plist
NetworkInterfaces.plist
preferences.plist

I've always had this issue with previous versions of macOs and Tunnelblick. Updated everything to latest with no change. Hope someone can help me sort this out.

**Desktop (please complete the following information):**
 - OS: Ventura 13.4.1 on M1
 - Tunnelblick 3.8.8b (build 5777)

**Comment by jkbullard** [comment]
Closing because of a lack of response.
