### ISSUE TITLE
Release vulnerabilities URL is not found

### ISSUE THREAD

**Issue by TinCanTech** [Tunnelblick/Tunnelblick#756]
**Describe the bug**
The following link is not found:
https://tunnelblick.net/2023-08-02-vulnerabilities

This link is posted on your latest releases.

**Comment by jkbullard** [comment]
Thanks. The ".html" suffix was missing on the links on the News, Release Notes, and Old Release Notes pages. That has now been fixed.

**Comment by TinCanTech** [comment]
FYI: It looks like the _Release_ email template in use, still has the incorrect URL for https://tunnelblick.net/2023-08-02-vulnerabilities

**Comment by jkbullard** [comment]
Thanks! That was a manual error, not a mistake in the template.
