### ISSUE TITLE
Could not get gid for Shared

### ISSUE THREAD

**Issue by ryandesign** [Tunnelblick/Tunnelblick#760]
**Describe the bug**
When importing a configuration, this error appears in Console.app:

```
default	02:12:55.979576+0000	Tunnelblick	'id' returned status = 1
stderr = 'id: Shared: no such user
'
default	02:12:55.979753+0000	Tunnelblick	Could not get gid for Shared
```

**To Reproduce**
1. Open /Applications/Utilities/Console.app
2. Type "Tunnelblick" into the search box and press Return
3. Click "Start streaming"
4. Import a configuration into Tunnelblick
5. See error in console

**Expected behavior**
This error shouldn't happen.

**Screenshots**
Not needed

**Desktop (please complete the following information):**
 - OS: macOS 11.7.9
 - Browser N/A
 - Version N/A

**Additional context**
I believe the problem is here:

https://github.com/Tunnelblick/Tunnelblick/blob/f042f33d6fdb76e75d349f07eec2072c2aaf8fe1/tunnelblick/SetupImporter.m#L208-L217

You enumerate all filesystem items in /Users and call `id -g` and `id -u` on each of them to look up the group and user IDs, respectively. But /Users/Shared is part of a standard macOS install and it does not belong to a user. Maybe skip a directory called "Shared", or use a different method of finding user accounts, such as `dscl`.

**Comment by jkbullard** [comment]
@ryandesign - Thank you for reporting this and digging into it to find the cause!
