### ISSUE TITLE
 Connection fails due to fatal error: Cannot find the configuration file or the configuration file cannot be deleted

### ISSUE THREAD

**Issue by featuring-max** [Tunnelblick/Tunnelblick#765]
Describe the bug
Unable to connect to a VPN

To Reproduce

1. Open TunnelBlick
2. Connect to a VPN
3. See error 
"Tunnelblick cannot find the 'tun' or 'tap' options in the OpenVPN configuration file.",
"Tunnelblick cannot find the configuration file or the configuration file cannot be deleted. Check the console log for more details."
4. connection fails due to fatal error

Expected behavior
A successful VPN connection should have been established.

Desktop (please complete the following information):

OS: MacOS Ventura 13.5.1
Tunnelblick 3.8.8

Additional context
Here is my diagnostic info

*Tunnelblick: macOS 13.5.1 (22G90); Tunnelblick 3.8.8d (build 5779); Admin user
git commit 85e5c2eda41b9d2367be4e51c90a649ffef3f887 + uncommitted changes:
?? ../third_party/sources/IOUserEthernetController.h 
The Tunnelblick.app process is not being translated (x86_64)
System Integrity Protection is enabled
Model: MacBookPro16,1

Configuration max@featuring.in

"Sanitized" condensed configuration file for /Library/Application Support/Tunnelblick/Shared/max@featuring.in.tblk:

================================================================================

Files in max@featuring.in.tblk:
      Contents/Resources/config.ovpn

================================================================================

Tunnelblick Kext Policy Data:

Error status -1 attempting to access the Kext Policy database
stdout =
(null)
stderr =
(null)

================================================================================

Configuration preferences:

-routeAllTrafficThroughVpn = 1
-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0

================================================================================

Wildcard preferences:

-notOKToCheckThatIPAddressDidNotChangeAfterConnection = 0

================================================================================

Program preferences:

launchAtNextLogin = 1
tunnelblickVersionHistory = (
    "3.8.8d (build 5779)"
)
lastLaunchTime = 715741030.525146
lastLanguageAtLaunchWasRTL = 0
connectionWindowDisplayCriteria = showWhenConnecting
maxLogDisplaySize = 102400
keyboardShortcutIndex = 1
updateCheckAutomatically = 1
NSWindow Frame ConnectingWindow = 701 677 389 217 0 0 1792 1095 
detailsWindowFrameVersion = 5779
detailsWindowFrame = {{436, 448}, {920, 522}}
detailsWindowLeftFrame = {{0, 0}, {167, 402}}
detailsWindowViewIndex = 0
detailsWindowConfigurationsTabIdentifier = settings
leftNavSelectedDisplayName = max@featuring.in
haveDealtWithOldTunTapPreferences = 1
haveDealtWithAlwaysShowLoginWindow = 1
haveDealtWithOldLoginItem = 1
haveDealtWithAfterDisconnect = 1
SUEnableAutomaticChecks = 1
SUScheduledCheckInterval = 86400
SULastCheckTime = 2023-09-07 00:57:11 +0000
SUHasLaunchedBefore = 1

================================================================================

Forced preferences:

(None)

================================================================================

Deployed forced preferences:

(None)

================================================================================

Tunnelblick Log:

================================================================================

Down log:

(Not found)
================================================================================

Previous down log:

14:28:00 *Tunnelblick:  **********************************************
14:28:00 *Tunnelblick:  Start of output from client.down.tunnelblick.sh
14:28:00 *Tunnelblick:  Cancelled monitoring system configuration changes
14:28:00 *Tunnelblick:  Restored State:DNS
14:28:00 *Tunnelblick:  Removed Setup:DNS
14:28:00 *Tunnelblick:  Removed State:SMB
14:28:00 *Tunnelblick:  Restored DNS and SMB settings
14:28:00 *Tunnelblick:  Re-enabled IPv6 (automatic) for "Thunderbolt Bridge"
14:28:00 *Tunnelblick:  Re-enabled IPv6 (automatic) for "Wi-Fi"
14:28:00 *Tunnelblick:  Flushed the DNS cache with dscacheutil -flushcache
14:28:00 *Tunnelblick:  Notified mDNSResponder that the DNS cache was flushed
14:28:01 *Tunnelblick:  Notified mDNSResponderHelper that the DNS cache was flushed
14:28:01 *Tunnelblick:  End of output from client.down.tunnelblick.sh
14:28:01 *Tunnelblick:  **********************************************

================================================================================

Network services:

An asterisk (*) denotes that a network service is disabled.
Thunderbolt Bridge
Wi-Fi

Wi-Fi Power (en0): On

================================================================================

ifconfig output:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22 
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x4 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex>)
	status: active
ap1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 36:7d:da:27:70:14 
	media: autoselect
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6463<RXCSUM,TXCSUM,TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 14:7d:da:27:70:14 
	inet 10.200.170.137 netmask 0xfffffe00 broadcast 10.200.171.255
	media: autoselect
	status: active
awdl0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=6463<RXCSUM,TXCSUM,TSO4,TSO6,CHANNEL_IO,PARTIAL_CSUM,ZEROINVERT_CSUM>
	ether 7e:ba:d2:5e:de:21 
	inet6 fe80::7cba:d2ff:fe5e:de21%awdl0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 7e:ba:d2:5e:de:21 
	inet6 fe80::7cba:d2ff:fe5e:de21%llw0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:bd:b0:05:90:01 
	media: autoselect <full-duplex>
	status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:bd:b0:05:90:05 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:bd:b0:05:90:00 
	media: autoselect <full-duplex>
	status: inactive
en4: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:bd:b0:05:90:04 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:bd:b0:05:90:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x0
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 11 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 12 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::3304:cdc8:7477:9259%utun0 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::649d:ffd:8430:3c54%utun1 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun2 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>

================================================================================

Non-Apple kexts that are loaded:

Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>

================================================================================

Quit Log:

2023-09-07 09:56:57.937707 applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes)
2023-09-07 09:56:57.961052 shutDownTunnelblick: started.
2023-09-07 09:56:57.961793 shutDownTunnelblick: Starting cleanup.
2023-09-07 09:56:57.962278 cleanup: Entering cleanup
2023-09-07 09:56:57.962930 cleanup aborted because Tunnelblick did not finish launching
2023-09-07 09:56:57.963325 shutDownTunnelblick: Cleanup finished.
2023-09-07 09:56:57.963652 Finished shutting down Tunnelblick; allowing termination

================================================================================

Traces Log:

================================================================================

Console Log:

**Comment by jkbullard** [comment]
Three things to try:
 1. Rename the configuration so the name does not have an "@" sign.
 2. Uninstall Tunnelblick using the "Uninstall" button on the "Tools" panel of Tunnelblick's "VPN Details" window, then reinstall 3.8.8d.
 3. Uninstall Tunnelblick using the "Uninstall" button on the "Tools" panel of Tunnelblick's "VPN Details" window, then reinstall Tunnelblick 3.8.8b from Tunnelblick's [Deprecated Downloads](https://tunnelblick.net/downloadsDeprecated.html).

**Comment by featuring-max** [comment]
I solved it with the first method, thank you! 😊
