### ISSUE TITLE
Tunnelblick Deletes Route not Associated With VPN Interface

### ISSUE THREAD

**Issue by nbauernfeind** [Tunnelblick/Tunnelblick#770]
**Description:**
If I connect to the vpn from inside of the vpn network, then the routing table is left broken after disconnect.

**To Reproduce:**

1. Look for the existing route:
```bash
$  sudo netstat -rn | grep "10.10/22"
10.10/22           link#15            UCS               en0      !
```
2. connect to vpn; note that it fails to add a route for `10.10/22`:
```bash
$ sudo netstat -rn | grep -e utun5 -e "10.10/22"
10.10/22           link#15            UCS               en0      !
10.10.5/24         10.10.5.5          UGSc            utun5
10.10.5.1/32       10.10.5.5          UGSc            utun5
10.10.5.5          10.10.5.6          UH              utun5
```
3. disconnect from vpn; now the `en0` route is completely missing
```bash
$ sudo netstat -rn | grep -e utun5 -e "10.10/22"
```

Note that if I connect once more, it successfully adds the route to `utun5`:
```bash
$ sudo netstat -rn | grep -e utun5 -e "10.10/22"
10.10/22           10.10.5.5          UGSc            utun5
10.10.5/24         10.10.5.5          UGSc            utun5
10.10.5.1/32       10.10.5.5          UGSc            utun5
10.10.5.5          10.10.5.6          UH              utun5
```

**Expected behavior:**
When disconnecting from the vpn, only remove routes that belong to the `utun` interface. One could argue they want the vpn route to actually go through the vpn while connected and then restore the original route when disconnected.

**Work around:**
Bounce wifi/network connection to reestablish proper routes through `en0`. (Also, don't connect to vpn from said network... but in this particular case I forgot to disconnect from the vpn while I was still away from home.)

**Desktop:**
- System: Apple M2 Max
 - OS: 13.4 (22F66)

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by nbauernfeind** [comment]
@jkbullard thanks for the reply. The problem persists on version `Tunnelblick 4.0.0beta11 (build 5910)`.

Attached are the logs:
[tunnelblick_log.txt](https://github.com/Tunnelblick/Tunnelblick/files/13283261/tunnelblick_log.txt)

**Comment by jkbullard** [comment]
The routing was wrong: either before the VPN was established, or as requested by the VPN. This shows the problem:

> 2023-11-07 09:13:44.263687 /sbin/route add -net 10.10.0.0 10.10.5.5 255.255.252.0
>                            route: writing to routing socket: File exists
>                            add net 10.10.0.0: gateway 10.10.5.5: File exists
> 

That is, the VPN is trying to set up a route that already exists.

Also, Tunnelblick itself does not do any routing or manipulation of routes. That is all done by OpenVPN. So if there is a real problem with routing, you should get help from OpenVPN experts.

**Comment by nbauernfeind** [comment]
The route already existed; I said as much in the details. It would be excellent if "the vpn software" did not remove a route on destruction that it did not make.

Understood that this is an OpenVPN implementation issue (if they consider it an issue)! Thanks for your time and response; I will file an issue (or look for an existing issue) with OpenVPN.

**Comment by jkbullard** [comment]
Take a look at OpenVPN's `--redirect-gateway` option, specifically the `local` option.
