### ISSUE TITLE
Disconnect VPN when certain WiFi is connected?

### ISSUE THREAD

**Issue by mensa84** [Tunnelblick/Tunnelblick#777]
Hello,

sometimes I forget to disconnect Tunnelblick and work with connected VPN inside the office.
Is it possible to configure Tunnelblick, that it disconnects when I am connected to office WiFi?

**Comment by jkbullard** [comment]
Tunnelblick does not include that capability.

There may be third-party programs that could control Tunnelblick and do that but I do not know of any.
