### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by namrabtw** [Tunnelblick/Tunnelblick#778]
id like to see the apps new icons in macOS style. Every app is in that style and only this app has old design.

**Comment by acharron-hl** [comment]
I whipped one up if the project is inclined to use it. I've been using it for a bit on my local machine.

<img width="180px" src="https://github.com/Tunnelblick/Tunnelblick/assets/146114816/1c5274f3-663b-4d60-9f2d-7b494617166a" />

**Comment by namrabtw** [comment]
This is fire!

**Comment by acharron-hl** [comment]
@ryandesign Your free to use that if you'd like.
