### ISSUE TITLE
Unable to update and install 

### ISSUE THREAD

**Issue by edwinvdpol** [Tunnelblick/Tunnelblick#779]
**Describe the bug**
When I tried to update Tunnelblick to the latest version, I got the popup below. When I click the Retry button, the popup reappears.
I removed the app completely, and downloaded the latest version from the [website](https://tunnelblick.net/index.html). The same popup is shown.
I am unable to use Tunnelblick now.

Version: **Tunnelblick_3.8.8g_build_5779.3**

**To Reproduce**
1. Install / update Tunnelblick
2. See error

**Expected behavior**
Tunnelblick installed on my Macbook.

**Screenshots**
![Screenshot 2023-12-04 at 15 02 29](https://github.com/Tunnelblick/Tunnelblick/assets/9265514/e9338c2d-1137-44e7-949d-bfefa36c4a75)

**Desktop (please complete the following information):**
![Screenshot 2023-12-04 at 15 06 28](https://github.com/Tunnelblick/Tunnelblick/assets/9265514/6eaf210e-df81-4436-ae3a-6973a531f81d)

**Comment by jkbullard** [comment]
@edwinvdpol - Thanks for your report.

Please post the contents of /Library/Application Support/Tunnelblick/tunnelblick-installer-log.txt

(Note: /Library…, not ~/Library…)

**Comment by jkbullard** [comment]
It appears you have a symlink (a symbolic link) at /Users/edwin/Library/Application Support/Tunnelblick/Configurations.

For security reasons, we do not allow symlinks in paths that are (or should be) used only by Tunnelblick.

Tunnelblick does not create such links; the link must have been created manually or by some other program.

**Comment by edwinvdpol** [comment]
Ah, you are right. Seems like [Mackup](https://github.com/lra/mackup) ([config](https://github.com/lra/mackup/blob/master/mackup/applications/tunnelblick.cfg)) has created the symlink.

Do wonder why Tunnelblick is supported by Mackup... Oh well!

Thank you for the clarification and quick response.
