### ISSUE TITLE
Dynamic challenge script AUTH_FAILED

### ISSUE THREAD

**Issue by YuriDenison** [Tunnelblick/Tunnelblick#786]
My configuration uses dynamic challenge to enter OTP code.
As mentioned on [scripts](https://tunnelblick.net/cUsingScripts.html) documentation page it is possible to use `dynamic-challenge-response.user.sh` script to generate this code.

My script successfully generates 6 letter time-based code, it uses echo as flag E always present in challenge.
```
#!/bin/bash
challenge="$1"
sleep 1
echo $(pass otp name)
```

Manual input works fine - I generate OTP code with the script and copy-paste it into NSAlert as on screenshot.

However if I add `dynamic-challenge-response.user.sh` then after challenge is completed I get `AUTH_FAILED` response from the server.

Logs:
```
2024-02-14 07:26:33.139843 *Tunnelblick: Saved dynamic challenge info for user nil with flags 'R,E', state 'edba97d6934b498991b24f13e5edc036', and prompt 'Enter OTP Code'
2024-02-14 07:26:33.148543 MANAGEMENT: CMD 'hold release'
2024-02-14 07:26:33.148885 NOTE: --mute triggered...
2024-02-14 07:26:35.371254 *Tunnelblick: Received response to challenge from dynamic-challenge-response.user.sh
2024-02-14 07:26:35.373470 *Tunnelblick: User responded to dynamic challenge
2024-02-14 07:26:35.375039 3 variation(s) on previous 3 message(s) suppressed by --mute
2024-02-14 07:26:35.375104 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
....
....
2024-02-14 07:26:36.611343 AUTH: Received control message: AUTH_FAILED
2024-02-14 07:26:36.612538 SIGUSR1[soft,auth-failure] received, process restarting
2024-02-14 07:26:36.612583 MANAGEMENT: >STATE:1707884796,RECONNECTING,auth-failure,,,,,
```

The output code of the script and the data I insert into NSAlert is the same, I can't understand the difference between 2 options.

I'm not very good with Objective-C, but the parser code looks straighforward, what is the problem with my script?
https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/VPNConnection.m#L4182

- MacOS Sonoma 14.3.1 
- Tunnelblick 4.0.0beta15 (build 5950)

<img width="263" alt="Screenshot 2024-02-14 at 07 15 38" src="https://github.com/Tunnelblick/Tunnelblick/assets/396556/1c3058fb-da08-4f82-a9ad-df8059cc8af6">

**Comment by jkbullard** [comment]
I don't think LF characters are stripped from the output of the `dynamic-challenge-response.user.sh` and `static-challenge-response.user.sh` scripts. If that's true, your script is sending the TOTP and a LF but the recipient of the code may rejecting it because of the LF.

The `echo $(pass otp name)` in your script outputs a LF character after the TOTP. Try using `printf "%s" "$(pass otp name)"` instead.

**Comment by YuriDenison** [comment]
I've tried `printf "%s" "$(pass otp name)"` and nothing changed. 
The same with `pass otp vivid_ru | tr -d '\n'`.

**Comment by jkbullard** [comment]
@YuriDenison – Maybe the "sleep 1" in your script is exposing a bug in Tunnelblick. I don't know of any reason to have it in the script. Try removing it and see if that helps.

Change the script to use `printf "%s" "$(pass otp name)"`, also. It is necessary as I described earlier.

You originally wrote:
> My script successfully generates 6 letter time-based code, it uses echo as flag E always present in challenge.

The "E" flag has nothing to do with the "echo" command. The "E" flag means that if the user is asked to type in the response, each letter of the response should be displayed to the user as the user types it, instead of displaying "*" characters. The flag is ignored when the response is coming from the script.

**Comment by YuriDenison** [comment]
@jkbullard  I've tried trimming LF previously, with and without `sleep`, with and without parsing the argument in first line.
I've created the issue only when I was out of ideas what causes the problem.

This one-liner should work fine but it doesn't. 
```
printf "%s" "$(pass otp name)"
```
Unfortunately on the server side there is no verbose logs, only `Failed two-step authentication` message.

**Comment by YuriDenison** [comment]
Is it possible to add more logs to the message sent to server?
For example to [this line](https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/VPNConnection.m#L4692)

**Comment by YuriDenison** [comment]
@jkbullard I've built Tunnelblick from sources, added some logs and found that the problem is somehow related to environment of [NSTask launch](https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/sharedRoutines.m#L1358).

With this script the parsed output is always `aaabbb`
```
#!/bin/bash
printf "aaa$(/opt/homebrew/bin/pass otp name)bbb"
```

I'm using [pass](https://www.passwordstore.org/) with [otp extension](https://github.com/tadfisher/pass-otp) installed with homebrew. It works fine in default terminal, but doesn't work when launched with `runToolExtended`. 
Digging futher.

**Comment by jkbullard** [comment]
@YuriDenison - `runToolExtended` sets the environment of the [NSTask](url) from `getSafeEnvironment`, which creates a very limited environment for security reasons, and sets `PATH` in that environment to `/usr/bin:/bin:/usr/sbin:/sbin`.

If `pass` or `otp_extension` need that path include `/opt/homebrew/bin/pass`, that could be a problem.

**Comment by YuriDenison** [comment]
@jkbullard I've added `/opt/homebrew/bin` to `STANDARD_PATH` for the test sake in my local build and finally my script worked as expected. It would be nice if there will be an option to "trust" user-defined scripts with wider environment setting, turned off by default.

**Comment by jkbullard** [comment]
Thanks for reporting the problem and a potential solution.

However, it’s really a problem with pass and/or the otp extension. I’m not inclined to add something that would break security, because it would need to be authorized by an administrator.

**Comment by jkbullard** [comment]
Can your script add `/opt/homebrew/bin` to `PATH` before it invokes `pass`? Wouldn't that solve the problem?

**Comment by YuriDenison** [comment]
Sure, this script works fine with current 4.0.0beta15 version, thank you for help.
```
#!/bin/bash
export PATH="$PATH:/opt/homebrew/bin"
printf "$(pass otp name)"
```
