### ISSUE TITLE
Username with space improperly handled

### ISSUE THREAD

**Issue by moritz-t-w** [Tunnelblick/Tunnelblick#787]
**Describe the bug**
Tunnelblick creates a config directory for every word in the username. For example: "Test user" results in the folders "Test" and "user" being created, instead of one folder "Test user". The config is stored in the folder that has the last part of the name, in this case "user".

**To Reproduce**
1. Ensure your username contains at least one space
2. Install a user configuration

**Expected behavior**
For username "Test user": a single folder called "Test 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser native app
 - Version 3.8.3a
 I haven't tested it in newer versions, I don't use tunnelblick anymore and I don't have time to test this

**Smartphone (please complete the following information):**
n/a

**Comment by jkbullard** [comment]
@moritz-t-w – What do you mean by "install a user configuration"? Tunnelblick installs VPN configurations, not user configurations.

**Comment by moritz-t-w** [comment]
Installing a vpn configuration "for this user only"

**Comment by moritz-t-w** [comment]
Well it must have been using the Full name because the two folders do exist. The client was not used by someone who would mess with those files. Either way, it might have been fixed since, the issue happened on an older version.

**Comment by moritz-t-w** [comment]
It might also have been initialized on an even older version.

**Comment by jkbullard** [comment]
@moritz-t-w wrote:
> For example: "Test user" results in the folders "Test" and "user" being created…

What is the full path of the two folders on the affected computer?

**Comment by moritz-t-w** [comment]
Somewhere in appdata, where the user specific configurations are usually stored. Unfortunately I don't have the installation anymore, so I can't check where exactly, but it'll just be the default location.
