### ISSUE TITLE
Tunnelblick 4.0.0 not able to connect

### ISSUE THREAD

**Issue by gernophil** [Tunnelblick/Tunnelblick#788]
Hey everyone,

I just updated to Tunnelblick 4.0.0 and I cannot connect to my VPN anymore. I just get the message: "Tunnelblick konnte OpenVPN nicht starten, um (config file) zu verbinden. Für Details sehen Sie bitte in das VPN Details… Fenster", which translated to sth. like: Tunnelblick couldn't start OpenVPN to connect (config file). For details check the VPN window.

Reverting back to 3.8.8b solved the issue and I can connect normally again.

Here's the truncated VPN log:
```
Could not start OpenVPN (openvpnstart returned with status #251)

Contents of the openvpnstart log:
openvpnstart log:
     OpenVPN returned with status 1, errno = 0:
          Undefined error: 0
     
(truncated)
     
          XXX.YYY 1 Note: Treating option '--ncp-ciphers' as  '--data-ciphers' (renamed in OpenVPN 2.5).
          XXX.YYY 40 Unsupported cipher in --data-ciphers: BF-CBC
          XXX.YYY b000 Options error: --data-ciphers list contains unsupported ciphers or is too long.
          XXX.YYY 1040 Use --help for more information.
         
     More details may be in the Console Log's "All Messages"
```

(already posted this in the Google groups, but I thought it might be better here)

**Comment by corporate-gadfly** [comment]
For others, looking to downgrade via brew, you can use the following command to downgrade.
```
brew install --cask <cask_url>
```
where `cask_url` is as follows:
* for version 3.8.8g
  * https://raw.githubusercontent.com/Homebrew/homebrew-cask/9c677338cb893d0b387b7f6079165c95f062fd87/Casks/t/tunnelblick.rb
* for version 3.8.8d
  * https://raw.githubusercontent.com/Homebrew/homebrew-cask/194000ad2de660cf9f2351631240ab6a0d63b3f5/Casks/tunnelblick.rb

Hope that helps.

**Comment by jkbullard** [comment]
> For others, looking to downgrade…

**Before you downgrade**, please reply to this Issue with the Diagnostic Info obtained by following the instructions at [Before You Post About a Problem](https://tunnelblick.net/cBeforeYouPost.html).

Then try Tunnelblick 3.8.8b, which can be found on our [Deprecated Downloads](https://tunnelblick.net/downloadsDeprecated.html) page.

**Comment by jkbullard** [comment]
@nbevans - A cursory look at [Mikrotik's documentation](https://help.mikrotik.com/docs/display/ROS/OpenVPN) indicates they default to using Blowfish encryption, which is [not recommended for VPNs](https://crypto.stackexchange.com/questions/1098/is-blowfish-strong-enough-for-vpn-encryption). But you can apparently use different encryption, which would be compatible with OpenSSL 3. Have you tried that?

A not-recommended alternative is to allow Blowfish to be used with OpenSSL 3 by adding the "providers legacy default" option to your OpenVPN configuration file.

Of course, that's assuming you're using the default Mikrotik encryption. If not, please post the Diagnostic Info as described in [Tunnelblick 4](https://tunnelblick.net/cTunnelblick4.html) so we can figure out what the problem is.

**Comment by nbevans** [comment]
I don't think its blowfish - the server side is using AES 256 CBC

My logs in Tunnelblick show this:

```
2024-03-11 17:54:06.502896 Using peer cipher 'AES-256-CBC'
2024-03-11 17:54:06.502991 Outgoing Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
2024-03-11 17:54:06.503006 Outgoing Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
2024-03-11 17:54:06.503033 Incoming Data Channel: Cipher 'AES-256-CBC' initialized with 256 bit key
2024-03-11 17:54:06.503044 Incoming Data Channel: Using 160 bit message hash 'SHA1' for HMAC authentication
```

**Comment by jkbullard** [comment]
@nbevans - OK, so please post the Diagnostic Info as described in [Before You Post About a Problem](https://tunnelblick.net/cBeforeYouPost.html) so we can figure out what the problem is.

**Comment by nbevans** [comment]
Just posted it above in my edit. Thanks!

**Comment by jkbullard** [comment]
@nbevans - Thanks for posting it!

The repeated log entries such as:

> 2024-03-11 18:04:45.176762 TLS: Initial packet from [AF_INET]51.140.178.8:1194, sid=1f26a11a 76f436b0
> 2024-03-11 18:04:45.278022 VERIFY OK: depth=1, C=UK, CN=xxxxxxxxxx.cloudapp.azure.com
> 2024-03-11 18:04:45.278280 VERIFY X509NAME OK: CN=xxxxxxxxxx.cloudapp.azure.com
> 2024-03-11 18:04:45.278354 VERIFY OK: depth=0, CN=xxxxxxxxxx.cloudapp.azure.com
> 2024-03-11 18:04:45.332208 Connection reset, restarting [0]

Indicate that the server reset the connection after sending its initial response to the client. Perhaps the client's response made the server think that the connection was invalid. (For example, if the client encrypts with an insecure cipher.)

@gernophil, @corporate-gadfly, @nbevans, and anyone else with this problem - Please try the workaround of adding the "providers legacy default" option to the OpenVPN configuration file, as described in [Tunnelblick 4](https://tunnelblick.net/cTunnelblick4.html). It would be appreciated if you could then post here with your results.

**Comment by gernophil** [comment]
Hey, sorry for not coming back to you. I got sent a new `.ovpn` from support and with that it worked (from 4.0.0 on).
