### ISSUE TITLE
"This copy of Tunnelblick has been tampered with" when restarting Tunnelblick after using VPN profile for first time

### ISSUE THREAD

**Issue by Makedeluxe** [Tunnelblick/Tunnelblick#792]
For some versions now users have been complaining about getting a window that says "This copy of Tunnelblick has been tampered with."
This window requires admin rights to continue from or can be temporarily circumvented by reinstalling Tunnelblick

**Steps to reproduce the behavior:**
1. Do a fresh install
2. Start VPN profile
3. Open VPN details
4. Close Tunnelblick
5. Restart Tunnelblick

Not all users are affected and it seems to be random whether step 2./3. need to be done

**Expected behavior**
Tunnelblick shouldn't require admin rights unless updated

**Screenshots**

![image_720](https://github.com/Tunnelblick/Tunnelblick/assets/46417721/4c1f9f8a-fbcc-41cf-a28c-23afac835820)

**Desktop (please complete the following information):**
 - OS: MacOS 13 and 14
 - Version 4.0.0beta1 and upwards

**Additional context**
`codesign -v -v /Applications/Tunnelblick.app` gives the following error: _unsealed contents present in the bundle root_

Somewhere between steps 2. and 4. Tunnelblick seems to generate a subfolder in /Applications/Tunnelblick.app also called Tunnelblick.app (so /Applications/Tunnelblick.app/Tunnelblick.app) which has an almost identical Contents folder. Deleting this extra folder removes the error message however Tunnelblick still wants the admin rights to secure the folder

**Comment by jkbullard** [comment]
@Makedeluxe - Thanks for your report and especially for tracking down why the signature is invalid.

Can you post a .zip of one of the bogus "Tunnelblick.app" subfolders that is being created? I'm hoping that will provide a clue about what part of Tunnelblick is creating it.

**Comment by jkbullard** [comment]
@Makedeluxe - it might also help if you could post the contents of /Library/Application Support/Tunnelblick/tunnelblick-installer-log.txt immediately after getting the error (before any reinstall).

**Comment by Makedeluxe** [comment]
Here's the contents of [tunnelblick-installer-log.txt](https://github.com/Tunnelblick/Tunnelblick/files/14570995/tunnelblick-installer-log.txt):
```
Tunnelblick installer started 2024-03-11 16:58:44.165220; getuid() = 503; geteuid() = 0; getgid() = 20; getegid() = 20
currentDirectoryPath = '/'; 1 arguments:
     0x0005
Determined username 'user1' from getuid(): 503
renamex_np() tests succeeded for /Applications
renamex_np() tests succeeded for /Library/Application Support/Tunnelblick
renamex_np() tests succeeded for /Users/user1/Library/Application Support/Tunnelblick/Configurations
Changed ownership of /Applications/Tunnelblick.app and its contents from 0:80 to 0:0
Removed any 'com.apple.quarantine' extended attributes
Tunnelblick installer succeeded
```


And here's the extra Tunnelblick.app -folder from inside Tunnelblick.app:

[bogus-tunnelblick.zip](https://github.com/Tunnelblick/Tunnelblick/files/14571196/bogus-tunnelblick.zip)

**Comment by jkbullard** [comment]
@Makedeluxe - Thanks. Very interesting.

Exactly how are the users installing Tunnelblick?

Could they be installing by dragging/dropping Tunnelblick into Applications? Or using a script to do that?

That's not the recommended method, which is to double-click the Tunnelblick.app in the disk image. Of course, that shouldn't cause the extra copy of Tunnelblick.app to be copied into Tunnelblick.app, but it could help point to where Tunnelblick is doing this.

**Comment by jkbullard** [comment]
@Makedeluxe - Yes, to me this looks like an intune problem, or an intone setup problem, because nobody else has reported it.

Please post your results of testing without intune, and close this Issue if that avoids the problem.

**Comment by Makedeluxe** [comment]
After disabling the installation from Intune the problem no longer appears. Apparently other apps installed in the same way also got the extra folder but they didn't respond as aggressively to it.

Thanks for the help, probably wouldn't have found the root of the problem without talking about it
