### ISSUE TITLE
The icon width for top menu bar

### ISSUE THREAD

**Issue by tmg0** [Tunnelblick/Tunnelblick#797]
**Describe**

I'm using Mac mini Apple M2, sonoma 14.4.1. The icon of Tunnelblick in the macOS top menu bar, when tapped the menu width that exceeds the width of other icons, making it look somewhat odd.

![截屏2024-04-08 10 17 28](https://github.com/Tunnelblick/Tunnelblick/assets/40710111/0a121bd5-bab7-4b03-9100-215a7a28d765)

**Solution**

![截屏2024-04-08 10 21 31](https://github.com/Tunnelblick/Tunnelblick/assets/40710111/8f5ff4a6-5313-4e02-a2bd-346f82d178ed)

I'm not quite sure if there's a standard width for icons in the top menu bar, but still hope it can maintain the same width as the others, or be slightly narrower.

Or is there any way I can modify it locally?

**Comment by jkbullard** [comment]
I don’t know if there’s a standard width; the tunnelblick icon hasn’t changed in many years. There isn’t a way that I know of to change the width. However, you can use your own customized icon set, see [Icon Animation](https://tunnelblick.net/cIconAnimation.html). So you could make a narrower icon set and use that.

**Comment by tmg0** [comment]
Thanks for response.

Custom icon is a good way!

**Comment by Victorious3** [comment]
Shouldn't this be an open issue? Sure you can fix it locally but this should be handled by the program itself right?
