### ISSUE TITLE
6.0beta01 (build 6050) crashes on startup

### ISSUE THREAD

**Issue by FliegenKLATSCH** [Tunnelblick/Tunnelblick#809]
**Describe the bug**
App doesn't start:
Library not loaded: @rpath/libclang_rt.ubsan_osx_dynamic.dylib

**To Reproduce**
Try to open on M1 macOS 14.5.

**Expected behavior**
App opens.

**Diagnostic info**
```
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/libclang_rt.ubsan_osx_dynamic.dylib","Referenced from: <53B6892B-4721-3624-B9EC-C1D5B07464E9> \/Volumes\/*\/Tunnelblick.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/A\/Sparkle","Reason: tried: '\/Volumes\/Tunnelblick\/Tunnelblick.app\/Contents\/MacOS\/libclang_rt.ubsan_osx_dynamic.dylib' (no such file), '\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/XcodeDefault.xctoolchain\/usr\/lib\/clang\/15.0.0\/lib\/darwin\/libclang_rt.ubsan_osx_dynamic.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/XcodeDefault.xctoolchain\/usr\/lib\/clang\/15.0.0\/lib\/darwin\/libclang_rt.ubsan_osx_dynamic.dylib' (no such file), '\/Volumes\/Tunnelblick\/Tunnelblick.app\/Contents\/MacOS\/..\/Frameworks\/libclang_rt.ubsan_osx_dynamic.dylib' (no such file), '\/Volumes\/Tunnelblick\/Tunnelblick.app\/Contents\/Frameworks\/libclang_rt.ubsan_osx_dynamic.dylib' (no such file), '\/Volumes\/Tunnelblick\/Tunnelblick.app\/Contents\/MacOS\/..\/Frameworks\/libclang_rt.ubsan_osx"]},
```

**Comment by jkbullard** [comment]
Thanks for your report, @FliegenKLATSCH.

Please email developers@tunnelblick.net to get a link to download a version of Tunnelblick that may fix this problem.

**Comment by FliegenKLATSCH** [comment]
Your forward to your Gmail address is broken :)
It is sending the email with my address as from - which is not allowed per SPF record, thus google rejects it..

This is the mail system at host vps2604.pairvps.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

**Comment by jkbullard** [comment]
@FliegenKLATSCH - developers@tunnelblick.net seems to forward properly for other people. You didn't include the attached message, so this is speculation, but it could have something to do with the email address you sent from. I understand that Gmail and other providers recently made changes that impose additional anti-spam requirements that have broken forwarding for high-volume mailers. Perhaps you are considered such a high-volume mailer, or your email address or the way you sent the email caused it to be aggregated with other email so it was considered to come from a high volume mailer.

**To everyone else**: I've received enough feedback about the crashing, and a fix for it, that I plan to release a new version of Tunnelblick that includes the fix "soon".

**Comment by jkbullard** [comment]
Anyone with problems with Tunnelblick 6.0beta01 or Tunnelblick 6.0beta02 should download and install (by double-clicking) Tunnelblick 6.0beta03 from [Tunnelblick Downloads](https://tunnelblick.net/downloads.html).
