### ISSUE TITLE
Impossible to uninstall Tunnelblick

### ISSUE THREAD

**Issue by jssilva25** [Tunnelblick/Tunnelblick#815]
I'm running Sonoma with OCLP on a MacBook Pro 9,1

After patching to Sonoma and reading here, I understand that Tunnelblick does not run on OCLP. That's fine.
Then, I want to uninstall but:

1. Cannot use the 'Uninstall' button because all I get is the spinning beachball forever, not being able to reach the VPN Details window.

2. The downloaded Tunnelblick_Uninstaller_1.8_build_4405 opens a window saying "“Tunnelblick Uninstaller.app” needs to be updated. The developer of this app needs to update it to work with this version of macOS"

**Expected behavior**
I should be able to uninstall

Please just tell how.

Thank you.

**Comment by jkbullard** [comment]
1. The same problem with OCLP is presumably causing the spinning beachball.
2. The "latest" stand-alone uninstaller is too old to run on Sonoma.

However, you should be able to uninstall Tunnelblick from the command line.

1. Quit Tunnelblick.
2. If Tunnelblick is in the Dock, remove it.
3. Copy/paste the following into /Applications/Utilities/Terminal:

`/usr/bin/osascript /Applications/Tunnelblick.app/Contents/Resources/tunnelblick-uninstaller.applescript
`

**Comment by jssilva25** [comment]
That did it, thank you so much!
