### ISSUE TITLE
Tunnelblick's web_auth authentication

### ISSUE THREAD

**Issue by lsx1205** [Tunnelblick/Tunnelblick#829]
I see Adds support for client-pending-auth with WEB_AUTH in the Tunnelblick4.0 description, but I use Tunnelblick to connect to my openvpn server. My server implements casdoor authentication through oauth plug-in, that is, jumping to the web interface for authentication, but during the connection process, Tunnelblick has an error, making me have to use key or auth-user-pass

<img width="687" alt="image" src="https://github.com/user-attachments/assets/10fb86ff-da68-4692-93f2-b5c14597ce1f">

**Comment by jkbullard** [comment]
This is an OpenVPN configuration issue. (Tunnelblick uses OpenVPN to implement VPNs.) Please consult OpenVPN resources – you can find some links on our [Support](https://tunnelblick.net/support.html) page.

**Comment by lsx1205** [comment]
> This is an OpenVPN configuration issue. (Tunnelblick uses OpenVPN to implement VPNs.) Please consult OpenVPN resources – you can find some links on our [Support](https://tunnelblick.net/support.html) page.

There is no problem in the Openvpn configuration, and there is no problem in using the openvpn client, because the oauth plug-in is used to implement web authentication, and it is not mandatory to use key or user/pass to log in, and the Tunnelblick version 4.1 supports web_auth authentication. I am directly imported openvpn ovpn file, and it must use key or user/pass error

**Comment by jkbullard** [comment]
The log message you posted:

> Options error: No client-side authentication method is specified. You must use either --cert/--key, --pcs12, or --auth-user-pass

is an OpenVPN error message, not a Tunnelblick error message.

**Comment by lsx1205** [comment]
So what does Tunnelblick's web_auth authentication refer to?
