### ISSUE TITLE
Why Tunnelblick May Not Work on the Latest Version

### ISSUE THREAD

**Issue by shankargowda-plivo** [Tunnelblick/Tunnelblick#830]
**Describe the bug**
Some users may encounter issues with the latest version of Tunnelblick. To resolve this, they may need to switch to a different version, such as 2.5.9 with OpenSSL v1.1.1w, to ensure compatibility and proper access.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Diagnostic info**
Please attach a file with the info obtained by following the instructions at [Before You Post About a Problem](https://tunnelblick.net/cBeforeYouPost.html)

**Comment by jkbullard** [comment]
See [Tunnelblick 4](https://tunnelblick.net/cTunnelblick4.html).

**Comment by shankargowda-plivo** [comment]
Hey- We are facing another issue: if we switch to another ISP, the VPN works with version 2.6.9. May I know why these changes are required?

**Comment by jkbullard** [comment]
@shankargowda-plivo - Not without rest of the information on the Issue form.
