### ISSUE TITLE
Legacy System Extension

### ISSUE THREAD

**Issue by marz8** [Tunnelblick/Tunnelblick#831]
Not really a bug, but I don't know where to report this. Got this message just now:

Existing software on your system loaded a system extension signed by “Jonathan Bullard” which will be incompatible with a future version of macOS. Contact the developer for support.

**Comment by jkbullard** [comment]
Please see [The Future of Tun and Tap VPNs on macOS](https://tunnelblick.net/cTunTapConnections.html).
