### ISSUE TITLE
Tunnelblick doesn't use DNS setting (Tunnelblick does not support multiple active network interfaces)

### ISSUE THREAD

**Issue by hiroyuki-sato** [Tunnelblick/Tunnelblick#833]
**Describe the bug**

In my environment, sometimes, the nameserver setting failed after the VPN connection was established.

Does **multiple active network** mean Tunelblick found multiple active networks interfaces from `ifconfig` outputs?
I sometimes use a USB Type-C Network Adapter, But In this VPN connection, I don't use that adaptor.
Could you tell me how to find active interfaces?

* macOS: 14.7.1
* Tunnelblick: 6.0beta09 (build 6130)
* DNS/WIN: set nameserver
* `192.168.182.202`: DNS Sever address which set via OpenVPN configuration like `push "dhcp-option DNS 192.168.182.202"`
* `192.168.133.20`: is the nameserver usually used in the internal network.

Server configuration.

```
push "dhcp-option DNS 192.168.182.202"
```

```

                           15:25:29 *Tunnelblick:  Retrieved from OpenVPN: name server(s) [ 192.168.182.202 ], search domain(s) [ ] and SMB server(s) [ ] and using default domain name [ openvpn ]
                           15:25:29 *Tunnelblick:  Not aggregating ServerAddresses because running on macOS 10.6 or higher
                           15:25:29 *Tunnelblick:  Setting search domains to 'openvpn' because the search domains were not set manually (or are allowed to be changed) and 'Prepend domain name to search domains' was not selected
2024-12-11 15:25:31.538768 *Tunnelblick: Warning: DNS server address 192.168.182.202 is not being used.
                            .................

                           15:25:30 *Tunnelblick:  DNS servers '192.168.182.202' will be used for DNS queries when the VPN is active
                            .................


2024-12-11 15:25:31.539099 *Tunnelblick: Warning: DNS server address 192.168.133.20 is being used but should not be used. That may indicate that more than one network interface is active. Tunnelblick does not support multiple active network interfaces.
```

**To Reproduce**
1. Connect VPN

**Expected behavior**

Use DNS server `192.168.182.202` (The address push from the OpenVPN server)
But, the connection doesn't use the nameserver.

**Screenshots**

**Additional context**

I found the message

```
2024-12-11 15:25:31.539099 *Tunnelblick: Warning: DNS server address 192.168.133.20 is being used but should not be used. That may indicate that more than one network interface is active. Tunnelblick does not support multiple active network interfaces.
```

**Diagnostic info**

attached file.

Best regards

[tunnelblick.txt](https://github.com/user-attachments/files/18094756/tunnelblick.txt)

**Comment by jkbullard** [comment]
More about getting the DHCP lease time:

When I used the commands in the article, two sets of DHCP info were shown even through Wi-Fi is turned off and I am only using wired Ethernet.

So, instead of the `cat` command given in the article, first (after `sudo su`), I did `ls -l /var/db/dhcpclient/leases/*` to get a list of the interface names. Mine were

```
-rw-r--r--  1 root  wheel  1116 Dec  7 21:44 /var/db/dhcpclient/leases/en0.plist
-rw-r--r--  1 root  wheel   997 Dec 11 04:09 /var/db/dhcpclient/leases/en7.plist
```

Then I did
```
cat /var/db/dhcpclient/leases/en0.plist
```

 to get the info for en0, and
```
cat /var/db/dhcpclient/leases/en7.plist
```
to get the info for en7.

On my MacBook Pro, en0 is Wi-Fi and en7 is my wired Ethernet connection (through USB C). I know that because with Wi-Fi turned off, en0 was shown as inactive in the output of `ifconfig`. So I could find the lease time for the wired Ethernet interface I was using, en7.

**Comment by hiroyuki-sato** [comment]
@jkbullard Thank you for your advice. The lease time was 1 hour (3,600sec). It seems this issue didn't happen in a few days. I'll check the lease time carefully.
